### ISSUE TITLE
Support for Paxels

### ISSUE THREAD

**Issue by MLMII** [Serilum/.issue-tracker#10]
In survival pickaxes are able to break the end portal blocks, but paxels aren't able to, would it be possible to allow paxels that are introduced by other mods the ability?

Thanks.

**Comment by stop-x13** [comment]
In fact if you rename something (anything) to pickaxe, it will be able to break the frame block

**Comment by ricksouth** [comment]
Hi! This has been fixed in the version 1.1 of the mod. Thanks for letting me know.
