### ISSUE TITLE
Additional Variation Wonderings

### ISSUE THREAD

**Issue by Foamimi** [Serilum/.issue-tracker#101]
## **Information**
Mod name: GUI Clock

## **Feature description**
Hey! Would you ever consider adding an option to allow just the icon of the clock to appear, rather than the number amounts? Plus would support for Curios API be possible for those who utilize the "mustHaveClockInInventoryForGameTime" feature?

**Comment by ricksouth** [comment]
It took a little while but I've just released version 1.9 of the mod which allows you to only show the clock icon. With the 'showOnlyMinecraftClockIcon' config option. Thanks for the idea!

https://www.curseforge.com/minecraft/mc-mods/gui-clock
