### ISSUE TITLE
It doesn't work!

### ISSUE THREAD

**Issue by GingleMeow** [Serilum/.issue-tracker#103]
## **Information**
Minecraft version: 1.15.2
Forge version: 31.1.47
Environment: Singleplayer

Mod name: mooshroom tweaks
Mod version: 1.0

## **Description**
I can't find brown mooshroom after install the mod, and i set probability at 1.0, 0.1 and 0.5, i can't find any which is brown. i try to use spawn egg, it also doesn't work. but spawner can spawn the brown in inverse proportion. 
that's all.

## **Crash report**
It doesn't cause crash.

**Comment by GingleMeow** [comment]
By the way, the mod named naturally charged creepers in the same version can't spawn charged creepers by use spawn egg.

**Comment by ricksouth** [comment]
I've just tested it with the latest Forge release and everything works as intended, both creepers and mooshrooms. Can you send me your config? I think something might not be configured correctly.

![2020-05-10_17 10 01](https://user-images.githubusercontent.com/38502394/81502924-3bfdb100-92e1-11ea-8ca9-31f9654efb55.png)
