### ISSUE TITLE
I really want to download your mod but I don't know how to. :D PS. when 1.16 releases can you make a version for that. ;)

### ISSUE THREAD

**Issue by thisusernameisnotavaliableanymorehahaha** [Serilum/.issue-tracker#104]
## **Information**
(you can remove whatever is not applicable)
Minecraft version: xx.xx.xx
Forge version: xx.xx.xx
Environment: Singleplayer / Multiplayer

Mod name: Mod
Mod version: x.x

## **Question**
?

**Comment by ricksouth** [comment]
Thanks for the interest in my mods! There should be a few youtube videos out there on how to do it. You need Forge to load the mods, and can just drop mine in the /mods folder afterwards.

https://www.youtube.com/results?search_query=how+to+setup+forge+with+mods
Some of these should be able to help you as well.
