### ISSUE TITLE
[Suggestion] Guard Villagers compatibility

### ISSUE THREAD

**Issue by Darkiceflame** [Serilum/.issue-tracker#105]
## **Information**
Mod name: Villager Names

## **Feature description**
It would be nice to have the guards added by the Guard Villagers mod by tallestegg_ be named as well.

**Comment by ricksouth** [comment]
Thanks for the suggestion! I've added it in version 2.1 of the mod. It also works with previous spawns in the world. :) It can be toggled in the config.

[https://www.curseforge.com/minecraft/mc-mods/villager-names](https://www.curseforge.com/minecraft/mc-mods/villager-names)
