### ISSUE TITLE
[Request] configurable blacklist for bone meal flowers

### ISSUE THREAD

**Issue by chimericdream** [Serilum/.issue-tracker#107]
## **Information**
Mod name: Random Bone Meal Flowers

## **Feature description**
I love this mod, but I recently added Botania to a pack, and I'd like to be able to blacklist all the functional flowers from the mod, possibly even all the flowers.

Basically I'd like to be able to specify either a whitelist or blacklist in the config with a set of flowers to explicitly enable/disable. I've seen mods that do something along these lines:

```
# list the items that should get special treatment
# default: []
itemList: ["mod:item", "mod:item"]

# is the list above a whitelist? (false means it's a blacklist)
# default: false
isWhitelist: false
```

That allows you to have a minimal config that can be used in either scenario.

Thanks!

**Comment by yukinagatosc2** [comment]
Even better would be the ability to specify overrides for flowers eg. these flowers spawn in these biomes, these flowers spawn everywhere etc.

**Comment by ricksouth** [comment]
I did attempt to have biome-based flowers, but couldn't get it to work. I'll give it another attempt in the future.

For now I've added a global blacklist feature! On first load the mod generates a "blacklist.txt" in "/config/randombonemealflowers/" with all the flower names, modded included. Here you can add an exclamation mark in front of the names you don't want the mod to spawn. The description has more details.

Thanks for using the mod and the idea!

[https://www.curseforge.com/minecraft/mc-mods/random-bone-meal-flowers](https://www.curseforge.com/minecraft/mc-mods/random-bone-meal-flowers)
