### ISSUE TITLE
sleepsooner OR later

### ISSUE THREAD

**Issue by wackoamd1** [Serilum/.issue-tracker#108]
## **Information**
Mod name: sleepsooner 1.15.2

## **Feature description**
would it be possible to set a time to go to sleep not only earlier then normal but also later then normal

**Comment by ricksouth** [comment]
Check out version 2.0, it adds the functionality you've requested :)

[https://www.curseforge.com/minecraft/mc-mods/sleep-sooner](https://www.curseforge.com/minecraft/mc-mods/sleep-sooner)
