### ISSUE TITLE
Complement to Tree Harvester

### ISSUE THREAD

**Issue by Rubiksensei** [Serilum/.issue-tracker#109]
## **Information**
Mod name: Tree Harvester

## **Feature description**
So, as I've told you in mp on curseforge website, I think your mod need some more options.
- The main one : allow instant leaves destruction or not when you chop a log. Because my ears bleed every time I chop a tree (T-T)
- Plus, the possibility to increase leaves decay.

And just one more idea :
"Natural" leaves disconnected/too far from the logs disappear. But in reality, when you chop a tree, it falls, so what if natural leaves ... fall instead of  disappear ? (something similar to scaffolding behaviors)

**Comment by ricksouth** [comment]
Thanks again! For now I've fixed the sound being spammed. I'm considering the other features, possibly in a separate mod, but that's for a future release. Version 1.1 is now available.

[https://www.curseforge.com/minecraft/mc-mods/tree-harvester](https://www.curseforge.com/minecraft/mc-mods/tree-harvester)
