### ISSUE TITLE
Mod Compat

### ISSUE THREAD

**Issue by Xaikii** [Serilum/.issue-tracker#11]
## **Information**
Mod name: Easy Elytra Takeoff

## **Feature description**
Possibly compat for [Colytra](https://www.curseforge.com/minecraft/mc-mods/colytra) or [Curious Elytra](https://www.curseforge.com/minecraft/mc-mods/curious-elytra)

**Comment by ricksouth** [comment]
Hi! Version 1.2 of the Easy Elytra Takeoff mod is now compatible with Colytra. Thanks for using the mod.

**Comment by Mattabase** [comment]
Any chance this could be added to the 1.12 version?

**Comment by shikyo13** [comment]
> 
> 
> Any chance this could be added to the 1.12 version?

Indeed also looking for this.  1.12.2 is far from dead. Thanks! :D
