### ISSUE TITLE
[1.15.2- crash dedicated server]

### ISSUE THREAD

**Issue by SDUBZ** [Serilum/.issue-tracker#114]
## **Information**
Minecraft version: 1.15.2
Forge version: 1.15.2-31.1.77
Environment:  Multiplayer

Mod name: Mod
Mod version:
villagernames_1.15-2.1.jar

## **Description**
Hey! This happened i was exploring and it crashed my server

## **Crash report**
report:
[crash-2020-05-12_11.06.11-server.txt](https://github.com/ricksouth/serilum-mc-mods/files/4614530/crash-2020-05-12_11.06.11-server.txt)

logs:
[debug.log](https://github.com/ricksouth/serilum-mc-mods/files/4614534/debug.log)
[latest.log](https://github.com/ricksouth/serilum-mc-mods/files/4614537/latest.log)

**Comment by ricksouth** [comment]
Thanks for the detailed logs! I couldn't replicate it locally but I'm pretty sure I've fixed it in version 2.2. But please let me know if it happens again.

[https://www.curseforge.com/minecraft/mc-mods/villager-names](https://www.curseforge.com/minecraft/mc-mods/villager-names)
