### ISSUE TITLE
Sound Culling.

### ISSUE THREAD

**Issue by thecanidcoder** [Serilum/.issue-tracker#116]
## **Information**
Mod name: Omega Mute

## **Feature description**
[Dynamic Surroundings: Sound Control](https://www.curseforge.com/minecraft/mc-mods/dynamic-surroundings-soundcontrol) has a feature known as culling which allows you to set certain sounds to have a sort of 'cooldown' on them so they can only play so often.

(Example: I set ambient villager noises to be culled with a setting of 10 seconds. Now, no matter how many villagers are around me, the absolute most I can hear their ambient noises are once every ten seconds.)

I loved this feature in the Dynamic Surroundings version for 1.12; the 1.14 version never quite worked properly for me and it's not currently available for 1.15. Would love to have this ability again.

**Comment by ricksouth** [comment]
Sounds like it could really attribute to the mod, thanks for the idea!

What comes to mind is instead of the "!" in front of the sound lines, add something like "10_" to add a 10 second cooldown to that sound. Also extend the commands to add it from in-game.

What do you think?

**Comment by thecanidcoder** [comment]
Sounds excellent to me!

**Comment by ricksouth** [comment]
Check out version 1.1 :)

It adds _/omegamute cull "time-in-seconds" "wildcard-string"_. If the time is 10, this adds  "10- " in front of the sound name in the soundmap. You can do that manually as well of course. Let me know if something doesn't work as expected!

[https://www.curseforge.com/minecraft/mc-mods/omega-mute](https://www.curseforge.com/minecraft/mc-mods/omega-mute)

**Comment by thecanidcoder** [comment]
That's some turnaround time; love it! Thank you!
