### ISSUE TITLE
humbling bundle duping mob pick up items

### ISSUE THREAD

**Issue by majijn** [Serilum/.issue-tracker#117]
Minecraft version: 1.12
Environment: Singleplayer 

Mod name: humbling bundle

## **Description**
humbling bundle duplicates items that get picked up by mobs
which makes it possible to dupe item containers

**Comment by ricksouth** [comment]
Well found! I've fixed it in version 1.2. Thanks for letting me know.

[https://www.curseforge.com/minecraft/mc-mods/humbling-bundle](https://www.curseforge.com/minecraft/mc-mods/humbling-bundle)

**Comment by ricksouth** [comment]
I see that you're using 1.12. I don't normally update it but I've made an exception. A 1.12 version is available on the files page too now.

**Comment by majijn** [comment]
thank you so much its working great!

**Comment by TheDeviantCrafter** [comment]
This is still an issue on version 1.3 for Minecraft 1.16.5.

**Comment by TheDeviantCrafter** [comment]
![image](https://user-images.githubusercontent.com/18755309/105932061-e7869700-6011-11eb-98f5-acaa301b4e83.png)

Skeleton bows are also duped. I recommend preventing any unstackable items from being duplicated.

**Comment by Thedeur** [comment]
It's still happening as of 1.16.5 for armour and weapons. This is hilariously ridiculous in mob farms, where the mob picks up the gear, doubles it, gets killed, then another one picks up the gear, doubles it, gets killed, and so on so forth until it's a huge uncountable power of two. I haven't encountered any crashes, but this seems kind of unstable.
