### ISSUE TITLE
Campfires have to be lit to have an effect

### ISSUE THREAD

**Issue by chypriote** [Serilum/.issue-tracker#119]
## **Information**
Mod name: No Hostiles around campfires/Healing Campfires

## **Feature description**
Would be great if the features of those mod could only be enabled when a campfire is lit. Currently on my game (1.15), even if a campfire is extinguished, I get the healing buff when I enter in range of it. It would be cool if that was not the case (since campfires are also used a lot as a decoration item).
Could see it as a configuration toggle

**Comment by ricksouth** [comment]
Thanks for the suggestion! Check out version 2.2 of both mods :)

[https://www.curseforge.com/minecraft/mc-mods/no-hostiles-around-campfire](https://www.curseforge.com/minecraft/mc-mods/no-hostiles-around-campfire)
[https://www.curseforge.com/minecraft/mc-mods/healing-campfire](https://www.curseforge.com/minecraft/mc-mods/healing-campfire)
