### ISSUE TITLE
End Portal Recipe Mod: Renamed Pickaxes Cannot Break Portal Frame

### ISSUE THREAD

**Issue by stop-x13** [Serilum/.issue-tracker#12]
## **Information**
Minecraft version: 1.14.4
Forge version: 28.1.113
Environment: Singleplayer

Mod name: End Portal Recipe
Mod version: 1.0

## **Description**
Any renamed pickaxes that does not have "pickaxe" in its name cannot break end portal frame block.

**Comment by ricksouth** [comment]
Hi! This has been fixed in the version 1.1 of the mod. Thanks for letting me know.
