### ISSUE TITLE
Only 1 door closes after automatically opening 2

### ISSUE THREAD

**Issue by Areolata7** [Serilum/.issue-tracker#120]
## **Information**
Minecraft version: 1.14.4
Forge version: 28.2.0
Environment: Singleplayer

Mod name: Mod
Mod version: doubledoors_1.14-2.0 & autodoors_1.14-1.3

## **Description**
I was using Double Doors a long time and recently discovered Automatic doors and added it. With the Auto mod both doors automatically open but only one will close when I move away from them. So one door always remains open until I manually close it.  When turning around and facing the doors it is always the right one that closes and the left stays open. 

I thought that Double Doors was interferring so I removed it but this did not change the behavior. I added Double Doors back in and still the same behavior. With Automatic Doors; both doors open but only one will ever close (2 types of wooden doors and also iron doors tested)

I do not see anything in the config file (for either mod) that will fix this. Should Double Doors be used when Automatic Doors is installed or should it be removed? What can I do to correct this? Please advise. 

## **Crash report**
If available.

**Comment by ricksouth** [comment]
Thanks for letting me know and using the mod! Version 1.4 should fix the problems you were having. Automatic- and Double Doors should be compatible with each other no problem.

[https://www.curseforge.com/minecraft/mc-mods/automatic-doors](https://www.curseforge.com/minecraft/mc-mods/automatic-doors)

**Comment by TinchoX** [comment]
1.12.2 Seems to have the same bug described above, any chance you update 1.12.2 to 1.4 as well?
