### ISSUE TITLE
[Bug] Grindstone applies names on tool without removing previous name.

### ISSUE THREAD

**Issue by SpiderKolo** [Serilum/.issue-tracker#121]
## **Information**
Minecraft version: 1.15.2
Forge version: 31.2.0
Environment: Found in Singleplayer, but might also happen in Multiplayer.

Mod name: Grindstone Sharper Tools 
Mod version: grindst_1.15.2-1.2.jar

## **Description**
Hey! This happened..
![image](https://user-images.githubusercontent.com/62638498/82218719-9b307680-991c-11ea-87d0-ecaface4072f.png)
When I started using my sharpened Stone Sword (I found a village with Grindstone), I noticed that the name and the durability amount is saved in name of the tool, and every time it is used, it writes additional uses while not removing previous naming, turning sword into... well, very badly named sword.

I don't know if it applies the buff or not, but the counter seems to work fine. I set maximum uses to 16 because I though 100 might be too much.

## **Crash report**
It didn't crash the game. It's just a visual bug I suppose.

Now I don't know why it is in name of a tool and not say description or another NBT data, but if it will keep applying new names on tools, it might ruin tools you wanted to call with specific name.

I hope it's not difficult thing to fix.

**Comment by ricksouth** [comment]
It was your own fault for changing the default uses prefix!! Just kidding-- I added the custom prefix of uses left in the name at a later date and forgot to update a check. The mod does use NBT tags to keep track of uses (so you can rename in between and keep the uses left) but putting it in the name made it easy to keep track of the actual uses left.

Long story short, I've fixed it in version 1.3. Thanks for letting me know and using the mod!

[https://www.curseforge.com/minecraft/mc-mods/grindstone-sharper-tools](https://www.curseforge.com/minecraft/mc-mods/grindstone-sharper-tool)
