### ISSUE TITLE
Trader's Llama Heads?

### ISSUE THREAD

**Issue by ShinyRayquaza9923** [Serilum/.issue-tracker#122]
## **Information**
Minecraft version: 1.15.2
Forge version: 31.1.79
Environment: Singleplayer

Mod name: Just Mob Head
Mod version: 2.2

## **Question**
I don't see a separate option for trade's llama in the config and I haven't got any of its head in the game. So does the mod not have heads for trader's llama?
The reason why I am asking is before I found this mod I used the datapack thingy for the mob heads and that had a separate head for trader's llama. If it really is not part of the mod, will you ever be adding it in the future?

**Comment by ricksouth** [comment]
Thanks for letting me know! I added the data values but forgot to add the actual code which makes them drop whenever a trader llama dies. I've fixed it in version 3.1, together with some new features! :smile: 

[https://www.curseforge.com/minecraft/mc-mods/just-mob-heads](https://www.curseforge.com/minecraft/mc-mods/just-mob-heads)
