### ISSUE TITLE
Enchanting-commands Crashes server

### ISSUE THREAD

**Issue by Fundryi** [Serilum/.issue-tracker#127]
## **Information**
Minecraft & Forge version: Minecraft Version: 1.15.2

(modded) forge-31.2.5
Environment: Singleplayer & Multiplayer

Mod name: https://www.curseforge.com/minecraft/mc-mods/enchanting-commands
Mod version: newerst for 1.15

## **Description**
Well if I use /ec "enchatment" "lvl" it crashes my server, nothing more xD

## **Crash report**
`---- Minecraft Crash Report ----
// I blame Dinnerbone.

Time: 5/27/20 3:48 PM
Description: Exception in server tick loop

java.lang.NoSuchMethodError: net.minecraft.enchantment.Enchantment.func_185262_c(I)Lnet/minecraft/enchantment/Enchantment;
	at com.natamus.enchantingcommands.cmds.CommandEc.lambda$register$3(CommandEc.java:56) ~[?:1.0] {re:classloading}
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:262) ~[?:?] {re:classloading}
	at net.minecraft.command.Commands.func_197059_a(Commands.java:205) ~[?:?] {re:classloading}
	at net.minecraft.network.play.ServerPlayNetHandler.func_147361_d(ServerPlayNetHandler.java:990) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.network.play.ServerPlayNetHandler.func_147354_a(ServerPlayNetHandler.java:973) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.network.play.client.CChatMessagePacket.func_148833_a(SourceFile:36) ~[?:?] {re:classloading}
	at net.minecraft.network.play.client.CChatMessagePacket.func_148833_a(SourceFile:9) ~[?:?] {re:classloading}
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:731) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:141) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:714) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:708) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:693) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:641) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Linux (amd64) version 4.15.0-88-generic
	Java Version: 1.8.0_242, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3262501360 bytes (3111 MB) / 7292846080 bytes (6955 MB) up to 18641584128 bytes (17778 MB)
	CPUs: 16
	JVM Flags: 2 total; -Xms128M -Xmx20000M
	ModLauncher: 5.1.0+69+master.79f13f7
	ModLauncher launch target: fmlserver
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.2.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.2.5.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.5.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.1.1-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.2.5.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.5.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.15.2-31.2.5.jar fml TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.3.jar mixinbootstrap TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.3.jar mixin PLUGINSERVICE 
		/MixinBootstrap-1.0.3.jar mixinbootstrap PLUGINSERVICE 
	FML: 31.2
	Forge: net.minecraftforge:31.2.5
	FML Language Providers: 
		javafml@31.2
		minecraft@1
		kotori_scala@2.13.2-build-2
	Mod List: 
		CyclopsCore-1.15.2-1.6.2.jar Cyclops Core {cyclopscore@1.6.2 DONE}
		AdditionalEnchantedMiner-1.15.2-15.2.9.jar QuarryPlus {quarryplus@15.2.9 DONE}
		NetherPortalFix_1.15.2-6.0.2.jar NetherPortalFix {netherportalfix@6.0.2 DONE}
		refinedpipes-0.4.1.jar Refined Pipes {refinedpipes@0.4.1 DONE}
		ExtendedCrafting-1.15.2-2.0.2.jar Extended Crafting {extendedcrafting@2.0.2 DONE}
		ProjectE-1.15.2-PE1.0.3B.jar ProjectE {projecte@1.0.3B DONE}
		Industrial Agriculture[Core]-1.15.2-1.7.0.jar Industrial Agriculture {industrialagriculture@1.15.2-1.7.0 DONE}
		KleeSlabs_1.15.2-8.0.0.jar KleeSlabs {kleeslabs@8.0.0 DONE}
		BetterSprinting-1.15.2-v3.1.0.jar Better Sprinting {bettersprinting@3.1.0 DONE}
		Placebo-1.15.2-3.0.2.jar Placebo {placebo@3.0.2 DONE}
		dankstorage-2.6.jar Dank Storage {dankstorage@2.6 DONE}
		rangedpumps-0.7.1.jar Ranged Pumps {rangedpumps@0.7.1 DONE}
		WitherSkeletonTweaks-1.15.1-4.0.0.jar Wither Skeleton Tweaks {wstweaks@4.0.0 DONE}
		Bookshelf-1.15.2-5.6.40.jar Bookshelf {bookshelf@5.6.40 DONE}
		Reliquary-1.15.2-1.3.4.995.jar Reliquary {xreliquary@1.15.2-1.3.4.995 DONE}
		ChanceCubes-1.15.2-5.0.2.371.jar Chance Cubes {chancecubes@1.15.2-5.0.2.371 DONE}
		DarkUtilities-1.15.2-3.0.6.jar Dark Utilities {darkutils@3.0.6 DONE}
		StorageTech R7.1.jar Storage Tech {storagetech@R7.1 DONE}
		Morpheus-1.15.2-4.2.50.jar Morpheus {morpheus@version DONE}
		MekanismGenerators-1.15.2-9.10.6.419.jar Mekanism: Generators {mekanismgenerators@9.10.6 DONE}
		Hwyla-forge-1.10.8-B72_1.15.2.jar Waila {waila@version DONE}
		JustEnoughResources-1.15.2-0.10.1.77.jar Just Enough Resources {jeresources@0.10.1.77 DONE}
		shetiphiancore-1.15-3.7.2.jar ShetiPhian-Core {shetiphiancore@3.7.2 DONE}
		MysticalAgradditions-1.15.2-3.0.0.jar Mystical Agradditions {mysticalagradditions@3.0.0 DONE}
		mysticallib-1.15.2-2.0.0.jar Mystical Lib {mysticallib@1.15.2-2.0.0 DONE}
		refinedstorage-1.8.4.jar Refined Storage {refinedstorage@1.8.4 DONE}
		corpse-1.15.2-1.0.5.jar Corpse {corpse@1.15.2-1.0.5 DONE}
		industrial-foregoing-1.15.2-2.3.2-e3bf186.jar Industrial Foregoing {industrialforegoing@2.3.2 DONE}
		torchmaster-2.1.1-rc0.jar Torchmaster {torchmaster@2.1.1-rc0 DONE}
		endertanks-1.15-1.8.1.jar EnderTanks {endertanks@1.8.1 DONE}
		CommonCapabilities-1.15.2-2.4.4.jar CommonCapabilities {commoncapabilities@2.4.4 DONE}
		AmbientSounds_v3.0.20_mc1.15.2.jar Ambient Sounds {ambientsounds@3.0.3 DONE}
		TreeGrowingSimulator2020-1.0.0-beta+31.jar Tree Growing Simulator 2020 {treegrowingsimulator@1.0.0-beta+31 DONE}
		BiomesOPlenty-1.15.2-10.0.0.363-universal.jar Biomes O' Plenty {biomesoplenty@1.15.2-10.0.0.363 DONE}
		projectvibrantjourneys-1.15.2-2.0.2.jar Project: Vibrant Journeys {projectvibrantjourneys@1.15.2-2.0.2 DONE}
		phosphor-forge-mc1.15.2-0.5.2+build.4.jar Phosphor {phosphor@0.5.2+build.4 DONE}
		MekanismAdditions-1.15.2-9.10.6.419.jar Mekanism: Additions {mekanismadditions@9.10.6 DONE}
		valhelsia_structures-15.0.2a.jar Valhelsia Structures {valhelsia_structures@15.0.2a DONE}
		curios-FORGE-1.15.2-2.0.2.2.jar Curios API {curios@FORGE-1.15.2-2.0.2.2 DONE}
		Botania-r1.15-384.jar Botania {botania@r1.15-384 DONE}
		Patchouli-1.15.2-1.2-33.jar Patchouli {patchouli@1.15.2-1.2-33 DONE}
		OreExcavation-1.7.151.jar Ore Excavation {oreexcavation@NONE DONE}
		libnonymous-1.15.2-1.1.1.5.jar Libnonymous {libnonymous@1.1.1.5 DONE}
		worldedit-forge-mc1.15.2-7.1.0.jar WorldEdit {worldedit@7.1.0;48cc31c DONE}
		MekanismTools-1.15.2-9.10.6.419.jar Mekanism: Tools {mekanismtools@9.10.6 DONE}
		AI-Improvements-1.15.2-0.3.0.jar AI-Improvements {aiimprovements@0.3.0 DONE}
		enchantcmds_1.15.2-1.0.jar Enchanting Commands {enchantcmds@1.0 DONE}
		tramplestopper-1.15.2-2.0.0.1-universal.jar Trample Stopper {tramplestopper@1.15.2-2.0.0.1-universal DONE}
		toms_storage-1.1.1.jar Tom's Simple Storage Mod {toms_storage@1.1.1 DONE}
		FastLeafDecay-v22.jar FastLeafDecay {fastleafdecay@v22 DONE}
		CleanView-1.15.2-v1a.jar CleanView {cleanview@1.15.2-v1a DONE}
		QuantumStorage-1.15.2-5.1.1.jar QuantumStorage {quantumstorage@NONE DONE}
		Industrial Agriculture[Industrial Foregoing]-1.15.2-1.6.1.jar Industrial Agriculture Plugin-Industrial Foregoing {iapif@1.15.2-1.6.1 DONE}
		inventorysorter-1.15.2-17.0.0.jar Simple Inventory Sorter {inventorysorter@17.0.0 DONE}
		Ma-Enchants-1.15.2-3.1.0.jar Ma Enchants {ma-enchants@1.15.2-3.1.0 DONE}
		Cucumber-1.15.2-3.0.6.jar Cucumber Library {cucumber@3.0.6 DONE}
		TrashSlot_1.15.2-11.0.0.jar TrashSlot {trashslot@11.0.0 DONE}
		craftingstation-3.1.0.jar Crafting Station {craftingstation@3.1.0 DONE}
		jei-1.15.2-6.0.0.4.jar Just Enough Items {jei@6.0.0.4 DONE}
		worleycaves-1.15.2-1.6.0.jar Worley's Caves {worleycaves@1.15.2-1.6.0 DONE}
		EverlastingAbilities-1.15.2-1.6.1.jar EverlastingAbilities {everlastingabilities@1.6.1 DONE}
		AttributeFix-1.15.2-7.0.2.jar AttributeFix {attributefix@7.0.2 DONE}
		tesseract-1.0.5-mc1.15.jar Tesseract {tesseract@1.0.5 DONE}
		Mekanism-1.15.2-9.10.6.419.jar Mekanism {mekanism@9.10.6 DONE}
		WAWLA-1.15.2-3.0.2.jar WAWLA {wawla@3.0.2 DONE}
		Clumps-5.0.2.jar Clumps {clumps@5.0.2 DONE}
		journeymap-1.15.2-5.7.0b2.jar Journeymap {journeymap@5.7.0b2 DONE}
		DungeonCrawl-1.15.2-1.6.3.jar Dungeon Crawl {dungeoncrawl@1.6.3 DONE}
		BonsaiTrees-2.1.2.6.jar Bonsai Trees 2 {bonsaitrees2@2.1.2.6 DONE}
		TinyMobFarm-1.15.2-1.0.7.jar Tiny Mob Farm {tinymobfarm@1.0.7 DONE}
		mcjtylib-1.15-4.1.0-beta.jar McJtyLib {mcjtylib@1.15-4.1.0-beta DONE}
		rftoolsbase-1.15-1.1.1-beta.jar RFToolsBase {rftoolsbase@1.15-1.1.1-beta DONE}
		xnet-1.15-2.1.3-beta.jar XNet {xnet@1.15-2.1.3-beta DONE}
		rftoolsstorage-1.15-1.1.3-beta.jar RFToolsStorage {rftoolsstorage@1.15-1.1.3-beta DONE}
		voyage-1.15.2-1.0.1.jar Voyage {voyage@1.0.1 DONE}
		traverse-1.15.2-3.2.0.jar Traverse {traverse@1.15.2-3.2.0 DONE}
		rftoolspower-1.15-2.1.1-beta.jar RFToolsPower {rftoolspower@1.15-2.1.1-beta DONE}
		extradisks-1.15.1-1.2.jar Extra Disks {extradisks@1.15.1-1.2 DONE}
		forge-1.15.2-31.2.5-universal.jar Forge {forge@31.2.5 DONE}
		WailaHarvestability-mc1.15.2-1.1.12.jar Waila Harvestability {wailaharvestability@1.1.12 DONE}
		ColossalChests-1.15.2-1.7.8.jar ColossalChests {colossalchests@1.7.8 DONE}
		MysticalAgriculture-1.15.2-3.0.5.jar Mystical Agriculture {mysticalagriculture@3.0.5 DONE}
		ironchest-1.15.2-10.0.3.jar Iron Chests {ironchest@1.15.2-10.0.1 DONE}
		CraftingTweaks_1.15.1-11.0.0.jar Crafting Tweaks {craftingtweaks@11.0.0 DONE}
		forge-1.15.2-31.2.5-server.jar Minecraft {minecraft@1.15.2 DONE}
		rftoolsutility-1.15-2.1.3-beta.jar RFToolsUtility {rftoolsutility@1.15-2.1.3-beta DONE}
		EnchantmentDescriptions-1.15.2-2.0.8.jar EnchantmentDescriptions {enchdesc@2.0.8 DONE}
		theoneprobe-1.15-2.0.2.jar The One Probe {theoneprobe@1.15-2.0.2 DONE}
		swingthroughgrass-1.15.2-1.4.0.jar SwingThroughGrass {swingthroughgrass@1.15.2-1.4.0 DONE}
		MouseTweaks-2.13-mc1.15.1.jar Mouse Tweaks {mousetweaks@2.13 DONE}
		titanium-1.15.2-2.4.1.jar Titanium {titanium@2.4.1 DONE}
		SoulShardsRespawn-forge-1.15.2-1.2.0-15.jar Soul Shards Respawn {soulshards@version DONE}
		LargeFluidTank-15.2.9.jar FluidTank {fluidtank@15.2.9 DONE}
		rftoolsbuilder-1.15-2.1.2-beta.jar RFToolsBuilder {rftoolsbuilder@1.15-2.1.2-beta DONE}
		jeiintegration_1.15.2-3.1.0.1.jar JEI Integration {jeiintegration@3.1.0.1 DONE}
		JAOPCA-1.15.2-3.2.0.9.jar JAOPCA {jaopca@3.2.0.9 DONE}
		extratags-1.1.jar Extra Tags {extratags@1.1 DONE}
		FastWorkbench-1.15.1-3.0.0.jar FastWorkbench {fastbench@3.0.0 DONE}
		AutoRegLib-1.5-40.jar AutoRegLib {autoreglib@1.5-40 DONE}
		Quark-r2.1-237.jar Quark {quark@r2.1-237 DONE}
		torcherino-10.0.1.jar Torcherino {torcherino@10.0.1 DONE}
		StorageDrawers-1.15.2-7.0.2.jar Storage Drawers {storagedrawers@1.15.2-7.0.1 DONE}
		FluxNetworks-1.15.2-5.0.1-2.jar Flux Networks {fluxnetworks@1.15.2-5.0.1-2 DONE}
		enderchests-1.15-1.6.1.jar EnderChests {enderchests@1.6.1 DONE}
		Harvest-forge-1.15.1-1.2.11-24.jar Harvest {harvest@version DONE}
		Animalium-0.5.3.jar Animalium {animalium@0.5.3 DONE}
		RSLargePatterns-1.15.2-2.0.0.0.jar Refined Storage Large Patterns {rslargepatterns@2.0.0.0 DONE}
		PickleTweaks-1.15.2-4.0.3.jar Pickle Tweaks {pickletweaks@4.0.3 DONE}
		FastFurnace-1.15.1-3.0.0.jar FastFurnace {fastfurnace@3.0.0 DONE}
		AppleSkin-mc1.15.2-forge-1.0.13.jar AppleSkin {appleskin@1.0.13 DONE}
		Biomes_You_Go-0.4.1-BETA.jar Oh The Biomes You'll Go {byg@0.4.0 DONE}
		Industrial Agriculture[Mekanism]-1.15.2-1.6.1.jar Industrial Agriculture Plugin-Mekanism {iapmekanism@1.15.2-1.6.1 DONE}
		UtilityWorlds-1.15.2_1.1.0.jar Utility Worlds {utilityworlds@1.1.0 DONE}
		refinedstorageaddons-0.6.1.jar Refined Storage Addons {refinedstorageaddons@0.6.1 DONE}
		Ma-Essentials-1.15.2-3.0.3.jar Ma Essentials {ma-essentials@1.15.2-3.0.3 DONE}
	Player Count: 1 / 2; [ServerPlayerEntity['Fundryi'/114, l='SurvivalWorld', x=5615.02, y=78.06, z=-12021.04]]
	Data Packs: mod:enchantcmds (incompatible), vanilla, inmemory:jaopca (incompatible), mod:cyclopscore (incompatible), mod:quarryplus, mod:netherportalfix (incompatible), mod:refinedpipes, mod:extendedcrafting, mod:projecte, mod:industrialagriculture (incompatible), mod:kleeslabs (incompatible), mod:bettersprinting, mod:placebo (incompatible), mod:dankstorage (incompatible), mod:rangedpumps (incompatible), mod:wstweaks (incompatible), mod:bookshelf (incompatible), mod:xreliquary (incompatible), mod:chancecubes, mod:darkutils (incompatible), mod:storagetech, mod:morpheus (incompatible), mod:mekanismgenerators, mod:waila (incompatible), mod:jeresources (incompatible), mod:shetiphiancore (incompatible), mod:mysticalagradditions, mod:mysticallib, mod:refinedstorage (incompatible), mod:corpse, mod:industrialforegoing (incompatible), mod:torchmaster (incompatible), mod:endertanks (incompatible), mod:commoncapabilities (incompatible), mod:ambientsounds (incompatible), mod:treegrowingsimulator (incompatible), mod:biomesoplenty, mod:projectvibrantjourneys, mod:phosphor, mod:mekanismadditions, mod:valhelsia_structures (incompatible), mod:curios (incompatible), mod:botania (incompatible), mod:patchouli (incompatible), mod:oreexcavation (incompatible), mod:libnonymous (incompatible), mod:worldedit (incompatible), mod:mekanismtools, mod:aiimprovements (incompatible), mod:tramplestopper (incompatible), mod:toms_storage, mod:fastleafdecay, mod:cleanview (incompatible), mod:quantumstorage (incompatible), mod:iapif, mod:inventorysorter (incompatible), mod:ma-enchants (incompatible), mod:cucumber, mod:trashslot (incompatible), mod:craftingstation (incompatible), mod:jei (incompatible), mod:worleycaves (incompatible), mod:everlastingabilities (incompatible), mod:attributefix (incompatible), mod:tesseract, mod:mekanism, mod:wawla (incompatible), mod:clumps (incompatible), mod:journeymap (incompatible), mod:dungeoncrawl (incompatible), mod:bonsaitrees2, mod:tinymobfarm (incompatible), mod:mcjtylib (incompatible), mod:rftoolsbase (incompatible), mod:xnet (incompatible), mod:rftoolsstorage (incompatible), mod:voyage (incompatible), mod:traverse, mod:rftoolspower (incompatible), mod:extradisks, mod:forge (incompatible), mod:wailaharvestability (incompatible), mod:colossalchests (incompatible), mod:mysticalagriculture, mod:ironchest, mod:craftingtweaks (incompatible), mod:rftoolsutility (incompatible), mod:enchdesc (incompatible), mod:theoneprobe (incompatible), mod:swingthroughgrass (incompatible), mod:mousetweaks (incompatible), mod:titanium (incompatible), mod:soulshards (incompatible), mod:fluidtank, mod:rftoolsbuilder (incompatible), mod:jeiintegration (incompatible), mod:jaopca (incompatible), mod:extratags (incompatible), mod:fastbench (incompatible), mod:autoreglib (incompatible), mod:quark, mod:torcherino, mod:storagedrawers (incompatible), mod:fluxnetworks, mod:enderchests (incompatible), mod:harvest (incompatible), mod:animalium (incompatible), mod:rslargepatterns (incompatible), mod:pickletweaks, mod:fastfurnace (incompatible), mod:appleskin (incompatible), mod:byg, mod:iapmekanism, mod:utilityworlds (incompatible), mod:refinedstorageaddons (incompatible), mod:ma-essentials (incompatible)
	Is Modded: Definitely; Server brand changed to 'forge'
	Type: Dedicated Server (map_server.txt)`

**Comment by ricksouth** [comment]
Thanks for letting me know! I've fixed it in version 1.1 :)

[https://www.curseforge.com/minecraft/mc-mods/enchanting-commands](https://www.curseforge.com/minecraft/mc-mods/enchanting-commands)
