### ISSUE TITLE
Stuck on new game loading at 100%

### ISSUE THREAD

**Issue by Giintaras** [Serilum/.issue-tracker#128]
## **Information**
Minecraft version: **1.14.4**
Forge version: **28.1.61**
Environment: **Singleplayer**

Mod name: **The Vanilla Experience modpack**
Mod version: **one for 1.14**

## **Description**
**Hello. I've encountered an issue whenever I try to start a new world loader just gets stuck at 100% and nothing happens.**

## **Crash report**
**Not available. Link to the screenshot:  https://prnt.sc/sq0g67 **

**Comment by ricksouth** [comment]
I've just released 2.0 of the modpack. Every mod has received an update, it should fix the problems you were having. Thanks for the interest!
