### ISSUE TITLE
Egg hatching w/ Configurable Despawn Timer

### ISSUE THREAD

**Issue by silvigon** [Serilum/.issue-tracker#13]
For the Despawning Eggs Hatch mod, if used with Configurable Despawn Timer, do the eggs hatch according to the set despawn time or is the time fixed at 6000 ticks?

**Comment by ricksouth** [comment]
Hi! Thanks for using the mod. The configurable despawn timer works with the despawning eggs hatch mod. You can both lower and increase the timer.
