### ISSUE TITLE
Guard Villagers mod support

### ISSUE THREAD

**Issue by Darkiceflame** [Serilum/.issue-tracker#130]
## **Information**
Mod name: Villager Death Messages

## **Feature description**
It would be nice if the mod announced when the villagers from the Guard Villagers mod died. This would be especially helpful during raids and zombie sieges to help players know if their guards are having trouble.

**Comment by ricksouth** [comment]
I've added it in version 1.3! Thanks for using the mod and the idea.

[https://www.curseforge.com/minecraft/mc-mods/villager-death-messages](https://www.curseforge.com/minecraft/mc-mods/villager-death-messages)

**Comment by ricksouth** [comment]
Correction-- version 1.4 :)
