### ISSUE TITLE
preventSpreadBlockString = "minecraft:obsidian" doesn't seem to work?

### ISSUE THREAD

**Issue by AveryCorvus** [Serilum/.issue-tracker#131]
## **Information**
Minecraft version: 1.15.2
Forge version: 31.2.9
Environment: Singleplayer

Mod name: Nether Portal Spread
Mod version: 3.0

## **Question**
I've configured this mod to check for 14 obsidian blocks; in other words, the Nether will only spread if someone built a portal with the corners cut off, but full portals are safe. But when I built a portal like that it didn't work. What am I doing wrong?

[netherpspr-common.txt](https://github.com/ricksouth/serilum-mc-mods/files/4745683/netherpspr-common.txt)

**Comment by ricksouth** [comment]
Thanks for opening the issue, this was my fault. Forgot to switch a variable inside the code. I've fixed it in version 3.1, and tested your config file. Everything should work as intended now!

[https://www.curseforge.com/minecraft/mc-mods/nether-portal-spread](https://www.curseforge.com/minecraft/mc-mods/nether-portal-spread)
