### ISSUE TITLE
Bug: campfire regeneration does not heal within campfire radius

### ISSUE THREAD

**Issue by ItsBonezey** [Serilum/.issue-tracker#133]
the campfire's healing is applied too frequently, and ls not allowed to tick down, therefore only functioning when out of range

Minecraft version: 1.15.2
Forge version: 31.2.9
Environment: Singleplayer

Mod name: Healing Campfire
Mod version: 1.15-2.2

**Comment by ricksouth** [comment]
Thanks for letting me know! I've fixed it in version 2.3.

[https://www.curseforge.com/minecraft/mc-mods/healing-campfire](https://www.curseforge.com/minecraft/mc-mods/healing-campfire)
