### ISSUE TITLE
Collective 1.7 - Spawn bug

### ISSUE THREAD

**Issue by Mikeliro** [Serilum/.issue-tracker#135]
## **Information**
Minecraft version: 1.15.2
Forge version: 31.2.9
Environment: Singleplayer / Multiplayer

Mod name: Collective 
Mod version: 1.7

## **Description**
Skeleton Horse and Stray are appearing on the map even without having placed or matching mod (Skeleton Horse Spawn and Stray Spawn)

**Comment by ricksouth** [comment]
I have no idea how that could have happened. *looks at two forgotten debug lines*

Fixed it in version 1.8, thanks for the quick catch and letting me know!
