### ISSUE TITLE
Zombie/Skeleton Horsemen unable to move from initial spawnpoint

### ISSUE THREAD

**Issue by The-Bernician-Lamb** [Serilum/.issue-tracker#136]
## **Information**
Minecraft version: 1.15.2
Forge version: 31.2.9
Environment: Singleplayer and Multiplayer

Mod name(s): Zombie Horse Spawn + Skeleton Horse Spawn + Collective
Mod version(s): 2.3, 1.2, 1.8

## **Description**
Whenever I notice a zombie riding a zombie horse or a skeleton riding a skeleton horse I find that they are able to look around when standing in the same spot but that they cannot move from the same spot after they have spawned in. If the horse dies or the rider dismounts then the rider is able to move again as normal and vice versa. 
![2020-06-11_15 53 28](https://user-images.githubusercontent.com/64381954/84403467-a4e88980-abfd-11ea-86a7-2c0dbd3ac2a8.png)
This is most noticeable with the zombies as they will raise their hands like in the screenshot above as if they are chasing something (which they are trying to do) but they are stuck to the spot and cannot move as long as they are mounted on the horse.
![2020-06-11_16 19 39](https://user-images.githubusercontent.com/64381954/84405017-79669e80-abff-11ea-8dbe-9e07b961535d.png)
When it happens with the skeletons they will still shoot at me but they will not strafe or try and avoid me like an unmounted skeleton would and they are unable to move, allowing me to just walk up and cut them down, after which the skeleton horse starts wandering around as normal. If the horse dies first then the skeleton starts strafing as normal.

It seems to me that for whatever reason the zombie or skeleton is unable to control the horse and because the mob on top always has control then the horse doesn't move and both mobs stay stuck where they initially spawned but that's just my best guess as to what is happening.

If you need any more information regarding this issue I would be happy to help!

**Comment by ricksouth** [comment]
First of all, thank you for the thorough descriptive issues you've submitted, also the other one. I've been a little behind on the updates and am slowly catching up so I didn't respond yet.

Collective has completely new code on how the spawning works, so I'm glad the last issue was resolved. In this case, they should of course definitely move around. I might have to add a custom AI to the zombie/skeleton horses so they can walk around. I'll keep you updated of my progress!

**Comment by ricksouth** [comment]
Should be fixed in version 1.9 of Collective. The Spawn mods didn't need an update. Thanks again! :)

[https://www.curseforge.com/minecraft/mc-mods/collective](https://www.curseforge.com/minecraft/mc-mods/collective)

**Comment by ricksouth** [comment]
In the end it was because I set "is the horse saddled" in the code to true. Apparently horses are unable to move when they're saddled and being ridden. Makes sense when a player is riding the entity but in this case it meant they were frozen in place.

**Comment by Mikeliro** [comment]
For some reason the bug persists in 1.9

**Comment by ricksouth** [comment]
It might be an old spawn prior to the 1.9 update. Could you check if that's the case and new entities are spawned in ok?

**Comment by Mikeliro** [comment]
They are appearing in areas of the map that I have not yet loaded.

**Comment by ricksouth** [comment]
I just updated Collective to 1.10, but that's because I forgot to remove a debug line. The horse code hasn't changed. I tested it out with a fresh install:

![ezgif-4-8c0476448f8a](https://user-images.githubusercontent.com/38502394/84515572-f3188e00-accc-11ea-9677-2d587d155f1c.gif)

It seems to be working fine on my end

**Comment by The-Bernician-Lamb** [comment]
I'm a little busy right now, But I can definitely test things when I have more time later today!

**Comment by ricksouth** [comment]
That'd be great, thank you!

**Comment by The-Bernician-Lamb** [comment]
So, I got time to test this and after testing in both singleplayer and multiplayer with Collective v1.11, I have found that everything seems to be working fine and the horsemen can move as normal. 

Therefore, I am closing this issue, since I can no longer reproduce it.

Thanks again for your help and keep up the good work!

**Comment by ricksouth** [comment]
Good to hear, thanks!

@Mikeliro Let me know if your problem persists. You can open a new issue.
