### ISSUE TITLE
Server crashed when someone tried to join

### ISSUE THREAD

**Issue by Blugori** [Serilum/.issue-tracker#138]
## **Information**
Minecraft version: 1.15.2
Forge version: 31.2.0
Environment: Multiplayer

Mod name: Villager names
Mod version: villagernames_1.15-2.3

## **Description**
Server crashed when I tried to join. I tried with the mod only on server too and it crashed.

## **Crash report**
[crash-2020-06-12_21.40.59-server.txt](https://github.com/ricksouth/serilum-mc-mods/files/4772882/crash-2020-06-12_21.40.59-server.txt)

**Comment by ricksouth** [comment]
Please update from version 2.3 to version 2.4. It should be fixed! Thanks for using the mod.
