### ISSUE TITLE
Mod description doesn't say Forge is required

### ISSUE THREAD

**Issue by montuos** [Serilum/.issue-tracker#139]
Could you please update your mod descriptions to say somewhere that they require Forge?  Since Curseforge doesn't say anywhere that Gui Clock depends on a modloader, I was hoping it was a standalone, and it took me far too long to figure out that it wasn't going to work in my Fabric setup.  Thanks!

**Comment by ricksouth** [comment]
I understand where you're coming from, but I see fabric as the alternative modloader. On curseforge if it isn't stated, forge is the default and all other mods which use something different from what I've seen always have it specified somewhere.

All files are however tagged with the Forge modloader label. It's an extra click but it does the trick! Thanks nonetheless for the interest in my mods :)
