### ISSUE TITLE
Husk spawn causing ticking entity crash in Multiplayer

### ISSUE THREAD

**Issue by dreckz** [Serilum/.issue-tracker#14]
## **Information**
Minecraft version: 1.14.4
Forge version: 28.1.107
Environment: **Multiplayer**

Mod name: Husk Spawn, Stray Spawn.  (I'd check zombie and skeleton horse spawn too)
Mod version: 1.0

## **Description**
Upon loading up the server, it would work for a while, but then while running with multiple people the server ends up crashing with this error

com.natamus.huskspawn.events.HuskEvent.onEntityJoin(HuskEvent.java:41) ~[?:1.0] {re:classloading}

I've found a very similar thing happen with stray spawn, zombie horse spawn, and skeleton horse spawn.  They're most likely all made with similar code base, and they're great mods, but crash on multiplayer :(.  Keep up the fantastic work though!  Love your mods 👍 

## **Crash report**
[crash-2020-01-18_14.27.13-server.txt](https://github.com/ricksouth/serilum-mc-mods/files/4088708/crash-2020-01-18_14.27.13-server.txt)

**Comment by ricksouth** [comment]
Hi, thanks for submitting the issue and using the mods! This has been fixed in the newest release. I now use Collective to combine all Mob Spawn events which resolves the incompatibility issues and the problems you were having.
