### ISSUE TITLE
[1.15.2] Grindstone Sharper Tools "Ticking entity" crash

### ISSUE THREAD

**Issue by Geethebluesky** [Serilum/.issue-tracker#140]
## **Information**
Minecraft version: 1.15.2
Forge version: 31.2.19
Environment: Singleplayer

Mod version: grindstonesharpertools_1.15-1.3.jar

## **Description**
It looks like a GrindEvent from this mod somehow interacted poorly with one of Lycanite's Mobs (Calpod). I was randomly building something and not interacting with that mob at all at the time (didn't even know it had spawned).

## **Crash report**
[Minecraft Crash Report](https://pastebin.com/kb2pGtwU)

[Latest.log section](https://pastebin.com/RUsPu8G9) when the crash occurred

**Comment by ricksouth** [comment]
Thanks for letting me know and using the mod! I've fixed it in version 1.4.

[https://www.curseforge.com/minecraft/mc-mods/grindstone-sharper-tools](https://www.curseforge.com/minecraft/mc-mods/grindstone-sharper-tools)
