### ISSUE TITLE
Edibles Mod

### ISSUE THREAD

**Issue by Mikeliro** [Serilum/.issue-tracker#142]
## **Information**
Mod name: Edibles

## **Feature description**
Add a cooldown to consume the items.

**Comment by ricksouth** [comment]
Thanks for opening the issue and using the mod! I've just released version 2.0 which has a global cooldown for edibles, by default 1 second. Also added a few extra edible ingredients.

[https://www.curseforge.com/minecraft/mc-mods/edibles](https://www.curseforge.com/minecraft/mc-mods/edibles)
