### ISSUE TITLE
Server crash with villager names

### ISSUE THREAD

**Issue by Blugori** [Serilum/.issue-tracker#143]
## **Information**
Minecraft version: 1.15.2
Forge version: 31.2.18
Environment: Multiplayer

Mod name: Villager names
Mod version: villagernames_1.15-2.4.jar

## **Description**
Hi, I tried to put a new mod "rotten creatures" on my server, but then I had a crash due (it seems) to villager names.

## **Crash report**
[crash-2020-06-15_11.43.26-server.txt](https://github.com/ricksouth/serilum-mc-mods/files/4779419/crash-2020-06-15_11.43.26-server.txt)

Thanks for reading

EDIT : It seems to be the same kind of issue so I'll just post it here.
I got this problem with sully's mod too, here is the crash report.

[crash-2020-06-15_14.55.18-server.txt](https://github.com/ricksouth/serilum-mc-mods/files/4780357/crash-2020-06-15_14.55.18-server.txt)

EDIT : I tried to install (again) a mod with new mobs : MoreMobs and got the same issue, that's strange...

[crash-2020-06-15_15.50.19-server.txt](https://github.com/ricksouth/serilum-mc-mods/files/4780643/crash-2020-06-15_15.50.19-server.txt)

These mods are made with MCreator and introduce new mobs, I have no idea if the issue is really coming from villager names, but that's the only clue I have to find the problem

**Comment by ricksouth** [comment]
Thanks for letting me know and the thorough crashlogs! I've fixed it in version 1.19 of Collective, Villager names doesn't need an update. While fixing it I've learned the difference between an Exception, Error and Throwable in Java :nerd_face:
