### ISSUE TITLE
Server crash with villager names and other mods

### ISSUE THREAD

**Issue by Blugori** [Serilum/.issue-tracker#144]
## **Information**
Minecraft version: 1.15.2
Forge version: 31.2.18
Environment: Multiplayer

Mod name: Villager names
Mod version: villagernames_1.15-2.4
Collective version : collective-1.15.2-1.19

## **Description**
Hi ! I got a problem (again) with compatibilty between villagers names and mods like "rotten creatures", "moremobs" and "sully's mod". The server crashed, I'll put the crash report that I got after testing villager names + rotten creatures, and I'll notice it if the other mods are working.

## **Crash report**
[crash-2020-06-15_20.58.36-server.txt](https://github.com/ricksouth/serilum-mc-mods/files/4782358/crash-2020-06-15_20.58.36-server.txt)

Thanks for reading
(I dont know how to use labels in github...)

Edit : For  sully's mod : 
[crash-2020-06-15_21.11.07-server.txt](https://github.com/ricksouth/serilum-mc-mods/files/4782407/crash-2020-06-15_21.11.07-server.txt)

Edit : For moremobs : 
[crash-2020-06-15_21.19.40-server.txt](https://github.com/ricksouth/serilum-mc-mods/files/4782458/crash-2020-06-15_21.19.40-server.txt)

**Comment by ricksouth** [comment]
At least it's a different error this time! Thanks for letting me know, update on the way. Don't worry about labels, I've never seen anyone beside me use them :P

**Comment by ricksouth** [comment]
Collective 1.20 should *definitely* fix the problems you were having. Thanks again for letting me know!

[https://curseforge.com/minecraft/mc-mods/collective](https://curseforge.com/minecraft/mc-mods/collective)
