### ISSUE TITLE
the config does nothing

### ISSUE THREAD

**Issue by potatopepe** [Serilum/.issue-tracker#145]
Minecraft version: 1.15.2
Forge version: 31.1.48
Environment: Singleplayer

Mod name: Transcending Trident
Mod version: 1.2

when i change the config mustHoldBucketOfWater to false nothing happens

**Comment by ricksouth** [comment]
Thanks for letting me know and using the mod! I've fixed it in version 1.3.

[https://www.curseforge.com/minecraft/mc-mods/transcending-trident](https://www.curseforge.com/minecraft/mc-mods/transcending-trident)
