### ISSUE TITLE
Bamboo doesn't spread on mod grass

### ISSUE THREAD

**Issue by WenXin20** [Serilum/.issue-tracker#146]
## **Information**
Minecraft version: 1.15.2
Forge version: 31.2.19
Environment: Multiplayer

Biomes You'll Go v0.5.0
Mod name: Bamboo Spreads
Mod version: v1.1

I can plant Bamboo on the Meadow Grass Block for Biomes You'll Go, but it won't spread.

## **Description**
Hey! This happened..

## **Crash report**
If available.

**Comment by ricksouth** [comment]
Thanks for letting me know and using the mod! I've fixed it (and tested) in version 1.22 of Collective. Bamboo Spreads doesn't need an update.

[https://www.curseforge.com/minecraft/mc-mods/collective](https://www.curseforge.com/minecraft/mc-mods/collective)

**Comment by WenXin20** [comment]
Thanks!
