### ISSUE TITLE
Zombie and Skeleton Horses burn during the day, even when underneath solid blocks or shelter

### ISSUE THREAD

**Issue by The-Bernician-Lamb** [Serilum/.issue-tracker#147]
## **Information**
Minecraft version: 1.15.2
Forge version: 31.2.20
Environment: Singleplayer and Multiplayer

Mod name(s): Zombie Horse Spawn, Skeleton Horse Spawn, Collective
Mod version(s): 2.3, 1.2, 1.22

## **Description**
I noticed when experimenting with Zombie and Skeleton Horses that they burn in the daytime even when there are solid blocks above them that should block sunlight and prevent them from burning. 
![2020-06-15_21 20 20](https://user-images.githubusercontent.com/64381954/84786046-22d4d800-afe4-11ea-8955-7d53e2389790.png)
I have found that this seems to occur no matter how many blocks are above them or what block type it is they still burn, even in when in complete darkness. In all of these situations zombies and skeletons do not burn and are perfectly safe.
![2020-06-16_15 09 20](https://user-images.githubusercontent.com/64381954/84786359-8fe86d80-afe4-11ea-9bdc-c8dc9202ddce.png)
I would love to be able to give my thoughts on why this is happening but I honestly have no idea, sorry.

**Comment by ricksouth** [comment]
Well found detective! I forgot to add a check for it.. silly me. I've fixed it in version 2.4 for Zombie Horse Spawn, 1.3 for Skeleton Horse Spawn and 2.1 for Giant Spawn.

Thanks for letting me know! I think you can have a career in game testing 😋
