### ISSUE TITLE
[1.15.2] Exception ticking world (Collective)

### ISSUE THREAD

**Issue by Geethebluesky** [Serilum/.issue-tracker#148]
## **Information**
Minecraft version: 1.15.2
Forge version: 31.2.19
Environment: Singleplayer

Mod name: Collective (trying to see which other one might cause this)
Mod version: collective-1.15.2-1.22.jar

## **Description**
Another random crash that happened, I believe when a mob tried to spawn (if I go by the CheckSpawn call), but I can't tell which mob it might have been from the logs.

I'll try to narrow it down by removing mob mods.

## **Crash report**
[Crash log](https://pastebin.com/cFveYF4y)

[Latest.log at the point where the crash happened](https://pastebin.com/C6ChKZm4)

**Comment by ricksouth** [comment]
I believe I've fixed it in version 1.23 of Collective. But please let me know if that's not the case. Thanks again for letting me know and using some of my mods :)

[https://www.curseforge.com/minecraft/mc-mods/collective](https://www.curseforge.com/minecraft/mc-mods/collective)
