### ISSUE TITLE
Internal server error multiplayer

### ISSUE THREAD

**Issue by dreckz** [Serilum/.issue-tracker#15]
## **Information**
Minecraft version: 1.14.4
Forge version: 28.1.107
Environment: Multiplayer

Mod name: World Border
Mod version: 1.2

## **Description**
When reaching the world border in a multiplayer server, the client crashes and has an internal server error.  The client canot log back in unless player data is wiped or borders are extended.  The setting on teleporting to the opposite side was also enabled.  Happens with Treasures of Altera modpack 1.3.7.

**Comment by ricksouth** [comment]
Took my a little (too) long, but I've fixed the issues you were having in version 2.0. Thanks for letting me know and using the mod!

[https://www.curseforge.com/minecraft/mc-mods/world-border](https://www.curseforge.com/minecraft/mc-mods/world-border)
