### ISSUE TITLE
[Request] Open source?

### ISSUE THREAD

**Issue by marios-andr** [Serilum/.issue-tracker#150]
Can you make all your mods open source or at least a few? Am new modding and trying to do some stuff it'd really help.

**Comment by ricksouth** [comment]
At this moment I'm keeping the source code private. It has taken me a lot of time to figure out my own style of coding. There are plenty of forum posts and open sourced mods out there which can help you out. Also you could deobfuscate any mod if you'd really want to.

Thanks for the interest though!
