### ISSUE TITLE
No Nether Portal Spread

### ISSUE THREAD

**Issue by WenXin20** [Serilum/.issue-tracker#152]
## **Information**
Minecraft version: v1.15.2
Forge version: v31.2.19
Environment: Multiplayer

Mod name: Nether Portal Spread
Mod version: v3.2

## **Description**
- On my private server, I noticed that no message was sent to the player and I did not see any nether spread after lighting the portal, checking my logs revealed a small error related to the text and the spread. No crash luckily.

## **Log**
https://gist.github.com/WenXin20/5505e4c60895767b4d111d8311f6d008

**Comment by ricksouth** [comment]
Yep totally my fault. Working on a fix right now! Thanks for letting me know.

**Comment by ricksouth** [comment]
Collective version 1.24 and Nether Portal Spread version 3.3 should fix the problems you were having! Thanks again.

[https://www.curseforge.com/minecraft/mc-mods/nether-portal-spread](https://www.curseforge.com/minecraft/mc-mods/nether-portal-spread)

**Comment by WenXin20** [comment]
Thanks!
