### ISSUE TITLE
Mod: Just Mob Heads configuration question

### ISSUE THREAD

**Issue by nlfiedler** [Serilum/.issue-tracker#153]
## Information

Minecraft version: 1.15.2
Forge version: 1.15.2
Environment: Singleplayer

Mod name: Just Mob Heads
Mod version: 1.5.2 (according to the jar file, but I don't see it in the curseforge files list now)

## **Question**

The configuration file, should it be `config/justmobheads-common.toml` as stated on the curseforge page, or should I edit the existing `jmh-common.toml` file instead? I tried creating `config/justmobheads-common.toml` that looks like this:

```
mobSpecificDropChances = false
overallDropChance = 1.0
```

but nothing happened, that is it did not seem to take effect. Then realising that this is a TOML file, I added the `[General]` section header at the top, but that also did not seem to have any effect.

Finally I just modified the settings in the `jmh-common.toml` and that worked as expected.

So the question is, what was I doing wrong?

Thanks

**Comment by ricksouth** [comment]
Hi, thanks for using the mod!

"jmh" was the old modid. I've changed this to "justmobheads". So you can remove the file tarting with jmh. I'm not sure why the changes in 'jmh-common.toml' actually had an effect, they shouldn't.

Try to remove both config files, reboot the game and make changes to "config/justmobheads-common.toml". I took another look at the code and that should work as intended. Let me know though!
