### ISSUE TITLE
using the last bottle puts exp bottle in the same slot

### ISSUE THREAD

**Issue by or-n** [Serilum/.issue-tracker#154]
Minecraft version: 1.15.2
Forge version: 32.2.0
Environment: Singleplayer

Mod name: Bottle Your Xp
Mod version: 1.3

Using the last bottle puts exp bottle in the same slot. It makes player break the bottle unintentionally.

Also rawXpConsumedOnCreation=10 seems too high. 8 seems to prevent duplication.
I'd really like an option to set a loss range with (with 0 possible).

**Comment by ricksouth** [comment]
Thanks for letting me know! I'll see what I can do.

As of the losless part; I don't want to change the default behaviour of the experience bottles, and the amount of xp you receive when you break a bottle is random (within a range). So the lossless range is not possible unfortunately.

**Comment by ricksouth** [comment]
Collective version 1.25 should fix the problems you were having. Bottle Your Xp doesn't need an update. For now I'll leave the config as is, but I'll keep it in mind. Thanks again!

[https://www.curseforge.com/minecraft/mc-mods/collective](https://www.curseforge.com/minecraft/mc-mods/collective)
