### ISSUE TITLE
Support for Quark Speleothems

### ISSUE THREAD

**Issue by WenXin20** [Serilum/.issue-tracker#155]
## **Information**
Minecraft version: 1.15.2

Mod name: Nether Portal Spread

## **Feature Idea**
- Currently, I can add Quark Speleothems to the config to change the Stone Speleothems into Netherrack Speleothems, but I ran into a problem. The Speleothems use three different blockstates, top, middle, & bottom, but when this mod converts the blocks, it only places the Speleothem with the bottom state, so the block ends up being broken into air.

Is it possible to add support for blockstates?

**Comment by ricksouth** [comment]
Unfortunately at this moment that's going to be difficult. I've tried a few things, but blocks can have dozens of different blockstate types, and modded blocks even more. There is currently no easy way to turn a string into a blockstate, at least not one I could find. I'll keep it in mind though, thanks for getting it to my attention!

**Comment by WenXin20** [comment]
Alright thanks
