### ISSUE TITLE
Leaves not decaying 

### ISSUE THREAD

**Issue by Areolata7** [Serilum/.issue-tracker#157]
## **Information**
Minecraft version: 1.14.4
Forge version: 28.2.0
Environment: Singleplayer

Mod name: Tree Harvester
Mod version: treeharvester_1.14-1.2.jar

## **Description**
I just replaced these two:
https://www.curseforge.com/minecraft/mc-mods/fast-leaf-decay
https://www.curseforge.com/minecraft/mc-mods/falling-tree
With your tree harvester mod. 

I always had issues with the two other mods. Falling tree had no leaf decay when I used it which is why I added fast leaf decay. But fast leaf decay did not function with any large vanilla trees or any mod trees that were generated _with_ the world - it would only work on small vanilla trees and any trees I planted myself. So far your mod is better but I still have some leaf decay problems. 

1. If I break logs normally (by hand or non-crouching axe) the leaves remain and will never decay. 
2. If I break a small tree via the mod (with axe and crouching) it breaks completely whether it be one that naturally generated or one I planted (yay!). It even works on WildNature trees (also yay!). 
3. But large trees will often leave large sections of leaves that never decay. I am talking about trees such as the largest vanilla oak trees that can grow naturally. So about 3/4 of the leaves instantly break when I crouch-axe but 1/4 of them never decay. These leftover leaf chunks are usually the highest layer of the big tree so I have to build up to break those leaves. 

I can understand the leaves not breaking instantly if the upper layers were not close enough to the logs that were broken. However the leaves should still eventually decay over time. I have left some floating for several mc days and they persisted. So is the default leaf decay process is turned off when using this mod?  Or is there some setting I need to check? I see nothing in your config but maybe I need to check a setting on the vanilla side?

Please advise. Thank you!

FYI I made sure I delected the config files for the other two mods when I deleted the mods themselves. 

## **Crash report**
NA

**Comment by ricksouth** [comment]
There might be interference from another mod, because leaves do decay in my world. Even when they would be left behind by the tree harvester mod.

Nonetheless I've updated the mod to version 1.3. I believe this should fix the problems you were having, by using a more accurate way to find and break all leaves. Could you see if it does? Thanks!

[https://www.curseforge.com/minecraft/mc-mods/tree-harvester](https://www.curseforge.com/minecraft/mc-mods/tree-harvester)

**Comment by Areolata7** [comment]
I am installing it now. I will let you know. Thank you!

**Comment by Areolata7** [comment]
Okay so the big tree issue is solved by the newest version. If I break one (while crouching) all leaves now break when the logs break. So there are no longer leftover chunks of leaves. Thank you for this.

Unfortunately the other issue still remains. With the mod installed I get no leaf decay on trees that I break the old-fashioned way (by punching or by axing each log individually). I break all the logs but the leaves persist forever. I have to break each leaf block by hand to completely eliminate the tree. Any thoughts?

**Comment by ricksouth** [comment]
Do the leaves decay for you with just Tree Harvester installed? Because they decay no problem within my dev environment.

**Comment by ricksouth** [comment]
A better question is, do the leaves decay when tree harvester is not installed?
