### ISSUE TITLE
Light Gray Sheep

### ISSUE THREAD

**Issue by ShinyRayquaza9923** [Serilum/.issue-tracker#159]
## **Information**
Minecraft version: 1.15.2
Forge version: 31.2.20
Environment: Singleplayer

Mod name: Just Mob Heads
Mod version: 3.1

## **Description**
Light Gray Sheeps drops Steve heads/normal player heads. Just to make sure I summoned 300 of them in testing world and confirmed 

Also, how do I add the mod label thing to this? I see other people doing it but I can't find it. (I might be blind)

Edit: I just found out that there is no light gray sheep in the mob specific drop chance config. Could this be the problem? Should I just add it in?

Edit 2: Is it silver sheep? (I probably should edit after looking at everything.....)

**Comment by ShinyRayquaza9923** [comment]
I meant mod label :)

**Comment by ricksouth** [comment]
Fix on the way!

![2020-06-20_14 52 21](https://user-images.githubusercontent.com/38502394/85202297-b6204d00-b305-11ea-84c3-d5d5133ad8eb.png)

**Comment by ricksouth** [comment]
Don't worry about the mod labels, I think only I can change it. Somewhere in an update the "silver" sheep has been changed to light gray. I missed that!

I've updated Just Mob Heads to version 3.2, which fixes the problems you were having. I've also updated the other sheep heads to better resemble the current sheep entity's head. I've also added the Jeb Sheep Head, which has a chance to drop for sheep renamed to "jeb_".

Thanks for letting me know and using the mod!

[https://www.curseforge.com/minecraft/mc-mods/just-mob-heads](https://www.curseforge.com/minecraft/mc-mods/just-mob-heads)

**Comment by ShinyRayquaza9923** [comment]
Keep up the great work.
I was using so many mods without realizing a lot of them were yours.
I'm a fan :D

YetAnotherEdit : By the way, will the existing sheep heads get updated or they will stay different? I'm getting this idea from Hermitcraft7. When they updated their datapack, they kept the old heads as is. So they have 2 types of each mob heads. (I hope I'm making sense... :) )

**Comment by ricksouth** [comment]
Thanks! :)

I'd like to keep the mob heads up to date with any texture changes to mobs. The heads are generated with vanilla resources only so any old head that you've gathered is still there, but only the new heads drop
