### ISSUE TITLE
"Village Spawn Point" not updated for 1.15

### ISSUE THREAD

**Issue by MilkissWhite** [Serilum/.issue-tracker#16]
## **Information**

Mod name: Village Spawn Point
Mod version: 1.14-1.0

## **Comment**
This mod is not updated for Minecraft 1.15
I checked all mods in "The Vanilla Experience" Modpack list at Curseforge. and this is only mod that have 1.14 mod file as lastest version.
Please check!

**Comment by ricksouth** [comment]
Sorry for the wait! I've found a solution and just released a 1.15.2 version. Thanks for the interest!

[https://www.curseforge.com/minecraft/mc-mods/village-spawn-point](https://www.curseforge.com/minecraft/mc-mods/village-spawn-point)
