### ISSUE TITLE
[Just Mob Heads] Support for mobs from other mods?

### ISSUE THREAD

**Issue by chimericdream** [Serilum/.issue-tracker#160]
## **Information**
Mod name: Just Mob Heads

## **Feature description**
The title says it all. Does the mod have support for mobs provided from other mods? If not, is that in the plans?

**Comment by ricksouth** [comment]
I tried this a long time ago, even made a custom website with picker for it ([https://jmh.natamus.com/](https://jmh.natamus.com/)) but the scope was too big at the time. It requires head texture data for every modded entity. I don't think there is a way to do it procedurally with just code.

The website works but there is a lot of data missing and the mod can't load it at the moment.

**Comment by ricksouth** [comment]
This is where the head data is:
https://github.com/ricksouth/jmh-web/tree/master/data

**Comment by HatTrkPatrk** [comment]
Perhaps this could be accomplished through sidemod calling? As in, if a mod creates a new entity and wants the head to be able to drop, they could provide that texture data. If the call fails then the head drop fails. (or an error, not sure myself how volatile that would be, if even possible.)

Or perhaps registration. I'm honestly not sure the system that's used to accomplish this but I have seen it in other mods.
