### ISSUE TITLE
Pyke mob

### ISSUE THREAD

**Issue by ShinyRayquaza9923** [Serilum/.issue-tracker#162]
## **Information**
Minecraft version: 1.15.2
Forge version: 31.2.20
Environment: Singleplayer

Mod name: Just Mob Heads
Mod version: 3.2

## **Description**
I don't know if this is a bug of intended feature in your mod or problem from Upgrade Aquatic mod.
Pyke mob from Upgrade Aquatic Mod (by minecraftabnormals version: 1.6.1) drops a Steve head.

**Comment by ricksouth** [comment]
Thanks for letting me know! Definitely wasn't intended. I've fixed it in version 3.3.

[https://www.curseforge.com/minecraft/mc-mods/just-mob-heads](https://www.curseforge.com/minecraft/mc-mods/just-mob-heads)

**Comment by ShinyRayquaza9923** [comment]
I love the fact that you are so active in fixing these few problems in your mod :)
I updated to 3.3 now and I just checked my headchances config file and found out that even if I update my mod, the config file doesn't. Last time I found the issue with the light gray sheep head, you said after fixing that problem and also added jeb_ sheep head. However, I didn't see the option for jeb_ sheep.
So I realized it would be (almost) impossible for modders to update config files since there are custom values in it.
I moved the old config out to desktop , started Minecraft for it to make new updated one, then started comparing.

Sorry for telling a long story. What I wanted to say was
1. Is it somehow possible for you to update the config file when updated mod has new things in it without changing the custom values I added(in this case, custom drop chance)?

2. While comparing I found out(in mod version 3.3) BEE is gone from the option. Can I just add it myself? "bee" : 0.3,

**Comment by ricksouth** [comment]
Possible and done! The mod now checks for any missing values in the config file and appends them to the end of the file. Thanks again for the suggestion and using the mod :)

-- The missing bee value was my fault. I've added some code which automatically adds it now if the mod's version is 1.15 so it doesn't happen again.

**Comment by ShinyRayquaza9923** [comment]
That sounds great :)
I will check it now
