### ISSUE TITLE
Mods Interferrences

### ISSUE THREAD

**Issue by The43thAlpha** [Serilum/.issue-tracker#163]
Im sorry to say, but i found after one long frustrating hour, that your mod (Double doors 1.15-2.1) interferes with Simple Farming mod.
it prevents right clicking on certain blocks from Simple Farming, which renders them unusable.
Dont know how it would, but it does.

**Comment by ricksouth** [comment]
I've never used Simple Farming. Could you give an example of which blocks can't be right-clicked and in which situation?

**Comment by The43thAlpha** [comment]
The berry bushes (blueberry, strawberry, etc), the Appletree, Plumtree, etc
Anything that can be harvested with an empty hand by right click and comes from SimpleFarming.

I dont know how Double doors checks for adjacent doors but if it messes with an other mod that other players might also use, it deserves to be checked and fix if possible.
Thanks for checking, eventho you never used it.

**Comment by ricksouth** [comment]
I've just tested it, and it seems to work for my in my dev environment. Is it possible another mod is interfering instead?


![ezgif-2-17a3662d29ad](https://user-images.githubusercontent.com/38502394/85675257-d9604900-b6c5-11ea-84b2-38a2d146cf8f.gif)

**Comment by The43thAlpha** [comment]
Well i tried disabling mobs one by one and double doors was the culprit, so i legit dont know anymore

**Comment by The43thAlpha** [comment]
Well okay... I reinstalled Double Doors and it works now... Guess thats a one time bug...
Anyway, thanks for checking up on this.

**Comment by ricksouth** [comment]
Good to hear! Let me know if it happens again and I'll do some more in-depth research with your other mods installed. Thanks for using the mod :)
