### ISSUE TITLE
Will version 1.12.2 be compatible?

### ISSUE THREAD

**Issue by Geezt435** [Serilum/.issue-tracker#165]
I want to add villager a names, I don't know if this will works on 1.12.2, will this be compatible without the lib?

**Comment by ricksouth** [comment]
Yes the 1.12 version should work! Collective is not needed. The main difference with the newer version is that it doesn't have support for modded villagers. Thanks for the interest!

[https://www.curseforge.com/minecraft/mc-mods/villager-names/files/2812899](https://www.curseforge.com/minecraft/mc-mods/villager-names/files/2812899)
