### ISSUE TITLE
replanting crops

### ISSUE THREAD

**Issue by richpenguin** [Serilum/.issue-tracker#168]
## **Information**
Minecraft version: 1.16.1
Forge version: 32.0.17
Environment: Singleplayer

Mod name: Mod replanting crops
Mod version: 1.3

## **Description**
just trying out this mod works great on wheat but when using oil beetroot it replants using the only beetroot harvested just causing you to get loads of seeds and no beetroot

## **Crash report**
N/a

**Comment by ricksouth** [comment]
Thanks for letting me know! I've fixed it in version 1.4.

[https://www.curseforge.com/minecraft/mc-mods/replanting-crops](https://www.curseforge.com/minecraft/mc-mods/replanting-crops)
