### ISSUE TITLE
Configurable NHAC

### ISSUE THREAD

**Issue by FynnWaelsing** [Serilum/.issue-tracker#169]
Mod name:  No Hostiles Around Campfire

Would it be possible to make this mod configurable as to which campfire repels hostiles (i.e., regular campfire OR soul campfire OR both). I can envision a situation where modpack makers would want to only have the soul campfire repel monsters so as to gate this feature behind the Nether, for example.  Love this and all your other mods!

**Comment by James103** [comment]
Same could apply for Healing Campfire. For example, only the regular campfire heals you, while only the soul campfire prevents hostile mob spawns. If you want both, you need both types of campfires.

**Comment by ricksouth** [comment]
I've added the options 'enableEffectForNormalCampfires' and 'enableEffectForSoulCampfires' for both no hostiles around campfire and healing campfire. Both config values are enabled by default, so you can tweak it however you'd like. Thanks for using the mod!

https://www.curseforge.com/minecraft/mc-mods/no-hostiles-around-campfire
