### ISSUE TITLE
[Question] Hostiles Around Campfires effect upon Spawners

### ISSUE THREAD

**Issue by noobanidus** [Serilum/.issue-tracker#17]
## **Information**
(you can remove whatever is not applicable)
Minecraft version: 1.14.4
Forge version: 28.1.116
Environment: Multiplayer

Mod name: No Hostiles Around Campfires
Mod version: (uncertain, sorry)

## **Question**
I'm curious if this also applies to mob spawners or creatures spawned in with the SPAWN_REASON=spawner, or whether it only applies to generically spawned in mobs? I really, really like it and I'd like to use it as an alternative to Torchmaster, but I think some people on my server will be concerned if it also blocks spawners, so I thought I'd ask first before the next update.

**Comment by ricksouth** [comment]
Thanks for the idea! It did block spawners as well. I've added a config option in version 2.0 which allows you to enable/disable the spawners from having their entities be denied spawning.

[https://www.curseforge.com/minecraft/mc-mods/no-hostiles-around-campfire](https://www.curseforge.com/minecraft/mc-mods/no-hostiles-around-campfire)

**Comment by noobanidus** [comment]
Awesome, thank you!
