### ISSUE TITLE
Minor Config Error

### ISSUE THREAD

**Issue by MLMII** [Serilum/.issue-tracker#170]
## **Information**
Minecraft version: 1.16.1
Forge version: 32.0.17
Environment: Singleplayer

Mod name: Mooshroosh Tweaks
Mod version: 1.16.1.1

## **Description**
The description in the config is backwards; the percentage to "turn brown" is really the percentage of staying red.

**Comment by ricksouth** [comment]
Well found! Thanks for letting me know. That's my fault for testing with a 0.5 value. I've fixed it in version 1.2 of the mod.

https://www.curseforge.com/minecraft/mc-mods/mooshroom-tweaks/files/all
