### ISSUE TITLE
Campfires have to be signalling to have an effect

### ISSUE THREAD

**Issue by Sindarin27** [Serilum/.issue-tracker#172]
## **Information**
Mod name: Healing Campfire / No hostiles around campfire

## **Feature description**
It would be amazing if there was a toggle in the config to make it possible that the campfire effect is only available if the campfire is in signal mode (AKA has a hay bale under it). This way, the hay bale could count as a sort of "upgrade" for your campfire.

**Comment by ricksouth** [comment]
Thanks for the idea and using the mods! It took some time but I've added the option in version 3.0 for both :)

https://www.curseforge.com/minecraft/mc-mods/healing-campfire
https://www.curseforge.com/minecraft/mc-mods/no-hostiles-around-campfire/files
