### ISSUE TITLE
Mods for 1.12.2 :3

### ISSUE THREAD

**Issue by Benjas333** [Serilum/.issue-tracker#173]
## **Information**
Mod name: All possible

## **Feature description**
You have some mods that aren't compatible with Minecraft 1.12.2. I know the reason is because are items/blocks missing from 1.14-1.16. But exists a mod called "Future MC" that adds a lot of items/blocks from those versions. So, I wish you can make a 1.12.2 mod version that requires Future MC or something like that.

I don't know if it's possible or not but it would be amazing.

Btw, sorry for my English hahaha.

**Comment by ricksouth** [comment]
Thanks for the interest, I appreciate it. But I'm no longer developing mods for 1.12. I'd suggest you update to a later version, there's some good new content!
