### ISSUE TITLE
Modpack

### ISSUE THREAD

**Issue by ShockMicro** [Serilum/.issue-tracker#175]
This whole modpack could realistically be one mod with a config, I have a feeling you've split it into 90 as a ploy to get more Curse points. Is there any real reason other than money to make 90 teeny tiny mods that could realistically just be in a single mod? _Ohh but then you get to choose which features you get--_ there's a thing called a "config" that I'd like you to get introduced to. This entire pack is a ploy for downloads and it's not cool.

**Comment by ricksouth** [comment]
Hi! Thanks for your cynical opinion.

I started out creating mods without any knowledge. I had an idea, and tried to make that a reality. When I had a new idea, I created another mod. This was over the span of 2 years.

I did not want a single mod with loads of features where people had to download it and only use 10%. A giant config still uses computational power, as the event has to be registered.

If you'd count the money I receive on a monthly basis and divide that by my hours I've put in, you'd be better off working in a supermarket.

Have a nice day,
Rick

**Comment by ShockMicro** [comment]
I'm really sorry for the cynical opinion, I was feeling pretty tired and annoyed earlier today and I unfortunately took it out on you. I should've put it in a better way, but ah well. I get it, people wouldn't use all of them all the time. That's cool. Again, sorry for how I put it. I was just gonna delete this but then I saw you already replied. Whoops. Ah well, thanks for the response. Cheers.

**Comment by ricksouth** [comment]
I appreciate the second message. We've all got ups and downs, just remember there's always another person on the other side. Deleting the message would've still left it in my email inbox. Hope you feel better!
