### ISSUE TITLE
/ec use by another mod/plugin

### ISSUE THREAD

**Issue by coffe3machine** [Serilum/.issue-tracker#176]
will there be a way for you to add another command then /ec for enchanting because the /ec is already use in my server by mycommand plugin for the enderchest

**Comment by ricksouth** [comment]
Hi, thanks for using the mod! I've added a config option in version 1.2, where you can change the default /ec command. That should do the trick! :)

[https://www.curseforge.com/minecraft/mc-mods/enchanting-commands](https://www.curseforge.com/minecraft/mc-mods/enchanting-commands)
