### ISSUE TITLE
Infinitetrading wandering Trader

### ISSUE THREAD

**Issue by Hulk3421** [Serilum/.issue-tracker#178]
Hey!
I dont know if it is intended but infinitetrading doesn´t work with the wandering trader.

**Comment by ricksouth** [comment]
I've added support for the wandering trader in version 1.2 of the mod. The functionality can be turned off in the config file. Thanks for opening the issue and using the mod!

https://www.curseforge.com/minecraft/mc-mods/infinite-trading/files/all
