### ISSUE TITLE
Starter Kit NBT compatability or CanDestroy for Players

### ISSUE THREAD

**Issue by tbeacham87** [Serilum/.issue-tracker#179]
Just a reminder about the idea of making Starter Kit able to give NBT specific items and about the possible creation of a mod to give players, without any items in hand, the CanDestroy NBT. Keep up the great work.

**Comment by ricksouth** [comment]
Hey! Check out version 2.0 of Starter Kit. It adds a '/starterkit set' command to write the entire inventory of the user to the config file. This also means it has support for NBT tags for things such as enchantments and written books. Let me know if anything should be different. Thanks for using the mod!

[https://www.curseforge.com/minecraft/mc-mods/starter-kit](https://www.curseforge.com/minecraft/mc-mods/starter-kit)
