### ISSUE TITLE
Using Giant Spawn (giantspawn_1.15-1.0.2.jar) in a modpack I am making. Just wondering about how the giants don't really DO anything, unless they are infernal (Atomic Strykers Infernal Mobs). Either way they don't move. Its a cool thing to see but other than that... Any plans for those things?

### ISSUE THREAD

**Issue by lowresgames** [Serilum/.issue-tracker#18]
## **Information**
(you can remove whatever is not applicable)
Minecraft version: xx.xx.xx
Forge version: xx.xx.xx
Environment: Singleplayer / Multiplayer

Mod name: Mod
Mod version: x.x

## **Question**
?

**Comment by ricksouth** [comment]
Hi, thanks for using the mod. The mod currently only spawns the giant mob that's already in the game, which does not have an AI itself. I have plans to give it the zombie AI in the future but it doesn't yet as of now.
