### ISSUE TITLE
Written Books don't spawn in player inventory

### ISSUE THREAD

**Issue by honestcactus** [Serilum/.issue-tracker#186]
## **Information**
Minecraft version: 1.16.1
Forge version: 32.0.52
Environment: Singleplayer

Mod name: Starter Kit
Mod version: 1.0

## **Description**
Giving players a written book does not seem to work. It either does not show up or it does not show up and also prevents the first item in the hotbar from spawning normally as well.
The written/signed book I was attempting to have players spawn with did include on-click events, as well as colouring tags so perhaps that might be the issue?
UPDATE: Attempted to do it without anything fancy. Just does not spawn a written book at all.

## **Crash report**
N/A

**Comment by ricksouth** [comment]
Hey! Check out version 2.0 of Starter Kit. It adds a '/starterkit set' command to write the entire inventory of the user to the config file. This also means it has support for NBT tags for things such as enchantments and written books. Let me know if anything should be different. Thanks for using the mod!

[https://www.curseforge.com/minecraft/mc-mods/starter-kit](https://www.curseforge.com/minecraft/mc-mods/starter-kit)
