### ISSUE TITLE
Compatibility with Baubles Elytra from the Colytra mod

### ISSUE THREAD

**Issue by KarlosWGeek** [Serilum/.issue-tracker#187]
## **Information**
**Mod name:** Easy Elytra Takeoff

## **Feature description**
When using **Easy Elytra Takeoff** with the **Colytra** mod, I've realised that the **Vanilla** Elytra works while the **Baubles** Elytra doesn't. That's a bummer. I suggested the creator of the Colytra mod to add support for Easy Elytra Takeoff, but he told me you would have to be the one to add the support for his mod, because _"since their mod contains the logic for that behavior, they just have to check for the existence of a colytra in the item data."_
So, yeah, that's my feature idea/suggestion.

**Comment by ricksouth** [comment]
Hi, thanks for using the mod and opening the issue. Easy Elytra Takeoff is compatible with Colytra. The 1.16 version wasn't correctly compatible but I've release an update which should solve it.
