### ISSUE TITLE
Easy Elytra Takeoff compatibility with Curious Elytra

### ISSUE THREAD

**Issue by tprk77** [Serilum/.issue-tracker#189]
## **Information**
Mod name: Easy Elytra Takeoff 

## **Feature description**
Easy Elytra Takeoff does not seem to work with [Curious Elytra](https://www.curseforge.com/minecraft/mc-mods/curious-elytra), which allows the the Elytra to be equiped on a back slot. It would be nice if these two mods were made compatible.

**Comment by tprk77** [comment]
I noticed that this is probably a dupe of #95.

But I wonder, is there any possibility of a "compatibility mod" that could depend on both mods? (Avoiding the need to add a direct dependency on Curious Elytra.)

**Comment by ricksouth** [comment]
Colytra is already compatible, I've asked the author to see if the same code can be extended to be used with Curious Elytra.

https://github.com/TheIllusiveC4/CuriousElytra/issues/9

**Comment by ricksouth** [comment]
Version 1.5 adds support for Curious Elytra! :)

https://www.curseforge.com/minecraft/mc-mods/easy-elytra-takeoff
