### ISSUE TITLE
Configurable Villager Names

### ISSUE THREAD

**Issue by DesertMoonGW** [Serilum/.issue-tracker#19]
## **Information**
Mod name: Villager Names

## **Feature description**
Allow us to remove and add whatever names for villagers we want.

**Comment by ricksouth** [comment]
Version 2.0 adds this feature! Read the description for more detail; [https://www.curseforge.com/minecraft/mc-mods/villager-names](https://www.curseforge.com/minecraft/mc-mods/villager-names).

Thanks for using the mod and the idea!
