### ISSUE TITLE
Named wandering traders and guard villagers aren't refered to by their names in Villager Death Messages

### ISSUE THREAD

**Issue by selened** [Serilum/.issue-tracker#191]
Minecraft version: 1.15.2
Forge version: 31.2.20
Environment: Singleplayer

Mod name: Villager Death Messages
Mod version: 1.4

So while the mod works with named and unnamed villagers, it doesn't work with named wandering traders or named guard villagers from the mod Guard Villagers. The chat message only refers to them as "a special villager" instead of their name provided by a name tag

**Comment by ricksouth** [comment]
Thanks for letting me know! I've fixed it in version 1.5 of the mod
