### ISSUE TITLE
[Enchanting Commands]

### ISSUE THREAD

**Issue by DarkPoke** [Serilum/.issue-tracker#194]
## **Information**
(you can remove whatever is not applicable)
Minecraft version: 1.12.2
Forge version: 14.23.5.2854
Environment: Singleplayer

Mod name: Enchanting Commands
Mod version: 1.0

## **Question**
I have 2.

Where would I find the config for the command? Since I can't seem to find it anywhere in my config folder, nor can I find any .toml file in my config folder. 

Also, is there a way to increase the enchant limit past the level 157 cap?

**Comment by ricksouth** [comment]
Unfortuntately I am no longer supporting 1.12 and this feature was added in version 1.14 and above. Sorry for the inconvenience. Thanks for the interest though!
