### ISSUE TITLE
Seems incompatible with new forge version 32.0.68

### ISSUE THREAD

**Issue by Fidulus** [Serilum/.issue-tracker#195]
And that already sums it up. 
I had a lot of incompatible mods with the new forge version, so i can't really pinpoint which of the crash reports it was.
But simply try to create a new world and it should crash to desktop.

**Comment by ricksouth** [comment]
I've released updates for every mod which uses commands. It was indeed the forge update which caused the issues. Thanks for letting me know and using the mods! :)
