### ISSUE TITLE
Crash after world loading

### ISSUE THREAD

**Issue by schan-99** [Serilum/.issue-tracker#196]
## **[Information]**
Minecraft version: 1.16.1
Forge version: 32.0.69
Environment: Singleplayer & Multiplayer

#### [Mods]
Mod name: Just Player Heads
Mod version: 1.16-1.1

Mod name: Just Mob Heads
Mod version: 1.16-3.4

## **Description**
Crash after successive world generation.
Most likely it happened because of forge update to **32.0.67** - new update for events registration.
The same (if it is really same) issue was also in [Mekanism](https://github.com/mekanism/Mekanism/issues/6340), [Refined Storage](https://github.com/refinedmods/refinedstorage/issues/2626), [Immersive Engineering](https://github.com/BluSunrize/ImmersiveEngineering/issues/4083), [Curios](https://github.com/TheIllusiveC4/Curios/issues/54), etc.

## **Crash report**
[crash-2020-07-18_02.47.58-server.txt](https://github.com/ricksouth/serilum-mc-mods/files/4940739/crash-2020-07-18_02.47.58-server.txt)
[debug.log](https://github.com/ricksouth/serilum-mc-mods/files/4940740/debug.log)
[latest.log](https://github.com/ricksouth/serilum-mc-mods/files/4940741/latest.log)

**Comment by schan-99** [comment]
Well, sorry for duplicate)

**Comment by ricksouth** [comment]
Thanks for letting me know and using the mods! I've released an update for every mod which uses commands. It was indeed the forge update which caused the issue.
