### ISSUE TITLE
Tree Cutter

### ISSUE THREAD

**Issue by LordHarkon** [Serilum/.issue-tracker#20]
## **Information**
Mod name: Tree Cutter

## **Feature description**
The ability to cut one of the base blocks of the tree and for the rest to break, but won't work if it's placed by a player or something so that you don't just cut your wood house.

**Comment by vico93** [comment]
A thing you could add is some animation of the blocks similar to [TimberJack](https://www.curseforge.com/minecraft/mc-mods/timberjack) (a mod CoverJaguar [did for 1.12](https://github.com/CovertJaguar/Timberjack)), plus maybe making breaking the base while crouching wont make the tree fall.

![](https://media-elerium.cursecdn.com/attachments/202/876/timberjack.gif)

**Comment by ricksouth** [comment]
I'm not great at custom animations, but I think this might be what you're looking for. Thanks for the idea!

[https://www.curseforge.com/minecraft/mc-mods/tree-harvester](https://www.curseforge.com/minecraft/mc-mods/tree-harvester)

**Comment by vico93** [comment]
Thanks @ricksouth , just a question: can we disable the sapling placement when broken the tree?

**Comment by ricksouth** [comment]
Yes that's contained within the config file
