### ISSUE TITLE
[1.15.2] Omega Mute command unusable on multiplayer server

### ISSUE THREAD

**Issue by katubug** [Serilum/.issue-tracker#200]
## **Information**
Minecraft version: 1.15.2
Forge version: 31.2.31
Environment: Multiplayer (dedicated server)

Mod name: Omega Mute
Mod version: 1.2

## **Description**
Hello! I was attempting to use the /omegamute command today on my dedicated multiplayer server (of which I am an op), however, the command does not show up. Neither hitting tab nor doing /help makes it show up. It does work in singleplayer, but I'd really like a way to mute sounds around me while I'm playing online, without having to go into singleplayer, create a world, place whatever thing is making the sound I don't like, and mute it that way. Is there anything that can be done for this?

Thanks!

**Comment by ricksouth** [comment]
Hey, thanks for opening the issue and using the mod! I've just released version 1.4, which should allow you to use the commands in a server environment. I've also added a hotkey (by default a dot) which allows you to reload the sound file.

[https://www.curseforge.com/minecraft/mc-mods/omega-mute](https://www.curseforge.com/minecraft/mc-mods/omega-mute)

**Comment by katubug** [comment]
Awesome, thank you so much!
