### ISSUE TITLE
On 1.16.1, Player Tracking Compass needle doesn't move

### ISSUE THREAD

**Issue by joelsmith** [Serilum/.issue-tracker#201]
## **Information**
Minecraft version: 1.16.1
Forge version: 32.0.74
ATLauncher 3.3.5.2 with Vanilla Minecraft, no other mods.
Environment: Multiplayer

Mod name: Collective
Mod version: 1.16.1-1.35

Mod name: Player Tracking Compass
Mod version: 1.16.1-1.2

## **Description**
The Player Tracking Compass worked great in 1.15, but it doesn't seem to work in 1.16.1.

* When playing with the mod, we place a Tracking Compass in the hot bar
* We right click on it
* We get a message saying "The compass is pointing at OtherPlayer"
* We spin around, but the direction of the needle's compass never changes. No matter which direction we're facing, or where we are, the compass needle never moves.

Thanks for a great mod and we look forward to being able to use it on 1.16.

## **Crash report**
N/A

**Comment by ricksouth** [comment]
I've released a new version for 1.16.2 which should solve the problem you were having. Unfortunately 1.16.1 is not supported anymore. Thanks for opening the issue and using the mod!

https://www.curseforge.com/minecraft/mc-mods/player-tracking-compass/files

**Comment by ghost** [comment]
This is happening again in 1.16.3, the compass always points to where the player was standing and never to where the player is.
