### ISSUE TITLE
[Omega Mute] (1.16.1) Mekanism machines not muted

### ISSUE THREAD

**Issue by ZAKsPop** [Serilum/.issue-tracker#205]
## **Information**
Minecraft version: 1.16.1
Forge version: 32.0.75
Environment: Singleplayer / Multiplayer

Mod name: Mekanism
Mod version: Mekanism-1.16.1-10.0.3.426

## **Description**
I am trying to mute the crusher.
I listen and see it listed as tile.machine.crusher
I type omegamute mute tile.machine.crusher
 The result is:
You have stopped listening to the active sounds. To toggle it
on use '/omegamute listen' again.
By using the wildcard string 'tile.machine.crusher', the following
1 sound events have been muted:
mekanism:tile.machine.crusher
The soundmap file has been updated.

It doesn't mute it.

## **Crash report**
It doesn't crash.

**Comment by ricksouth** [comment]
I'm trying to replicate the issue, but can't turn on the crusher. What do I need? :P
