### ISSUE TITLE
crash on world creation[1.16.1]

### ISSUE THREAD

**Issue by SDUBZ** [Serilum/.issue-tracker#207]
## **Information**
Minecraft version: 1.16.1
Forge version: alllootdrops-1.16-2.0.jar
Environment: Singleplayer

Mod name: All loot drops
Mod version: 2.0

## **Description**
created a world
Encountered an unexpected exception
java.lang.NullPointerException: null
	at net.minecraft.entity.ai.attributes.AttributeModifierManager.func_233795_c_(SourceFile:62) ~[?:?]
	at net.minecraft.entity.LivingEntity.func_233637_b_(LivingEntity.java:1728) ~[?:?]
	at net.minecraft.entity.LivingEntity.func_110138_aP(LivingEntity.java:1508) ~[?:?]
	at net.minecraft.entity.LivingEntity.<init>(LivingEntity.java:206) ~[?:?]
	at net.minecraft.entity.MobEntity.<init>(MobEntity.java:107) ~[?:?]

## **Crash report**
[crash-2020-07-27_23.18.23-server.txt](https://github.com/ricksouth/serilum-mc-mods/files/4982272/crash-2020-07-27_23.18.23-server.txt)

logs:
[latest.log](https://github.com/ricksouth/serilum-mc-mods/files/4982271/latest.log)

**Comment by ricksouth** [comment]
Seems like an incompatibility problem with another mod passing a null entity. Nonetheless I've fixed it in version 1.38 of Collective, All Loot Drops doesn't need an update. Thanks for opening the issue!

https://www.curseforge.com/minecraft/mc-mods/collective/files/all

**Comment by SDUBZ** [comment]
there is a bigger issue here man 
![image](https://user-images.githubusercontent.com/14084377/90953725-6438a680-e4b1-11ea-9adf-cadc0b631e8f.png)
the twitch app doesnt know of newer versions

actually you derped big time here 
![image](https://user-images.githubusercontent.com/14084377/90953758-a9f56f00-e4b1-11ea-81b8-e2625dcaa8a3.png)

**Comment by SDUBZ** [comment]
there is no build 38 for 1.16.1
