### ISSUE TITLE
"Ticking entity" crash in the Nether relating to Fireballs

### ISSUE THREAD

**Issue by tlsctf2** [Serilum/.issue-tracker#208]
## **Information**
Minecraft version: 1.15.2
Forge version: 31.2.31
Environment: Singleplayer

Mod name: Passive Endermen
Mod version: 1.1

## **Description**
In the Nether, seemingly at random (I never got to get the cause to render on-screen), this mod will cause a "Ticked entity" crash to occur. I asked a Discord server I'm in, and it seems like something to do with an Enderman and a Fireball was the issue. I was advised to uninstall this mod to test it, and it fixed the issue when I did. I've included a crash report from the first time this happened to me today.

## **Crash report**
[crash-2020-07-27_14.57.59-server.txt](https://github.com/ricksouth/serilum-mc-mods/files/4984661/crash-2020-07-27_14.57.59-server.txt)

**Comment by GiggySmalls** [comment]
I have just created an issue describing the same thing. I could not say for sure that it was a fireball issue but it always occurred near fortresses so you could be right. Hopefully this can be fixed...

**Comment by ricksouth** [comment]
Thanks @tlsctf2 and @GiggySmalls !

I've fixed it in version 1.2 of the mod, for all supported minecraft versions. I wasn't able to replicate it but am pretty certain where the problem was. Let me know if it still doesn't work as intended though!
