### ISSUE TITLE
Name Tag Tweaks Crashes on Latest Version of 1.16.1 Forge

### ISSUE THREAD

**Issue by Orange1861** [Serilum/.issue-tracker#209]
## **Information**
Minecraft version: 1.16.1
Forge version: 32.0.97
Environment: Singleplayer / Multiplayer

Mod name: Name Tag Tweaks
Mod version: 1.16-1.1

## **Description**

This mod crashes on the latest version of forge on start up.

## **Crash report**

[latest.log](https://github.com/ricksouth/serilum-mc-mods/files/4992758/latest.log)

**Comment by ricksouth** [comment]
This has been fixed in v1.2 for Minecraft 1.16.2. Thanks for opening the issue!
https://www.curseforge.com/minecraft/mc-mods/name-tag-tweaks/files
