### ISSUE TITLE
Villager Names Vs Railcraft

### ISSUE THREAD

**Issue by chriskeena** [Serilum/.issue-tracker#21]
## **Information**
Minecraft version: 1.12.2
Forge version: 14.23.5.2847
Environment: Singleplayer

Mod name: Villager Names
Mod version: 1.4

## **Description**
getting problems with villagers from Railcraft not interacting while this mod is loaded.
Since the Railcraft project seems to have halted I'm hoping a fix is possible from your end.

## **Crash report**
If available.

**Comment by ricksouth** [comment]
I'm not sure what would've caused the problem. Unfortunately I'm only updating the mods for 1.14+, I had to draw the line somewhere. If Railcraft updates to a later version I'll definitely try a workaround. Thanks for using the mod though!
