### ISSUE TITLE
Totemic Villager Error

### ISSUE THREAD

**Issue by hugonoss** [Serilum/.issue-tracker#210]
## **Information**
Minecraft version: 1.12.2
Forge version: 14.23.5.2854
Environment: Singleplayer

Mod name: Villager Names
Mod version: 1.4

## **Description**
I tried to trade with a villager from Totemic, no GUI popped up while an error message appeared.

## **Crash report**
[crash-2020-07-29_22.41.16-server.txt](https://github.com/ricksouth/serilum-mc-mods/files/4995919/crash-2020-07-29_22.41.16-server.txt)

**Comment by ricksouth** [comment]
This has been fixed in later versions but only in 1.14.4 and above. I no longer support 1.12. Thanks for opening the issue though!
