### ISSUE TITLE
How do you change the despawn timer?

### ISSUE THREAD

**Issue by be4ryllium** [Serilum/.issue-tracker#211]
I'm playing with one of your mods(Configurable despawn timer) and i do not know how to change the timer.

Minecraft version: 1.16.1
Forge version: 32.0.97
Environment: Singleplayer

Mod name: Configurable despawn timer
Mod version: 1.3

Is there a command? Is there a setting? Pls help because this seems like an easy question
?

**Comment by ricksouth** [comment]
Thanks for the interest in the mod! There is a config file located in ./config/ named confdespawntimer.toml where you can change the settings. This is where all the config files are located for other mods as well.
