### ISSUE TITLE
Portal spread 1.16+ default configuration should include 1.16+ blocks

### ISSUE THREAD

**Issue by InsaneGrox** [Serilum/.issue-tracker#212]
## **Information**
Mod name: Nether Portal Spread

## **Feature description**
I think that versions of nether portal spread above 1.16 should spawn nether blocks added in 1.16 for consistancy reasons, especially since the abandoned portals that generate use newer blocks surrounding them as well, I even created a messy custom temporary-ish configuration that could be used as a basis that I'm using for myself, it doesn't have everything but it has some of the new stuff like trees being converted to the nether trees, grass being converted to nylium instead of netherrack, gold ore being converted to it's netherrack equivilant, and cobblestone being converted to blackstone (since it's basically identical)

`stone; [netherrack>10 + magma_block>2 + nether_quartz_ore>1],
grass; [nether_sprouts>1],
cobblestone; [blackstone>1],
grass_block; [crimson_nylium>1],
dirt; [netherrack>1],
coarse_dirt; [soul_soil>1],
sand; [soul_sand>1],
gravel; [soul_soil>1],
stone_bricks; [nether_bricks>2 + red_nether_bricks>1],
sea_lantern; [glowstone>1],
farmland; [soul_sand>1],
wheat; [nether_wart>1],
gold_ore; [nether_gold_ore>1],
fern; [nether_sprouts>1],
oak_leaves; [nether_wart_block>1],
spruce_leaves; [nether_wart_block>1],
birch_leaves; [warped_wart_block>1],
jungle_leaves; [warped_wart_block>1],
acacia_leaves; [nether_wart_block>1],
dark_oak_leaves; [warped_wart_block>1],
oak_log; [crimson_stem>1],
spruce_log; [crimson_stem>1],
birch_log; [warped_stem>1],
jungle_log; [warped_stem>1],
acacia_log; [crimson_stem>1],
dark_oak_log; [warped_stem>1]`

**Comment by ricksouth** [comment]
Thanks for working the config out yourself instead of just giving the idea! I'm definitely going to take a look at implementing this in the next few days

**Comment by OniOnyMan** [comment]
I'm agree with proposed feature and want to suggest some sand derivative blocks replacing: 
`sand; [soul_sand>1 + soul_soil>1], sandstone; [blackstone>1], cut_sandstone; [polished_blackstone>], chiseled_sandstone; [chiseled_polished_blackstone>1], smooth_sandstone; [basalt>1], red_sand; [soul_soil>1 + soul_sand>1], red_sandstone; [blackstone>1], cut_red_sandstone; [polished_blackstone>], chiseled_red_sandstone; [chiseled_polished_blackstone>1], smooth_red_sandstone; [basalt>1]`

**Comment by James103** [comment]
You forgot a `1` in `[polished_blackstone>]`; it should be `[polished_blackstone>1]`.

**Comment by ricksouth** [comment]
I've added a combination of both your config files in the new 4.0 version, which I've just released. Thank you!

[https://www.curseforge.com/minecraft/mc-mods/nether-portal-spread](https://www.curseforge.com/minecraft/mc-mods/nether-portal-spread)

@James103 well spotted :)
