### ISSUE TITLE
Name Tag Tweaks won't load

### ISSUE THREAD

**Issue by ravenbuilder934** [Serilum/.issue-tracker#213]
## **Information**
Minecraft version: 1.16.1
Forge version: 32.0.98
Environment: Singleplayer

Mod name: Name Tag Tweaks
Mod version: 1.1

## **Description**
When I try to open Minecraft, I get this screen: 
![Annotation 2020-07-30 173453](https://user-images.githubusercontent.com/63612548/88981284-39c94400-d28b-11ea-9c39-02f7db78cc38.png)

## **Crash report**
Didn't crash. Latest.log [here](https://gist.github.com/ravenbuilder934/7c44a4cc77c98541abb48c80a762c0f2).

**Comment by ricksouth** [comment]
This has been fixed in the latest version for Minecraft 1.16.2. Thanks for using the mod!
https://www.curseforge.com/minecraft/mc-mods/name-tag-tweaks/files
