### ISSUE TITLE
Starter Kit: Can I specify the dyed color version of an item, like leather armor?

### ISSUE THREAD

**Issue by jengendler** [Serilum/.issue-tracker#218]
## **Information**
(you can remove whatever is not applicable)
Minecraft version: 1.15.2+

Mod name: Starter Kit
Mod version: 1.0

## **Question**
I'd like a starting kit to include a set of purple dyed leather armor but am unsure how to achieve this. I looked up the format for doing so using the /give command but it didn't work with this mod. Is it possible to have a dyed version of an item like this set in the txt file? I would love to know! Thank you!

FYI, I use this mod a lot for testing modpacks, as I have to constantly start new worlds all the time to test new configurations. So, having a starter kit automatically load into my inventory saves me so much time. Thank you for that. :)

**Comment by James103** [comment]
Assuming #203 is implemented, you could use a custom loot table to do exactly that, as well as unlock many more possibilities for populating the player's starting inventory.
For this specific case, the minimal custom loot table would be as follows: `{"type":"chest","pools":[{"rolls":1,"entries":[{"type":"item","weight":1,"name":"minecraft:leather_chestplate","functions":[{"function":"set_count","count":1},{"function":"set_nbt","tag":"{display:{color:9341695}}"}]}]}]}` (replace `leather_chestplate` with any other leather armor (including horse armor) and replace `{color:9341695}` with any color of your choosing).

**Comment by ricksouth** [comment]
Hey! Check out version 2.0 of Starter Kit. It adds a '/starterkit set' command to write the entire inventory of the user to the config file. This also means it has support for NBT tags for things such as enchantments and written books. Let me know if anything should be different. Thanks for using the mod!

[https://www.curseforge.com/minecraft/mc-mods/starter-kit](https://www.curseforge.com/minecraft/mc-mods/starter-kit)
