### ISSUE TITLE
ALL MODS FOR FABRIC?

### ISSUE THREAD

**Issue by ElLuki** [Serilum/.issue-tracker#219]
## **Information**
(you can remove whatever is not applicable)
Minecraft version: 1.16.1
Forge version: no se :v
Environment: Singleplayer / Multiplayer

Mod name: Mod
Mod version: 1.16.1

## **Question**
?

Hello Man No have all mods for fabric?

**Comment by ElLuki** [comment]
Hello?

**Comment by ElLuki** [comment]
### _**Hello?**_

**Comment by ricksouth** [comment]
Hello!

All of my mods are for Forge, with no plans to port them to Fabric. Thanks for the interest though!
