### ISSUE TITLE
Dismount Entity Mod not work on ViesCraft - Airships! Mod

### ISSUE THREAD

**Issue by ColaLiao** [Serilum/.issue-tracker#22]
Minecraft version: 1.12.2
Forge version: 14.23.5.2847
Environment: Singleplayer

Mod name: Dismount Entity Mod
Mod version:  dismounte_1.12-1.0.jar

## **Question**
Not work on ViesCraft - Airships! Mod

**Comment by ricksouth** [comment]
Version 1.1 will work with all (modded) mounted entities. Thanks for the suggestion.
