### ISSUE TITLE
Zombie and Skeleton Horses burn during the day when under leaves, even when it is raining

### ISSUE THREAD

**Issue by The-Bernician-Lamb** [Serilum/.issue-tracker#222]
## **Information**
Minecraft version: 1.16.1
Forge version: 32.0.107
Environment: Singleplayer

Mod name: Zombie Horse Spawn and Skeleton Horse Spawn
Mod version: 2.4, 1.3

## **Description**
I have found that when I've been messing around in some of my Creative worlds, that Zombie Horses and Skeleton horses are not sheltered from the sun when they are under both modded and vanilla leaf blocks, despite vanilla zombies and skeletons being just fine. Oddly enough the undead horses will still burn under leaf blocks even when it is raining and when they wander out from underneath the leaves, the rain then puts them out. 

Zombie Horses and Skeleton Horses:
![2020-08-09_16 55 24](https://user-images.githubusercontent.com/64381954/89737133-a05a1900-da66-11ea-8250-41a5fa866620.png)
Vanilla Zombies and Skeletons in the same situation:
![2020-08-09_16 56 10](https://user-images.githubusercontent.com/64381954/89737167-cf708a80-da66-11ea-8194-5205b809c182.png)

**Comment by ricksouth** [comment]
Thanks for reporting it! I've fixed it in version 1.39 of Collective. The other mods didn't need an update
