### ISSUE TITLE
How to make my mods trees compatitable with tree harvester mod?

### ISSUE THREAD

**Issue by GamehunterKaan** [Serilum/.issue-tracker#223]
## **Information**
Minecraft version:1.15.2
Forge version: 31.20
Environment: Singleplayer / Multiplayer

Mod name: Tree Harvester
Mod version: 1.3

My Mods Name:Colorful Biomes

**Comment by ricksouth** [comment]
You just have to make sure to extend the LogBlock and LeavesBlock, just like the vanilla code. That's what my mod checks for. 1.16 changed the LogBlock to something else I believe but the idea is the same. Just look at how vanilla does it.

Thanks for the interest!
