### ISSUE TITLE
net::ERR_CERT_DATE_INVALID when accessing minecraft.natamus.com

### ISSUE THREAD

**Issue by James103** [Serilum/.issue-tracker#224]
## **Information**
Website URL: https://minecraft.natamus.com/
Problematic resource URL: https://cors.ntmsdata.com:8080/https://addons-ecs.forgesvc.net/api/v2/addon/search?searchFilter=serilum&gameId=432

## **Description**
When attempting to access the given website using a debugger, the debugger reports that a different URL (also listed above) that was queried has returned an error code saying that its certificate expired on July 31, 2020. As of the time of posting, it's been 11 days since certificate expiry.

This means that the website itself does not work properly (no mods are loaded, and the number of unique mods and total downloads are hidden).

**Comment by James103** [comment]
Fixed as of 15 August 2020 (certificate renewed).

**Comment by ricksouth** [comment]
I fixed it a few days ago after reading your post via my email. Thanks for letting me know! :)

**Comment by James103** [comment]
I'm getting `net:ERR_CERT_DATE_INVALID` again while attempting to access minecraft.natamus.com because the certificate expired last week, on September 23, 2021. Will you please fix it as soon as possible?

**Comment by James103** [comment]
The certificate has now been updated, and the website can be accessed over HTTP. Closing this again for now.
