### ISSUE TITLE
Idea: Player skin/head caching for Just Player Heads

### ISSUE THREAD

**Issue by James103** [Serilum/.issue-tracker#228]
## **Information**
Mod name: Just Player Heads

## **Feature description**
The Mojang API functions used to fetch player skins for use in Just Player Heads limits request rates such that you can't successfully request the same profile twice within 1 minute of each other. Additionally, no/bad internet connections (whether it be on user, server, or Mojang's end) can prevent the head from being generated properly. Would it be possible to have Just Player Heads use the caches it creates when generating player heads as well as Minecraft's own player skin cache to continue generating player heads as a fallback measure in case no internet service is available?

**Comment by ricksouth** [comment]
I think that would be a welcome feature! I think it would be best to clear the cache on a server reboot and add an option to do it by command after a skin change. And a config option to disable it completely.

I'll take a look in the next few days!

**Comment by ricksouth** [comment]
![2020-08-21_13 40 46](https://user-images.githubusercontent.com/38502394/90887090-007c8380-e3b4-11ea-934f-d7ed90476fdb.png)

Head caching on the way :)

**Comment by ricksouth** [comment]
Version 1.4 of the mod adds the texture cache feature. Thanks again for the idea!

https://www.curseforge.com/minecraft/mc-mods/just-player-heads/files
