### ISSUE TITLE
Village Spawn Point for 1.15.2

### ISSUE THREAD

**Issue by dreckz** [Serilum/.issue-tracker#23]
## **Information**
Mod name: **Village Spawn Point**

## **Feature description**
I really loved the simplicity, yet incredibly useful mechanic of spawning within or near a village.  It really helped craft an awesome RPG experience for one of my modpacks (Treasures of Altera).  I'm gonna be creating a sequel for 1.15.2 and I would LOVE to see version ported up to 1.15! :)

That's all!

**Comment by ricksouth** [comment]
Sorry for the wait! I've found a solution and just released a 1.15.2 version. Thanks for the interest!

[https://www.curseforge.com/minecraft/mc-mods/village-spawn-point](https://www.curseforge.com/minecraft/mc-mods/village-spawn-point)
