### ISSUE TITLE
Botania Functional Flora/Generating Flora spawning from bonemeal is OP. (Random Bone Meal Flowers)

### ISSUE THREAD

**Issue by dudeloony** [Serilum/.issue-tracker#230]
## **Information**
Minecraft version: 1.15.2
Forge version: 1.15.2-31.2.0
Environment: Singleplayer
Mod name: [Mod File Name] rndbmflowers_1.15-1.2.jar and Botania-r1.15-388.jar
Mod version: x.x

## **Description**
There was no crash or error, but your mod creates Botania generating flora and functional flora when bonemeal is applied, meaning that items that are normally late game can easily be gotten with just some bonemeal. It's nothing particularly hard to deal with. I for one just throw the flower away when that happens, but it could hurt progression in modpacks where people want to go forward and just assume that is how you are supposed to get functional flora. It's no biggie but it would be helpful for compatibility for that to be fixed.
P.S, it also spawns glimmering flowers, which I like even though normally those would cost glowstone.
## **Crash report**
N/A

**Comment by ricksouth** [comment]
The mod first generates a list of all the flowers in ./config/randombonemealflowers. See the description for more details: https://www.curseforge.com/minecraft/mc-mods/random-bone-meal-flowers

Here you can add an exclamation mark in front of the flowers you don't want to use. In this case the OP flowers from Botania. Thanks for using the mod!

**Comment by TheNimbleNinja** [comment]
i black listed all of botania flowers and they are  still spawning from bonemeal!

**Comment by JaxckLl** [comment]
I have the same problem. Blacklist has ALL of Botania marked, still getting more Functional Flora than anything else.

**Comment by Lucipo** [comment]
![image](https://user-images.githubusercontent.com/36358294/211450050-7788ef30-357c-4bf4-b8db-1b239c9a7ea7.png)

The config does not put any of the botania flowers into the blacklist file, I have yet to test if blacklisting them with ! even works but judging by how it doesnt put it into there, it may be broken still.

1.19.2 forge latest version btw

**Comment by ricksouth** [comment]
This has (finally) been fixed in version 4.1 of Random Bone Meal Flowers. Tested with Botania in 1.19.2. Thank you!

https://www.curseforge.com/minecraft/mc-mods/random-bone-meal-flowers/files
