### ISSUE TITLE
getRequestedBlockAroundEntitySpawn removes passengers

### ISSUE THREAD

**Issue by Sindarin27** [Serilum/.issue-tracker#233]
## **Information**
Minecraft version: 1.15.2
Forge version: 31.2.27
Environment: Singleplayer & Multiplayer

Mod name: Collective
Mod version: 1.35

## **Description**
When finding a block using the method getRequestedBlockAroundEntitySpawn, the method appears to be looping through all passengers of the given entity, and removes all of them. This causes issues with mods allowing a player to "carry" an entity as a passenger. There also appears to be no reason for removing these passengers, thus it should be possible to safely remove this part of the code.

**Comment by ricksouth** [comment]
Ah very well found. At first it prevented the spawn within that piece of code. Later I made it return the position instead. Working on an update right now!

**Comment by ricksouth** [comment]
I've fixed it in version 1.39 of Collective. The passenger code has been moved to No Hostiles Around Campfire, as was always the intention. Thanks for doing the research and using the mod!
