### ISSUE TITLE
I can't download

### ISSUE THREAD

**Issue by Modeeves** [Serilum/.issue-tracker#237]
## **Information**
Minecraft version: 1.16.2
Forge version: 33.0.2
Environment: Singleplayer / Multiplayer

Mod name: Collective
Mod version: 1.39

## **Comment**
!
Hello! I just wanna say first that your mods are amazing.  My problem now is when I was trying to update it to 1.16.2, I can't do anything.  Whenever I try to download your Collective Lib, it just says "download failed".  Is there something going on right now for the 1.16.2 version?  I tried downloading other MODS and they were all working fine and I was able to download them all.

**Comment by ricksouth** [comment]
Are you using the Twitch launcher or directly downloading it from curseforge.com? The Twitch launcher unfortunately does not support 1.16.2 yet and gives some problems. In the future I hope Overwolf adds support a lot quicker.
