### ISSUE TITLE
Occasional crash.

### ISSUE THREAD

**Issue by ValianceHD** [Serilum/.issue-tracker#24]
Occured when trying to break out of a web cause by an infernal mob. Seemingly a rare crash even under identical circumstances. 
[crash-2020-02-08_16.36.03-server.txt](https://github.com/ricksouth/serilum-mc-mods/files/4175284/crash-2020-02-08_16.36.03-server.txt)

**Comment by ricksouth** [comment]
This has been fixed in version 1.3, thanks for letting me know! Even though I don't officially support Minecraft 1.12 anymore, I've also updated it because I saw you were using it.
