### ISSUE TITLE
Glowstone Dust and nearby player entities

### ISSUE THREAD

**Issue by HatTrkPatrk** [Serilum/.issue-tracker#240]
## **Information**
(you can remove whatever is not applicable)
Minecraft version: 1.16.2
Environment: Multiplayer

Mod name: Edibles
Mod version: 1.1

## **Question**
Does the Glowstone Dust effect reveal nearby players? If so, could this possibly be disabled when PvP is active?

**Comment by ricksouth** [comment]
Thanks for opening the issue! I don't think the glow effect should affect players at all, because getting a sudden potion effect would be a little weird. Other mobs don't mind I'm sure ;)

I've changed it in Edibles version 1.2!

https://curseforge.com/minecraft/mc-mods/edibles
