### ISSUE TITLE
Applying to other mobs?

### ISSUE THREAD

**Issue by Iggynatz** [Serilum/.issue-tracker#241]
I grabbed the 1.12 version of Weaker Spiderwebs quickly and tested it before reading thoroughly what it did. I see now it only works for players. I'm using it with MCA and Minecolonies and was hoping I could find a way to make it so that npc villagers (and vanilla ones for that matter) could also break the webs. I don't know if this is possible without allowing all entities to break them but I'd even take that as an option if nothing else. If this could be added that would be great! If not, no biggie. Thank you either way for all your mods.

**Comment by ricksouth** [comment]
It's not really where I want to take the mod, as it will take a lot more computing power to check when other entities are in a web block. Thanks for the idea though and the kind words!
