### ISSUE TITLE
Make trades refresh when trading something else, instead of just be infinite (configuration option)

### ISSUE THREAD

**Issue by winsrp** [Serilum/.issue-tracker#243]
Mod name: infinite trading

## **Feature description**
I've had this amazing idea.. -> Make trades refresh when trading something else, instead of just be infinite (configuration option), so trades are infinite as long as you trade something different to refresh the rest of the trades.

**Comment by ricksouth** [comment]
I understand why you'd want it, but that's basically vanilla behaviour already. Not where I'd like to take the mod's functionality. Thanks for using the mod and the idea though!
