### ISSUE TITLE
A Nether down below

### ISSUE THREAD

**Issue by ghost** [Serilum/.issue-tracker#244]
## **Information**
Mod name: Underworld Nether

## **Feature description**
I've had this amazing idea, you could do a mod that actually places the nether below the overworld, maybe separated by obsidian, or you could make an item within the mod to break the roof of the nether, my idea was that the layer of bedrock at the bottom of the overworld was also the same layer as the roof of the nether or something like that, and instead of creating a portal, you could make an item, to break the overworld floor, and when you break it below the 0, you'd fall into the nether, maybe, with a seamless nether portal below the layer 0, it would probably be easier to do it this way

**Comment by James103** [comment]
This can already be done with the [Immersive Portals](https://www.curseforge.com/minecraft/mc-mods/immersive-portals-mod) mod.
