### ISSUE TITLE
Easy Elytra Takeoff - Winged mod compatibility

### ISSUE THREAD

**Issue by James103** [Serilum/.issue-tracker#245]
## **Information**
Mod name: Easy Elytra Takeoff

## **Feature description**
If only there was a way to make the soulbound wings from the Winged mod compatible with Easy Elytra Takeoff (if not already compatible).

**Comment by James103** [comment]
Note that this requires Fabric support for your mods in order for the idea to be implemented, as your mods are currently only supported on Forge and Winged mod is only on Fabric.

**Comment by ricksouth** [comment]
Let me know if they port to Forge, I'll give it a try :)

**Comment by James103** [comment]
@ricksouth Will you please re-open this issue and/or add the requested Winged mod compatibility for the Fabric version of Easy Elytra Takeoff, as since this issue was last active, you have ported Easy Elytra Takeoff to Fabric?

**Comment by ricksouth** [comment]
Thanks for open the issue and giving the mod a try! Version 3.1 of Easy Elytra Takeoff adds support for modded elytra's and Winged wings in Fabric. :)

https://www.curseforge.com/minecraft/mc-mods/easy-elytra-takeoff-fabric/files
