### ISSUE TITLE
bug with bamboo jungle biomes

### ISSUE THREAD

**Issue by lebanni** [Serilum/.issue-tracker#247]
## **Information**
Minecraft version: 1.15.2
Forge version: 31.2.36
Environment: Singleplayer / Multiplayer : both.

Mod name: bamboospreads
Mod version: 1.1

## **Description**
In bamboo jungle biomes, the mod cause bamboos to instant break and gazillion saplings floating around.
I don't know if it's relevant but I have terraforged mod installed.

## **Crash report**
No crash.

**Comment by ricksouth** [comment]
Apparently Mojang uses static references to blocks, so when I had overwritten the bamboo block for this mod the biome generation still tried to use the old bamboo block. It can't find it and the biome generation get's messed up.

I've tried a few things but couldn't change the biome generation in an appropriate way. I think I'll have to make a separate bamboo spreading block and leave the default generation alone.

I'm giving this another try in the next few days. Thanks for bringing it to my attention!

**Comment by EightBlade** [comment]
I'm having this same issue.
