### ISSUE TITLE
Sleep Sooner not working correctly

### ISSUE THREAD

**Issue by BigAl607** [Serilum/.issue-tracker#248]
Minecraft version: 1.16.1
Forge version: 32.0.108
Environment: Singleplayer

Mod name: Sleep Sooner
Mod version: 1.16-2.1

## **Description**
Right-clink on the bed and all I get is the comments in the game chat. Doesn't actually allow me to sleep or increase the time of day

## **Crash report**
n/a
![sleep-sooner](https://user-images.githubusercontent.com/13182567/91650688-ab460f00-ea50-11ea-8b06-5bc1803890cb.png)

**Comment by ricksouth** [comment]
It's been a while, but in my test environment it works fine. Let me know if the issue still persists and I'll reopen the issue. Thanks for trying the mod out.

![2020-10-03_01 17 50](https://user-images.githubusercontent.com/38502394/94976810-6cefb400-0516-11eb-9e0b-969de9f35ed8.png)

**Comment by BigAl607** [comment]
It's still not working, but I'm now using the 1.16.3 version, 1.16.3_2.1


![sleep-sooner2](https://user-images.githubusercontent.com/13182567/94981095-7587c080-04fd-11eb-966f-71109b637309.png)

**Comment by ricksouth** [comment]
My bad, it started to not work after the first day. My test worlds were all on the first day which is why it wasn't a problem. I've fixed it in version 2.2 of the mod. Thanks for opening the issue!

https://www.curseforge.com/minecraft/mc-mods/sleep-sooner
