### ISSUE TITLE
Server actively skipping thousands of entities with blank ids

### ISSUE THREAD

**Issue by Hydraheads** [Serilum/.issue-tracker#249]
## **Information**
Minecraft version: 1.12.2
Forge version: latest
Environment: Multiplayer

Mod name: Configurable despawn timer
Mod version: confdespawnt_1.12-1.0.jar

## **Description**
Ever since I updated my modpack with this mod, the server log has been spammed with:
30.08 10:52:55 [Server] Server thread/WARN Skipping Entity with id minecraft:
30.08 10:52:55 [Server] Server thread/WARN Skipping Entity with id minecraft:
30.08 10:52:55 [Server] Server thread/WARN Skipping Entity with id minecraft:
30.08 10:52:55 [Server] Server thread/WARN Skipping Entity with id minecraft:
30.08 10:52:55 [Server] Server thread/WARN Skipping Entity with id minecraft:
30.08 10:52:55 [Server] Server thread/WARN Skipping Entity with id minecraft:
30.08 10:52:55 [Server] Server thread/WARN Skipping Entity with id minecraft:
30.08 10:52:55 [Server] Server thread/WARN Skipping Entity with id minecraft:
30.08 10:52:55 [Server] Server thread/WARN Skipping Entity with id minecraft:
To be fair, I am not 100% certain this mod causes it (I also updated future mc which switched some ids around), but this is the only mod added in the update that messes with a base minecraft entity actively, so it lines up.  This of course makes the log file way larger.  Does that mean entities are getting saved incorrectly, or what?  In any case, it seems potentially dangerous, is it possible you could look into this?

Another detail for reproducing, items on my server are set to despawn every 30 seconds

## **Crash report**
N/A

**Comment by ricksouth** [comment]
The mod configurable despawn timer doesn't look at entities to skip. It merely sets the lifespan of all new entities in the world to the config value. Seems like another mod is causing the issue. Thanks for using the mod!
