### ISSUE TITLE
Zombie Horse Glitch

### ISSUE THREAD

**Issue by Meskino** [Serilum/.issue-tracker#25]
## **Information**
Minecraft version: 1.12.2
Forge version: 14.23.5.2847
Environment: Singleplayer / Multiplayer

Mod name: Zombie Horse Mod
Mod version: 2.1

## **Description**
Zombie Horse still burn in the day as it rains

## **Crash report**
Not Included.

**Comment by ricksouth** [comment]
Hi, thanks for submitting the issue and using the mod! As of the newest release they don't burn in the rain anymore.

[https://www.curseforge.com/minecraft/mc-mods/zombie-horse-spawn](https://www.curseforge.com/minecraft/mc-mods/zombie-horse-spawn)
