### ISSUE TITLE
Does it work on Fabric?

### ISSUE THREAD

**Issue by vgnoyadesign** [Serilum/.issue-tracker#250]
Minecraft version: 1.16.2
Forge version: I use Fabric
Environment: Singleplayer 

Mod name: Villager Names
Mod version: 1.16.2-2.4.jar

## **Question**
I use Fabric, primarily because of the Sodium Mod that boost performance far beyond OptiFine can do to my PC, but I would love to have this mod working in my game. Sorry if you get this question a lot, but in the mod page there's no reference if it works on Fabric or not, and by just installing it on my game it didn't worked. I have the Collective library installed as well...

Any way, thanks for your incredible mods. 
👍

**Comment by ricksouth** [comment]
Thanks for the interest! Please check out the FAQ:
https://github.com/ricksouth/serilum-mc-mods/wiki/FAQ
