### ISSUE TITLE
java.util.ConcurrentModificationException: null in  *Skeleton Horse Spawn* mod

### ISSUE THREAD

**Issue by SpinyOwl** [Serilum/.issue-tracker#251]
## **Information**
Minecraft version: 1.15.2
Forge version: 31.2.30
Environment: Multiplayer

Mod name: Skeleton Horse Spawn
Mod version: 1.3

## **Description**
java.util.ConcurrentModificationException: null

## **Crash report**
[crash-2020-08-31_15.30.06-server.txt](https://github.com/ricksouth/serilum-mc-mods/files/5150575/crash-2020-08-31_15.30.06-server.txt)

**Comment by James103** [comment]
Are you able to reproduce this crash?

**Comment by SpinyOwl** [comment]
Yeah, it happens when dedicated server just started and someone (in nearest 10 seconds) tries to enter the server.

**Comment by SpinyOwl** [comment]
This happens because you are using iteration mechanism in loop through entities.
Instead try to create some local buffer list for iteration through entities (so changes in original list won't cause such issue)

**Comment by ricksouth** [comment]
Thanks for letting me know and using the mod! I've fixed the issue in the latest version. In the end decided to use "CopyOnWriteArrayList", instead of making a manual copy. The other Spawn mods have been altered as well.

https://www.curseforge.com/minecraft/mc-mods/skeleton-horse-spawn

**Comment by SpinyOwl** [comment]
Thank you 😄
