### ISSUE TITLE
Any chance we can get 1.16.1 version (infinite trading)?

### ISSUE THREAD

**Issue by Xetaxheb** [Serilum/.issue-tracker#254]
Mod name: Infinite trading

## **Question**
Could we get a 1.16.1 version against collective-1.16.1-1.35? There are many mods not updated to 1.16.2 yet (if they even will be) and this is a very useful mod.

**Comment by ricksouth** [comment]
I've unarchived the 1.16.1 version if you still need it. Thanks for using the mod!
