### ISSUE TITLE
despawning eggs have a chance to hatch

### ISSUE THREAD

**Issue by Mr-Clay** [Serilum/.issue-tracker#256]
## **Information**
Mod name: Mod
despawning chicken eggs has over done the chickens in my game. 

## **Feature description**

could there be a config added to give eggs a % chance to hatch instead of always hatch.

**Comment by ricksouth** [comment]
Hi, thanks for using the mod. There is already a config file where you can set the chance an egg hatches. Check the description for more details:

https://www.curseforge.com/minecraft/mc-mods/despawning-eggs-hatch

And the FAQ where the config files are located:

https://github.com/ricksouth/serilum-mc-mods/wiki/FAQ
