### ISSUE TITLE
seed replanting

### ISSUE THREAD

**Issue by Mr-Clay** [Serilum/.issue-tracker#257]
## **Information**
Mod name: Mod

## **Feature description**
have the replanting work with an empty hand, hoe, or right-click. have had issues with needing to dig up a block below the seed and unable to, do to replanting.

**Comment by ricksouth** [comment]
You were able to prevent the replanting by crouching while harvesting, but I've added the 'mustHoldHoeForReplanting' config option in version 2.0. Enabled by default. Thanks for opening the issue and using the mod!

[https://www.curseforge.com/minecraft/mc-mods/replanting-crops](https://www.curseforge.com/minecraft/mc-mods/replanting-crops)
