### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by CatProgrammer-Java** [Serilum/.issue-tracker#258]
## **Information**
Minecraft version: 1.15.2
Forge version: 31.2.36
Environment: Singleplayer

Mod name: Collective lib
Mod version: 1.39

When launching minecraft forge with collective lib then crash with exit code -1

**Comment by James103** [comment]
Do you have the logs and crash report? If so, can you please upload them both here if possible?

**Comment by CatProgrammer-Java** [comment]
here you are
[crash-2020-09-07_17.42.20-client.txt](https://github.com/ricksouth/serilum-mc-mods/files/5183876/crash-2020-09-07_17.42.20-client.txt)
[debug.log](https://github.com/ricksouth/serilum-mc-mods/files/5183878/debug.log)
[latest.log](https://github.com/ricksouth/serilum-mc-mods/files/5183879/latest.log)

**Comment by ricksouth** [comment]
Hi. First of all please download my mods from https://www.curseforge.com/members/serilum/projects alone. All other sites steal their content for advertisement revenue.

It seems like the Collective mod has nothing to do with your crash. Seems like it's a problem somewhere else.
