### ISSUE TITLE
Skeleton Horse Glitch

### ISSUE THREAD

**Issue by Meskino** [Serilum/.issue-tracker#26]
## **Information**
Minecraft version: 1.12.2
Forge version: 14.23.5.2847
Environment: Singleplayer / Multiplayer

Mod name: Skeleton Horse Mod
Mod version: 1.1

## **Description**
Skeleton Horse still burn in the day as it rains

## **Crash report**
Not Included

**Comment by ricksouth** [comment]
Hi, thanks for submitting the issue and using the mod! As of the newest release they don't burn in the rain anymore.

[https://www.curseforge.com/minecraft/mc-mods/skeleton-horse-spawn](https://www.curseforge.com/minecraft/mc-mods/skeleton-horse-spawn)
