### ISSUE TITLE
Collective lib should support 1.16.3

### ISSUE THREAD

**Issue by Tsoccerguy3** [Serilum/.issue-tracker#264]
## **Information**
Minecraft version: 1.16.3
Forge version: 1.16.3-34.0.1
Environment: Singleplayer / Multiplayer

Mod name: collective
Mod version: -1.16.2-1.39

## **Description**
The code should support 1.16.3

## **Crash report**
If available.

**Comment by Tsoccerguy3** [comment]
Only tested with Full Bright mod , Not working in 1.16.3

**Comment by ricksouth** [comment]
Collective now has a 1.16.3 version. Thanks for using the mod!
