### ISSUE TITLE
for fabric？

### ISSUE THREAD

**Issue by KawaiiTamako** [Serilum/.issue-tracker#265]
## **Information**
(you can remove whatever is not applicable)
Minecraft version: 1.15.2
for fabric？
Environment: Singleplayer 

Mod name: Mod
Mod version: x.x

## **Comment**
!

**Comment by James103** [comment]
Related to / duplicate of #250, #219, and #183

Quoting from @ricksouth's earlier responses:
> All of my mods are for Forge, with no plans to port them to Fabric. Thanks for the interest though!

**Comment by ricksouth** [comment]
Thanks for the interest, please check out the FAQ here:
https://github.com/ricksouth/serilum-mc-mods/wiki/FAQ
