### ISSUE TITLE
(Feature Suggestion) Disable leaf break on harvest

### ISSUE THREAD

**Issue by FastBoye127** [Serilum/.issue-tracker#267]
Hi! I love this mod! good to have a decent treechopping mod in 1.15.2. My suggestion is to disable breaking leaves with logs, for those of us who have fast leaf decay handled by another mod. With leaves being broken on harvest, surrounding trees tend to get foliage lopped off, creating bad-looking trees everywhere. It also turns some surrounding trees into leafless vertical logs, rendering TreeHarvester unable to recognize them as trees.

**Comment by ricksouth** [comment]
Thanks for the suggestion and using the mod! I've added a config option in version 1.5 which can be set to False to disable leaves being broken when chopping down a tree.

[https://www.curseforge.com/minecraft/mc-mods/tree-harvester](https://www.curseforge.com/minecraft/mc-mods/tree-harvester)
