### ISSUE TITLE
Compatibility between the mods "dramatic doors" and double doors

### ISSUE THREAD

**Issue by Blugori** [Serilum/.issue-tracker#268]
It would be great if you could add the functionnality of "double doors" to the mod "dramatic doors" for 1.16.1
The mod adds 3 blocks tall doors, that would be epic to see the compatibility :)
Thanks for your work !

**Comment by Blugori** [comment]
The mod "dramatic doors" has been updated to 1.16.3

**Comment by ricksouth** [comment]
I've already had a conversation with the author of Dramatic Doors, and unfortunately compatibility isn't possible at this moment. Thanks for the suggestion though!
