### ISSUE TITLE
Full Brightness Toggle Fabric Support

### ISSUE THREAD

**Issue by DTRW919** [Serilum/.issue-tracker#271]
## **Full Brightness Toggle Fabric Support**

Minecraft version 1.16.1
Multiplayer and Singleplayer

Full Brightness Toggle
Mod version 1.0

I would just like to ask for you to start supporting the Fabric Mod Loader, which is much more lightweight than forge. The reason for this is because many of us players have started switching to this loader, which has an increasing amount of users every single day, using this could get you more downloads, especially for the full brightness toggle mod, which is a good feature for cave explorers. Thanks for reading this ;D

**Comment by James103** [comment]
Your specific use case (Fabric support for Full Brightness Toggle) can have the same effects replicated via the following:
1. Download and install Fabric mod loader.
2. Download and install Fabric API.
3. Download and install [Client Commands](https://github.com/Earthcomputer/clientcommands/releases/tag/v2.4.7).
4. In-game, run `/cgamma 16` for full brightness even in caves. Use lower values for a less drastic increase in brightness.

**Comment by ricksouth** [comment]
Thanks for the interest! Please use the steps James provided or read the FAQ on Fabric versions:
https://github.com/ricksouth/serilum-mc-mods/wiki/FAQ
