### ISSUE TITLE
Config for Adult only dropping the head

### ISSUE THREAD

**Issue by ghost** [Serilum/.issue-tracker#273]
## **Information**
Mod name: JustMobHeads (any version, but particularly 1.12.2)

## **Feature description**
Would it be possible to drop heads only from adult chickens?  I realise if your mod changes LootTables this might not be possible.  Im working on a skyblock modpack and want to make it a bit harder for the player to gain the heads.  The chicken heads are used to craft Modded Chicken Spawn Eggs

Thank You

**Comment by ricksouth** [comment]
I've added the config option 'onlyAdultMobsDropTheirHead' in version 3.7. Unfortunately I no longer support version 1.12. Hope it's still useful. Thanks for using the mod!

[https://www.curseforge.com/minecraft/mc-mods/just-mob-heads](https://www.curseforge.com/minecraft/mc-mods/just-mob-heads)

**Comment by ghost** [comment]
Thank you for the update, Its a nice mod !
