### ISSUE TITLE
Plans to Fabric

### ISSUE THREAD

**Issue by vico93** [Serilum/.issue-tracker#274]
Does Serilum have plans to port his mods to Fabric? Didnt see anything related to it on FAQ, thats why i'm asking.

I moved from Forge and for 1.16+ i began using Fabric as main modloader for my modpack and i got a brutal performance improvement, testing both with the same mods (the ones who have Forge and Fabric ports).

**Comment by ricksouth** [comment]
I'm keeping it in mind, but for now I don't have plans for a fabric version. With the current infrastructure it would mean having another 100+ projects pages. Maybe if in the future a better separation in the file upload section exists, I'll consider it again. Thanks for the interest though!
