### ISSUE TITLE
Bulk download failed

### ISSUE THREAD

**Issue by dheivs** [Serilum/.issue-tracker#275]
Hello Serilum,

I tried downloading all of your mods for 1.16 and followed the instructions, but when I clicked on "Start manifest download for 98 mods", it keeps on saying that the ZIP file "download failed - no file".   So I can't even proceed to put it to CMPDL yet as the files are empty.

Thank you ^_^

![image](https://user-images.githubusercontent.com/72005130/94398986-2c500d80-0199-11eb-92b0-c2f72f91a991.png)

![image](https://user-images.githubusercontent.com/72005130/94399009-35d97580-0199-11eb-97bf-3383ae5790dd.png)

**Comment by ricksouth** [comment]
I've fixed the issue. Silly file permissions when switching servers. Should work as intended now! Thanks for letting me know, using the mods and the images!
