### ISSUE TITLE
PotionCore incompatiblity; refuses to open Villager GUI when interacting with villagers that have careers.

### ISSUE THREAD

**Issue by ghost** [Serilum/.issue-tracker#276]
## **Information**
Minecraft version: 1.12.2
Forge version: 14.23.5.2584
Environment: Singleplayer

Mod name: Villager Names
Mod version: 1.4

## **Description**
When right clicking on a villager, the GUI never appears, and VanillaFix catches the exception.  Apparently PotionCore gives issue with gathering network packet data for the trade GUI with a named villager that has a role.

## **Crash report**
[crash-2020-09-29_23.23.13-server.txt](https://github.com/ricksouth/serilum-mc-mods/files/5302156/crash-2020-09-29_23.23.13-server.txt)

**Comment by James103** [comment]
Are you able to reproduce the crash?

**Comment by ghost** [comment]
over and over and over, simply by right clicking any villager that has a role (such as blacksmith etc, normal trading villagers work).  was able to make VanillaFix complain via an alert toast over six times in a row.  the crash report I have attached is the sixth time, all crash reports have the same trace.  The GUI would never open after right clicking on said villager; the "crash" would always happen instead.

**Comment by ghost** [comment]
it seems to be a server side issue during data collection routines when rendering the villager trade gui (again, related to naming the villager with their role such as "Blah Blah **the Blacksmith**", the bolded text is probably the "sixth" index potioncore hates ).  the array index is out of bounds and it seems potion core may be at fault.  thus I named this issue "incompatibility" as I feel the only way to fix this is with some sort of backend change to the data packets during the GUI opening sequence.

**Comment by ricksouth** [comment]
Thanks for using the mod and opening the issue. Unfortunately I no longer support version 1.12, as the code is very much different now. You'll have to choose one of the incompatible mods, or update to a newer version :)
