### ISSUE TITLE
Healing Campfire Bug

### ISSUE THREAD

**Issue by FlyGuy240** [Serilum/.issue-tracker#278]
## **Information**
Minecraft version: 1.16.3
Forge version: 34.1.0
Environment: Singleplayer

Mod name: Healing Campfire
Mod version: 2.3

## **Description**
Standing near the Campfire gives me the regen buff, but my health stops regenerating entirely until i step away from the fire.

## **Crash report**
If available. N/A

**Comment by Iggynatz** [comment]
Im having the same issue in 1.16.2. The regen buff appears in the corner but I'm not healing at all.

**Comment by ricksouth** [comment]
Thanks for opening the issue and using the mod! I've fixed the problem in version 3.0 by changing how the regeneration effect is applied. If the player has less than half of the configured duration left and is near the campfire, the effect is refreshed. This should give the game enough time to actually apply the effect.

https://www.curseforge.com/minecraft/mc-mods/healing-campfire
