### ISSUE TITLE
How to remove iron/carrots/potatoes from zombies loot table with this mod active?

### ISSUE THREAD

**Issue by mgaray99** [Serilum/.issue-tracker#28]
My pack has a progression system where you're not supposed to be able to obtain iron ingots until after building an iron ore refiner, unless you get really lucky by finding loot in a chest. With this mod on, zombies and their variants drop iron, potatoes and carrots, making it extremely easy to get iron ingots at night and avoiding the system entirely (also dropping carrots/potatoes is just dumb). I've tried altering the zombies loot table via datapack but they still drop everything from their vanilla loot table.

**Comment by ricksouth** [comment]
The mod currently only has the functionality to drop all loot. Allowing changes kind of changes the whole idea it. I'll keep it in mind, but it's not something I'll work on right now. Thanks for the idea!
