### ISSUE TITLE
Extract poison : compatibility with "spiders 2.0"

### ISSUE THREAD

**Issue by Blugori** [Serilum/.issue-tracker#280]
## **Information**
Minecraft version: 1.16.3
Forge version: 34.1.0
Environment: Singleplayer

Mod name: Extract Poison
Mod version: 1.1

## **Description**
I'm playing with "extract poison" and "spider 2.0". The "spider 2.0" replace the vanilla spiders by spiders which have a better climbing animation (both types of spiders). So when I tried taking poison on the cave spider, I couldnt. Could you please add compatibility :3 ?
Best regards

**Comment by ricksouth** [comment]
Thanks for using the mod, glad you like it! I've added support for Spiders 2.0 in version 1.2 of the mod :)

[https://www.curseforge.com/minecraft/mc-mods/extract-poison](https://www.curseforge.com/minecraft/mc-mods/extract-poison)

**Comment by Druwan-ctrl** [comment]
Hi, i want to use both mods on a sponge server, so 1.12.2. Could you make them compatible for 1.12 please? It would add so much immersion!
