### ISSUE TITLE
Crash while playing with "giant spawn"

### ISSUE THREAD

**Issue by Blugori** [Serilum/.issue-tracker#282]
## **Information**
Minecraft version: 1.16.3
Forge version: 34.1.0
Environment: Singleplayer

Mod name: Giant spawn
Mod version: 1.16.3_2.1

## **Description**
When the day comes, giant zombies and zombie horses may crash the game. (I use a lot of mods so maybe the issue isnt coming from your mods)

## **Latest log Crash report debug log**
[latest.log](https://github.com/ricksouth/serilum-mc-mods/files/5323703/latest.log)

[crash-2020-10-04_18.59.08-server.txt](https://github.com/ricksouth/serilum-mc-mods/files/5323698/crash-2020-10-04_18.59.08-server.txt)

[debug.log](https://github.com/ricksouth/serilum-mc-mods/files/5323705/debug.log)

**Comment by ricksouth** [comment]
Seems like Immersive Portals is the cause of this crash:
"Caused by: java.lang.IllegalStateException: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.NullPointerException
	at com.qouteall.immersive_portals.Helper.noError(Helper.java:483) ~[?:0.4] {re:classloading,re:mixin}"

Try opening an issue there. Thanks for using the mod!
