### ISSUE TITLE
config for other web types and vertical movement

### ISSUE THREAD

**Issue by Biviho** [Serilum/.issue-tracker#285]
Weaker spider web feature:

hi, i have noticed that there are some mod that add their own custom spider web (one that come into my mind is beter animal plus...or it was the erebus...? i can't recall correctly... the black one that add a wither effect on contact) and it looks like those blocks are unaffected by this mod.
i suggest to add a list of spider web that will be affected by the mod if it's possible.

also, i have noticed that while horizontal movement can break webs, vertical movement can't, so i wanted to suggest the ability to add vertical movement to the possible movement that can break webs

**Comment by ricksouth** [comment]
I've updated the mod to 1.5, which should add compatibility to modded spiderwebs and improve the performance. As for the movement direction, horizontal or vertical doesn't matter, as long as the player is in the block itself. Thanks for using the mod!

[https://www.curseforge.com/minecraft/mc-mods/weaker-spiderwebs](https://www.curseforge.com/minecraft/mc-mods/weaker-spiderwebs)
