### ISSUE TITLE
Shulker Drops Two Question

### ISSUE THREAD

**Issue by SmileTheServant** [Serilum/.issue-tracker#286]
Minecraft version: 1.16.3
Forge version: 1.16.3 - 34.1.11
Environment: Singleplayer 

Mod name: Shulker Drops Two
Mod version: 1.16.3 - 1.2

Question: How do I configure the amount of shells that the shulkers drop? When I click on the mod in-game on forge I cannot press the "config" button and I can't find any tutorials for how to config it. Thanks!

**Comment by ricksouth** [comment]
Hi, thanks for using the mod! The config files for all mods are located in your .minecraft folder inside the /config folder. The one for shulker drops two is called shulkderdt-common.toml. Here you can change the values.
