### ISSUE TITLE
Update to 1.15.2?

### ISSUE THREAD

**Issue by xnemesis72** [Serilum/.issue-tracker#29]
## **Information**
(you can remove whatever is not applicable)
Minecraft version: xx.xx.xx
Forge version: xx.xx.xx
Environment: Singleplayer / Multiplayer

Mod name: Infinite trading
Mod version: 1.15.1

## **Question**
?
Hi, any plans on updating to 1.15.2?

**Comment by ricksouth** [comment]
Hi, thanks for using the mod. It has been updated to 1.15.2.
