### ISSUE TITLE
Save and Load Inventories set other player's inventories

### ISSUE THREAD

**Issue by ClaudiusMinimus** [Serilum/.issue-tracker#290]
## **Information**
Mod name: Starter Kit

## **Feature description**
It would be nice to have the following commands for Starter Kit:

1. /starterkit addKit [kit name] _for addinging new kits_
2. /starterkit give [kit name] [_player name_] _to be able to give a kit to self or optionally to another player on the server, including the "Starter Kit"_
3. /starterkit set [kit name] _update a named kit_
4. /starterkit delete [kit name] _delete a named kit_

**Comment by ClaudiusMinimus** [comment]
I also found through testing if I delete the playerdata folder the player does not receive a starter kit. For pack devs, this would be very useful.

**Comment by ricksouth** [comment]
You're looking for this mod: https://www.curseforge.com/minecraft/mc-mods/save-and-load-inventories

I'll add the set kit to other players feature on the todo list :)

**Comment by ClaudiusMinimus** [comment]
Who can create the inventories - Normal or OP? If normal, then this could be abused. If only OP, then it looks great!

**Comment by ricksouth** [comment]
Players with cheat access only :)

**Comment by ClaudiusMinimus** [comment]
Wonderful!
Thanks!

**Comment by ricksouth** [comment]
I'm keeping the issue open to remind me of the kit other players feature

**Comment by ricksouth** [comment]
Version 1.1 adds the command /loadinventory <inventory_name> <player_name> which allows you to set other players' inventories as well :)

[https://www.curseforge.com/minecraft/mc-mods/save-and-load-inventories](https://www.curseforge.com/minecraft/mc-mods/save-and-load-inventories)
