### ISSUE TITLE
Error in Starter Kit Generated Text File

### ISSUE THREAD

**Issue by ClaudiusMinimus** [Serilum/.issue-tracker#291]
I am using your mod for one of my packs.

## **Information**
Minecraft version: 1.16.3
Forge version: 34.0.9
Environment: Singleplayer

Mod name: Starter Kit
Mod version: 1.16.3-2.0

## **Starter Kit Error**
I created the kit using "/starterkit set". I created a new world and was given the specified items as set in the [starterkit.txt](https://github.com/ricksouth/serilum-mc-mods/files/5372820/starterkit.txt). However, upon creating another new world the kit fails and I found this error in the latest.log: 
`
[STDOUT/]: [com.natamus.starterkit.util.Util:setGlobalStarterkitFromGearString:195]: [Error] setPlayerGearFromString: The gear config does not contain 40 lines and is invalid.`

**Comment by ricksouth** [comment]
Thanks for letting me know and using the mod! I've fixed it in version 2.1 of the mod. Tested it with your config and it works. 

[https://www.curseforge.com/minecraft/mc-mods/starter-kit](https://www.curseforge.com/minecraft/mc-mods/starter-kit)
