### ISSUE TITLE
Config not working in Villager Names.

### ISSUE THREAD

**Issue by Inpaladin** [Serilum/.issue-tracker#293]
Mod Name: Villager Names
Mod version: 1.16.3-2.5
Forge version: 3.4.1.0

Title.  In Villagernames-common, _useCustomNames is set to true by default.  When I go into customnames there's only three entiries(Rick, Bob and Eve) despite villagers spawning with many more different names in game.  Changing/adding names in customnames doesn't do anything.

**Comment by ricksouth** [comment]
You can disable the preset female and male names with the other two config options. When those are disabled, only custom names are used. Which will mean you can see the custom names more often than 1/5000 otherwise

**Comment by ricksouth** [comment]
I've changed the description to make it a little clearer :) Thanks for using the mod!

**Comment by Inpaladin** [comment]
thank you!
