### ISSUE TITLE
Feature Request: Configurable blocks to clay balls instead

### ISSUE THREAD

**Issue by UnseenAcademical** [Serilum/.issue-tracker#297]
## **Information**
Mod name: Eroding Stone Entities
Version: 1.16.3

## **Feature description**
I love the concept of this mod! The other non-renewable block I could use large amounts of is clay. Would it be possible to make certain blocks erode to clay instead of sand? Preferably with an ability to toggle which blocks go to clay / sand / red sand?

Thank you!

**Comment by ricksouth** [comment]
The problem with it is that sand is basically tiny rocks, but clay has other properties as well. Which block would be able to form into clay do you think?

**Comment by seanimusprime** [comment]
Terracotta could work

**Comment by ricksouth** [comment]
@seanimusprime sometimes it's too obvious haha. That's of course very logical, thanks! I'll add clay to the mod, with a config.

**Comment by ricksouth** [comment]
I've just released version 2.0 of the mod which makes everything configurable and adds compatibility for clay. By default all terracotta blocks turn into clay balls. Thanks for opening the issue!

[https://www.curseforge.com/minecraft/mc-mods/eroding-stone-entities](https://www.curseforge.com/minecraft/mc-mods/eroding-stone-entities)
