### ISSUE TITLE
Random Loot and this mod

### ISSUE THREAD

**Issue by DatrixTHLK** [Serilum/.issue-tracker#298]
## **Information**
Mod name: Random Loot 
Mods axes don't work with the tree harvester mod

## **Feature description**
I wanted to get this mod and Random loot to play nice with one another.

Issue was placed in random loots issue board.
Mentioned here: https://github.com/TheMarstonConnell/randomlootmod/issues/62

[Random Loot Mod](https://www.curseforge.com/minecraft/mc-mods/random-loot-mod): 2.1.7

**Comment by ricksouth** [comment]
Thanks for opening the issue and using the mod! This is not something I can resolve at my end. I've suggested a solution to the author of Random Loot though.

**Comment by DatrixTHLK** [comment]
I see, thanks for the feedback. I really appreciate it.
