### ISSUE TITLE
Named Areas doesn't work in multiplayer (yet)

### ISSUE THREAD

**Issue by ricksouth** [Serilum/.issue-tracker#3]
## **Information**
Minecraft version: 1.12+
Forge version: 26+
Environment: Multiplayer

Mod name: Named Areas
Mod version: 3.8

## **Description**
Currently I'm working out some issues with the server side GUI processing, I'm learning too! :) Named Areas works fine in single player currently, and also
doesn't effect the server negatively when loading it. It just doesn't process the area signs.

## **Crash report**
N/A

**Comment by Giggitybyte** [comment]
Have you made progress on this?

**Comment by Ithirahad** [comment]
Ahhh ok. We tried to put this mod on our 1.12 multiplayer server and couldn't figure out what was going on. Unfortunate, as nothing else really provides this functionality as cleanly...

**Comment by ricksouth** [comment]
Sorry for the inconvenience. I must admit I've kind of placed this in the back of my mind because I did not immediately know how to fix the problem.

I'm working through the other issues on this repository right now, and will be creating the mod from the ground up again with the focus on multiplayer. I think it'll definitely shine the brightest in that environment.

**Comment by Giggitybyte** [comment]
Great to hear!

**Comment by mr-poyo** [comment]
Can confirm same issue with 1.15.2 servers. Glad to hear it's on the agenda. 👍

**Comment by ricksouth** [comment]
Named Areas is getting an update tomorrow! I've rewritten the entire mod from scratch. It works in multiplayer now.

**Comment by ricksouth** [comment]
Named Areas has been re-released as [Areas](https://www.curseforge.com/minecraft/mc-mods/areas). This is the initial version and I'll probably add more functionality to it in the future! The mod should be approved in a few hours. Would love to hear feedback, but multiplayer is finally a thing! :)

[https://www.curseforge.com/minecraft/mc-mods/areas](https://www.curseforge.com/minecraft/mc-mods/areas)
