### ISSUE TITLE
Nether Blocks Changing Far From Portal

### ISSUE THREAD

**Issue by thaKnza** [Serilum/.issue-tracker#30]
## **Information**
Minecraft version: 1.14.4
Forge version: 28.2.0
Environment: Multiplayer

Mod name: Nether Portal Spread
Mod version: nps_1.14-2.1

## **Question**
On my MP server, NPS seems to be working but strangely. The nether bricks are spreading far away from the portal. It almost seems as if the spread is happening just outside the set radius (15). No blocks close to the nether portal are being  changed, only ones farther away.

**Comment by ricksouth** [comment]
Little late, but thanks opening an issue! I can't seem to replicate the issue you're having. I've changed a lot of code in version 3, could you see if it has solved the issues you were having? I'd appreciate it!

[https://www.curseforge.com/minecraft/mc-mods/nether-portal-spread](https://www.curseforge.com/minecraft/mc-mods/nether-portal-spread)
