### ISSUE TITLE
Respawn Delay - Void Death Loop

### ISSUE THREAD

**Issue by Darkosto** [Serilum/.issue-tracker#304]
## **Information**
Minecraft version: 1.16.3
Forge version: 34.1.23
Environment: Singleplayer

Mod name: Respawn Delay
Mod version: 1.0

## **Description**
Fell into the void and respawn delay does not move the player high enough to stop the deathloop. Even when in spectator

## **Crash report**
If available.

**Comment by ricksouth** [comment]
Thanks for opening the issue and trying out the mod! I've fixed it in version 1.1. There's now a config option named 'lowestPossibleYCoordinate', with a default value of y = -10, which a player's position will be set to when their y is lower on death. Pretty much only when they fall into the void I think :)

The player's movement is also set to 0, so their position will be exactly y=-10 by default. You can increase it if need be.

[https://www.curseforge.com/minecraft/mc-mods/respawn-delay](https://www.curseforge.com/minecraft/mc-mods/respawn-delay)
