### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by RealBaconMaster** [Serilum/.issue-tracker#308]
## **Question**
So when I try to download all the mods on your website, you have to download this other program to extract the file or whatever and it wont run/work on lunix (unbuntu), do you know if there is anyother way to run the thing or any other way to download all your mods at once?
This isnt a huge issue so dont stress and keep up the great mods!

-RealBaconMaster

**Comment by ricksouth** [comment]
Thanks for the interest! You can also use MultiMc for example to import the zip file you download. It'll treat it as a modpack, but you could just copy over the downloaded mod files if you want :)

https://multimc.org/

**Comment by RealBaconMaster** [comment]
Thanks for responding and will do!
