### ISSUE TITLE
Real time clock  have one extra hour. 13:00 to 14:00  (Bug)

### ISSUE THREAD

**Issue by ghost** [Serilum/.issue-tracker#309]
Minecraft version: 1.15.2
Forge version:     31.2.36
Environment:       Singleplayer

Mod name: GUI Clock
Mod version: guiclock_1.15.2-2.0.jar

When "showRealTime" is enabled one more hour is being added, if it is 13:00 it shows up like 14:00.  I tried deleting config files to recreate them and it didn't work.

Thanks for the mod :)

**Comment by James103** [comment]
Is this a bug related to Daylight Saving Time not being handled properly?

**Comment by ghost** [comment]
It doesn't seem to be it... we don't do it around here and all the settings related to DST are disabled...
Also, I tried removing all mods leaving only the Collective lib and the problem persisted...

**Comment by ghost** [comment]
After messing around with the time settings,I noticed that the error starts after October 17th.  Before that day it works normally, but from there on the bug appears.

**Comment by James103** [comment]
Have you tried bisecting to see whether the errant time difference persists starting in early 2020, and to see when exactly that ends?

**Comment by ghost** [comment]
I did it. before october 17th there is no error. after october 17th the error is there. no matter which time I set in between. It never ends.

**Comment by James103** [comment]
Do you know when (at what time) during October 17 does the clock jump (besides just going from 13:00 to 14:00)?

**Comment by ghost** [comment]
Exactly at midnight. goes from 23:59 to 01:00.  same when using am/pm format.

**Comment by ricksouth** [comment]
The real time is linked to your local pc's settings. I can't change this in the mod. Thanks nonetheless for submitting the bug report though!
