### ISSUE TITLE
How do I configure this mod?

### ISSUE THREAD

**Issue by JohnathansCat** [Serilum/.issue-tracker#311]
I'm new to messing around with mods and i'm not quite sure how to edit a .class file. I Know I need to decompile it (atleast thats what iv been told) and I have eclipse but i'm not sure how to do it. Can you tell me how?

**Comment by ricksouth** [comment]
Thanks for using the mod! Check out the first question in the FAQ: https://github.com/ricksouth/serilum-mc-mods/wiki/FAQ

You don't have to decompile anything. There's a /config folder in your minecraft game folder where config files for all the mods are located.
