### ISSUE TITLE
Modding Software?

### ISSUE THREAD

**Issue by RealBaconMaster** [Serilum/.issue-tracker#314]
## **Question**
So not super important but what software/website/program do you use to code your mods, I cant find any good ones and is it free?

xx thanks

**Comment by ricksouth** [comment]
I use Eclipse to code all the mods. Aside from that I've coded some software to make the exporting process easier for the amount of mods I have. Just the normal stuff basically!

**Comment by RealBaconMaster** [comment]
Ok ty, I want to get into modding a just needed a modding software, ty

**Comment by ricksouth** [comment]
No problem, good luck! :)
