### ISSUE TITLE
Fabric Support

### ISSUE THREAD

**Issue by srnyx** [Serilum/.issue-tracker#316]
## **Information**
Mod names: Collective & Full Brightness Toggle

## **Feature description**
Would be great if you could add support for Fabric, thanks.

**Comment by James103** [comment]
The FAQ has a question about this: https://github.com/ricksouth/serilum-mc-mods/wiki/FAQ

**Comment by ricksouth** [comment]
As James said, unless curseforge adds seperate file uploads for fabric and forge, I'm sticking to forge for now. Thanks for the interest.
