### ISSUE TITLE
1.16.4? 

### ISSUE THREAD

**Issue by livisiwz** [Serilum/.issue-tracker#317]
Will you be updating the modpack to 1.16.4? I want to use it on a realm with some friends because of the cool features it brings!

**Comment by ricksouth** [comment]
Thanks for the interest! I had to wait for the launcher to update. I've just released a 1.16.4 of the modpack.

[https://www.curseforge.com/minecraft/modpacks/the-vanilla-experience/files](https://www.curseforge.com/minecraft/modpacks/the-vanilla-experience/files)
