### ISSUE TITLE
Soul Campfire not a config option

### ISSUE THREAD

**Issue by NixityNull** [Serilum/.issue-tracker#318]
I am currently using Healing Campfire for Minecraft ver. 1.16.1

The healing factor is a bit overpowered considering how easy campfires are to get, and I wanted to set it to only soul campfires as those require an ingredient from the nether, making it more balanced. However, the config options to not say anything about "Soul campfire only" or anything of the like. Is this a bug or am I just using an old version?

**Comment by ricksouth** [comment]
I'm not releasing updates for the mods for every sub version of the game. It'll always be the latest for each major version. Sorry for the inconvenience. The soul campfire config option is available for 1.16.3 and 1.16.4.

Thanks for the interest!
