### ISSUE TITLE
Seeds replanted on grass blocks

### ISSUE THREAD

**Issue by johnpb-0** [Serilum/.issue-tracker#319]
## **Information**
Minecraft version: 1.12.2
Forge version: 14.23.5.2854
Environment: Singleplayer

Mod name: Replanting Crops
Mod version: 1.1

## **Description**
When breaking tall grass the seeds get replanted on the grass block, they break if you update them but you can't break them normally, only with shift-clicking.

![2020-11-17_11 33 16](https://user-images.githubusercontent.com/73952341/99402965-b464b080-28c8-11eb-92f7-6205a35d2b61.png)

**Comment by James103** [comment]
If you replace the loot table for `minecraft:grass` with the loot table for carrot crops (`minecraft:carrots`), are you still able to reproduce this bug?

**Comment by ricksouth** [comment]
Unfortunately right now I don't support the 1.12 version of Minecraft, version 2.0 of the mod doesn't have this problem. Sorry for the inconvenience.
