### ISSUE TITLE
[Feature Request] World Boarder dimensions config

### ISSUE THREAD

**Issue by DVorriose** [Serilum/.issue-tracker#32]
Mod name: World Boarder

Request config or .json to add world boarders to other dimensions (different/user defined for each dimension).

Consider Nether/modded portals (either set past boarder as unsafe/unavailable, or wrap-around).

**Comment by ricksouth** [comment]
Took my a little while, but I've added the features in version 2.0. Thanks for using the mod!

[https://www.curseforge.com/minecraft/mc-mods/world-border](https://www.curseforge.com/minecraft/mc-mods/world-border)

**Comment by UnseenAcademical** [comment]
Thanks! Really great to see the feature I was going to request is already present, this is going to make my modpack so much more effective.

Is there any documentation on how to add arbitrary dimensions to the config file? I don't immediately see anything that would indicate it.
