### ISSUE TITLE
1.16.3 Tree Harvester Issue (No Crash)

### ISSUE THREAD

**Issue by 4dtxt** [Serilum/.issue-tracker#320]
## **Information**
Minecraft version: 1.16.3
Forge version: 34.1.42
Environment: Multiplayer

Mod name: Tree Harvester
Mod version: 2.0

## **Description**
I'm playing on a dedicated server and Tree Harvester doesn't seem to work. I have a myriad of other mods but nothing that I think could be conflicting. (Unless I've been exclusively trying it on BiomesOPlenty trees.) The same mod works in my singleplayer world so I don't know what the issue could be.

**Comment by James103** [comment]
Did you try using Tree Harvester on vanilla trees (i.e. for example get 4x `minecraft:spruce_sapling`, plant them, and wait/bone meal until the tree grows)?

**Comment by 4dtxt** [comment]
> Did you try using Tree Harvester on vanilla trees (i.e. for example get 4x `minecraft:spruce_sapling`, plant them, and wait/bone meal until the tree grows)?

Just tried, the first couple times I grew the tree it would work in creative and not survival, but upon trying several more times later in survival it started to work.

Could it just have something to do with the processing speed of the server itself? I've noticed general lag centered around the fact that I'm using an aternos server without much RAM allotment.

**Comment by ricksouth** [comment]
Thanks for opening the issue! This should be fixed in version 2.2 of the mod. Please open another issue of the problem persists.

https://www.curseforge.com/minecraft/mc-mods/tree-harvester
