### ISSUE TITLE
All Loot Drops not dropping all loot.

### ISSUE THREAD

**Issue by KiniroKaen** [Serilum/.issue-tracker#323]
Mobs won't drop all their loot, and when it drops, it doesn't drop at the configured value. Sometimes they drop all their loot, but only one of the items gets dropped at the configured value. For example, if a skeleton dropped both bones and arrows, only one of those items might be dropped at the configured number of drops.
Minecraft version: 1.16.4
Forge version: 1.16.4-forge-35.1.2
Environment: Singleplayer

Mod name: All Loot Drops
Mod version: 1.16.4-2.0

## **Description**
Hey! This happened..

## **Crash report**
If available.

**Comment by James103** [comment]
Have you tried increasing the value of `loopsAmountUsedToGetAllEntityDrops` in the Collective library's config?

**Comment by KiniroKaen** [comment]
> Have you tried increasing the value of `loopsAmountUsedToGetAllEntityDrops` in the Collective library's config?

Yes, I increased it to 200 which is the highest value in the range. The problem still persists.

**Comment by ricksouth** [comment]
Thanks for submitting the bug report and using the mod! I've fixed it in version 2.1 of the mod.

https://www.curseforge.com/minecraft/mc-mods/all-loot-drops
