### ISSUE TITLE
Mods does not work/function. Trees still take block by block chopping. 

### ISSUE THREAD

**Issue by TnTori** [Serilum/.issue-tracker#324]
## **Information**
Minecraft version: 1.15.2
Forge version: 1.15.2-31.2.0
Environment: Singleplayer / Multiplayer

Mod name: Tree Harvester
Mod version: x1.15.2-2.0

## **Description**
The trees are behaving like vanilla. I have tried sneak right click (just to try). I have tried different axes (with Tree Chopper mod in 1.12 your hands didn't work. I'm not sure what other troubleshooting steps to follow. Please let me know. I tried this same mod in all 1.16 minecraft and it still did not work. Thanks. 

## **Crash report**
No crash, game loads ok.

**Comment by ricksouth** [comment]
Thanks for opening the issue! This should be fixed in version 2.2 of the mod. Please open another issue of the problem persists.

https://www.curseforge.com/minecraft/mc-mods/tree-harvester
