### ISSUE TITLE
Suggestion: Omega Mute Hotkey

### ISSUE THREAD

**Issue by thelizardcode** [Serilum/.issue-tracker#325]
## **Information**
Mod name: Omega Mute

## **Feature description**
Add hotkey to open menu?

I have an issue with not being able to open Omega Mute when using something else that adds a button to the inventory screen, for example, Doggy Talents adds this Doggy Inventories mod and overrides the Omega Mute button. Would it be possible to add a hotkey that opens the Omega Mute menu, if it isn't possible to add the button on top of the existing inventory buttons.
![image](https://user-images.githubusercontent.com/61859032/100293939-3dd94a00-2f7d-11eb-9b65-fba9f3f03887.png)

**Comment by ricksouth** [comment]
You can use Omega Mute via a hotkey ( . or dot by default). Thanks for using the mod!
