### ISSUE TITLE
Feature request:  Dramatic Doors compatibility

### ISSUE THREAD

**Issue by UnixRonin** [Serilum/.issue-tracker#327]
This mod seems to already work with some modded doors, including the tall windows from Macaw's Windows which appear to be based upon the vanilla door class.  Is there any possibility it could be made to work with non-standard mod doors such as the tall doors from Fizzware's Dramatic Doors?

**Comment by James103** [comment]
What mod do you mean with regards for the suggestion?

**Comment by UnixRonin** [comment]
I'm specifically thinking, as I said, Fizzware's mod Tall Doors, but I don't know if there are or will be other non-standard-door mods for 1.16.  Roxa's Tall Doors had 1x3, 2x3 and 2x4 doors, but she hasn't updated it in a long time.  I don't know whether this is something that might be accomplished as conceptually simply as having a config list that says "These things from these other mods should also be treated as doors"?

**Comment by ricksouth** [comment]
Thank you for opening the issue and giving the mod a try! Support for modded doors has been added in version 5.3 of Double Doors.

https://curseforge.com/minecraft/mc-mods/double-doors/files
