### ISSUE TITLE
nhaCampfire config not working

### ISSUE THREAD

**Issue by NixityNull** [Serilum/.issue-tracker#330]
## **Information**
Forge version: 1.16.4
Environment: Singleplayer 
Mod name: No hostiles around campfire

## **Description**
Setting "only works when lit" to true in configs does not do anything. unlit campfires still set mobs on fire.

## **Crash report**
If available.

**Comment by James103** [comment]
1. Did you actually save the edited config in the right place?
2. Did you make sure there were no typos in the config entry (as they may cause the entry or the entire config to be ignored or reset to default)?

**Comment by NixityNull** [comment]
all i did was change false to true.

Could it be a compatibility error with the unlit campfires mod? (all it does is set the block state to unlit when placed, but i don't know if that would be enough to cause an error.)

**Comment by NixityNull** [comment]
nevermind, it was just a minor bug caused by an incompatibility with another mod.
