### ISSUE TITLE
Is 1.12.2 backporting planned?

### ISSUE THREAD

**Issue by jadenquinn** [Serilum/.issue-tracker#333]
## **Information**
Minecraft version: 1.12,2
Forge version: 14.xxx.xx.x.2xxx
Environment: Multiplayer

Mod name: Tracking Compass Backport
Mod version: x.x_1122

Are there backporting plans for Minecraft 1.12.2? There aren't any tracking compass mods for 1.12.2 so someone should backport. I've been wanting to do manhunts on modded for a while but there still aren't any backports.

**Comment by ricksouth** [comment]
At this moment I no longer support 1.12.2. Thanks for the interest though!
