### ISSUE TITLE
Mod isn't serverside only?

### ISSUE THREAD

**Issue by frenchiveruti** [Serilum/.issue-tracker#334]
Hello I've installed your mod on a forge 1.16.3 version server, and the client isn't getting any messages when a villager dies, only the server posts the message.

**Comment by James103** [comment]
What mod do you mean when you say that the mod is actually not server-side only?

**Comment by frenchiveruti** [comment]
I am sorry I didn't realize this repo was for several mods.  
I'm talking specifically about Villager Death Messages.  
https://www.curseforge.com/minecraft/mc-mods/villager-death-messages
When a villager dies, the server is the only one to get the message but it doesn't post it on the general chat for the players.

**Comment by James103** [comment]
If you have the server, client A with the mod installed, and client B without the mod installed, is it that only the server and client A get the message, and not client B?

**Comment by frenchiveruti** [comment]
Yes, client B doesn't get the message.

**Comment by ricksouth** [comment]
This has been fixed in Collective version 1.57. Villager Death Messages doesn't need to be updated. Thanks for using the mod and submitting the bug report!

https://www.curseforge.com/minecraft/mc-mods/collective
https://www.curseforge.com/minecraft/mc-mods/villager-death-messages
