### ISSUE TITLE
Minecraft version:1.16.4

### ISSUE THREAD

**Issue by Platipucat** [Serilum/.issue-tracker#338]
## **Information**
Minecraft version: 1.16.4
Forge version: 35.1.13
Environment: Multiplayer

Mod name: Mod
Mod version: 2.0

## **Description**
when i loop back i get teleported to the bottom of the ocean ,even if there is ice above

## **Crash report**
no crash :)

**Comment by ricksouth** [comment]
Thanks for submitting the bug report and using the mod! This has been fixed in version 1.59 of Collective and version 2.2 of World Border. Sorry for the inconvenience.

https://www.curseforge.com/minecraft/mc-mods/world-border
https://www.curseforge.com/minecraft/mc-mods/collective
