### ISSUE TITLE
Custom Dimensions?

### ISSUE THREAD

**Issue by danemorgan** [Serilum/.issue-tracker#340]
## **Information**
(you can remove whatever is not applicable)
Minecraft version: 1.16.4
Forge version: 35.1.9
Environment: Singleplayer

Mod name: Mineral Chanc e
Mod version: 1.16.4-1.0

## **Question**
Should I be seeing hits when mining overworld stone in a custom dimension?

**Comment by ricksouth** [comment]
The mod checks for "overworld" in the dimension name. If the custom dimension has that in its name it will produce minerals when mining. Thanks for using the mod!
