### ISSUE TITLE
Transcending Trident

### ISSUE THREAD

**Issue by zachsai** [Serilum/.issue-tracker#341]
## **Information**
(you can remove whatever is not applicable)
Minecraft version: 1.16.4
Forge version: xx.xx.xx
Environment: Singleplayer / Multiplayer

Mod name: Mod
Mod version: x.x

## **Question**
Could you make it possible in the configs to add various trident ids to work with the bucket? The Tide Trident from Ice and Fire 1.16.4 does not work currently with Transcending Trident mod

**Comment by ricksouth** [comment]
Version 2.0 should add the compatibility with modded tridents that extend the TridentItem. Let me know if anything doesn't work as intended. Thanks for the suggestion!

https://www.curseforge.com/minecraft/mc-mods/transcending-trident/files/all
