### ISSUE TITLE
Is this mod fabric?

### ISSUE THREAD

**Issue by MCGamerDad** [Serilum/.issue-tracker#346]
## **Information**

Minecraft version: 1.16.4
Fabric 1.16.4
Environment: Singleplayer & Multiplayer

Mod name: Bottle Your XP
Mod version: 1.16.4

## **Question**
I have installed the mod in my mod folder, but it does not show up in the game. Does this mod support Fabric?

Thanks!

MC_GamerDad

**Comment by James103** [comment]
This should be answered in [the FAQ](https://github.com/ricksouth/serilum-mc-mods/wiki/FAQ).

In other words, all of Ricksouth's mods are for Forge and Forge only, with no plans to port to Fabric anytime soon. You should either find a Fabric alternative or switch to Forge if you want to use Ricksouth's mods.

**Comment by MCGamerDad** [comment]
Thank you for your reply
