### ISSUE TITLE
Add notice to README.md about reading the FAQ before posting

### ISSUE THREAD

**Issue by James103** [Serilum/.issue-tracker#347]
## **Information**
This pertains to [the FAQ](https://github.com/ricksouth/serilum-mc-mods/wiki/FAQ) and [this search query](https://github.com/ricksouth/serilum-mc-mods/issues?q=fabric).

## **Comment**
What if you added something to `README.md` (and/or `CONTRIBUTING.md`) that tells users to read the FAQ **before** posting an issue? I see a lot of issues opened and closed that all have to deal with Fabric support, and I hope that a notice in these locations would help cut down on the number of new issues reported that deal with Fabric support.

## **Example**
> Please read [the FAQ](https://github.com/ricksouth/serilum-mc-mods/wiki/FAQ) before posting an issue!

**Comment by ricksouth** [comment]
Done! :) Better late than never huh
