### ISSUE TITLE
how to use a 1.12 mod that requires collective 

### ISSUE THREAD

**Issue by SpiderOden** [Serilum/.issue-tracker#350]
## **Information** ##

Mod name: end portal recipe , collective
Mod version: 1.12

## **Question**
how is anyone supposed to use end portal recipe in 1.12 if there is no 1.12 version of collective?

**Comment by James103** [comment]
Does the mod work by itself without the Collective library?

**Comment by SpiderOden** [comment]
I don't know but I'll try

**Comment by SpiderOden** [comment]
yep
