### ISSUE TITLE
Stack Refill for 1.12.2?

### ISSUE THREAD

**Issue by BloodyRain2k** [Serilum/.issue-tracker#351]
Hi, I wanted to ask if it would be possible to get Stack Refill also for 1.12.2?

I've been looking for a mod that refills my hotbar when items are used up, but Inventory Tweaks does it too agressively when I don't want it.
So I've been hoping that Stack Refill offers the option to exclude certain things from being refilled when they end up in the hotbar and then are being thrown away etc.

An example where InvTweaks is annoying would be when I have my wanted 64 arrows in my inv and an excess in hand to put them into the drawer that has the arrows and then it refills the hand with the 64 arrows that should have stayed where they were.
And there's no option to exclude these from the auto refill.

**Comment by ricksouth** [comment]
At this moment I no longer support 1.12.2. Thanks for the interest though!
