### ISSUE TITLE
Mod Does not break axe after hitting 0 Durability

### ISSUE THREAD

**Issue by Foodbegger** [Serilum/.issue-tracker#353]
## **Information**
Minecraft version: 1.16.4
Forge version: 35.1.28
Environment: Singleplayer but might also work on multi

Mod name: TreeHarvester
Mod version: 2.0 (Latest As of 12/30/2020)

## **Description**
So i was messing with some mods and i noticed while using this mod's tree harvesting function it does not actully break your axe if it hits 0 durability. I tested this on a instance where there where no other mods but TreeHarvester and JEI. The axe wouldnt be removed from my inventory after hitting 0 durability. 
The axe pretty much could be used infinitely entill you break a block without using the TreeHarvesting fuction.
https://user-images.githubusercontent.com/47768358/103338286-1d4c5600-4a3b-11eb-813d-383c4f221785.mp4

## **Crash report**
If available.

**Comment by ricksouth** [comment]
Thanks for opening the issue! This should be fixed in version 2.2 of the mod. Please open another issue of the problem persists.

https://www.curseforge.com/minecraft/mc-mods/tree-harvester
