### ISSUE TITLE
[World Border] shouldLoopToOppositeBorder teleports to bottom of the ocean.

### ISSUE THREAD

**Issue by mindcloud69** [Serilum/.issue-tracker#355]
## **Information**
Minecraft version: 1.16.4
Forge version: 35.1.13
Environment: Singleplayer

Mod name: Worldborder
Mod version: 2.0

## **Description**
When looping from dry land to an ocean on the other side with shouldLoopToOppositeBorder enabled, it teleports you to the bottom of the ocean. The natural expected behavior it to teleport you to the surface not underwater. It caused me to drown the first time as I was not expecting it at all.

**Comment by ricksouth** [comment]
Thanks for submitting the bug report and using the mod! This has been fixed in version 1.59 of Collective and version 2.2 of World Border. Sorry for the inconvenience.

https://www.curseforge.com/minecraft/mc-mods/world-border
https://www.curseforge.com/minecraft/mc-mods/collective
