### ISSUE TITLE
Update 1.12.2 version to World Border 2.0

### ISSUE THREAD

**Issue by itsdinkd** [Serilum/.issue-tracker#356]
## **Information**
Mod name: World Border

## **Feature description**
Version 1.12.2 Minecraft still has a HUGE player base as most mod packs are ran in this version. Your most downloaded file is the 1.12.2 version, with 10k downloads, all your other versions for other Minecraft versions are under 1k downloads. 

Please update world border to 2.0 for 1.12.2, thank you.

**Comment by ricksouth** [comment]
At this moment I no longer support 1.12.2. The code used in the mods changed a lot in 1.13. Sorry for the inconvenience.
