### ISSUE TITLE
Add setting to include other compasses & disable Z-coords

### ISSUE THREAD

**Issue by Pentasis** [Serilum/.issue-tracker#357]
## **Information**
Mod name: GUI Compass

## **Feature description**
Two ideas:
1) Add an option in the settings to include other compasses. Personally I always use the north-compass from inspirations. It would be nice if that also showed the gui.
2) Add an option to exclude the Z-coord (height) from the gui.

**Comment by ricksouth** [comment]
It has taken a while, but both features are included in version 2.1 of GUI Compass. Thanks for opening the issue and giving the mod a try!

https://www.curseforge.com/minecraft/mc-mods/gui-compass/files
