### ISSUE TITLE
Villager Names - feature requests

### ISSUE THREAD

**Issue by bessiq** [Serilum/.issue-tracker#358]
## **Information**
Mod name: Villager Names

## **Feature description**
Hello! I found a few modded villagers you could add to your mod:
charm:lumberjack
charm:beekeeper
immersiveengineering:gunsmith
immersiveengineering:engineer
immersiveengineering:electrician
immersiveengineering:machinist
mystictools:merchant
pneumaticcraft:mechanic

Also, would it be possible for custom names to respect uppercase letters that aren't at the beginning of the name? Currently, only the first letter is capitalized, so names like `Billy Bob` end up as `Billy bob`. Not a big deal but thought I'd ask. Thanks!

**Comment by ricksouth** [comment]
Thanks for the suggestions! I've added support for all the modded villagers and the multi-names in version 1.58 of Collective en version 2.8 of Villager Names.

https://www.curseforge.com/minecraft/mc-mods/collective
https://www.curseforge.com/minecraft/mc-mods/villager-names
