### ISSUE TITLE
"Merge" overlapping Areas of identical name

### ISSUE THREAD

**Issue by Ithirahad** [Serilum/.issue-tracker#359]
## **Information**
Mod name: Areas

## **Feature description**
Don't display leaving message if there's another overlapping area that has the same exact name. I mourn the loss of biome-defined named areas, but if that can't come back, this would at least be a partial solution for areas that aren't perfect spheres (so, most actual areas ingame).

**Comment by ricksouth** [comment]
Version 2.0 of Areas fixes this issue. Overlapping areas won't show up in the GUI anymore. Thanks for submitting the issue and using the mod!

https://www.curseforge.com/minecraft/mc-mods/areas
