### ISSUE TITLE
GUI Followers crash when running on a server but not on client

### ISSUE THREAD

**Issue by oOBoomberOo** [Serilum/.issue-tracker#360]
## **Information**
Minecraft version: 1.16.4
Forge version: 35.1.4
Environment: Multiplayer

Mod name: [GUI Followers](https://www.curseforge.com/minecraft/mc-mods/gui-followers)
Mod version: 1.0

## **Description**
The server crash when trying to start a server with this mod installed.  
I understand that this is a client-side mod but other client-side mods have managed to make it not crash the game when loading in the server before so I would like to ask you to implement it like the other mods as well.

And a slight annoyance with this issue is that I have to remove the mod from the server which will cause Forge to warn the player that their mod list is incompatible with the server when it is not.

## **Crash report**
[crash-fml.txt](https://github.com/ricksouth/serilum-mc-mods/files/5762070/crash-2021-01-03_13.41.22-fml.txt)
[latest.log](https://github.com/ricksouth/serilum-mc-mods/files/5762071/latest.log)

**Comment by ricksouth** [comment]
Thanks for letting me know! This has been fixed in version 1.1.

https://www.curseforge.com/minecraft/mc-mods/gui-followers/files/all
