### ISSUE TITLE
Failure: Unable to parse backup data 

### ISSUE THREAD

**Issue by Tschensche** [Serilum/.issue-tracker#361]
## **Information**
Minecraft version: 1.16.4
Forge version: 35.1.11
Environment: Singleplayer and Local LAN Multiplayer 

Mod name: Death Backup
Mod version: 1.16.4

## **Description**
Hey @ricksouth ! Thanks for the awesome Mod. It is really a great idea and just what I needed. 

Sadly, I'm having problems using it. I pretty much relied on this mod the first time I used it, only to find out that all my enchanted stuff und nice items cannot be restored. 

When I die, the success message is shown. However, when I try to load the backup (index 0 or any other), it says: "(Failure): Unable to parse backup data"

I checked the world folder - the data is there and ready to be parsed. I tried to open up permissions for reading and writing for the whole "death backup folder", but apparently, permissions is not the issue. How else could I fix this? Thanks a lot.

**Comment by ricksouth** [comment]
Hi @Tschensche, thanks for opening the issue and the kind words! Could you upload your death backup txt files if you still have them? They're located in ./world-folder/data/deathbackup/time.txt

**Comment by ricksouth** [comment]
Please check out version 1.2 of Death Backup. That should hopefully fix the problems you were having. Otherwise feel free to open another issue.

https://www.curseforge.com/minecraft/mc-mods/death-backup/files
