### ISSUE TITLE
Giant Zombie ID?

### ISSUE THREAD

**Issue by nanonestor** [Serilum/.issue-tracker#362]
Giant Zombie IDs?
Minecraft version: 1.16.4
Forge version: 35.1.28
Environment: Singleplayer / Multiplayer

Mod name: Giant Spawn
Mod version: 2.2

## **Question**
Trying to figure out what name/tag/id giant zombies are when they spawn?  Is it possible to target them in some way to alter some of their properties?  For example looking to use the mod 'In Control!' to change spawning to certain biomes, etc.

**Comment by James103** [comment]
By default, giant zombies are just called `minecraft:giant`.
