### ISSUE TITLE
Transcending Trident: Doesn't apply to modded tridents

### ISSUE THREAD

**Issue by Syampuuh** [Serilum/.issue-tracker#363]
## **Information**
Minecraft version: 1.16.4
Forge version: 35.1.29
Environment: Any

Mod name: Transcending Trident
Mod version: 1.3

## **Description**
The mod currently only applies its changes to the vanilla trident item. If it would be at all possible to apply it to modded tridents, such as Ice and Fire's, that would be great.

**Comment by ricksouth** [comment]
Version 2.0 should add the compatibility with modded tridents that extend the TridentItem. Let me know if anything doesn't work as intended. Thanks for the suggestion!

https://www.curseforge.com/minecraft/mc-mods/transcending-trident/files/all
