### ISSUE TITLE
Scaffolding Drops Nearby - 1.16.4 Crash

### ISSUE THREAD

**Issue by COLDW0LF** [Serilum/.issue-tracker#364]
## **Information**
Minecraft version: 1.16.4
Forge version: 35.1.28
Environment: Singleplayer

Mod name: Scaffolding Drops Nearby
Mod version: 1.1

## **Description**
Breaking a scaffold with multiple branches caused a crash, error log is attached.
Let me know if you need any more info

## **Crash report**
https://pastebin.pl/view/835d9725

**Comment by ricksouth** [comment]
Thanks for submitting the bug report and using the mod! This has been fixed in version 1.2.

https://www.curseforge.com/minecraft/mc-mods/scaffolding-drops-nearby

**Comment by TheFlyron** [comment]
When will version 1.2 be released? This also crashed my server in Multiplayer.
