### ISSUE TITLE
Trade Prices Increasing - Infinite Trading

### ISSUE THREAD

**Issue by SquareBall789** [Serilum/.issue-tracker#37]
Trade Prices Sky Rocketing
Minecraft version: 1.14.4
Forge version: 28.1.116
Environment: Singleplayer

Mod name: Infinite Trading 
Mod version: 1.0

After trading a couple stacks of items with a villager their trade goes up to 64 emeralds (example: 1 emerald for a mending book --> 64 emeralds for a mending book).

I have seen it happen with farmers and cartographers, not all trades go this high usually only one or two trades will do this

**Comment by ricksouth** [comment]
I think this has to do with your popularity in the village. I've tested it on my game and it doesn't seem to happen. Feel free to open the issue again if you don't think that's the problem.

[https://minecraft.gamepedia.com/Village#Popularity](https://minecraft.gamepedia.com/Village#Popularity)

**Comment by ConduCard** [comment]
Same happens to me. Dont think its for village popularity.

**Comment by GSCY123** [comment]
Same happens to me too,just stay in a village for like 10~30 minute without doing anything but sleep at night,the deal you got with the villager will be worse.
