### ISSUE TITLE
So how do we actually make a server for The Vanilla Experience? 

### ISSUE THREAD

**Issue by ShadowX116** [Serilum/.issue-tracker#373]
## **Information**

Minecraft version: 1.16.4 
Forge version: forge-35.0.15 
Environment: Multiplayer 

Pack: The Vanilla Experience 
Version: TheVanillaExperience_1.16.4-2.26.zip - (Release) - (current) 

## **Question**
In the pack description, it says, "A server can be created by just copying all mods into the server mods folder. Client-side-only mods will be disabled on launch without errors." 
What server files? Vanilla? I can't find any server files on your project page. Your zip files look like they're only packaged for Curse's use, and not for drag-and-dropping into a server folder. 

Vanilla server files don't work because you didn't include a forge jar to load any mods. Even when I went looking for it myself, the version your pack uses is no longer listed on Forge's page as far as I could tell (there are a lot @_@). I picked the closest (slightly more recent) version I could (forge-1.16.4-35.1.4.jar via installer), and even then it didn't work because of a whole slew of errors. 
I've made custom drag-and-drop packs before, but I've never seen this kind of crash, and I don't know enough code to see what's caused it. 

So, how can I fix this and make it a proper server for my friends where LAN isn't an option? 
I think the crash log is attached? If you can't see it, I can paste the plain text later if you want. 

[crash-2021-01-12_13.45.41-fml.txt](https://github.com/ricksouth/serilum-mc-mods/files/5806610/crash-2021-01-12_13.45.41-fml.txt)

**Comment by YoYoK3nny** [comment]
@ShadowX116 Try removing guifollowers_1.16.4-1.0.jar, omegamute_1.16.4-1.5.jar and advancementscreenshot_1.16.4-1.0.jar from the server. Those 3 mods are erroring and causing the crash.
@ricksouth Are those 3 mods client-side only?

**Comment by ricksouth** [comment]
Thanks @ShadowX116 and @YoYoK3nny for the information! There were indeed 3 client-side mods not working as intended (which is being ignored) when run in a server environment. I've updated all three and the modpack as well. Servers with 2.28 will work with all mods in the server folder.

https://www.curseforge.com/minecraft/modpacks/the-vanilla-experience/files/all
