### ISSUE TITLE
Suggestion for Villager Names: Custom Names for different sexes

### ISSUE THREAD

**Issue by Zothen1973** [Serilum/.issue-tracker#374]
## **Information**
Mod name: Villager Names

## **Feature description**
It would be cool if one could specify, which custom names are female und which are male.

**Comment by ricksouth** [comment]
I understand why you'd want it, but this is not something I'd like to implement at this moment. The male/female function is for the names already inside the mod. You can put anything else in the custom names if you'd like that. Thanks fmor the interest though!

**Comment by Zothen1973** [comment]
Well, I am using the mod "Gender Mod" for visual difference between "male" and "female" NPCs.

If you could expand your mod to attach female names to those female NPCs and male names to male NPCs, that would be a real cool feature. In that case, two different custom name files would make sense.

As it is now, I would have to disable Villager Names, because I personally prefer female features on female chars and don't want male names on them ;)
