### ISSUE TITLE
Cannot /loadinventory

### ISSUE THREAD

**Issue by neain** [Serilum/.issue-tracker#375]
## **Information**
Minecraft version: 1.16.4
Forge version: 35.1.4
Environment: Singleplayer

Mod name: Save and Load Inventories
Mod version: 1.1 I believe
File Name: saveandloadinventories_1.16.4-1.1.jar

## **Description**
I could save my inventory, seems to have gone fine as I can find the txt files in the correct location and when I look inside it seems to be correct. When I attempt to load, it says that it cant. I even restarted to see if anything changed.
![image](https://user-images.githubusercontent.com/38475365/104516780-7f1fca80-55ba-11eb-9b97-ed5dc1e9a1d3.png)

## **Crash report**
If available.
did not crash, just didn't work.

**Comment by James103** [comment]
Are there any relevant logs that show this kind of behavior that you could post here?

**Comment by neain** [comment]
only logs I know to pull are in the screenshot

**Comment by ricksouth** [comment]
Hi @neain, thanks for opening the issue. If you still have them, could you upload the text files of the saved inventories here? They're located in ./config/saveandloadinventories/name.txt. In your Minecraft folder.
