### ISSUE TITLE
Easy Elytra Take Off Colyta support

### ISSUE THREAD

**Issue by Nextia-Git** [Serilum/.issue-tracker#376]
## **Information**
Minecraft version: 1.12.2
Forge version: 14.23.5.2847
Environment: Singleplayer + Multiplayer

Mod name: Easy Elytra Take Off
Mod version: 1.1

## **Question**
Hi,

Recently I've gotten round to using your mod since it's been added onto a Cubic Chunks test server which also uses it, and I've noticed it doesnt support Colyta like it says on the mod page? It works just fine with a regular elytra, but both the chestplate combined version along with the bauble version seem to not want to work with using rockets straight from the ground. Is this an issue or does it really just not have the support?

Hope to hear back soon, thanks.

**Comment by ricksouth** [comment]
The compatibility starts in version 1.14.4 and above. 1.12.2 is no longer supported unfortunately. Thanks for the interest though!
