### ISSUE TITLE
Awesome Mod Discovery!!!

### ISSUE THREAD

**Issue by TheIrishStud** [Serilum/.issue-tracker#377]
So I was gandering about in modded hardcore survival when it occured to me that the "Stack Refill" mod doesn't work with fishing poles? Why not? It can be combined with the Forge Autofishing mod for the best starter afk food alternative!... provided players are lucky enough to find a spider spawner right next to the world spawn in the middle of the 1st handful of chunks! Please consider taking a look at this with the fishing pole replacing feature active if you think it's within the realm of possibilities. Thank you for take the time to read this and for doing all the work that you do to make Minecraft better. ^_^

**Comment by ricksouth** [comment]
Thanks for using the mod and opening the issue! I've added compatibility with fishing rods in version 1.2 of the mod:
https://i.gyazo.com/c7908ffca32ef46e8c636dc9a9a24bd3.gif

https://www.curseforge.com/minecraft/mc-mods/stack-refill
