### ISSUE TITLE
[1.12.2] Various zombie-related spawn mods go nuts

### ISSUE THREAD

**Issue by Sunconure11** [Serilum/.issue-tracker#378]
## **Information**
Minecraft version: 1.12.2
Forge version: 14.23.5.2854
Environment: Both

Mod name: Zombie villagers from spawners, zombie horses, and a few others
Mod version: Multiple mods of yours are at fault. Let me just say latest for the appropriate version

## **Description**
The spawn rates of things like zombie villagers and what not are absolutely nuts when it comes to spawners. This causes some absurd lag. They spawn to the point of making normal zombies and what not uncommon from spawners. Is there a workaround for this? Or alternatively, something you can do?

## **Crash report**
N/A

**Comment by ricksouth** [comment]
Unfortunately I no longer support 1.12.2. Thanks for the interest nonetheless! Sorry for the inconvenience.
