### ISSUE TITLE
Bug when spawnproofing End Island

### ISSUE THREAD

**Issue by groovysmooth** [Serilum/.issue-tracker#38]
## **Information**
Minecraft version: 1.14.4
Forge version: 28.2.0
Environment: Multiplayer

Mod name: No Hostiles Around Campfires
Mod version: 1.5

## **Description**
Hi there, love the mod. Have been using a combinations of your campfires and torches to spawn proof the main End island. It was going great and no mobs were spawning on the surface, so i moved to the sides of the island where they had all grouped to. Right after I completely spawn proofed the island, a heap of mobs all started spawning on the surface (which had been mob-free up until this point) all right next to campfires. 

Does the campfire just redirect the mobs to spawn in another location? If so it seems the mobs ran out of places to go and just overloaded on the spawn-proofed territory, instead of not spawning at all.

Would like to know if this is a bug, and if so if it could be fixed. Otherwise, if this is how the campfires are intended to work, a way to work around this issue.

## **Crash report**
No crash.

**Comment by groovysmooth** [comment]
Update: Mobs have begun randomly ignoring campfires in overworld as well. When they do choose to spawn around campfires it's in a large amount. Usually after reloading the server it corrects the issue, but only temporarily.

**Comment by ricksouth** [comment]
I've entirely rewritten the mod in version 2.0. It now requires an external library mod, but the code is a lot more efficient and it should fix the problems you were having. Feel free to open another the issue if that's not the case.

Thanks for letting me know!

[https://www.curseforge.com/minecraft/mc-mods/no-hostiles-around-campfire](https://www.curseforge.com/minecraft/mc-mods/no-hostiles-around-campfire)
