### ISSUE TITLE
for fabric?

### ISSUE THREAD

**Issue by KawaiiTamako** [Serilum/.issue-tracker#381]
## **Information**
(you can remove whatever is not applicable)
Minecraft version: xx.xx.xx
Forge version: xx.xx.xx
Environment: Singleplayer / Multiplayer

Mod name: Mod
Mod version: x.x

## **Comment**
!
for fabric?

**Comment by James103** [comment]
Duplicate of #219
See [the FAQ](https://github.com/ricksouth/serilum-mc-mods/wiki/FAQ) for why the mods are Forge only for the time being.
