### ISSUE TITLE
Config for Message Size

### ISSUE THREAD

**Issue by Crazydude323** [Serilum/.issue-tracker#382]
Mod name: Areas

Super simple idea; a config for the size of the leaving/entering area message. This would let players use the Areas mod to create more varied styles of messages. A classic example is how many games (such as Dark Souls for instance) have a message in large text that appears in the middle of the screen when you enter an area. You can already move the message towards the center using the Y value config, but a config for message size would be great to really convey that feeling of importance.

**Comment by ricksouth** [comment]
Version 2.0 adds the 'HUD_FontSizeScaleModifier' config option, which should work with what you're trying to accomplish. Thank you for submitting the idea and using the mod!

https://www.curseforge.com/minecraft/mc-mods/areas
