### ISSUE TITLE
Where's My Bucket?

### ISSUE THREAD

**Issue by Wasquash** [Serilum/.issue-tracker#383]
When you drink milk with this mod installed and other milk buckets in your inventory, it will refill your slot with another milk bucket like its supposed to, but the ORIGINAL milk bucket is gone. How it SHOULD work is after you drink the bucket, the bucket still appears in your inventory like normal. Because you don't drink the iron bucket.

**Comment by Wasquash** [comment]
Simplified, When you drink a milk bucket with another one in your inventory, it will delete the bucket that's supposed to appear there.

**Comment by ricksouth** [comment]
Thanks for letting me know and using the mod! I can't replace your lost buckets, but version 1.2 of the mod fixes the problem:

https://i.gyazo.com/a5096fe9753c1e0ce7a8190427b7b3b8.gif

**Comment by ricksouth** [comment]
https://www.curseforge.com/minecraft/mc-mods/stack-refill
