### ISSUE TITLE
Use in Vanilla Anarchy Server

### ISSUE THREAD

**Issue by NinjaJedi04** [Serilum/.issue-tracker#384]
## **Information**
(you can remove whatever is not applicable)
Minecraft version: 1.16.4
Forge version: 35.1.4
Environment: Multiplayer

Mod name: All Loot Drops
Mod version: 2.0

## **Question**
I have been playing in a vanilla anarchy server with mods that work for me but do not effect anyone else on the server, including the full brightness mod that you created, is there a way to get the mob loot mod to work on the server for just me as well?

**Comment by ricksouth** [comment]
They're server side mods and won't work when only installed on the client unfortunately. Thanks for the interest!
