### ISSUE TITLE
Does not fertilize crops.

### ISSUE THREAD

**Issue by danemorgan** [Serilum/.issue-tracker#387]
## **Information**
Minecraft version: 1.16.4
Forge version: 35.1.37
Environment: Singleplayer

Mod name: Kelp Fertilizer
Mod version: 1.1

## **Description**
Kelp fertilizes grass, but not crops. I tried with wheat, carrots, and potatoes and none of these take it as fertilizer, but grass blocks still do.

## **Crash report**
No Crash

**Comment by ricksouth** [comment]
I wasn't able to replicate your issue, but I've updated some code and released version 1.2 of the mod. I'm closing the issue for now but if it doesn't solve it on your side please open another one. Thanks for using the mod and submitting the bug report!

https://www.curseforge.com/minecraft/mc-mods/kelp-fertilizer
