### ISSUE TITLE
[REQ] Update for 1.16.5

### ISSUE THREAD

**Issue by Zothen1973** [Serilum/.issue-tracker#388]
Thanks for all your efforts you put into your mods.

Mind updating them for 1.16.5?

**Comment by ricksouth** [comment]
Thank you for the interest! I'm working on the 1.16.5 update right now.

**Comment by ricksouth** [comment]
All mods have been updated to work with 1.16.5

**Comment by Zothen1973** [comment]
Thank you very much!
