### ISSUE TITLE
All Loot Doesn't Drop?

### ISSUE THREAD

**Issue by LeonardoGolden** [Serilum/.issue-tracker#391]
Minecraft version: 1.16.5
Forge version: 36.0.1
Environment: Singleplayer

Mod name: All Loot Drops
Mod version: 1.53

When I used the mod I just went into the config and edited the lootQuantity to 5 and then I started playing, in-game when I kill an entity for the first time I get the 5 things(e.g. when I killed Salmon, I got 5 Salmon and 5 Bone Meal) but when I killed my second of the same entity I got lower than 5(e.g. I killed a second Salmon and I got 1 Salmon and 5 Bone Meal).

Is this a feature or an issue?

**Comment by James103** [comment]
Have you tried increasing the value of `loopsAmountUsedToGetAllEntityDrops` in the Collective library's config?

**Comment by LeonardoGolden** [comment]
> Have you tried increasing the value of `loopsAmountUsedToGetAllEntityDrops` in the Collective library's config?

Yes, it doesn't change anything from my experience, I've tried increasing it and decreasing it, nothing changed.
Do you have the same problem?

**Comment by ricksouth** [comment]
Thanks for submitting the bug report and using the mod! I've fixed it in version 2.1 of the mod.

https://www.curseforge.com/minecraft/mc-mods/all-loot-drops
