### ISSUE TITLE
Stack Refill crash issue

### ISSUE THREAD

**Issue by TheIrishStud** [Serilum/.issue-tracker#392]
Apologies for not quite figuring out how to post this information or that information but when I tried to run 1.16.4 with the latest version of Forge while using the most recent update of Stack Refill version 1.16.5-1.2 a crash error screen popped up saying that this version "needs language provider javafml:36 or above to load". I'm not quite tech savvy but I'll figure out how to post everything eventually. Sorry about this inconvenience.

**Comment by TheIrishStud** [comment]
Apologies for making this issue... I see what I have done wrong.

**Comment by TheIrishStud** [comment]
... Or maybe not... The same crash error occured... X / I thought it might be because I am using the recommended version of Forge and not the Latest version of Forge but that didn't seem to work either.

**Comment by ricksouth** [comment]
You'll need Forge 1.16.5 to run the updated mod. But 1.16.5 should be compatible with most mods of 1.16.4. Sorry for the inconvenience.
