### ISSUE TITLE
Command blocks give error when trying to enchant!

### ISSUE THREAD

**Issue by AustinBryant** [Serilum/.issue-tracker#396]
## **Information**
Minecraft version: 1.16.3
Forge version: 1.16.3-34.1.0
Environment: Singleplayer / Multiplayer (Both)

Mod name: Enchanting Commands
Mod version: 1.3

## **Description**
The commands work fine when executed by a player. However command block and command computers(CC tweaked) can't execute /ec enchant or /ec list.

## **Crash report**
Does not crash, just returns invalid command. It appears in the auto fill. I have not made a mod in a while but it appears that it might not be added to a register for command blocks or it is not being passed through command blocks properly.

**Comment by AustinBryant** [comment]
If you need help managing mods I would not mind some extra work. I am a CS Major and I work part time R&D languages.

**Comment by ricksouth** [comment]
Thanks for the report and the proposition, I'll keep it in mind! Do you have your debug log file? Does it show more information on the error?

**Comment by AustinBryant** [comment]
[debug.log](https://github.com/ricksouth/serilum-mc-mods/files/5900573/debug.log)

**Comment by AustinBryant** [comment]
![Screenshot (4)](https://user-images.githubusercontent.com/59342909/106397007-ea4a0900-63d0-11eb-81c8-560e0415d42e.png)
![Screenshot (5)](https://user-images.githubusercontent.com/59342909/106397008-ea4a0900-63d0-11eb-9f59-82a4d185f84b.png)

The same command works when I run it from chat.

**Comment by James103** [comment]
Maybe the permission level for the `/ec` command is set to 3 or 4, whereas command blocks only get permission level 2, meaning that the command is unusable in command blocks due to insufficient permission.

**Comment by ricksouth** [comment]
Version 1.5 makes the enchanting command compatible with command blocks. Thanks for opening the issue and using the mod!

https://www.curseforge.com/minecraft/mc-mods/enchanting-commands
