### ISSUE TITLE
Crash when entering Border Zone

### ISSUE THREAD

**Issue by Frederick404** [Serilum/.issue-tracker#40]
## **Information**
Minecraft version: 1.14.4
Forge version: 28.2.2
Environment: Dedicated MP Server
Other Mods:
-Yungs Better Caves 1.1.1
-WorldEdit 7.0.1
-Dooglamoo Worlds 1.2.6
-EnhancedSnowman 1.0.1
-Fragile Torches 1.0.0
-PeacefulSurface v2a
-Ruins 4.6
-Save My Stronghold 1.0.0
-Spiders Produce Webs 1.0
//I Honestly Doubt that the other mods do something to cause this crash.

Mod name: World Borders
Mod version: 1.2

## **Description**
Player Crashes from Server when in the Border. Server Stays running and an Error is printed into the Console.
## **Crash report**
Short Paste. Only The Error Itself.
https://pastebin.pl/view/1d6fec8a
Long Paste. Multiple Errors.
https://pastebin.pl/view/efd663be

**Comment by tiphilou17** [comment]
idem in 1.15.2, crash player when tp starting

**Comment by SilverKytten** [comment]
Came here to BR the same issue. 
Server log, for reference.
[latest.log](https://github.com/ricksouth/serilum-mc-mods/files/4672648/latest.log)

**Comment by ricksouth** [comment]
Took my a little (too) long, but I've fixed the issues you were having in version 2.0. Thanks for letting me know and using the mod!

[https://www.curseforge.com/minecraft/mc-mods/world-border](https://www.curseforge.com/minecraft/mc-mods/world-border)
