### ISSUE TITLE
Tree Harvester block breaks not registered to events (or not triggering them)

### ISSUE THREAD

**Issue by Caltinor** [Serilum/.issue-tracker#401]
## **Information**
Minecraft version: 1.16.4
Forge version: 35.1.37
Environment: Singleplayer

Mod name: Tree Harvester
Mod version: 2.0

## **Description**
All blocks broken after the the first during entire-tree break mechanic are not being registered to `BlockEvent#BreakEvent`.  This causes Tree Harvester to break blocks in a way that prevents tracking mods such as PMMO and protection mods from properly tracking/preventing the block breaks.

**Comment by ricksouth** [comment]
Version 2.3 should fix the compatibility issue. The correct events are now being raised. Thanks for using the mod and submitting the issue!

https://www.curseforge.com/minecraft/mc-mods/tree-harvester

**Comment by Caltinor** [comment]
Thank you for working on this.

I did a test on this and was able to confirm the first block broken does trigger the `BreakEvent` however, the other blocks being broken (logs and leaves) are not.

Also, I did not mention this in the initial issue, but it did not occur to me until now.  The placing of the sapling should also be checked via `EntityPlaceEvent`.

**Comment by ricksouth** [comment]
Apologies that it has taken so long. But version 5.0 of Tree Harvester now actually fires the BlockBreak events for the harvested logs and the BlockPlace event for the replaced saplings. Thanks for opening the issue and giving the mod a try!

https://www.curseforge.com/minecraft/mc-mods/tree-harvester
