### ISSUE TITLE
Stack Refill Exnihilo sequentia compatibility

### ISSUE THREAD

**Issue by Staegrin** [Serilum/.issue-tracker#404]
## **Information**
Stack Refill & Exnihilo sequentia.

## **Feature description**
When sieving gravel/sand/dust and a stack gets used you need to go into your inventory to switch to the next stack of gravel/sand/dust. It would be great if the stack would refill.

**Comment by ricksouth** [comment]
I've added support for modded blocks such as sieves in version 1.4 of the mod. Thanks for the suggestion and using the mod!

https://www.curseforge.com/minecraft/mc-mods/stack-refill

**Comment by Staegrin** [comment]
Works great. Thank you.

**Comment by Staegrin** [comment]
![2021-02-10_18 47 20](https://user-images.githubusercontent.com/8494635/107549711-71b52a80-6bd0-11eb-8866-019353ef24f8.png)
Found a bug in the compatibility. Default range for a sieve is 2 so a 5 by 5 arrangement of sieves is the default set-up. In case of a 3 by 3 the stack refill works. Sadly when you add more sieves the gravel/sand/dust no longer gets put in the hotbar after using the current stack.

The mod config lets you go up to 11 by 11. Not sure if those give problems as well.

**Comment by ricksouth** [comment]
Version 1.6 should work with the 5x5 setup. If not, please let me know. Thanks!

https://www.curseforge.com/minecraft/mc-mods/stack-refill

**Comment by Staegrin** [comment]
It works great. Thanks for all the hard work.

**Comment by ricksouth** [comment]
Good to hear! :)
