### ISSUE TITLE
Stack Refill removes bucket of fish if multiple buckets of water exist in your inventory

### ISSUE THREAD

**Issue by gorturtle** [Serilum/.issue-tracker#406]
## **Information**
Minecraft version: 1.16.5
Forge version: 36.0.7 and 36.0.14
Environment: Singleplayer and Multiplayer Survival

Mod name: Stack Refill
Mod version: 1.2 and 1.3

## **Description**
When attempting to catch fish entities using a bucket of water with at least one other bucket of water in your inventory in order to get a bucket of fish item (ex. pufferfish_bucket) when you click on the entity with the bucket of water, the bucket of fish will be overwritten by the bucket of water from your inventory resulting in the loss of the bucket and the fish entity. I was able to replicate this issue multiple times with both vanilla and modded fish entities on instances of minecraft where it was the only mod enabled as well as when other mods were present. This behavior only seems to happen when in survival mode. In creative mode, you will receive the proper bucket of fish item. The server I am hosting with the mod is using forge version 36.0.7 but I was able to replicate this in newer versions of forge as well. 

## **Crash report**
The game does not crash and does not generate any report.

**Comment by ricksouth** [comment]
Thanks for using the mod and submitting the bug report! I've fixed this in version 1.4 of the mod.

https://www.curseforge.com/minecraft/mc-mods/stack-refill
