### ISSUE TITLE
Does not work well with Corail Tombstone (and probably other grave mods)

### ISSUE THREAD

**Issue by Gotyam** [Serilum/.issue-tracker#408]
## **Information**
Minecraft version: 1.16.5
Forge version: 36.0.14
Environment: Singleplayer

Mod name: Respawn Delay
Mod version: 1.2

## **Description**
When you die using both Respawn Delay and Corail Tombstone you drop items as per a vanilla death, rather than getting a tombstone. As disabling dropping items = keep inventory, that still results in no grave.

I hope it is possible to make Respawn Delay work nicely with grave mods, as I do like the idea of having a respawn delay.

**Comment by ricksouth** [comment]
Unfortunately I'm aware of this. I tried to make them compatible but didn't succeed so far. I'll give it another try. Thanks for using the mod!

**Comment by ricksouth** [comment]
Version 2.0 of Respawn Delay is compatible with gravestone mods. Thanks for submitting the issue and giving the mod a try.

https://www.curseforge.com/minecraft/mc-mods/respawn-delay
