### ISSUE TITLE
Crash on Giant Spawn event

### ISSUE THREAD

**Issue by groovysmooth** [Serilum/.issue-tracker#41]
## **Information**
Minecraft version: 1.14.4
Forge version: 28.2.0
Environment: Multiplayer

Mod name: Giant Spawn
Mod version: 1.0.2

## **Description**
Crash on what appears to be the giant spawn event. It doesn't do this every time, as I have seen one spawn before, but this has crashed the server multiple times now.

## **Crash report**
[crash-2020-03-01_14.38.05-server.txt](https://github.com/ricksouth/serilum-mc-mods/files/4272325/crash-2020-03-01_14.38.05-server.txt)

**Comment by ricksouth** [comment]
Thanks for using the mod and submitting the issue! This has been fixed in the latest release, together with custom AI for the giants.

[https://www.curseforge.com/minecraft/mc-mods/giant-spawn](https://www.curseforge.com/minecraft/mc-mods/giant-spawn)
