### ISSUE TITLE
GUI Clock X Coord

### ISSUE THREAD

**Issue by Fortist** [Serilum/.issue-tracker#410]
For the GUI clock mod, you have a Y coordinate config setting, but no X? Theres a few mods that add stuff to both corners of the screen, and I'd like to move the clock to the left side of my minimap in the top right corner.

**Comment by ricksouth** [comment]
Thanks for the suggestion and giving the mod a try! I've added the clockWidthOffset config option in version 2.6 of GUI clock.

https://www.curseforge.com/minecraft/mc-mods/gui-clock/files
