### ISSUE TITLE
axes doesn't lose durability when chopping trees

### ISSUE THREAD

**Issue by justin9106** [Serilum/.issue-tracker#413]
Minecraft version: 1.16.4
Forge version: 35.1.37
Environment: Singleplayer

Mod name: Tree Harvester
Mod version: 2.0

## **Description**
axes doesn't lose durability when chopping trees

**Comment by ricksouth** [comment]
This has been fixed in version 2.2 of the mod. It's only available for Minecraft version 1.16.5 though. Thanks for letting me know and using the mod nonetheless!

https://www.curseforge.com/minecraft/mc-mods/tree-harvester
