### ISSUE TITLE
Drop Percentages Not Working Properly?

### ISSUE THREAD

**Issue by viiizee** [Serilum/.issue-tracker#415]
## **Information**
Minecraft version: 1.16.4
Forge version: 35.1.37
Environment: Singleplayer

Mod name: Configurable Extra Mob Drops
Mod version: 1.1

## **Description**
So I've been trying to use the /cemd addhand command for the better part of 3 hours trying to get a drop chance for a particular item that is semi-rare. Unfortunately, there doesn't seem to be any rime or merit to how this percentage works as sometimes I'll put 0.02 (assuming 2% drop chance, only to get what seems to be a 100% drop chance. Then I'll use /cemd clear drops and try the same value again only to kill like (no exaggeration) 300 of that particular mob and get no drops.

A better explanation of the allowable drop percentages would be nice. I've also noticed that the drop chance seems to increase the further I bring the decimal place to the left or right with the middle being maybe somewhere around 0.01, but honestly I have no idea it's all over the place.

## **Crash report**
None.

**Comment by ricksouth** [comment]
Thanks for using the mod and submitting the bug report! Version 1.2 of the mod solves the issues you were having. The dropchance didn't work correctly anymore after the first drop. Sorry for the inconvenience. The lower dropchances (1/100, 1/1000 etc) are working correctly now.

https://www.curseforge.com/minecraft/mc-mods/configurable-extra-mob-drops
