### ISSUE TITLE
Forge Server running The Vanilla Experience Modpack hanging after stop command

### ISSUE THREAD

**Issue by HuntingForVodka** [Serilum/.issue-tracker#416]
## **Information**
Minecraft version: 1.16.5
Forge version: 36.0.1
Environment:  Multiplayer

Mod name: [The Vanilla Experience](https://www.curseforge.com/minecraft/modpacks/the-vanilla-experience) - Modpack
Mod version: 2.28
[modlist.txt](https://github.com/ricksouth/serilum-mc-mods/files/5940051/modlist.txt)

## **Description**
Forge server with above modpack seems to hang after using the stop command.
Server closes down and saves correctly but left in hanging state.
requiring the terminal window to be closed or Ctrl+C to exit.

## **Testing so Far**
Server setup is as described on the [modpack ](https://www.curseforge.com/minecraft/modpacks/the-vanilla-experience)page  on fresh install of Forge server 36.0.1 
Then copying all the mods in the mods CurseForge 2.28 version of modpack to the server.
Then Launching server via .bat file no java arguments beyond -Xms4G
[Start bat.txt](https://github.com/ricksouth/serilum-mc-mods/files/5940099/Start.bat.txt)

Test are preformed launching from start script (Windows 10 and Ubunto 20.04)

Confirmed that fresh install of forge does not behave the same close and returns as normal. 
once mods are added either a fresh world or vanilla world using the stop command will close and exit the server.
but leaving the terminal stuck.

Next step would be process elimination removing mods one by one.

Figure I should start ticket first.

## **Crash report**
No Crash report, Logs added.
[debug.log](https://github.com/ricksouth/serilum-mc-mods/files/5940111/debug.log)
[latest.log](https://github.com/ricksouth/serilum-mc-mods/files/5940112/latest.log)

**Comment by ricksouth** [comment]
First of all, thanks for using the modpack! Haven't come across this problem before. Does it also happen when you install another modpack on the same server? Or just for The Vanilla Experience?

**Comment by HuntingForVodka** [comment]
Thank you for the quick reply. 
Went and grabbed the first pack I could find that is same versions of Minecraft and Forge
[Slightly Vanilla 1.16.5-1.1.0 ](https://www.curseforge.com/minecraft/modpacks/slightly-vanilla-flavoured)
[modlist.txt](https://github.com/ricksouth/serilum-mc-mods/files/5940183/modlist.txt)

While it bothers me that is listed as an alpha release it does not exhibit the same behavior.
Using the same test Server setup and same start script fire ups and then using the Stop command saves and exits normally.

*Edit correct version

**Comment by HuntingForVodka** [comment]
Alright had the chance to cut through all the mods 
and it seems to be [Quick Paths](https://www.curseforge.com/minecraft/mc-mods/quick-paths) Doing this. 

Same server setup as before but only the below mods in the mod folder
collective-1.16.5-1.53.jar
quickpaths_1.16.5-1.2.jar 

*Update*
Attempted with updated versions same issue persist
collective-1.16.5-1.58.jar
quickpaths_1.16.5-1.3.jar

as well the reverse is true removing just quickpaths as well no longer hangs

**Comment by ricksouth** [comment]
I've changed the clean memory function of Quick Paths to work on the main thread (Server tick) which should solve the problem. Version 1.4 of Quick Paths is available and as soon as the API of the CurseForge app updates I'll release an updated version of The Vanilla Experience. I'll close the issue as soon as the new TVE version is uploaded.

Thanks for figuring the problem out and using the modpack!

https://www.curseforge.com/minecraft/mc-mods/quick-paths

**Comment by HuntingForVodka** [comment]
Can confirm server now stops and close correctly with most update version of mods.
Mods used in testing.
collective-1.16.5-1.58.jar
quickpaths_1.16.5-1.4.jar

Cheers and thanks for the help!

**Comment by ricksouth** [comment]
Good to hear! No problem. I've uploaded The Vanilla Experience 2.29 which updates a lot of mods including Quick Paths. Thanks again!

https://curseforge.com/minecraft/modpacks/the-vanilla-experience
