### ISSUE TITLE
Fresh install of TNT Bedrock still doesn't break bedrock

### ISSUE THREAD

**Issue by Lughbaloo** [Serilum/.issue-tracker#417]
I've just downloaded fresh versions in 1.16.5 and started a brand new world and this still does not break bedrock with tnt.

![image](https://user-images.githubusercontent.com/44557173/107164205-0115d000-697c-11eb-8e03-b9ee5a06cae1.png)

![image](https://user-images.githubusercontent.com/44557173/107164214-0bd06500-697c-11eb-8861-4df1cbb7fc4f.png)

![image](https://user-images.githubusercontent.com/44557173/107164220-112daf80-697c-11eb-8d9f-310d0abd0173.png)

![image](https://user-images.githubusercontent.com/44557173/107164231-2571ac80-697c-11eb-9e1d-8a88ce976cc0.png)

This is in single player. There are no extra mods as you can see. The world is brand new as you can also see. 

I've also attached the latest.log and latest debug.log
[debug.log](https://github.com/ricksouth/serilum-mc-mods/files/5940577/debug.log)

[latest.log](https://github.com/ricksouth/serilum-mc-mods/files/5940575/latest.log)

Not sure what to tell you sir. Everything is fresh installed.

_Originally posted by @Lughbaloo in https://github.com/ricksouth/serilum-mc-mods/issues/399#issuecomment-774801990_

**Comment by ricksouth** [comment]
![2021-02-08_12 35 56](https://user-images.githubusercontent.com/38502394/107214530-50a2dd00-6a0a-11eb-8c2a-12a394f77aa3.png)
![2021-02-08_12 35 59](https://user-images.githubusercontent.com/38502394/107214533-513b7380-6a0a-11eb-92e4-523d95a5d434.png)
![2021-02-08_12 36 26](https://user-images.githubusercontent.com/38502394/107214535-513b7380-6a0a-11eb-926e-ba59d822a65d.png)
![2021-02-08_12 36 29](https://user-images.githubusercontent.com/38502394/107214536-513b7380-6a0a-11eb-963d-db7c957db796.png)

**Comment by ricksouth** [comment]
There is the problem, a redstone torch doesn't work! Thanks for the bug report, I'll try to fix it right now.

**Comment by ricksouth** [comment]
I've fixed it in version 1.4 of the mod. Tested with both the flint & steel and a redstone torch. Thanks for submitting another bug report and using the mod!

https://www.curseforge.com/minecraft/mc-mods/tnt-breaks-bedrock
