### ISSUE TITLE
Refill eggs

### ISSUE THREAD

**Issue by Napkin** [Serilum/.issue-tracker#418]
## **Information**
Mod name: Stack Refill

## **Feature description**
It would be very convenient if eggs could also be automatically refilled into the hotbar after throwing all of the stack. Thank you!

**Comment by ricksouth** [comment]
Thanks for the suggestion and using the mod! I've added thrown eggs replacement in version 1.5 of the mod.

https://www.curseforge.com/minecraft/mc-mods/stack-refill
