### ISSUE TITLE
Clock not showing

### ISSUE THREAD

**Issue by CrxsTagz** [Serilum/.issue-tracker#419]
## **Information**
(you can remove whatever is not applicable)
Minecraft version: 1.16.5
Forge version: Latest
Environment: Singleplayer

Mod name: GUI Clock
Mod version: 2.1

## **Question**
How can i see the clock??? I've tried to configure it but it's not available!!!

Please Help

**Comment by ricksouth** [comment]
By default you need a clock item in your inventory. Otherwise you can change the config, for that check the FAQ: https://github.com/ricksouth/serilum-mc-mods/wiki/FAQ

Thanks for using the mod!
