### ISSUE TITLE
Server Hang

### ISSUE THREAD

**Issue by frakier** [Serilum/.issue-tracker#42]
## **Information**
Minecraft version: 1.14.4
Forge version: 28.2.0
Environment: Multiplayer

Mod name: nhacampfire_1.14-1.5.jar No Hostiles Around Campfire
Mod version: 1.5

## **Description**
Been having problems for awhile started with 28.1.114, updated to 28.2.0 to see if anything changed. We run into the old problem from minecraft where a horse disappears or lag and you get ghost block so you have to log out and back in ever so foten, no problem most of the time but ever so often when you log back in you either get disconnected or you get in and the world does not load and you get kicked with a time out and as time passed the problem got worse. Once you are kicked out if you wait long enough 20-30 minutes the server will eventually crash and this is the error in the crash report... 
ServerHangWatchdog detected that a single server tick took 1200.00 seconds (should be max 0.05)

## **Crash report**
[crash-2020-03-08_16.54.00-server.txt](https://github.com/ricksouth/serilum-mc-mods/files/4304265/crash-2020-03-08_16.54.00-server.txt)

Hope this helps. I have tried to reproduce the error on a server starting from scratch [deleting the world and starting over] and could not get this error. Seems the error shows up more as the world gets older/more use.

**Comment by ricksouth** [comment]
I've entirely rewritten the mod in version 2.0. It now requires an external library mod, but the code is a lot more efficient and it should fix the problems you were having. Feel free to open another the issue if that's not the case.

Thanks for letting me know!

[https://www.curseforge.com/minecraft/mc-mods/no-hostiles-around-campfire](https://www.curseforge.com/minecraft/mc-mods/no-hostiles-around-campfire)
