### ISSUE TITLE
Stack Refill spams logs

### ISSUE THREAD

**Issue by ghost** [Serilum/.issue-tracker#422]
Minecraft version: 1.16.5
Forge version: 36.0.15
Environment: Singleplayer

Mod name: Stack Refill
Mod version: 1.4

Logs get spammed with actions such as block interactions and dropping items. My guess is that you just forgot to turn off debug messages.

**Comment by ricksouth** [comment]
Yep something went wrong with exporting the jar file. Thanks for letting me know! Working on a fix right now.

**Comment by ricksouth** [comment]
This has been fixed in version 1.5 of the mod. Thanks again! :)

https://www.curseforge.com/minecraft/mc-mods/stack-refill
