### ISSUE TITLE
Automatic Doors activate even in spectator mode

### ISSUE THREAD

**Issue by ghost** [Serilum/.issue-tracker#424]
Minecraft version: 1.16.5
Forge version: 36.0.22
Environment: Singleplayer

Mod name: Automatic Doors
Mod version: 1.5

Doors automatically open even in spectator mode. Not much more to say.

**Comment by ricksouth** [comment]
Thanks for opening the issue and using the mod! This has been fixed in version 1.6 of the mod.

https://www.curseforge.com/minecraft/mc-mods/automatic-doors
