### ISSUE TITLE
Allow automatic doors to activate at y-values below the door

### ISSUE THREAD

**Issue by ghost** [Serilum/.issue-tracker#425]
Mod name: Automatic Doors

Doors only function at y-levels between the bottom of the door and two blocks up (e.g. if a grass path or slab is next to the top block of a door and a player walks on it, the door opens). However, if there is a block that isn't a full block high (such as a grass path) in front of the door, it will not automatically open.

It's not technically a bug, so that's why I'm submitting this as a feature idea.

![door_shenanigans](https://user-images.githubusercontent.com/11356733/107603199-fb2d2280-6bf9-11eb-9694-dc724f132fb0.png)
Left: door opens
Right: door does not open

**Comment by ricksouth** [comment]
Thanks for submitting the bug report and using the mod! This has been fixed in version 1.7 of the mod.

https://www.curseforge.com/minecraft/mc-mods/automatic-doors
