### ISSUE TITLE
Giant Zombies do not catch fire in daylight?

### ISSUE THREAD

**Issue by nanonestor** [Serilum/.issue-tracker#428]
## **Information**
Minecraft version: 1.16.5
Forge version: 36.0.21
Environment: Singleplayer / Multiplayer

Mod name: Giant Spawn
Mod version: giantspawn_1.16.5-2.2.jar
Collective version: collective-1.16.5-1.59.jar

## **Description**

Unfortunately - Giant Zombies are not catching fire in daylight despite:
shouldBurnGiantsInDaylight = true

No log data appears regarding in latest.log or debug log.
Let me know if you have any questions or would like other information.  
The modpack being used is my own which is published on curseforge: [https://www.curseforge.com/minecraft/modpacks/the-briar-patch](url)

**Comment by ricksouth** [comment]
Thanks for submitting the bug report and using the mod! I've just released version 2.3 of the mod which makes some tweaks and should fix your problem.

https://www.curseforge.com/minecraft/mc-mods/giant-spawn

**Comment by nanonestor** [comment]
Hi Ricksouth - I never got back about this - however still as of the current release giants will not catch fire in daylight.  I don't  really know what other information I can provide other than that as log files / debug log don't show any errors being thrown.  Let me know if there are any questions I could answer possibly though - thanks.
