### ISSUE TITLE
not necessarily bad but surprising bug

### ISSUE THREAD

**Issue by npcgoblin** [Serilum/.issue-tracker#43]
## **Information**
Minecraft version: 1.15.2
Forge version: xx.xx.xx
Environment: Singleplayer / LAN

Mod name: no hostiles around campfire
Mod version: x.x

## **Description**
so ya know how it prevents hostiles form spaning but allows passive mobs, i encountered something that through logic and testing afterwards im90% sure that it was a bugged thing that happened when a baby zombie chicken jockey spawned in the area of a campfire.

i encountered a chicken that was hostile and making baby zombie sounds. there was no zombie on top of it whatsoever even after killing it, but it seemed like the chicken zombie jockey attempted to spawn and the campfire stopped the zombie from spawning but didnt stop the chicken from spawning but i believe the chicken didnt realize the change to its status without the zombie gone so the game's ai for that chicken was still acting as if it had a zombie riding it so it behaved exactly like the baby zombie would have and was an aggressive chicken lol

## **Crash report**
If available.

**Comment by ricksouth** [comment]
That's pretty well found! I've prevented the chickens from spawning as well in version 2.0 of the mod. This should fix the issues you were having. Thanks for letting me know.

[https://www.curseforge.com/minecraft/mc-mods/no-hostiles-around-campfire](https://www.curseforge.com/minecraft/mc-mods/no-hostiles-around-campfire)
