### ISSUE TITLE
Giant Spawn features

### ISSUE THREAD

**Issue by ricksouth** [Serilum/.issue-tracker#431]
## **Information**
Mod name: Giant Spawn

## **Feature description**
48004800: "1  The Giants in your mod arenot undead creatures.(They are attacked by wither}

2 Giants shuold find their target at a greater distance.

3 Giants cannot counterattack 

4 Giants should have some good drops and more xp"

**Comment by 4zy1** [comment]
I agree with the more XP, it's pretty underwhelming when you get the same amount as regular Zombies.

**Comment by NixityNull** [comment]
I don't know if this was mentioned before, but the hitbox also needs to be fixed. It is currently at the size of a regular zombie, making it practically impossible to hit without being within the area where it can hit you. It's really disappointing to not be able to shoot a giant zombie with arrows and stuff because his hitbox is in his toes.

**Comment by louis-vinchon** [comment]
Related to https://github.com/ricksouth/serilum-mc-mods/issues/397 I suppose.

May I suggest that the XP / loot modifier, HP, damage, and size be configurable?

I would love me some stronger / taller zombies but not a 10x taller one. I was hoping to add some variety in combats, not really an "attack on titan" sized zombie.

**Comment by James103** [comment]
> May I suggest that the XP / loot modifier, HP, damage, ...

That could be done while retaining the server-side-only nature of Giant Spawn mod.

> ...and size be configurable?

That would not be feasible in a single server-side mod as it would require changes on the client-side to work properly (mainly entity model rendering and hitboxes).

**Comment by louis-vinchon** [comment]
Alright, I don't know the subtilities of server vs client in Minecraft so I'll take your work for it; not planned for now.

**Comment by ricksouth** [comment]
I appreciate the feature suggestion! In order to reduce the amount of open issues on this Github repository, I've created a separate Github project page for all mod feature requests. It can be found here:
https://serilum.com/mods/requests.

I'll be closing this issue, but I'm keeping track of all ideas on the project page over there.

It definitely does not mean I am not interested, and I will post a comment here as well if/when a feature is implemented.

Thank you very much for the suggestion!

**Comment by ricksouth** [comment]
Hey!

I still appreciate the submission a lot, and wanted to give an update on this. While I'd love to add all features submitted on the issue-tracker, due to having limited time, I've just not been able to. In order to see which features users would like to see most, I've updated https://serilum.com/mods/requests. The page now shows a table, with all feature request submitted.

Users are able to upvote requests by reacting to the first issue post here on GitHub with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top.

This doesn't necessary mean I'll only work on popular features in the upcoming years, but it does help with prioritizing.

Thank you again for the suggestion!
