### ISSUE TITLE
Drop heads only from charged creeper feature

### ISSUE THREAD

**Issue by ricksouth** [Serilum/.issue-tracker#434]
## **Information**
Mod name: Just Mob Heads/Just Player Heads

## **Feature description**
34638a: "If it is at all possible could there be a configuration option added to make it so that mob heads only drop from charged creeper explosions, regardless of the mob, in addition to the standard set of zombies, skeletons and creepers?"

**Comment by James103** [comment]
And same for player heads (i.e. you only drop your own head if you are killed by a charged creeper)?

**Comment by ricksouth** [comment]
I've added the config option **onlyDropHeadsByChargedCreeper** in version 5.0 of Just Mob Heads.

https://www.curseforge.com/minecraft/mc-mods/just-mob-heads/files/all

Keeping the issue for Just Player Heads.

**Comment by ricksouth** [comment]
I appreciate the feature suggestion! In order to reduce the amount of open issues on this Github repository, I've created a separate Github project page for all mod feature requests. It can be found here:
https://serilum.com/mods/requests.

I'll be closing this issue, but I'm keeping track of all ideas on the project page over there.

It definitely does not mean I am not interested, and I will post a comment here as well if/when a feature is implemented.

Thank you very much for the suggestion!

**Comment by ricksouth** [comment]
Hey!

I still appreciate the submission a lot, and wanted to give an update on this. While I'd love to add all features submitted on the issue-tracker, due to having limited time, I've just not been able to. In order to see which features users would like to see most, I've updated https://serilum.com/mods/requests. The page now shows a table, with all feature request submitted.

Users are able to upvote requests by reacting to the first issue post here on GitHub with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top.

This doesn't necessary mean I'll only work on popular features in the upcoming years, but it does help with prioritizing.

Thank you again for the suggestion!
