### ISSUE TITLE
Using bonemeal in non minecraft biomes spawns no flowers

### ISSUE THREAD

**Issue by halloo123** [Serilum/.issue-tracker#436]
## **Information**
Minecraft version: 1.16.5
Forge version: 36.0.22
Environment: Singleplayer or Multiplayer

Mod name: Random Bone Meal Flowers
Mod version: 1.2

## **Description**
If I use bonemeal in minecraft biomes the mod works properly, if I use bonemeal in a biomesoplenty biome for example no flowers will spawn at all.

## **Crash report**
No crash to report

**Comment by ricksouth** [comment]
The mod replaces existing flowers and randomizes them. I think in this case the biomeofplenty biome doesn't spawn flowers itself, so the mod has nothing to replace. I don't see this as a bug. Thanks for submitting the issue and using the mod though!
