### ISSUE TITLE
Config Option

### ISSUE THREAD

**Issue by Scamper10** [Serilum/.issue-tracker#437]
## **Information**
Mod name: Tree Harvester for 1.15.2

## **Feature description**
The mod already works with other modded trees, but sometimes it doesn't know which block is the "bottom block." This could be fixed by adding a config option to change whether or not it needs to be the bottom block for the tree to be destroyed.

**Comment by ricksouth** [comment]
Apologies that it took so long to get to it. I've just released version 4.0 of Tree Harvester which adds the config option 'automaticallyFindBottomBlock', enabled by default. This should add the functionality you've requested. Thanks for giving the mod a try and submitting the sugestion!

https://www.curseforge.com/minecraft/mc-mods/tree-harvester/files
