### ISSUE TITLE
Not a Villager but tried to give death message?

### ISSUE THREAD

**Issue by Thoughtful-Username** [Serilum/.issue-tracker#439]
## **Information**
Minecraft version: 1.12.2
Forge version: 14.23.5.2854
Environment: Singleplayer

Mod name: Villager Death Messages
Mod version: 1.6

## **Description**
'Treasure2' mod spawned a graveyard within a village and on killing one of the mobs associated with the graveyard, Villager Death Messages caused a crash.

[crash-2021-02-14_13.34.45-server.txt](https://github.com/ricksouth/serilum-mc-mods/files/5978280/crash-2021-02-14_13.34.45-server.txt)

## **Crash report**
If available.

**Comment by ricksouth** [comment]
Thanks for submitting the bug report and using the mod. This has been fixed in version 1.7.

https://www.curseforge.com/minecraft/mc-mods/villager-death-messages
