### ISSUE TITLE
[Starter Kit] command don't apply nbt on config

### ISSUE THREAD

**Issue by AlleCraft-alterego** [Serilum/.issue-tracker#440]
## **Information**
Starter Kit: starterkit_1.16.5-2.2
Minecraft version: 1.16.4
Forge version: 36.0.22
Environment: Singleplayer

command of mod (/starterkit set) don't apply nbt on config

**Comment by ricksouth** [comment]
Can you supply screenshots of your inventory and upload the starterkit.txt file(s) here?

**Comment by AlleCraft-alterego** [comment]
sorry, I found that sophisticated backpack in the latest versions has changed the method for holding items
