### ISSUE TITLE
Villager Death Messages

### ISSUE THREAD

**Issue by TheTntExpert29** [Serilum/.issue-tracker#442]
## **Information**
(you can remove whatever is not applicable)
Minecraft version: 1.15.2
Forge version: I don't know the version
Environment: Singleplayer

Mod name: Villager Death Messages
Mod version: 1,6

## **Question**
How can I config the settings?

**Comment by ricksouth** [comment]
Thanks for using the mod! Please check the FAQ on how to configure mods: https://github.com/ricksouth/serilum-mc-mods/wiki/FAQ
