### ISSUE TITLE
Pets in other dimension (nether) will still show up on follower GUI

### ISSUE THREAD

**Issue by AzureMonument** [Serilum/.issue-tracker#443]
## **Information**
Minecraft version: 1.16.5
Forge version: 36.0.22
Environment: Singleplayer

Mod name: GUI Followers
Mod version: 1.2

## **Description**
So, I've downloaded another mod called Yung's Better Portals that changes how you get to and from the nether, and I also have quark which added foxhounds. I've tamed a foxhound while in the nether, but as of right now there is either a bug or it's simply not implemented where entities other than the player cannot be teleported out of the nether. (note that I only tested this while my foxhound was standing up, meaning I left the nether while it was standing and not sitting)

![2021-02-15_14 43 24](https://user-images.githubusercontent.com/43318292/107989059-63d02280-6f9f-11eb-9293-c5733260735e.png)

Now, this is where this mod comes in. After teleporting to the overworld without my pet foxhound, I noticed I could still see its GUI.
![2021-02-15_14 45 39](https://user-images.githubusercontent.com/43318292/107989106-7a767980-6f9f-11eb-82e6-a701278a0fa6.png)

Attempting to reach the position of my follower (in the overworld) as stated, led to me an area of open sky. Here you can see me on the ground (and jumping in the second image) to show there's nothing there.

![2021-02-15_14 46 14](https://user-images.githubusercontent.com/43318292/107989153-9bd76580-6f9f-11eb-8448-da7b522b7c88.png)
![2021-02-15_14 46 15](https://user-images.githubusercontent.com/43318292/107989156-9da12900-6f9f-11eb-99bf-b63dd7c6aba1.png)

I then went back to the nether and made my foxhound lay down, before teleporting back to the overworld. But then I noticed another bug! My foxhound GUI was still there! So I teleported back to the nether to check on my foxhound, and lo and behold the GUI was now on despite my foxhound laying down/sitting!
![2021-02-15_15 08 28](https://user-images.githubusercontent.com/43318292/107989291-fe306600-6f9f-11eb-9055-433557b60451.png)

I even tried having my foxhound stand up then sit again, to no avail.
![2021-02-15_15 11 11](https://user-images.githubusercontent.com/43318292/107989340-1902da80-6fa0-11eb-9436-f3287a4b6b71.png)
![2021-02-15_15 11 17](https://user-images.githubusercontent.com/43318292/107989342-1c966180-6fa0-11eb-9d3c-c335b55e1a0c.png)

Instead, it seems to have duplicated my foxhound GUI data. ... I just realized this may simply be a bug with Yung's Portals duplicating entity data... Uh. Well, I'll still submit this here just incase.

EDIT: Wait, that wouldn't make sense then, as the same GUI I have in the overworld also exists in the nether, regardless of my original foxhound...

## **Crash report**
No crashes

**Comment by AzureMonument** [comment]
![2021-02-15_15 17 30](https://user-images.githubusercontent.com/43318292/107989764-f1604200-6fa0-11eb-9c1a-660c95cbb764.png)

Save & quitting seems to have removed the extra follower data.
EDIT: also, leaving the nether while your pet is sitting seems to work fine.

**Comment by ricksouth** [comment]
Thanks for the detailed bug report! I appreciate it. I'll take a look at it soon when I can.

**Comment by ricksouth** [comment]
I've fixed it in version 1.3 of the mod. Thanks again!

https://www.curseforge.com/minecraft/mc-mods/gui-followers
