### ISSUE TITLE
Gui

### ISSUE THREAD

**Issue by SourishLemon-pro** [Serilum/.issue-tracker#447]
## **I have no idea how to configure the mod. I Just need the day counter part and can't find anything on youtube (Im on Mac btw)**

Minecraft version: 1.16.5.
Forge version: 36.0.14
Environment: Singleplayer 
Mod name: Gui clocks
Mod version: 2.1

## **How do I configure the day counter**
?

**Comment by ricksouth** [comment]
Please check out the FAQ on how to configure mods: https://github.com/ricksouth/serilum-mc-mods/wiki/FAQ
