### ISSUE TITLE
Error during complete event phase

### ISSUE THREAD

**Issue by GrimmATN** [Serilum/.issue-tracker#448]
When launching the game I'm taken to the mod loading error screen.

It states:

"Kelp Fertilizer (kelpfertilizer) encountered an error during the complete event phase
java.lang.ArrayIndexOutOfBoundsException: -1"

Crash TXT File: [kelpmodcrash.txt](https://github.com/ricksouth/serilum-mc-mods/files/6000337/kelpmodcrash.txt)

**Comment by ricksouth** [comment]
Thanks for submitting the bug report and using the mod! This has been fixed in version 1.3 of the mod.

https://www.curseforge.com/minecraft/mc-mods/kelp-fertilizer
