### ISSUE TITLE
make them look like crack/meth heads

### ISSUE THREAD

**Issue by kreezxil** [Serilum/.issue-tracker#45]
## **Information**
Mod name: Edible Sugar

## **Feature description**
do something to the player model that makes their eyes dart around when viewed by other players.

I don't even know if this doable but ... let's just see what happens. :)

**Comment by ricksouth** [comment]
This is unfortunately not something I currently know how to do. If I ever get to work with the player models I'll keep it in mind. Thanks for the idea!
