### ISSUE TITLE
respawn delay crashes my server after someone dies then leaves.

### ISSUE THREAD

**Issue by K1ngClown** [Serilum/.issue-tracker#451]
## **Information**
Minecraft version: 1.16.4
Forge version: latest
Environment:  / Multiplayer

Mod name: Respawn Delay
Mod version: 1.16.4

## **Description**
Hey! This happened.. whenever someone dies, then leaves the server it crashes the server , a suggeston to fix this issue would be to kick the player who dies for whatever amount of time was configed

## **Crash report**
If available.

**Comment by ricksouth** [comment]
Please provide the crash report so I can understand where the problem is. It's in a folder in your main server location.

**Comment by ricksouth** [comment]
Closing this until provided with a crash log.

**Comment by tequt** [comment]
Has anyone managed to replicate this?
