### ISSUE TITLE
Use on Servers

### ISSUE THREAD

**Issue by NHoltz02** [Serilum/.issue-tracker#452]
## **Information**
(you can remove whatever is not applicable)
Minecraft version: 1.16.4
Forge version: 351.36
Environment: Multiplayer

Mod name: Automatic Doors
Mod version: x.x

If I install this on a Forge server, does the mod need to be installed client side as well in order for it to work??

**Comment by ricksouth** [comment]
Thanks for the interest. The mod has to only be installed on the server. The client is not needed.
