### ISSUE TITLE
Village Generation?

### ISSUE THREAD

**Issue by mcquestion** [Serilum/.issue-tracker#453]
## **Information**
Minecraft version: 1.16.5
Forge version: 36.0.42
Environment: Singleplayer

Mod name: Village Spawn Point
Mod version: 1.4

## **Question**
If the mod cannot find a village close to 0, 0, does it generate one? Or simply keep looking until it finds one?
Thanks, love the mod btw!

**Comment by ricksouth** [comment]
It keeps looking in a radius of 10000 blocks. If it can't find one, the default spawn will be used. The chance there isn't a village within that radius is pretty much 0%. Thanks for the interest!
