### ISSUE TITLE
1.16.3 TNTbreakBedrock crashes Server

### ISSUE THREAD

**Issue by HeroGamer2119** [Serilum/.issue-tracker#455]
## **Information**
Minecraft version: 1.16.3
Forge version: 34.1.42
Environment: Multiplayer Server
Mod name: TNT Breaks Bedrock
Mod version: 1.2

I put the Mod on my Server along with 44 other mods, which work fine, and on startup the Server immedeatly crashes.

---- Minecraft Crash Report ----
// Ooh. Shiny.

Time: 2/23/21 11:59 AM
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:85) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:51) ~[forge:?] {re:classloading}
	at net.minecraft.server.Main.main(Main.java:96) ~[?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_252] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_252] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252] {}
	at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[server.jar:34.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?] {}
	at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63) [server.jar:?] {}
	at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60) [server.jar:?] {}
	at net.minecraftforge.server.ServerMain.main(ServerMain.java:57) [server.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: main
Stacktrace:
	at net.minecraftforge.fml.CrashReportExtender.lambda$dumpModLoadingCrashReport$7(CrashReportExtender.java:88) ~[forge:?] {re:classloading}
-- MOD tntbrbedrock --
Details:
	Mod File: tntbrbedrock_1.16.2-1.2.jar
	Failure message: Mod tntbrbedrock requires collective 1.36 or above
		Currently, collective is not installed
	Mod Version: 1.2
	Mod Issue URL: https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20TNT%20Breaks%20Bedrock
	Exception message: MISSING EXCEPTION MESSAGE
Stacktrace:
	at net.minecraftforge.fml.CrashReportExtender.lambda$dumpModLoadingCrashReport$7(CrashReportExtender.java:88) ~[forge:?] {re:classloading}
	at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:1.8.0_252] {re:computing_frames}
	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:86) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:51) ~[forge:?] {re:classloading}
	at net.minecraft.server.Main.main(Main.java:96) ~[?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_252] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_252] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252] {}
	at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[server.jar:34.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?] {}
	at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63) [server.jar:?] {}
	at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60) [server.jar:?] {}
	at net.minecraftforge.server.ServerMain.main(ServerMain.java:57) [server.jar:?] {}

-- System Details --
Details:
	Minecraft Version: 1.16.3
	Minecraft Version ID: 1.16.3
	Operating System: Linux (amd64) version 4.19.0-14-amd64
	Java Version: 1.8.0_252, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 385233552 bytes (367 MB) / 718798848 bytes (685 MB) up to 4772593664 bytes (4551 MB)
	CPUs: 2
	JVM Flags: 2 total; -Xms128M -Xmx5120M
	ModLauncher: 8.0.6+85+master.325de55
	ModLauncher launch target: fmlserver
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-3.0.3-service.jar eventbus PLUGINSERVICE 
		/server.jar object_holder_definalize PLUGINSERVICE 
		/server.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/server.jar capability_inject_definalize PLUGINSERVICE 
		/server.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/server.jar fml TRANSFORMATIONSERVICE 
	FML: 34.1
	Forge: net.minecraftforge:34.1.42
	FML Language Providers: 
		javafml@34.1
		minecraft@1
	Mod List: 
		forge-1.16.3-34.1.42-server.jar                   |Minecraft                     |minecraft                     |1.16.3              |NONE      |NOSIGNATURE
		useful_backpacks-1.16.3-1.11.6.84.jar             |Useful Backpacks              |usefulbackpacks               |1.11.6.84           |NONE      |f4:a6:0b:ee:cb:8a:1a:ea:9f:9d:45:91:8f:8b:b3:ae:26:f3:bf:05:86:1d:90:9e:f6:32:2a:1a:ed:1d:ce:b0
		QuarkOddities-1.16.3.jar                          |Quark Oddities                |quarkoddities                 |1.16.3              |NONE      |NOSIGNATURE
		EnchantmentDescriptions-1.16.3-5.0.1.jar          |EnchantmentDescriptions       |enchdesc                      |5.0.1               |NONE      |NOSIGNATURE
		theoneprobe-1.16-3.0.7.jar                        |The One Probe                 |theoneprobe                   |1.16-3.0.7          |NONE      |NOSIGNATURE
		MouseTweaks-2.13-mc1.16.2.jar                     |Mouse Tweaks                  |mousetweaks                   |2.13                |NONE      |NOSIGNATURE
		NetherPortalFix_1.16.3-7.2.1.jar                  |NetherPortalFix               |netherportalfix               |7.2.1               |NONE      |NOSIGNATURE
		ImmersiveEngineering-1.16.3-4.1.1-127.jar         |Immersive Engineering         |immersiveengineering          |1.16.3-4.1.1-127    |NONE      |44:39:94:cf:1d:8c:be:3c:7f:a9:ee:f4:1e:63:a5:ac:61:f9:c2:87:d5:5b:d9:d6:8c:b5:3e:96:5d:8e:3f:b7
		practicaltools-1.16.3-1.8.jar                     |Practical Tools               |practicaltools                |1.16.3-1.8          |NONE      |NOSIGNATURE
		jei-1.16.3-7.6.0.51.jar                           |Just Enough Items             |jei                           |7.6.0.50            |NONE      |NOSIGNATURE
		Uppers-0.3.1.jar                                  |Uppers                        |uppers                        |0.3.1               |NONE      |NOSIGNATURE
		curios-forge-1.16.3-4.0.1.0.jar                   |Curios API                    |curios                        |1.16.3-4.0.1.0      |NONE      |NOSIGNATURE
		SpartanShields-1.16.4-2.1.1.jar                   |Spartan Shields               |spartanshields                |2.1.1               |NONE      |NOSIGNATURE
		Quark-r2.4-283.jar                                |Quark                         |quark                         |r2.4-283            |NONE      |NOSIGNATURE
		Neat 1.7-27.jar                                   |Neat                          |neat                          |1.7-27              |NONE      |NOSIGNATURE
		create-mc1.16.3_v0.3e.jar                         |Create                        |create                        |mc1.16.3_v0.3e      |NONE      |NOSIGNATURE
		Xaeros_Minimap_21.1.1_Forge_1.16.5.jar            |Xaero's Minimap               |xaerominimap                  |21.1.1              |NONE      |NOSIGNATURE
		XaerosWorldMap_1.11.10_Forge_1.16.5.jar           |Xaero's World Map             |xaeroworldmap                 |1.11.10             |NONE      |NOSIGNATURE
		light-overlay-5.5.4.jar                           |Light Overlay Forge           |lightoverlay-forge            |NONE                |NONE      |NOSIGNATURE
		Controlling-7.0.0.9.jar                           |Controlling                   |controlling                   |7.0.0.9             |NONE      |NOSIGNATURE
		ReAuth-1.16-Forge-3.9.3.jar                       |ReAuth                        |reauth                        |3.9.3               |NONE      |3d:06:1e:e5:da:e2:ff:ae:04:00:be:45:5b:ff:fd:70:65:00:67:0b:33:87:a6:5f:af:20:3c:b6:a1:35:ca:7e
		comforts-forge-1.16.3-4.0.0.1.jar                 |Comforts                      |comforts                      |1.16.3-4.0.0.1      |NONE      |NOSIGNATURE
		AutoRegLib-1.6-47.jar                             |AutoRegLib                    |autoreglib                    |1.6-47              |NONE      |NOSIGNATURE
		TravelersBackpack-1.16.3-5.2.1.jar                |Traveler's Backpack           |travelersbackpack             |5.2.1               |NONE      |NOSIGNATURE
		StorageDrawers-1.16.3-8.2.2.jar                   |Storage Drawers               |storagedrawers                |8.2.2               |NONE      |NOSIGNATURE
		ftb-gui-library-1603.1.1.19.jar                   |FTB GUI Library               |ftbguilibrary                 |1603.1.1.19         |NONE      |NOSIGNATURE
		Bookshelf-1.16.3-8.7.20.jar                       |Bookshelf                     |bookshelf                     |8.7.20              |NONE      |NOSIGNATURE
		Uncrafted-1.16-4.0.0pre1.jar                      |Uncrafted                     |uncrafted                     |4.0.0pre1           |NONE      |NOSIGNATURE
		Runelic-1.16.3-5.0.1.jar                          |Runelic                       |runelic                       |5.0.1               |NONE      |NOSIGNATURE
		u_team_core-1.16.3-3.1.12.185.jar                 |U Team Core                   |uteamcore                     |3.1.12.185          |NONE      |f4:a6:0b:ee:cb:8a:1a:ea:9f:9d:45:91:8f:8b:b3:ae:26:f3:bf:05:86:1d:90:9e:f6:32:2a:1a:ed:1d:ce:b0
		tntbrbedrock_1.16.2-1.2.jar                       |TNT Breaks Bedrock            |tntbrbedrock                  |1.2                 |NONE      |NOSIGNATURE
		SpartanWeaponry-1.16.4-2.1.0-beta-3.jar           |Spartan Weaponry              |spartanweaponry               |2.1.0 beta 3        |NONE      |NOSIGNATURE
		DarkUtilities-1.16.3-6.0.3.jar                    |Dark Utilities                |darkutils                     |6.0.3               |NONE      |NOSIGNATURE
		AppleSkin-mc1.16.2-forge-1.0.14.jar               |AppleSkin                     |appleskin                     |1.0.14              |NONE      |NOSIGNATURE
		EasyPaxel(1.16.3) - 1.0.9.jar                     |Easy Paxel                    |easypaxelmod                  |1.16.3-1.0.9        |NONE      |NOSIGNATURE
		cloth-config-forge-4.1.3.jar                      |Cloth Config v4 API           |cloth-config                  |4.1.3               |NONE      |NOSIGNATURE
		Ma-Essentials-1.16.3-3.4.0.jar                    |Ma Essentials                 |maessentials                  |1.16.3-3.4.0        |NONE      |NOSIGNATURE
		ImmersivePetroleum-1.16.3-3.1.0.jar               |Immersive Petroleum           |immersivepetroleum            |3.1.0               |NONE      |NOSIGNATURE
		ftb-chunks-1603.2.0.42.jar                        |FTB Chunks                    |ftbchunks                     |1603.2.0.42         |NONE      |NOSIGNATURE
		forge-1.16.3-34.1.42-universal.jar                |Forge                         |forge                         |34.1.42             |NONE      |22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		overloadedarmorbar-5.1.0.jar                      |Overloaded Armor Bar          |overloadedarmorbar            |5.1.0               |NONE      |NOSIGNATURE
		Upgraded Netherite 1.16.4 - 1.7.0.jar             |Upgraded Netherite            |upgradednetherite             |1.7.0               |NONE      |NOSIGNATURE
		ironchest-1.16.4-11.2.10.jar                      |Iron Chests                   |ironchest                     |1.16.4-11.2.10      |NONE      |NOSIGNATURE
		Cyclic-1.16.3-0.8.3.jar                           |Cyclic                        |cyclic                        |1.16.3-0.8.3        |NONE      |1f:47:ac:b1:61:82:96:b8:47:19:16:d2:61:81:11:60:3a:06:4b:61:31:56:7d:44:31:1e:0c:6f:22:5b:4c:ed
		CraftingTweaks_1.16.3-12.2.0.jar                  |Crafting Tweaks               |craftingtweaks                |12.2.0              |NONE      |NOSIGNATURE
		
		*Edit: Wrong Crash Report XD

**Comment by ricksouth** [comment]
Thanks for using the mod. As mentioned in the crash log, the mod requires Collective:

Failure message: Mod tntbrbedrock requires collective 1.36 or above
Currently, collective is not installed

https://www.curseforge.com/minecraft/mc-mods/collective

**Comment by HeroGamer2119** [comment]
Umm, which version would you recommend?
There are only 1.16.5 versions.
nvm, ill just try

**Comment by ricksouth** [comment]
If you're using 1.16.3 you can sort the versions in the All Files part on curseforge. Here's a link to make it easier:

https://www.curseforge.com/minecraft/mc-mods/collective/files/all?filter-game-version=2020709689%3A8056

You can use the latest 1.53 version.

**Comment by HeroGamer2119** [comment]
k thanks
