### ISSUE TITLE
Expanding upon your campfire mods: Spawnpoint Campfires

### ISSUE THREAD

**Issue by Corvus20** [Serilum/.issue-tracker#456]
## **Information**
Mod name: Campfire Spawnpoint. (I would call it home camp but a fabric mod that doesn't plan on porting already took that name.)

## **Feature description**
If you are out adventuring and want to set a sort of checkpoint in case you die (say, outside of a tough dungeon), you can shift right click a campfire to set it as your home camp, a secondary spawn point. When you die, you  will respawn at that campfire, but it will go out. Combining this with a mechanic make campfires start out unlit (Via a mod like campfire overhaul) could be really cool. Even better if you have some text above the hotbar that says "campfire lit" or something like that.

**Comment by ricksouth** [comment]
Apologies for not letting you know, but this mod exists now! :) Thanks for the suggestion.

https://www.curseforge.com/minecraft/mc-mods/campfire-spawn-and-tweaks
