### ISSUE TITLE
Cycle Painting also moves painting

### ISSUE THREAD

**Issue by NielsPilgaard** [Serilum/.issue-tracker#46]
## **Information**
Minecraft version: 1.15.2
Forge version: 31.1.17
Environment: Singleplayer

Mod name: Cycle Paintings
Mod version: 1.0

## **Description**
When cycling a painting by clicking it with another, it moves one block to the right in the process.

## **Crash report**
If available.

**Comment by ricksouth** [comment]
Thanks for the issue. It seems like it is also based on the direction the player is facing. Working on it right now.

**Comment by ricksouth** [comment]
Should be fixed in version 1.1. The Forge/Minecraft painting position code acts quite strange, but I've added some new custom code and tested every direction, position and painting.

**Comment by Yupoman** [comment]
Hi, this keeps happening that moves the paintings, when you change them the painting moves down a block (only paintings of a block wide). I have mods that add new paints, although I don't know if that's the problem. (https://www.curseforge.com/minecraft/mc-mods/dark-paintings/) (https://www.curseforge.com/minecraft/mc-mods/buildersaddition) and cyclepaintings_1.16-1.3
