### ISSUE TITLE
Does

### ISSUE THREAD

**Issue by Kinetic1000** [Serilum/.issue-tracker#460]
## **Information**
(you can remove whatever is not applicable)
Minecraft version: 1.12.2

Mod name: Difficulty Lock
Mod version: 1.1

## **Question**
Does Difficulty Lock work with mods that introduce new difficulties (example https://www.curseforge.com/minecraft/mc-mods/more-difficulty-levels)
oops for the name xD

**Comment by ricksouth** [comment]
Unfortunately it doesn't. If you'd like that, I suggest asking the author of the mod if he can add that feature to his code. Thanks for asking though!
