### ISSUE TITLE
Respawning Shulkers, possible problem with Shulker spawners.

### ISSUE THREAD

**Issue by AbsorbingSafe11** [Serilum/.issue-tracker#462]
## **Information**
In modded Minecraft it is possible to, without just cheating, to obtain a Shulker spawner or for a Shulker spawner to generate via a dungeon mod. (like repurposed structures as an example)

## **Question**

Will this mod resummon dead Shulkers that have been spawned in via a spawner?
If that is the case it would cause possible huge issues with some players games as they could kill all of their spawned Shulkers only to have more spawn and the already dead ones try and respawn.
As a possible fix for this potential problem, if a Shulker would be spawned via a spawner, it would be ineligible for respawn.
(however, I don't know if it is possible for a mod to check if a mob is naturally spawned or if it is spawned via a spawner)

Mod name: Respawning Shulkers
Mod version: all versions (Potentially)

**Comment by ricksouth** [comment]
Thanks for submitting the issue and using the mod! I hadn't thought about that. Version 1.3 adds a config option, enabled by default, which prevents shulkers that originate from spawners from respawning.

https://www.curseforge.com/minecraft/mc-mods/respawning-shulkers
