### ISSUE TITLE
Compatibility with Campful

### ISSUE THREAD

**Issue by SHXRKIEgg** [Serilum/.issue-tracker#463]
## **Information**
Mod name: Healing Campfire

## **Feature description**
Is it possible you can make all the additional campfires from Campful mod: https://www.curseforge.com/minecraft/mc-mods/campful Compatible with Healing Campfire?

Thanks

**Comment by ricksouth** [comment]
Support for modded campfires has been added in the latest version. Thanks for the suggestion and giving the mod a try!

https://www.curseforge.com/minecraft/mc-mods/healing-campfire/files
