### ISSUE TITLE
Not able to takeoff with dyed/bannered elytra in the back curio slot

### ISSUE THREAD

**Issue by i-am-bad-at-names** [Serilum/.issue-tracker#464]
## **Information**
Minecraft version: 1.16.5
Forge version: 36.0.26
Environment: Singleplayer(multiplayer not tested)

Mod name: [Easy Elytra Takeoff](https://www.curseforge.com/minecraft/mc-mods/easy-elytra-takeoff), [Customisable Elytra](https://www.curseforge.com/minecraft/mc-mods/customizable-elytra), [Curious Elytra](https://www.curseforge.com/minecraft/mc-mods/curious-elytra)
Mod version: 1.6

Description
When using an Elytra dyed/with a banner and inside the curio slot, I am unable to takeoff using [Easy Elytra Takeoff](https://www.curseforge.com/minecraft/mc-mods/easy-elytra-takeoff). It works using a regular elytra in the curio slot, a regular elytra in the chestplate slot, a modified elytra in the chestplate slot but not with a modified elytra in the back slot

**Comment by ricksouth** [comment]
Thanks for using the mod! I think this is a problem with Curious Elytra. I'm checking if the player has certain attributes to make the normal elytra compatible; if the attribute "flight modifier" or "elytra curio modifier" exists. It seems that a dyed elytra does not give this attribute to the player.

Please open an issue here: https://github.com/TheIllusiveC4/CuriousElytra/issues and reference this post. It might be something on my end but I don't think so.

**Comment by i-am-bad-at-names** [comment]
As I was filing a report on their github I noticed I was using an outdated version of their mod, using the latest version fixed the issue. My bad

**Comment by ricksouth** [comment]
Alright! No problem. Thanks for using the mod.
