### ISSUE TITLE
Passive Shield Mod Not Rendering Shield

### ISSUE THREAD

**Issue by Gabe8273** [Serilum/.issue-tracker#465]
Minecraft version: 1.16.5
Forge version: 36.0.43
Environment: Singleplayer

Mod name: Passive Shield
Mod version: 1.1

My shield won't render in first-person when I raise it. Is there a way to fix this?

https://user-images.githubusercontent.com/79672099/109233424-7ad8f680-778f-11eb-88a5-5427dae30176.mp4

**Comment by ricksouth** [comment]
Thanks for submitting the bug report and giving the mod a try. Could you send me your mod list? And did anything happen before it didn't render anymore? Did it work when you first loaded the mod?

**Comment by ricksouth** [comment]
I believe I've fixed it in version 1.2 of the mod. But please let me know if it's not the case.

https://www.curseforge.com/minecraft/mc-mods/passive-shield
