### ISSUE TITLE
Add config for explosion strength

### ISSUE THREAD

**Issue by ricksouth** [Serilum/.issue-tracker#467]
## **Information**
Mod name: TNT Breaks Bedrock

## **Feature description**
GhosToast: was wondering if it were possible to add a config or setting to the mod "TNT Breaks Bedrock" in which it would be possible to adjust the amount of bedrock broken by TNT, as I find it too overpowered the way it currently is.

Also I kinda want a precise hole in the roof and not a huge crater.

**Comment by James103** [comment]
An alternative could be as follows:
* Blowing up TNT near bedrock cracks the bedrock, as shown using vanilla block mining progress overlays.
* While the bedrock is cracked, it can be mined (hardness is that of obsidian if you use a netherite pickaxe to mine it).
* After a few minutes, any remaining cracked bedrock heals, reverting back into regular bedrock.

This allows you to define exactly which bedrock blocks to break and in what shape, even shapes not normally possible using just TNT and lowering the blast resistance of bedrock.

---

Another alternative if setting mining progress of arbitrary blocks is not feasible:
* When blowing up TNT, if the TNT is sitting on top of bedrock, that piece of bedrock gets broken and nothing else.
* Else, if the TNT is set on the block right below a bedrock block, that bedrock block gets broken and nothing else.
* Else, normal block damage occurs.

In all cases, (living) entity damage is not affected.

**Comment by ricksouth** [comment]
I appreciate the feature suggestion! In order to reduce the amount of open issues on this Github repository, I've created a separate Github project page for all mod feature requests. It can be found here:
https://serilum.com/mods/requests.

I'll be closing this issue, but I'm keeping track of all ideas on the project page over there.

It definitely does not mean I am not interested, and I will post a comment here as well if/when a feature is implemented.

Thank you very much for the suggestion!

**Comment by ricksouth** [comment]
Hey!

I still appreciate the submission a lot, and wanted to give an update on this. While I'd love to add all features submitted on the issue-tracker, due to having limited time, I've just not been able to. In order to see which features users would like to see most, I've updated https://serilum.com/mods/requests. The page now shows a table, with all feature request submitted.

Users are able to upvote requests by reacting to the first issue post here on GitHub with one of the 👍 😀 🎉 ❤️ 🚀 👀 emoji's. The request with the most unique reactions, will be shown at the top.

This doesn't necessary mean I'll only work on popular features in the upcoming years, but it does help with prioritizing.

Thank you again for the suggestion!
