### ISSUE TITLE
Configurable Despawn Timer

### ISSUE THREAD

**Issue by EnterFor** [Serilum/.issue-tracker#47]
## **Information**
Mod name: Configurable Despawn Timer 1.15

## **Feature description**
I've been shopping around for a long time and finally found a cleanup module that supports 1.15Forge!
But this Mod only cleans items, can you add cleaning Mob?
At last! I love this Mod！！！

**Comment by EnterFor** [comment]
I'm sorry, I don't know how to add labels
My English is very poor. I'm Chinese

**Comment by ricksouth** [comment]
Do you mean a mod that makes mobs despawn after some time around the player?

**Comment by EnterFor** [comment]
> 您的意思是让玩家在玩家周围一段时间后会消失的MOD吗？

I mean, can you add the ability to clean up entities

**Comment by EnterFor** [comment]
> Do you mean a mod that makes mobs despawn after some time around the player?

sorry，It seems to mean the same thing.

**Comment by EnterFor** [comment]
I'd like to know, is my suggestion in the plan?
I have been paying attention to this project. I can make a donation to you

**Comment by ricksouth** [comment]
Could you give a little bit more information of what you want in the mod? You can write it in Chinese and I'll use google translate. Just give me as much information as possible :)

**Comment by EnterFor** [comment]
类似spigot服务器一样，可以安装清理插件，用来减少服务器滞后。
比如清理怪物，当怪物达到一定数量就会执行清理。
或者说隔一段时间，清理怪物

Like the spigot server, the cleanup plug-in can be installed to reduce server latency.
For example, when monsters reach a certain number, they will be cleaned up.
Or every once in a while, clean up monsters

**Comment by EnterFor** [comment]
https://www.curseforge.com/minecraft/mc-mods/streetsweeper
https://github.com/BrassGoggledCoders/StreetSweeper

I found the Mod that explains what I said,
But it doesn't support 1.15
I hope I can help you

**Comment by ricksouth** [comment]
I've put the idea on the list, and will keep it in mind. I have to prioritise other things right now, but thanks for the idea nonetheless!
