### ISSUE TITLE
Freeze at 100% Worldgen

### ISSUE THREAD

**Issue by agentwolf88** [Serilum/.issue-tracker#470]
## **Information**
Minecraft version: 1.16.5
Forge version: 36.0.43
Environment: Singleplayer

Mod name: Realistic Bees
Mod version: 1.1

BUG: Worldgen freeze at 100%

## **Description**
Hey! This happened..

## **Crash report**
https://paste.ee/p/DEMOc

**Comment by James103** [comment]
Gmail said "message clipped" and an online character counter said that your above comment was over 116 KB. Can you please create a Gist or Pastebin with the logs and crash report, link to the Gist or Pastebin you created, and delete the logs and crash report from the comment?

**Comment by agentwolf88** [comment]
Its not realy a crash, just a freeze without a crashlog. Here is a debug log.

https://paste.ee/p/DEMOc

**Comment by James103** [comment]
Converted paste to text file as the paste is about to expire:
[DEMOc.txt](https://github.com/ricksouth/serilum-mc-mods/files/6217136/DEMOc.txt)

**Comment by ricksouth** [comment]
Thanks for submitting the bug report! Fixed in version 1.5 of Realistic Bees.

https://www.curseforge.com/minecraft/mc-mods/realistic-bees/files/all
