### ISSUE TITLE
Suggestion: option to limit Tree Harvester to specific axes

### ISSUE THREAD

**Issue by TheOldOne822** [Serilum/.issue-tracker#472]
## **Information**
Mod name: Tree Harvester 

## **Feature description**
It would be nice if there was an option to have only some axes work for cutting down the whole tree. Either via a whitelist or blacklist
Example would be having wooden axe not being covered by the mod or someone could make only gold axe work to give gold a use.

**Comment by smmmadden** [comment]
I agree with this as well.  I use another mod that reserves the wooden axe and want to use a gold or netherite axe to to work.  If this is added already, can you tell me where I can change it as the default config file doesn't list it (1.18.1 - 4.2).  Thanks!

**Comment by ricksouth** [comment]
Thanks for the suggestion! This has been added in version 5.0 of Tree Harvester. On first load a blacklist is created located at **./config/treeharvester/harvestable_axe_blacklist.txt**. Here you can add an exclamation mark to whatever axe you don't want to be able to harvest trees. It works for modded axes.

https://www.curseforge.com/minecraft/mc-mods/tree-harvester/files
