### ISSUE TITLE
loadinventory broken

### ISSUE THREAD

**Issue by MRqaza2006** [Serilum/.issue-tracker#474]
## **Information**
Minecraft version: 1.16.5
Forge version: 1.16.5 (36.0.43)
Environment: Multiplayer

Mod name: saveandloadinventories_1.16.5-1.3.jar
Mod version: 1.3

## **Description**
Hey! if i try to load my saved inventorys it cant find them but it says in the list that they exist

.

## **Crash report**
If available.

**Comment by ricksouth** [comment]
Can you post the files located in /config/loadandsaveinventories/ in your minecraft folder?

**Comment by James103** [comment]
Which Minecraft version, Forge version, and "Save and Load Inventories" version are you using?

**Comment by MRqaza2006** [comment]
![16145363492629163175550396039554](https://user-images.githubusercontent.com/79805581/109429002-e920f180-79f9-11eb-9c78-2133ebac8b44.jpg)
I'm using it on a server so it looks a little weird.

**Comment by James103** [comment]
Do you have the actual text to paste in (or a file to download off the server and upload here? If so, can you do that please?

**Comment by MRqaza2006** [comment]
here it is

'offhand' : '{id:"minecraft:firework_rocket",Count:64b}',
'head' : '{id:"minecraft:iron_helmet",Count:1b,tag:{RepairCost:0,Damage:0,Enchantments:[{lvl:1s,id:"minecraft:blast_protection"},{lvl:1s,id:"minecraft:aqua_affinity"},{lvl:1s,id:"minecraft:thorns"}],display:{Name:'{"text":"mod helmet"}'}}}',
'chest' : '{id:"minecraft:elytra",Count:1b,tag:{RepairCost:0,Damage:0,Enchantments:[{lvl:1s,id:"minecraft:mending"}],display:{Name:'{"text":"mod elytra"}'}}}',
'legs' : '{id:"minecraft:iron_leggings",Count:1b,tag:{RepairCost:0,Damage:0,Enchantments:[{lvl:1s,id:"minecraft:blast_protection"},{lvl:2s,id:"minecraft:thorns"}],display:{Name:'{"text":"mod leggings"}'}}}',
'feet' : '{id:"minecraft:iron_boots",Count:1b,tag:{RepairCost:0,Damage:0,Enchantments:[{lvl:1s,id:"minecraft:blast_protection"},{lvl:2s,id:"minecraft:thorns"},{lvl:1s,id:"minecraft:feather_falling"}],display:{Name:'{"text":"mod boots"}'}}}',
0 : '{id:"minecraft:diamond_axe",Count:1b,tag:{RepairCost:0,Damage:0,Enchantments:[{lvl:4s,id:"minecraft:efficiency"},{lvl:2s,id:"minecraft:unbreaking"}],display:{Name:'{"text":"mod axe"}'}}}',
1 : '{id:"minecraft:diamond_sword",Count:1b,tag:{RepairCost:0,Damage:0,Enchantments:[{lvl:1s,id:"minecraft:fire_aspect"},{lvl:5s,id:"minecraft:sharpness"},{lvl:1s,id:"minecraft:knockback"}],display:{Name:'{"text":"mod sword"}'}}}',
2 : '{id:"minecraft:diamond_pickaxe",Count:1b,tag:{RepairCost:0,Damage:0,Enchantments:[{lvl:4s,id:"minecraft:efficiency"},{lvl:2s,id:"minecraft:unbreaking"},{lvl:3s,id:"minecraft:fortune"}],display:{Name:'{"text":"mod pickaxe"}'}}}',
3 : '',
4 : '',
5 : '{id:"minecraft:firework_rocket",Count:64b}',
6 : '{id:"minecraft:firework_rocket",Count:64b}',
7 : '{id:"minecraft:torch",Count:64b}',
8 : '{id:"minecraft:cooked_beef",Count:64b}',
9 : '{id:"minecraft:iron_chestplate",Count:1b,tag:{RepairCost:0,Damage:0,Enchantments:[{lvl:1s,id:"minecraft:blast_protection"},{lvl:1s,id:"minecraft:thorns"}],display:{Name:'{"text":"mod chestplate"}'}}}',
10 : '{id:"minecraft:diamond_hoe",Count:1b,tag:{RepairCost:0,Damage:0,Enchantments:[{lvl:1s,id:"minecraft:efficiency"}],display:{Name:'{"text":"dumbass hoe"}'}}}',
11 : '{id:"minecraft:diamond_shovel",Count:1b,tag:{RepairCost:0,Damage:0,Enchantments:[{lvl:1s,id:"minecraft:efficiency"}],display:{Name:'{"text":"mod shouvel"}'}}}',
12 : '',
13 : '',
14 : '',
15 : '',
16 : '',
17 : '',
18 : '',
19 : '',
20 : '',
21 : '',
22 : '',
23 : '',
24 : '',
25 : '',
26 : '',
27 : '',
28 : '',
29 : '',
30 : '',
31 : '',
32 : '',
33 : '',
34 : '',
35 : '',

**Comment by ricksouth** [comment]
![2021-02-28_21 05 05](https://user-images.githubusercontent.com/38502394/109431815-a7e40e00-7a08-11eb-87cf-deedac1ef181.png)

Thanks for sending me the text data. I've managed to fix the mod, will upload the new version in a bit.

**Comment by MRqaza2006** [comment]
thank you for fixing

**Comment by ricksouth** [comment]
Fixed in version 2.3 of Collective and version 1.4 of Save and Load Inventories.

https://www.curseforge.com/minecraft/mc-mods/collective
https://www.curseforge.com/minecraft/mc-mods/save-and-load-inventories
