### ISSUE TITLE
Spread always as default regardless of configuration

### ISSUE THREAD

**Issue by SgtSteakfries** [Serilum/.issue-tracker#476]
## **Information**
Minecraft version: 1.15.2
Forge version: 31.2.44
Environment: Singleplayer

Mod name: Nether Portal Spread
Mod version: 15.2-4.6

## **Description**
I was trying to alter the config files to the max spread range (that being 1000), but no matter how I try to change it, the results are always the default. I'm not sure how to fix it.

**Comment by ricksouth** [comment]
The maximum spread range is set to 100 blocks. Is it possible that you entered 1000 which the mod didn't accept?

**Comment by SgtSteakfries** [comment]
I couldn't recall, though I tweaked it to the max possible.

I'm using minecraft 15.2 if that helps.

**Comment by ricksouth** [comment]
Spread starts from the portal and goes out every so often, after the set delay. How did you test it not spreading to 1000/100 blocks?

**Comment by SgtSteakfries** [comment]
Well, I tried lowering the spread tick rate to just above the minimum (25 ticks - minimum of 20), then it crashed and gave back a 'divide by zero' report.

**Comment by James103** [comment]
Can you please post the full crash log here?

**Comment by SgtSteakfries** [comment]
Yeah sure, I need to find where it got printed first.

**Comment by SgtSteakfries** [comment]
---- Minecraft Crash Report ----
// My bad.

Time: 3/1/21 12:54 PM
Description: Exception in server tick loop

java.lang.ArithmeticException: / by zero
	at com.natamus.netherportalspread.events.SpreadEvent.onWorldTick(SpreadEvent.java:49) ~[?:_1.15.2-1.0] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_333_SpreadEvent_onWorldTick_WorldTickEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPostWorldTick(BasicEventHooks.java:99) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:855) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:114) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:637) [?:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 417320664 bytes (397 MB) / 3715104768 bytes (3543 MB) up to 8649703424 bytes (8249 MB)
	CPUs: 8
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx9280m -Xms256m -XX:PermSize=256m
	ModLauncher: 5.1.2+70+master.2845bb9
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.1.jar mixin PLUGINSERVICE 
		/eventbus-2.2.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.2.44.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.44.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.1.3-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.2.44.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.44.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.1.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.15.2-31.2.44.jar fml TRANSFORMATIONSERVICE 
	FML: 31.2
	Forge: net.minecraftforge:31.2.44
	FML Language Providers: 
		javafml@31.2
		minecraft@1
	Mod List: 
		forge-1.15.2-31.2.44-client.jar Minecraft {minecraft@1.15.2 DONE}
		tetra-1.15.2-2.18.1.jar Tetra {tetra@1.15.2-2.18.1 DONE}
		SaveMyStronghold-1.15.2-1.0.1.jar Save My Stronghold! {savemystronghold@1.15.2-1.0.1 DONE}
		swingthroughgrass-1.15.2-1.4.1.jar SwingThroughGrass {swingthroughgrass@1.15.2-1.4.1 DONE}
		SoundControl-1.15.2-1.0.0.2.jar §3Dynamic Surroundings: §eSound Control {sndctrl@1.15.2-1.0.0.1 DONE}
		Environs-1.15.2-1.0.0.0.jar §3Dynamic Surroundings: §eEnvirons {environs@1.15.2-1.0.0.0 DONE}
		MouseTweaks-2.13-mc1.15.1.jar Mouse Tweaks {mousetweaks@2.13 DONE}
		netherportalspread_1.15.2-4.6.jar Nether Portal Spread {netherportalspread@4.6 DONE}
		SilentLib-1.15.2-4.6.6+59.jar Silent Lib {silentlib@4.6.6+59 DONE}
		BiomesOPlenty-1.15.2-10.0.0.366-universal.jar Biomes O' Plenty {biomesoplenty@1.15.2-10.0.0.366 DONE}
		Blur-1.1.0-1.jar Blur {blur@1.1.0-1 DONE}
		ElenaiDodge-1.15.2-1.7.2.jar Elenai Dodge {elenaidodge@1.15.2-1.7.2 DONE}
		SaveYourPets-1.15.1-1.0.0.3.jar Save Your Pets {syp@1.0.0.3 DONE}
		CreativeCore_v2.0.5_mc1.15.2.jar CreativeCore {creativecore@2.0.0 DONE}
		enchantable-1.3.0-1.15.2.jar Enchantable {enchantable@1.3.0 DONE}
		AttributeFix-1.15.2-7.0.2.jar AttributeFix {attributefix@7.0.2 DONE}
		incontrol-1.15-4.0.4.jar InControl {incontrol@1.15-4.0.4 DONE}
		ChickenChunks-1.15.2-2.5.1.79-universal.jar ChickenChunks {chickenchunks@1.15.2-2.5.1.79 DONE}
		ContentTweaker-1.15-1.0.0.develop.20.jar ContentTweaker {contenttweaker@1.0.0.develop.20 DONE}
		Patchouli-1.15.2-1.2-35.jar Patchouli {patchouli@1.15.2-1.2-35 DONE}
		Neat 1.6-22.jar Neat {neat@1.6-22 DONE}
		BetterCaves-1.15.2-1.0.jar YUNG's Better Caves {bettercaves@1.15.2-1.0 DONE}
		Xaeros_Minimap_21.4.0_Forge_1.15.2.jar Xaero's Minimap {xaerominimap@21.4.0 DONE}
		collective-1.15.2-2.8.jar Collective {collective@2.8 DONE}
		mgui-1.15.2-2.1.1.jar mgui {mgui@2.1.1 DONE}
		FastWorkbench-1.15.2-3.1.0.jar FastWorkbench {fastbench@3.1.0 DONE}
		EnhancedVisuals_v1.3.15_mc1.15.2.jar EnhancedVisuals {enhancedvisuals@1.3.0 DONE}
		Placebo-1.15.2-3.1.0.jar Placebo {placebo@3.1.0 DONE}
		SpawnInVillage-1.15.2-1.2.jar Spawn in Village {spawnvillage@1.2 DONE}
		HardcoreRevival_1.15.2-4.0.2.jar Hardcore Revival {hardcorerevival@4.0.2 DONE}
		Creeper_AI_Updated-1.2_1.15.jar Creeper AI Updated {creeperaiupdated@1.2 DONE}
		theloader-1.15.2-1.1.0.jar The Loader {theloader@1.15.2-1.1.0 DONE}
		guardvillagers-1.15.2-1.0.8.jar Guard Villagers {guardvillagers@1.0.7 DONE}
		BetterHurtTimer-1.15.2-2.4.0.0.jar Better Hurt Timer {betterhurttimer@1.15.2-2.4.0.0 DONE}
		AppleSkin-mc1.15.2-forge-1.0.14.jar AppleSkin {appleskin@1.0.14 DONE}
		AI-Improvements-1.15.2-0.3.0.jar AI-Improvements {aiimprovements@0.3.0 DONE}
		JEITweaker-1.15.2-1.0.1.3.jar JEI Tweaker {jeitweaker@1.0.1.3 DONE}
		DamageTilt-1.15-forge-0.1.1.jar DamageTilt {damagetilt@0.1.1 DONE}
		dynamic_world-1.15.2-0.3.2.0.jar Dynamic World {dynamic_world@0.3.0.0 DONE}
		CraftTweaker-1.15.2-6.0.0.45.jar CraftTweaker {crafttweaker@6.0.0.45 DONE}
		BetterBurning-1.15.2-1.3.4.jar BetterBurning {betterburning@1.3.4 DONE}
		forge-1.15.2-31.2.44-universal.jar Forge {forge@31.2.44 DONE}
		castle_dungeons-1.3-1.15.2.jar Castle Dungeons {castle_dungeons@1.3 DONE}
		ScalingHealth-1.15.2-3.0.9+54.jar Scaling Health {scalinghealth@3.0.9+54 DONE}
		FastLeafDecay-v22.1.jar FastLeafDecay {fastleafdecay@v22.1 DONE}
		CodeChickenLib-1.15.2-3.3.5.407-universal.jar CodeChicken Lib {codechickenlib@3.3.5.407 DONE}
		BetterMineshaftsForge-1.15.2-1.3.1.jar YUNG's Better Mineshafts {bettermineshafts@1.15.2-1.3.1 DONE}
		portablelightsources-1.15.2-1.0.2.jar Portable Light Sources {portablelightsources@1.15.2-1.0.2 DONE}
	Patchouli open book context: n/a
	Player Count: 0 / 8; []
	Data Packs: mod:netherportalspread, mod:collective (incompatible), vanilla, mod:tetra, mod:savemystronghold (incompatible), mod:swingthroughgrass (incompatible), mod:sndctrl (incompatible), mod:environs (incompatible), mod:mousetweaks (incompatible), mod:silentlib (incompatible), mod:biomesoplenty, mod:blur (incompatible), mod:elenaidodge, mod:syp, mod:creativecore (incompatible), mod:enchantable (incompatible), mod:attributefix (incompatible), mod:incontrol (incompatible), mod:chickenchunks (incompatible), mod:contenttweaker (incompatible), mod:patchouli (incompatible), mod:neat (incompatible), mod:bettercaves (incompatible), mod:xaerominimap, mod:mgui (incompatible), mod:fastbench (incompatible), mod:enhancedvisuals (incompatible), mod:placebo (incompatible), mod:spawnvillage, mod:hardcorerevival (incompatible), mod:creeperaiupdated, mod:theloader (incompatible), mod:guardvillagers (incompatible), mod:betterhurttimer (incompatible), mod:appleskin (incompatible), mod:aiimprovements (incompatible), mod:jeitweaker, mod:damagetilt (incompatible), mod:dynamic_world, mod:crafttweaker (incompatible), mod:betterburning (incompatible), mod:forge (incompatible), mod:castle_dungeons, mod:scalinghealth, mod:fastleafdecay, mod:codechickenlib (incompatible), mod:bettermineshafts (incompatible), mod:portablelightsources, the_loader/contenttweaker
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'

**Comment by James103** [comment]
Are you able to reproduce the crash with just Collective and Nether Portal Spread enabled?

**Comment by SgtSteakfries** [comment]
Yup, here's the Log

---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 3/3/21 12:37 PM
Description: Exception in server tick loop

java.lang.ArithmeticException: / by zero
	at com.natamus.netherportalspread.events.SpreadEvent.onWorldTick(SpreadEvent.java:49) ~[?:_1.15.2-1.0] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_15_SpreadEvent_onWorldTick_WorldTickEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPostWorldTick(BasicEventHooks.java:99) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:855) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:114) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:637) [?:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2687413176 bytes (2562 MB) / 3555721216 bytes (3391 MB) up to 8649703424 bytes (8249 MB)
	CPUs: 8
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx9280m -Xms256m -XX:PermSize=256m
	ModLauncher: 5.1.2+70+master.2845bb9
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.1.jar mixin PLUGINSERVICE 
		/eventbus-2.2.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.2.44.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.44.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.1.3-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.2.44.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.44.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.1.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.15.2-31.2.44.jar fml TRANSFORMATIONSERVICE 
	FML: 31.2
	Forge: net.minecraftforge:31.2.44
	FML Language Providers: 
		javafml@31.2
		minecraft@1
	Mod List: 
		forge-1.15.2-31.2.44-client.jar Minecraft {minecraft@1.15.2 DONE}
		forge-1.15.2-31.2.44-universal.jar Forge {forge@31.2.44 DONE}
		netherportalspread_1.15.2-4.6.jar Nether Portal Spread {netherportalspread@4.6 DONE}
		collective-1.15.2-2.9.jar Collective {collective@2.9 DONE}
	Player Count: 0 / 8; []
	Data Packs: vanilla, mod:forge (incompatible), mod:netherportalspread, mod:collective (incompatible)
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'

----

I've also tweaked only this config file here.


[General]
	#The message sent on preventspread blocks found.
	messageOnPreventSpreadBlocksFound = "With enough %preventSpreadBlockString% placed, you feel the corrupted energy fade."
	#The amount of blocks that are instantly converted to a nether block around a portal when it is detected. If there are existing nether blocks within the radius, their count is substracted from this number.
	#Range: 0 ~ 1000
	instantConvertAmount = 50
	#When enabled, sends a message to players around the portal when it is broken.
	sendMessageOnPortalBroken = true
	#The amount of prevent-spread-blocks (defined) needed within the radius of the nether portal to prevent spread.
	preventSpreadBlockAmountNeeded = 4
	#When enabled, blocks the spread effect when there are n (defined) prevent-spread-blocks (defined) within the radius.
	preventSpreadWithBlock = true
	#The radius around the portal to which the nether blocks can spread.
	#Range: 1 ~ 100
	portalSpreadRadius = 100
	#The delay in ms in between the spread around the nether portal.
	#Range: 20 ~ 360000
	spreadDelay = 25
	#When enabled, shows the portal coordinates in portal messages.
	prefixPortalCoordsInMessage = true
	#The block which prevents the nether portal from spreading. By default a coal block (minecraft:coal_block is the namespace ID).
	preventSpreadBlockString = "minecraft:coal_block"
	#The message sent on portal creation.
	messageOnPortalCreation = "You feel a corrupted energy coming from the portal. The nether will slowly spread into the overworld unless %preventSpreadBlockAmountNeeded% %preventSpreadBlockString% are placed within a %portalSpreadRadius% block radius around the portal."
	#When enabled, sends a message to players around the portal that the nether spread has stopped when the portal detects new 'preventSpreadBlockString' blocks.
	sendMessageOnPreventSpreadBlocksFound = true
	#The message sent when a portal is broken.
	messageOnPortalBroken = "With the nether portal broken, the corrupted energy is no longer able to enter the overworld."
	#When enabled, sends a message to players around the portal that the nether is spreading and that you can stop the spread with 'preventSpreadBlockAmountNeeded' of the 'preventSpreadBlockString' block.
	sendMessageOnPortalCreation = true

**Comment by SgtSteakfries** [comment]
I even changed the tick rate back to 2500 and still crashes by zero. It's like it completely breaks down upon modification.

**Comment by ricksouth** [comment]
Thanks for opening the issue and using the mod! This has been fixed in version 5.0 of the mod. The config value has been changed to spreadDelayTicks and works with it set to 1.

https://www.curseforge.com/minecraft/mc-mods/nether-portal-spread
