### ISSUE TITLE
Bug: Campfires burn mobs despite being unlit.

### ISSUE THREAD

**Issue by Akitori** [Serilum/.issue-tracker#478]
## **Information**
Minecraft version: 1.16.5
Forge version: 36.0.43
Environment: Singleplayer

Mod name: No Hostiles Around Campfire
Mod version: 3.2

## **Description**
I have a mod that makes campfires place unlit. When i place unlit campfires, it still sets mobs on fire for a while. Maybe its the interaction, but I wouldn't want mobs burning if the campfire's off. That's all, thanks!

**Comment by ricksouth** [comment]
Thanks for submitting the issue and using the mod! This has been fixed in version 3.3 of the mod.

https://curseforge.com/minecraft/mc-mods/no-hostiles-around-campfire
