### ISSUE TITLE
Possibility for one, single huge mod containing all the mods?

### ISSUE THREAD

**Issue by ghost** [Serilum/.issue-tracker#48]
Minecraft version: 1.12.2
Environment: Singleplayer & Multiplayer

Firstly, I love all of the mods you've put out, and sorry if this has been asked before. I just wanted to know if there's potential of having them all, or at least most of them, combined into one large mod, with configurable features similar to quark?  This would make it so much more convenient for larger packs. I know this may sound like asking for a lot but just curious if it's at all a possibility or something to consider!

**Comment by ricksouth** [comment]
Hi!

Thanks for the input and interest in my mods! I have thought about this before, and am not saying no but it does require some extra thoughts on how to do it. I don't want to rush a release. When I create a mod that includes everything, it will require me to do double work when updating and creating new things. It's in the back of my mind!

**Comment by Thedeur** [comment]
Seconded. I feel like _most_ of these mods are pretty good, but there will always be a few that aren't quite to my fancy, and a configurable downloadable .zip file/mod itself would be fantastic-- similar to something like Quark's download page. As opposed to downloading them one by one.

**Comment by ricksouth** [comment]
I'm keeping it in mind!
