### ISSUE TITLE
Crashed after entering nether and placing a campfire

### ISSUE THREAD

**Issue by Krulza** [Serilum/.issue-tracker#480]
[crash-2021-03-02_18.02.21-server.txt](https://github.com/ricksouth/serilum-mc-mods/files/6072335/crash-2021-03-02_18.02.21-server.txt)

Not able to load back into the save either.

**Comment by Krulza** [comment]
This is from The Vanilla Experience

**Comment by ricksouth** [comment]
This has been fixed in version 1.1 of Random Village Names which is included in version 2.39 of The Vanilla Experience. Thanks for submitting the bug!

https://www.curseforge.com/minecraft/mc-mods/random-village-names
https://www.curseforge.com/minecraft/modpacks/the-vanilla-experience
