### ISSUE TITLE
Mob Drop editor Problem

### ISSUE THREAD

**Issue by Gork12** [Serilum/.issue-tracker#481]
Minecraft version: 1.16.5
Forge version: 1.16.5
Environment: Singleplayer
Mod name: Configurable Extra Mob Drops
Mod version: 1.16.5

So when using I added a drop to the zombie just to test it and it worked but when I went to do /cemd cleardrops zombie it would say successfully clear drops for zombie horse instead of zombie and so I tried /cemd cleardrops zombie_horse and it did the same thing so I cant clear the extra drops for zombie.

**Comment by James103** [comment]
Have you tried running `/cemd cleardrops piglin`? If the output is something like "Successfully cleared drops for piglin_brute", then there's probably some automatic tab-completion going on, where it chooses the most specific name that matches the input (`minecraft:zombie_horse` for input `zombie`), instead of the exact name found if any (such as `minecraft:zombie` for input `zombie`).

**Comment by Gork12** [comment]
ok ill try that

**Comment by Gork12** [comment]
> Have you tried running `/cemd cleardrops piglin`? If the output is something like "Successfully cleared drops for piglin_brute", then there's probably some automatic tab-completion going on, where it chooses the most specific name that matches the input (`minecraft:zombie_horse` for input `zombie`), instead of the exact name found if any (such as `minecraft:zombie` for input `zombie`).

It doesnt let me put minecraft:zombie it has to be like zombie or zombie_horse and I did some testing piglin and brute dont do this nether does skeleton and skeleton horse it seems to be a problem with just the zombie and with what you said on auto fill it doesnt fill in it makes you type everything out like if you mean where you do like zom and above it shows in yellow zombie or zombie_horse cause it doesnt do that

**Comment by ricksouth** [comment]
Thanks for submitting the issue and using the mod! This has been fixed in version 1.4 of the mod.

https://www.curseforge.com/minecraft/mc-mods/configurable-extra-mob-drop
