### ISSUE TITLE
Modded Compat

### ISSUE THREAD

**Issue by The-Brandolorian** [Serilum/.issue-tracker#483]
## **Information**
Mod name: Campfirespawnandtweaks

## **Feature description**
Would you be able to add compat with the fire starter from Charcoal Pit? Or possibly inform me how to do myself. Cheers 
- https://www.curseforge.com/minecraft/mc-mods/charcoal-pit

**Comment by ricksouth** [comment]
Thanks for the request! I think they'd work really well together. I'm currently checking for (block instanceof CampfireBlock). You could extend your fire with that, but it would mean that it should contain CampfireBlock.Lit (and CampfireBlock.waterlogged).

Otherwise you could send me your campfire code in private so I can take a look.

**Comment by The-Brandolorian** [comment]
Sorry for the confusion! I am not the creator of said mod.
I just wasn't sure if it could be done through data packs via tags or something, but i shall create a thread on their page and link them to here :)

**Comment by EnderiumSmith** [comment]
Does this do anything special with the relight or would just copying the flint and steel code work?

**Comment by ricksouth** [comment]
Hmm the mod does some special checks, but all based on the format of the Campfire block. I can also add some extra checks in the mod itself whether the boolean properties for Lit and waterlogged exist.

Is it possible for your campfire class to extend CampfireBlock? Or would that cause problems?

**Comment by EnderiumSmith** [comment]
i dont add any custom campfires. i add custom flint and steel

**Comment by ricksouth** [comment]
Keep in mind I haven't used your mod. I'm following a request.

You can extend FlintAndSteelItem with your custom flint & steel. Is that possible?

**Comment by The-Brandolorian** [comment]
Compat has been included.
