### ISSUE TITLE
Making head drop chance more rare by config

### ISSUE THREAD

**Issue by FurryApocalypse** [Serilum/.issue-tracker#484]
## **Information**
(you can remove whatever is not applicable)
Minecraft version: 1.16.5
Forge version: 36.0.40+
Environment: Singleplayer / Multiplayer

Mod name: Just mobs heads
Mod version: new update if upcoming

## **Question**
Hi there. My question is if you have any posibility to make config that would work like 0.01 drop chance?
Im asking couse 0.1 is like equal to 10% drop chance of mobs head and i would like to do it like 0.01 - just to sightly reduce drop chance with config. (Just not sure if i can make 1% drop chance with current config)
When i tried to 0.01 it just crashed on server so thats why im asking. ^^"

**Comment by ricksouth** [comment]
Can you provide me with the crash log from your server? It's located in the 'crash-reports' folder

**Comment by FurryApocalypse** [comment]
Okay i looked at the crash report and turned out it was some problem with forge 36.0.40.
I had reinstalled it and it is now working properly.
Thank you and sorry for making problems!

**Comment by ricksouth** [comment]
No problem! Glad it's working. Thanks for giving the mod a try.
