### ISSUE TITLE
guicompass giving incorrect direction

### ISSUE THREAD

**Issue by dromedar17** [Serilum/.issue-tracker#487]
## **Information**
Minecraft version: 1.16.5
Forge version: 36.0.46
Environment: Singleplayer

Mod name: Guicompass
Mod version: 1.5

## **Description**
The direction indicator starts to be off after a while and starts to say that I am facing SW when I am facing E. I can pretty reliably make this happen by making a quick 360 turn on the spot. An option to turn of the direction and just display coordinates would also be appreciated (as a workaround or just to free up some screen space).

**Comment by ksk-waqs** [comment]
Confirmed, encountered the same problem

**Comment by ozBillo** [comment]
Same problem in Minecraft 1.18

Minecraft version: 1.18
Forge version: 38.0.16
Environment: Singleplayer
Mod name: Guicompass
Mod version: 1.7

**Comment by ricksouth** [comment]
This has taken me way too long to figure out, but I have managed to fix the problem in version 2.1 of GUI Compass. This should fix the desync issues that have been occurring. Thanks for opening the issue and giving the mod a try everyone. Sorry for the inconvenience and it taking so long!

https://www.curseforge.com/minecraft/mc-mods/gui-compass/files
