### ISSUE TITLE
shield not appearing when it should

### ISSUE THREAD

**Issue by kubistonek** [Serilum/.issue-tracker#489]
shield goes invisible sometimes, even if holding right mouse (the shield works, and you are slower, but there is no shield on the screen. 

when it happends only restarting helps

**Comment by ricksouth** [comment]
Apologies for the late fix, thanks for opening the issue and giving the mod a try! This has been fixed in version 2.0 of Passive Shield.

https://www.curseforge.com/minecraft/mc-mods/passive-shield/files
