### ISSUE TITLE
Bug with Cycle Paintings and Macaw's Paintings

### ISSUE THREAD

**Issue by FionaTheMortal** [Serilum/.issue-tracker#490]
## **Information**
Minecraft version: 1.16.5
Forge version: 36.0.46
Environment: Singleplayer

Mod name: Cycle Paintings
Mod version: 1.5

## **Description**
Macaw's Paintings adds 3x3 paintings which when right clicked cycle and get moved over by 1 block.

**Comment by ricksouth** [comment]
Thanks for giving the mod a try and submitting the issue! I've fixed it in version 1.6. Made the code a lot more simple and it should work with any modded painting no problem now.

https://www.curseforge.com/minecraft/mc-mods/cycle-paintings
