### ISSUE TITLE
[Suggestion] Biomes You'll Go and Endergetic Expansion compatibility

### ISSUE THREAD

**Issue by MarioSMB** [Serilum/.issue-tracker#491]
## **Information**
Mod name: No Hostiles Around Campfire

## **Feature description**
It would be cool to be able to use the Ender Campfire from the Endergetic Expansion and the Boric/Cryptic Campfires from
Oh the Biomes You'll Go to keep mobs from spawning around bases.

**Comment by MarioSMB** [comment]
I'd just like to add that it may be worth using the existing `minecraft:campfires` block tag to identify which blocks/campfires count as hostile repellents, allowing mod and datapack support out of the box.

**Comment by ghost** [comment]
It would be fantastic if this small change suggested by @MarioSMB could be made. Would pretty much fix all issues relating to campfires not doing what they're supposed to.

**Comment by ghost** [comment]
Okay yeah so the immediate feedback was indeed that this mod SHOULD be using the `minecraft:campfires` tag:
https://github.com/team-abnormals/endergetic/issues/174#issuecomment-846445059

**Comment by ricksouth** [comment]
Support for modded campfires has been added in the latest version. Thanks for the suggestion and giving the mods a try!

https://www.curseforge.com/minecraft/mc-mods/no-hostiles-around-campfire/files
https://www.curseforge.com/minecraft/mc-mods/healing-campfire/files
