### ISSUE TITLE
Hand Over Your Items: Only give item in main hand?

### ISSUE THREAD

**Issue by ephys** [Serilum/.issue-tracker#492]
## **Information**
Mod name: Hand Over Your Items

## **Feature description**

Current behaviour of Hand Over Your Items is to give items from both hands to the target player. We've been surprised many times by this (accidentally giving our shield or torches), and think only giving items from the main hand would be a better behaviour.

What do you think?

**Comment by ricksouth** [comment]
I agree! Thanks for the suggestion and using the mod. Version 1.2 makes it so that only items held in the main hand will be transferred.

https://www.curseforge.com/minecraft/mc-mods/hand-over-your-items

**Comment by ephys** [comment]
Thank you :)
