### ISSUE TITLE
Server crash by the mod RespawnDelay

### ISSUE THREAD

**Issue by Taknax** [Serilum/.issue-tracker#494]
## **Information**
Minecraft version: 1.12.2
Forge version: 14.23.5.2855
Environment: Multiplayer

Mod name: RespawnDelay
Mod version: 2.2

## **Description**
Server crash. The report is not a crashlog. Its the last output from the server console.
Everything seems working. I die and get the spectator mod. the second count down. Instead of respawn the crash occures.

## **Crash report**
https://pastebin.com/N1zY1fEf

**Comment by ricksouth** [comment]
Thanks for giving the mod a try and submitting the issue! This has been fixed in version 2.3 of the mod. Make sure to update Collective as well.

https://www.curseforge.com/minecraft/mc-mods/respawn-delay
https://www.curseforge.com/minecraft/mc-mods/collective

**Comment by Taknax** [comment]
Ty. I have to thank you, for a ton of amazing mods.
