### ISSUE TITLE
Vanilla Experience crash on server start up

### ISSUE THREAD

**Issue by 2el222** [Serilum/.issue-tracker#499]
## **Information**
Minecraft version: 1.16.5
Forge version: 36.0.58
Environment:  Multiplayer

Mod name: Vanilla Experience Mod
Mod version: 1.0

## **Description**
Hey! This happened..

## **Crash report**
If available.
[crash-2021-03-14_01.56.31-fml.txt](https://github.com/ricksouth/serilum-mc-mods/files/6135828/crash-2021-03-14_01.56.31-fml.txt)

**Comment by James103** [comment]
Have you tried reinstalling the Vanilla Experience modpack from the [Curseforge page](https://www.curseforge.com/minecraft/modpacks/the-vanilla-experience/files/3235542)?
(use the Download button which is only available in the file detail page, which is linked directly above)

**Comment by 2el222** [comment]
> Have you tried reinstalling the Vanilla Experience modpack from the [Curseforge page](https://www.curseforge.com/minecraft/modpacks/the-vanilla-experience/files/3235542)?
> (use the Download button which is only available in the file detail page, which is linked directly above)

im using the mod, not the modpack

**Comment by ricksouth** [comment]
Thanks for submitting the issue and giving the mod a try! This has been fixed in version 1.1 of the mod.

https://www.curseforge.com/minecraft/mc-mods/the-vanilla-experience
