### ISSUE TITLE
Feature Suggestion

### ISSUE THREAD

**Issue by MLMII** [Serilum/.issue-tracker#5]
Based off of your "village spawn" mod, would it be possible to always set World Spawn to 0, 0?

**Comment by ricksouth** [comment]
I think that shouldn't be too hard! Which version of Minecraft are you currently using? e.g. do you need support for 1.12?

**Comment by ricksouth** [comment]
It hasn't been approved yet, but in about 24 hours you'll find the mod requested here: [https://www.curseforge.com/minecraft/mc-mods/set-world-spawn-point/](https://www.curseforge.com/minecraft/mc-mods/set-world-spawn-point/)
