### ISSUE TITLE
Crash: No Hostiles Around Campfire nhacampfire_1.15.2-1.5

### ISSUE THREAD

**Issue by ClaudiusMinimus** [Serilum/.issue-tracker#50]
## **Information**
Minecraft Version: 1.15.2
Operating System: Linux (amd64) version 4.15.0-88-generic
Java VM Version: OpenJDK 64-Bit Server VM (mixed mode)
Memory: 2643292368 bytes (2520 MB) / 6442450944 bytes (6144 MB) up to 6442450944 bytes (6144 MB)
CPUs: 8
Forge version: xx.xx.xx
Environment: Multiplayer

Mod name: No Hostiles Around Campfire
Mod version: nhacampfire_1.15.2-1.5

## **Description**
I'm developing a pack and seemed to work in SP, but when testing on my server I noticed a lot of lag. If I teleported home from another dimension the server crashed. Upon disabling No Hostiles Around Campfire the server is running smoothly.

Not sure if this is related, but after disabling the mod, mobs in the area were passive, like the world was in creative. I checked using /difficulty and was set to normal. I ended up changing to creative and then switched back to survival and seemed to fix it.

## **Crash report**
[crash-2020-03-19_06.38.56-server.txt](https://github.com/ricksouth/serilum-mc-mods/files/4356208/crash-2020-03-19_06.38.56-server.txt)

**Comment by ricksouth** [comment]
I've entirely rewritten the mod in version 2.0. It now requires an external library mod, but the code is a lot more efficient and it should fix the problems you were having. Feel free to open another the issue if that's not the case.

Thanks for letting me know!

[https://www.curseforge.com/minecraft/mc-mods/no-hostiles-around-campfire](https://www.curseforge.com/minecraft/mc-mods/no-hostiles-around-campfire)
