### ISSUE TITLE
Mod Compat with VillageNames?

### ISSUE THREAD

**Issue by Taknax** [Serilum/.issue-tracker#501]
I use VillagerNames (by you) and VillageNames (by AstroLibs)
[https://www.curseforge.com/minecraft/mc-mods/village-names](url)
Minecraft version: 1.12.2
Forge version: 14.23.5.2855
Environment: Singleplayer and Multiplayer

Mod name: VillagerNames
Mod version: 2.9

My main qustion is: does the two mods the same? If not, are they incompatible?

**Comment by ricksouth** [comment]
They should work together without problems. Villager Names sets the name tag of unnamed villagers, so it doesn't interact in a special way.
