### ISSUE TITLE
crash while launching a local server

### ISSUE THREAD

**Issue by Wedge1453** [Serilum/.issue-tracker#502]
so I tried to test my modpack's server file, I ran the command to launch the thing, and it crashed, I saw TVE name mentionned in the crash log so I thought I would share with you (btw I can't thank you enough for grouping all your mods in one, it helped a lot with modpack managing), I'm not sure if it is the cause, here is the crash log:
[crash-2021-03-16_22.10.19-fml.txt](https://github.com/ricksouth/serilum-mc-mods/files/6152324/crash-2021-03-16_22.10.19-fml.txt)

**Comment by ricksouth** [comment]
Thanks for submitting the issue! This has been fixed in version 1.1 of the mod. Glad you like them.

https://www.curseforge.com/minecraft/mc-mods/the-vanilla-experience
