### ISSUE TITLE
how do i edit how far the nether portal spreads on my apex server?

### ISSUE THREAD

**Issue by BusterBoys** [Serilum/.issue-tracker#503]
Minecraft version: 1.16.5
Forge version: 36.0.52
Environment: Multiplayer

Mod name: Netherportal Spread
Mod version: 5.1

How do i edit how far and fast the netherportal spreads on my apex server?

**Comment by ricksouth** [comment]
Please check out the FAQ on how to configure mods: https://github.com/ricksouth/serilum-mc-mods/wiki/FAQ

Thanks for using the mod!
