### ISSUE TITLE
NHAC not effecting Hunger from Outvoted mod

### ISSUE THREAD

**Issue by VallenFrostweaver** [Serilum/.issue-tracker#504]
Minecraft 1.16.5
Forge 36.0.48
No Hostiles Around Campfire 3.3
OutVoted 1.1.6

Hunger are mobs that spawn in the desert via the OutVoted mod. These are not affected by the No Hostiles Around Campfire mod. D:

**Comment by ricksouth** [comment]
I believe this is something on their end. I've opened an issue.

**Comment by ricksouth** [comment]
This has been fixed in the latest version of OutVoted. Thanks @VallenFrostweaver and How-Bout-No!
