### ISSUE TITLE
Configurable Mob Drop: Mob Drop not working with mobs with same entity Name

### ISSUE THREAD

**Issue by RedSeaObject** [Serilum/.issue-tracker#506]
Mods used: Mystical World mod, Environmental Mod(Team Abnormals)
Issue: when adding new mob drops to certain similar entities from both mods such as frogs and deers. said mobs do not drop added drops. Tried adding <mysticalworld:antlers> item to Environmental mod's Deer (enviromental:deer) does not drop any antlers. same goes with frogs. but other than that, everything seems to work fine.

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been fixed in version 1.5. Make sure to use a - instead of a : when specifying modded entities.

https://www.curseforge.com/minecraft/mc-mods/configurable-extra-mob-drops
