### ISSUE TITLE
Witch head doesn't have her hat

### ISSUE THREAD

**Issue by Federsavo** [Serilum/.issue-tracker#51]
## **Information**
Mod name: Just Mob Heads

## **Feature description**
I love this mod but I kinda hate the fact that the witch head has his hat cut off. Would it be possible to add an item just for the witch head (I understand the intent of this mod is to not add blocks, but maybe you could make it configurable with configs)

**Comment by ricksouth** [comment]
The mob heads are all a single block, and use the vanilla resources. I won't add a custom block. Is there an item you can use instead? I think you can get an upside-down hopper with a command. Does that work? :)

**Comment by ricksouth** [comment]
Glad it's resolved on your end.

**Comment by Federsavo** [comment]
I mean, I will try the hopper thing, but If the goal of the mod is to not add new block I won't bother with suggestions that wants to add custom blocks. This is the reason why I closed the issue

**Comment by ricksouth** [comment]
I understand. Maybe you can try to add a custom block yourself? I believe MCEdit allows this without much knowledge of coding, or of course use the normal Forge API.

**Comment by Federsavo** [comment]
I will try it. Thanks for the help.
