### ISSUE TITLE
is there a list of mods that are client'side only, server-side only, and both?

### ISSUE THREAD

**Issue by Wedge1453** [Serilum/.issue-tracker#511]

**Comment by ricksouth** [comment]
The following mods are client-only. The rest needs to be installed on the server:

https://www.curseforge.com/minecraft/mc-mods/advancement-screenshot
https://www.curseforge.com/minecraft/mc-mods/full-brightness-toggle
https://www.curseforge.com/minecraft/mc-mods/gui-clock
https://www.curseforge.com/minecraft/mc-mods/gui-compass
https://www.curseforge.com/minecraft/mc-mods/gui-followers
https://www.curseforge.com/minecraft/mc-mods/hidden-recipe-book
https://www.curseforge.com/minecraft/mc-mods/hide-hands
https://www.curseforge.com/minecraft/mc-mods/omega-mute

**Comment by ricksouth** [comment]
I believe only Areas needs to be installed on both sides.

**Comment by Wedge1453** [comment]
thank you very much!

**Comment by ricksouth** [comment]
No problem! Thanks for giving my mods a try! :)
