### ISSUE TITLE
Add multiple download ignore for collective check

### ISSUE THREAD

**Issue by sirben99** [Serilum/.issue-tracker#512]
Minecraft version: 1.16.5
Forge version: 36.1.0
Environment: Singleplayer

Mod name: Collective
Mod version: 1.16.5-2.24

Description
Hey!

I noticed when using Collective, it says that i have downloaded it on other sources than curseforge. But the issues is that i have 100% downloaded it on Curseforge (https://www.curseforge.com/minecraft/mc-mods/collective/files/3238039). I never download form any other source, unless i know its safe (For e.g optifine or forge installer).
I sucpect it sees that i launched from MultiMc, the mod thoughs i have a illigamate version. Also tested on Technic launcher, and the same message appears. It doesent seem to however happen in multiplayer.
![image](https://user-images.githubusercontent.com/32977052/111910940-19453880-8a6c-11eb-87f6-1dae77fa16f7.png)

Collective seem to be the only one of your mods that causes this.

EDIT: I tested on a official minecraft launcher, and the same message appears. Seems like somethings wrong with the mod itself.
![image](https://user-images.githubusercontent.com/32977052/111911132-e3ed1a80-8a6c-11eb-8047-dcfd1e615d97.png)

Ofc, i dont have a proper way to give you proof that i have an official verion of Collective, other than my word. So i highly sugsect testing it yourself.

Ben

**Comment by ricksouth** [comment]
Did you by any chance rename the file?

**Comment by sirben99** [comment]
> Did you by any chance rename the file?

Nope. Downloaded it, dropped to mods folder, and launched

**Comment by James103** [comment]
Did you download the mod from Curseforge or [Serilum's mod website](https://minecraft.natamus.com/collective/)?

**Comment by sirben99** [comment]
> Did you download the mod from Curseforge or [Serilum's mod website](https://minecraft.natamus.com/collective/)?

Curseforge, like stated in the op post

**Comment by ricksouth** [comment]
Could you send a screenshot of the folder with the collective file displayed?

**Comment by sirben99** [comment]
> Could you send a screenshot of the folder with the collective file displayed?

Wait... i just noticed that since i downloaded the file multiple times, theres a (numberhere) at the end of it. And if you mod detects name changes, this could be the reason
![image](https://user-images.githubusercontent.com/32977052/111913005-d9368380-8a74-11eb-9bbd-0b47292fdded.png)

**Comment by ricksouth** [comment]
Yep that's it! The reposting is quite a big problem, so this is an attempt to prevent some of it. I'll add an ignore check for the next update with the (x) appends for multiple downloads. Thanks opening the issue and the extensive documentation!

**Comment by sirben99** [comment]
> Yep that's it! The reposting is quite a big problem, so this is an attempt to prevent some of it. I'll add an ignore check for the next update with the (x) appends for multiple downloads. Thanks opening the issue

Np! Sorry that i dint think of the (x) earlyer, but im glad that this is sorted out now!

You can close the issues now you want, since i dont have any more problems.

Thank you for taking a look and quick respond times!

Ben

**Comment by ricksouth** [comment]
I'll leave it open as a reminder, and will close it when I release the update. No problem! :)

**Comment by ricksouth** [comment]
This has been fixed in version 2.25 of Collective.

https://curseforge.com/minecraft/mc-mods/collective
