### ISSUE TITLE
Collective/ Skeleton Horse Spawn stall with Cubic Chunks.

### ISSUE THREAD

**Issue by border999** [Serilum/.issue-tracker#513]
## **Information**
Minecraft version: 1.12.2
Forge version: 1.12.2-forge-14.23.5.2854
Environment: Singleplayer

Mod name: Collective/ skeletonhorsespawn
Mod version: collective-1.12.2-2.24 / skeletonhorsespawn_1.12.2-1.6 / CubicChunks-1.12.2-0.0.1185.0-SNAPSHOT-all

## **Description**
Opened world and it stalled.

Stall Report: 
[stall-2021-03-21_19.59.01-2.txt](https://github.com/ricksouth/serilum-mc-mods/files/6179882/stall-2021-03-21_19.59.01-2.txt)

**Comment by ricksouth** [comment]
This has been fixed in version 2.46 of Collective. Thanks for submitting the report!

https://www.curseforge.com/minecraft/mc-mods/collective/files
