### ISSUE TITLE
Weaker spider webs issue

### ISSUE THREAD

**Issue by ghost** [Serilum/.issue-tracker#516]
## **Information**
Mod name: Weaker spider webs

## **Issue**
This only works if the player has fallen on the web from above. It doesn't collapse if you hit it with your head. 
(I think, because coordinates are counted from the feet)

**Comment by ricksouth** [comment]
Thanks for submitting the issue! This has been fixed in version 2.0 of Weaker Spiderwebs.

https://www.curseforge.com/minecraft/mc-mods/weaker-spiderwebs/files/all
