### ISSUE TITLE
Worlds won't load with newer versions of Collective and TVE

### ISSUE THREAD

**Issue by 4ilur0phile** [Serilum/.issue-tracker#517]
## **Information**
Minecraft version: 1.16.5
Forge version: 36.0.53
Environment: Singleplayer

Mod name: Collective and The Vanilla Experience
Mod version: 
Collective: Any version past 1.16.5-2.13
The Vanilla Experience: Any version past 1.16.5-1.0

## **Description**
If I try to use any version past the ones mentioned, my game refuses to load worlds. The game doesn't say it's frozen/not responding when it happens, but the world just won't load, and I have to completely close minecraft.

## **Crash report**
My only way to deal with the game refusing to load worlds or do anything else is force-quitting, so I don't have any crash reports. My best guess is that my plethora of other mods don't like whatever was changed in newer versions of the mods.

**Comment by ricksouth** [comment]
Thanks for submitting the bug report! I've made a lot of changes to the code lately in both TVE and Collective, and the problem you were having should be resolved.

https://www.curseforge.com/minecraft/mc-mods/collective/files
https://www.curseforge.com/minecraft/mc-mods/the-vanilla-experience/files
