### ISSUE TITLE
Recast timeout

### ISSUE THREAD

**Issue by oddsoul** [Serilum/.issue-tracker#518]
## **Information**
Minecraft version: 1.16.5
Forge version: 36.1.0
Environment: Multiplayer

Mod name: recast
Mod version: recast_1.16.5-1.2.jar

## **Description**
There is a bug that makes the fishing line disapear after a while if there is no fish caught within a certain time

**Comment by ricksouth** [comment]
I've tested how long it takes for the line to disappear, and it's much later than when you're able to catch a fish. With a few nibbles in between. I don't think it's wrong if you miss 10 or so fish nibbles that the line should disappear. Thanks for submitting the issue though and giving the mod a try!
