### ISSUE TITLE
[idea][Double Doors] [Any MC Version if still maintained] trigger iron doors

### ISSUE THREAD

**Issue by Bass2style** [Serilum/.issue-tracker#52]
## **Information**
Mod name: Double Doors

## **Feature description**
if possible, adding the control of two iron (or modded variants) when a door is actioned with redstone. because doing a redstone circuit is really not clean and pertinent in a modded environment.

**Comment by ricksouth** [comment]
Thanks for the idea! Check out version 2.0, it adds this and other features :)
[https://www.curseforge.com/minecraft/mc-mods/double-doors](https://www.curseforge.com/minecraft/mc-mods/double-doors)
