### ISSUE TITLE
Can't mute minecarts

### ISSUE THREAD

**Issue by patatjuih** [Serilum/.issue-tracker#523]
Minecraft version: 1.16.1
Forge version: 32.0.108
Environment: Singleplayer 

Mod name: omegamute
Mod version: omegamute_1.16-1.3.jar

When I do /omegamute listen it doesn't register the sound of a minecart with hopper and I can't mute it.

**Comment by James103** [comment]
Have you tried muting the following sound events?
```
entity.minecart.inside
entity.minecart.riding
```
Search for them in `./config/omegamute/soundmap.txt` and replace them with
```
!entity.minecart.inside
!entity.minecart.riding
```
to mute the sounds.

Reload the config file by restarting Minecraft or running the command `/omegamute reload` to apply the changes.

**Comment by patatjuih** [comment]
how can I find ./config/omegamute/soundmap.txt 
and when I do /omegamute mute entity.minecart.inside and entity.minecart.riding, I can still hear them

**Comment by James103** [comment]
In this case, `./config` means to go to the config folder of the Minecraft instance you are running.
The rest of the path should be self-explanatory. See [the FAQ](https://github.com/ricksouth/serilum-mc-mods/wiki/FAQ) for more information.

**Comment by patatjuih** [comment]
nope it doesn't work
