### ISSUE TITLE
Config of MoreZombieVillager doesnt work

### ISSUE THREAD

**Issue by r0sso** [Serilum/.issue-tracker#527]
## **Information**
Minecraft version: 1.16.5
Forge version: 36.0.48
Environment: Multiplayer

Mod name: Mod MoreZombieVillager
Mod version: 1.3

## **Description**
Hey. I set the value of the zombie spawn chance to 0, but for some reason this does not disable the spawn of zombie villagers. After killing a villager from a zombie, he becomes a zombie villager everytime.

**Comment by James103** [comment]
Are you on Hard difficulty? If so, what happens if you retest on Easy and Normal difficulties?

**Comment by r0sso** [comment]
Yes on hard. I needed all features of hard and I was looking for a mod that would disable the spawn of zombie villagers. on normal difficulty, a value of 0 completely disables spawning zombie villagers?

**Comment by r0sso** [comment]
even on normal difficulty, a value of 0 does not make any difference. zombies also continue to infect villagers

**Comment by James103** [comment]
What happens if you set the zombie spawn chance to 1? Maybe the value 0 is getting remapped to a value of 100 (on a percentage scale).

**Comment by r0sso** [comment]
The same. The more mod description says  "zombieIsVillagerChance (default = 0.25, min 0, max 1.0)"

**Comment by ricksouth** [comment]
Thanks for submitting the bug report. The mod does not change the chance of existing zombie villagers. The config value means "The overridden chance a new zombie spawn is of the villager variant.". So if a new zombie spawns, the mod by default has a 25% chance to change that zombie to a zombie villager. Sorry for the inconvenience.
