### ISSUE TITLE
World border

### ISSUE THREAD

**Issue by nix-bou** [Serilum/.issue-tracker#528]
Minecraft version: 1.16.4

Mod: World Border

Hi, so im simply wondering how to use this command: enableCustomOverworldBorder (default = true) and set it to false so my minecraft server doesn't have a world border anymore

**Comment by ricksouth** [comment]
Thanks for giving the mod a try! This FAQ entry explains how to change config values:

https://github.com/ricksouth/serilum-mc-mods/wiki/FAQ

Where can I configure the mod? Where is the configuration file located?
All my mods use the Forge Configuration Manager. The config files are located in your root minecraft folder in ./config/. You can edit the .toml files with any text editor, like notepad. The name of the config file starts with the mod id.
