### ISSUE TITLE
Double Doors Wont close

### ISSUE THREAD

**Issue by cpepperkorn** [Serilum/.issue-tracker#529]
## **Information**
Minecraft version: 1.12.2
Forge version: 14.25.5.2854
Environment: Singleplayer

Mod name: Double Doors
Mod version:1.2

## **Description**
I love the mod, but whenever I open the double doors they wont close, I can open them fine, but they stay open and have the sound effect but still stay open.

**Comment by ricksouth** [comment]
Thanks for submitting the bug report! Unfortunately due to the nature of code changes in 1.13, the 1.12 version of Double Doors is no longer supported. Sorry for the inconvenience.

**Comment by oyuno-miyumi** [comment]
Malisis doors affects vanilla doors and doors made with the door factory, but not doors from other mods. Disabling the replacement of vanilla doors in the malisis doors config makes the vanilla doors open and close properly, but the doors from the door factory will still have issues. If you don't have any other mods that add doors, then you don't need this one. If you do, then you need to decide between this mod and malisis doors. (I have biomes o plenty and macaw's doors)
