### ISSUE TITLE
Grindstone Sharper Tools - two minor problems

### ISSUE THREAD

**Issue by zanecek** [Serilum/.issue-tracker#531]
## **Information**
Minecraft version: 1.16.5
Forge version: 36.1.0
Environment: Singleplayer
Mod name: Grindstone_Sharper_Tools-1.5

## **Description**
1) Config "sendUsesLeftInChat = false" looks not working.
2) Sharpening (can) change tool name and font (_italic_) and after the sharpness is used up, it does not return them back. It would be optimal to display any current sharpening as additional info in item tooltip.

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! Both have been fixed in version 2.2 of Grindstone Sharper Tools.

https://www.curseforge.com/minecraft/mc-mods/grindstone-sharper-tools/files
