### ISSUE TITLE
Can't open config

### ISSUE THREAD

**Issue by GranCeros** [Serilum/.issue-tracker#534]
## **Information**
Minecraft version: 1.16.5
Forge version: 36.1.0
Environment: Both

Mod name: GUI Clock
Mod version: 2.3

## **Description**
Hey! This happened when I am trying to activate the mod, but it doesn't let me open config thingy
https://cdn.discordapp.com/attachments/724972366387478590/827211373389414420/unknown.png
Screenshot if that explains it

## **Crash report**
no, no crash report

**Comment by ricksouth** [comment]
Thanks for giving the mod a try! 1.14+ does not have the in-game config available. This FAQ entry explains it:

https://github.com/ricksouth/serilum-mc-mods/wiki/FAQ
- Where can I configure the mod? Where is the configuration file located?

All my mods use the Forge Configuration Manager. The config files are located in your root minecraft folder in ./config/. You can edit the .toml files with any text editor, like notepad. The name of the config file starts with the mod id.
