### ISSUE TITLE
is there any performance difference between disabling uneeded mods in TVE mod config and installing each needed mod separatly?

### ISSUE THREAD

**Issue by Wedge1453** [Serilum/.issue-tracker#535]
in other words, is diasabling a mod in TVE config like not installing it?

**Comment by ricksouth** [comment]
The main difference is a little longer boot time. I estimate it being <1ms difference. The TVE mod checks which mods to enable via the config and other variables. After load it's as if the mod isn't installed when disabled in the config. Thanks for the interest!
