### ISSUE TITLE
Areas mod doesn't work on server

### ISSUE THREAD

**Issue by LobaCW** [Serilum/.issue-tracker#537]
## **Information**
Minecraft version: 1.16.5
Forge version: 36.1.0
Environment: Multiplayer Server

Mod name: Areas
Mod version: 2.2

## **Description**
Areas mod works perfectly in singleplayer, but not on my local server, even though I have areas mod and collective mod (version 2.25) installed on both the client and the server

**Comment by arrisar** [comment]
Hi @LobaCW, could you describe what specifically is not working? I want to make sure we don't raise the same issue.

I've created a sign and run the `/areas` command, but it does register the name, or show me a message when entering/leaving the area. The village-generated signs work fine.

![image](https://user-images.githubusercontent.com/846173/113984827-dc13df80-988e-11eb-85ce-6624e8d22c3c.png)

**Comment by LobaCW** [comment]
So, in singleplayer it works perfectly fine:
![1](https://user-images.githubusercontent.com/81968724/114090344-ad493980-988d-11eb-9987-73ab25a11852.png)

But that happens when I open to LAN:
![2](https://user-images.githubusercontent.com/81968724/114090352-afab9380-988d-11eb-8472-55accc5b2f99.png)

Same as in a server:
![3](https://user-images.githubusercontent.com/81968724/114090356-b1755700-988d-11eb-8e2c-99f5922cb529.png)

As I noticed now the sign actually generate the area...more or less.
Well, what is happening is that the names of the areas is not showing up nor the titles for them, but with the command /areas you can see that the area is there, with no name.
I discover now how to "fix" this, when I restart the server or the world that is opened to LAN, the signs placed will work, the bug here is just it won't show when first placed, which is a bit of a bummer.
Hope this information was useful to help fix it.

Edit: I changed the config files as you can see in the first image but just so you know that doesn't interfere in nothing since I deleted the config an ran the server again to see if this was the problem but nothing changed regarding the bug.

**Comment by arrisar** [comment]
I've reproduced the fix, once my dedicated server was restarted, the area started working as intended.

It appears that the error lies in the initialisation of a new sign.

**Comment by arrisar** [comment]
@ricksouth sorry to hassle, but any word on this issue?

**Comment by ghost** [comment]
@arrisar I am also 100% having this issue. Restarting my server DOES make the signs work, but I also found a work-around / that the first option:
> sendChatMessages = true

Does work, but seems to still require showHUDMessages = true

Results on forge 1.16.5 Server: 

1. **Chat messages work, HUD messages do not** _whatsoever, regardless of what HUD settings I have tweaked._
2. **Signs require server to full hard-restart for new Areas to take effect.**
![2021-05-11_18 53 28](https://user-images.githubusercontent.com/84054111/117906949-be210c80-b28a-11eb-8b2c-e74db2f95b17.png)

@ricksouth Know you are busy, but just wanted to confirm this is a legitimate bug right now with the latest version. This is a very important mod right now for 1.16.5 servers! Would love to have HUD messages working again.

**Comment by ricksouth** [comment]
Sorry for the delay everyone. I've just released version 2.7 of Area which should fix all the issues you were having. The problem seemed to be that Areas was checking the sign content too quickly, before it was updated on the client. Because of this the sign was added to an "ignore this sign in future checks"-list.

I appreciate all the screenshots and investigations. Thank you!! If there are still problems please let me know.

https://www.curseforge.com/minecraft/mc-mods/areas/files/all
