### ISSUE TITLE
/areas command not working

### ISSUE THREAD

**Issue by EpicDRC** [Serilum/.issue-tracker#539]
## **Information**
Minecraft version: 1.16.4
Forge version: 35.1.4
Environment: Singleplayer / Multiplayer

Mod name: Areas
Mod version: 1.16.4-1.1

## **Description**
The /areas command is not working on either singleplayer or multiplayer, everything else works fine.

**Comment by ricksouth** [comment]
The /areas command was added in the 1.16.5 version. Please update to the latest minecraft release. Most 1.16.4 mods should work no problem in the newer version. Thanks for giving the mod a try and opening the issue!
