### ISSUE TITLE
Dismount Entity and Carry On mods work together?

### ISSUE THREAD

**Issue by ftzi** [Serilum/.issue-tracker#541]
## **Question**
Does the [Dismount Entity](https://www.curseforge.com/minecraft/mc-mods/dismount-entity) works with the [Carry On](https://www.google.com/search?channel=fs&client=ubuntu&q=carry+on+mod) mod? If so, it will only carry if the entity is unmounted?

**Comment by ricksouth** [comment]
It should work fine, just don't hold the sneak button when picking it up or change the hotkey! Thanks for the interest.
