### ISSUE TITLE
Minecraft Clock Icon does not Show

### ISSUE THREAD

**Issue by vibhavroy91** [Serilum/.issue-tracker#542]
## **Information**
Minecraft version: 1.16.5
Forge version: 36.1.4
Environment: Singleplayer

Mod name: Mod
Mod version: guiclock-1.16.5-2.3

## **Description**
When the config to show in-game clock was enabled the clock did not show up at all.

## **Crash report**
No Crash

##**Config Settings at the time**

[General]
	#Places the GUI clock on the right.
	clockPositionIsRight = false
	#The vertical offset (y coord) for the Clock. This determines how far down the time should be on the screen. Can be changed to prevent GUIs from overlapping.
	#Range: 0 ~ 3000
	clockHeightOffset = 5
	#Places the GUI clock in the middle.
	clockPositionIsCenter = true
	#The red RGB value for the clock text.
	#Range: 0 ~ 255
	RGB_R = 255
	#Places the GUI clock on the left.
	clockPositionIsLeft = false
	#When enabled, will only show the real time when a clock is present in the inventory.
	mustHaveClockInInventoryForRealTime = false
	#Sets the format of the clock to the 24-hour format.
	_24hourformat = false
	#When enabled, will only show the game time when a clock is present in the inventory.
	mustHaveClockInInventoryForGameTime = false
	#The green RGB value for the clock text.
	#Range: 0 ~ 255
	RGB_G = 255
	#Show the days played in the world.
	showDaysPlayedWorld = true
	#The blue RGB value for the clock text.
	#Range: 0 ~ 255
	RGB_B = 255
	#When enabled, shows the clock item icon instead of a clock with numbers.
	showOnlyMinecraftClockIcon = true
	#Show actual local time instead of in-game time.
	showRealTime = false
	#Show the seconds in the clock.
	showRealTimeSeconds = false
	#Show both in-game time and real local time.
	showBothTimes = false

**Comment by SonicX8000** [comment]
"guiclock_1.12.2-2.3.jar"

Perhaps related but this also occurs in the 1.12.2 Version. Set the "showOnlyMinecraftClockIcon" to true and the hud icon doesn't render. The Text & Day does if it was set to false, however.

This is with or without having the "minecraft:clock" in your inventory, depending on how the "mustHaveClockInInventory" is set.

**Comment by ricksouth** [comment]
Thanks for submitting the bug report and giving the mod a try! This has been fixed in version 2.5 of GUI Clock. Please let me know if there are any more issues.

https://www.curseforge.com/minecraft/mc-mods/gui-clock/files/all
