### ISSUE TITLE
kelp won't grow crops, maybe a pam's compatibility issue?

### ISSUE THREAD

**Issue by kingfaenor** [Serilum/.issue-tracker#543]
## **Information**
Minecraft version: 1.16.5
Forge version: 36.1.3
Environment: Singleplayer and Multiplayer

Mod name: Mod
Mod version: 1.4

## **Description**
The kelp bonemeal works on grass but not on crops. I have not tried uninstalling pam's, because I would rather play with pams than with this mod. Hopefully I can play with both though

## **Crash report**
[mods.txt](https://github.com/ricksouth/serilum-mc-mods/files/6291203/mods.txt)
list of my installed mods if that would help

**Comment by ricksouth** [comment]
I've opened an issue here: https://github.com/MatrexsVigil/phc2crops/issues/47. And will try to add compatibility when possible.

**Comment by ricksouth** [comment]
Indeed a compatibility issue. Unfortunately not something I can fix on my end. I've opened the issue on Pam's Github. Hope they can fix it on their end. If not, they can always contact me to find a solution.
