### ISSUE TITLE
How do I not smash the boat?

### ISSUE THREAD

**Issue by relsqui** [Serilum/.issue-tracker#545]
## **Information**
(you can remove whatever is not applicable)
Minecraft version: 1.16.5
Forge version: 36.1.10
Environment: Singleplayer

Mod name: Move Boats
Mod version: 1.5

## **Question**
Every time I try to move a boat it dissolves into planks in my hands. What circumstances cause this? What are the limits on how I'm allowed to move the boat?

**Comment by ricksouth** [comment]
You should just be able to move it up. Which block is below the boat when this happens? E.g. water or a modded block?

**Comment by relsqui** [comment]
I tried it just now in a pool of water in vanilla stone. Placed a vanilla spruce boat, shift rclicked to pick it up, and as soon as I moved my mouse to set it down it broke. It's not always that fast -- sometimes it's after I take a step, or a couple of steps, but never seems to be a collision with anything or in any remarkable terrain.

**Comment by James103** [comment]
@ricksouth Have you tried patching the code in the Move Boats mod such that a boat that is being picked up and moved with the mod gets its fall distance reset every tick? Maybe the boat is accumulating fall distance while being moved around, causing it to take (massive) damage when touching the ground.

**Comment by ricksouth** [comment]
Thanks @James103 for suggesting the solution. I've added the code to set the fall damage of the boat to 0 while moving. Hopefully that fixes the issue you were having @relsqui. Thanks for submitting the bug report and giving the mod a try!

https://www.curseforge.com/minecraft/mc-mods/move-boats/files/all
