### ISSUE TITLE
[1.16.5] Areas cannot be made with non-vanilla signs

### ISSUE THREAD

**Issue by Not-February** [Serilum/.issue-tracker#547]
## **Information**
Mod name: Areas

## **Feature description**
There are many mods that add custom wood variants to signs for their woods like vanilla, but when I tested and checked with the /area command, Areas only seems to properly be created when using the vanilla signs specifically. It would be great if Areas could be made compatible with other mod-added signs.

A few examples of mods which do this: Abundance, Atmospheric, Autumnity, Bayou Blues, Environmental

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! Compatibility has been added in version 5.0 of Areas, alongside other bug fixes and QoL features. Apologies it took so long for me to get to.

https://www.curseforge.com/minecraft/mc-mods/areas/files
