### ISSUE TITLE
[1.16.x] incompatibility

### ISSUE THREAD

**Issue by Bass2style** [Serilum/.issue-tracker#548]
## **Information**
Minecraft version: 1.16.5
Forge version: 36.1.4
Environment: Singleplayer / Multiplayer > both seems affected

Mod name: UnderWaterEnchanting
Mod version: 1.3

## **Description**
Hi,

due to Apotheosis appropriating Vanilla blocks for is mod, and changing some of their mechanics, UnderWaterEnchantig is not working.
could it possible to add Apotheosis compatibility ? (with both Vanilla and Apotheosis shelfs could be perfect.)

## **Crash report**
no crashlogs, not sure that there are stacktraces about that in the logs tbh.

have a nice day.

**Comment by ricksouth** [comment]
Thanks for submitting the bug report! The enchantment table of Apotheosis is so complex, it can't be fixed on my end. You could resolve the issue by asking the author if they can make it so that their enchantment table works under water. Appreciate it though!
