### ISSUE TITLE
Re-Open Question (Issue #54)

### ISSUE THREAD

**Issue by Artuotpz** [Serilum/.issue-tracker#55]
## **Information**

Minecraft version: 1.15.2
Forge version: 31.1.24
Environment: Singleplayer / Multiplayer (Both)

Mod name: Gui Compass
Mod version: 1.1

## **Question**
Hello, I was wondering how do I open the config file for the mod, in order to modify a line to "false". In your curseforge mod webpage, you mention the ability to change that but unfortunately I'm unable to get to it. Thanks in advanced!

**Comment by ricksouth** [comment]
Hi, thanks for using the mod! In your minecraft save folder there's a folder called "config". In this there are config files for all your mods. The one for GUI Compass is called "guicompass-common.toml". Open this with a text editor (like Notepad) and you can edit the config as a text file.
