### ISSUE TITLE
[Village Spawn Point] Bonus chest doesn't generate/can't be found

### ISSUE THREAD

**Issue by tlitookilakin** [Serilum/.issue-tracker#550]
## **Information**
Minecraft version: 1.16.5
Forge version: 36.1.4
Environment: Singleplayer / Multiplayer

Mod name: Village Spawn Point
Mod version: 1.5

## **Description**
When generating a world with the bonus chest enabled, bonus chest either does not appear or cannot be found near spawn point.

**Comment by ricksouth** [comment]
Thanks for submitting the bug report and giving the mod a try! Version 1.8 of Village Spawn Point adds compatibility with the bonus chest world generation feature. Another chest will be placed around the village spawn position if it's enabled.

https://www.curseforge.com/minecraft/mc-mods/village-spawn-point/files
