### ISSUE TITLE
Areas for 1.12.2? 

### ISSUE THREAD

**Issue by randowitharequest** [Serilum/.issue-tracker#552]
So, I am starting up a 1.12.2. server, and we want to use your mod, but the files don't seem to go back far enough to support our server. And Named Areas isn't multiplayer - hence your rebrand. just wondering if configuring it for 1.12 might be a possibility. Thanks!

**Comment by ricksouth** [comment]
Unfortunately due to the code changes, Areas won't be released for 1.12.2. I appreciate the interest though!
