### ISSUE TITLE
Collective API Not Working On MC 1.16.4 Says I Need 1.16.5

### ISSUE THREAD

**Issue by Arnav214** [Serilum/.issue-tracker#553]
## **Information**
Minecraft version: 1.16.4
Forge version: latest
Environment: Singleplayer

Mod name: Collective API
Mod version: 2.26

## **Comment**
Hi, I cannot get this mod to work on 1.16.4 it says that I need 1.16.5 for the mod

**Comment by James103** [comment]
Have you tried upgrading Minecraft to 1.16.5 (with the corresponding latest or recommended Forge version)? If you get a crash, can you please post that crash file and/or the `latest.log`?

**Comment by Arnav214** [comment]
> Have you tried upgrading Minecraft to 1.16.5 (with the corresponding latest or recommended Forge version)? If you get a crash, can you please post that crash file and/or the `latest.log`?

It does not crash and I have all the mods that I have downloaded for 1.16.4 so I cant use 1.16.5 Currently I cannot send any details as it is on my pc and currently I am unable to use it

**Comment by ricksouth** [comment]
There is a 1.16.4 version available here: https://www.curseforge.com/minecraft/mc-mods/collective/files/all?filter-status=1&filter-game-version=2020709689%3A8134

Thanks for giving the mods a try!
