### ISSUE TITLE
Hostile foxhounds spawn around campfires (Quark conflict)

### ISSUE THREAD

**Issue by MarioSMB** [Serilum/.issue-tracker#554]
## **Information**
Minecraft version: 1.16.5
Forge version: 36.1.4
Environment: Multiplayer

Mod name: No Hostiles Around Campfire
Mod version: 3.3

## **Description**
The Quark mod's foxhound is a creature that spawns in the Nether which is naturally aggressive towards players who do not have fire resistance. These creatures are currently ignoring the no hostiles rule by campfires and spawning anywhere regardless.  
Having dug into Quark's code a little, I can see that they are using `EntityClassification.CREATURE` which may be an error on their part, however as a user I am unsure how such conflicts are resolved and am reporting this here as it is your mod that is affected.

**Comment by ricksouth** [comment]
A possible solution would be to add a config option for players to include modded mobs that are not hostile by default. I'll see what I can do!

**Comment by ricksouth** [comment]
I've added the FoxHound to a custom list within No Hostiles Around Campfire. It should not spawn within a campfire radius now. Let me know if any other entities should be included as well. Thanks for using the mod! Added in version 3.6.

https://www.curseforge.com/minecraft/mc-mods/no-hostiles-around-campfire/files/all
