### ISSUE TITLE
[Question, All Mods] Thoughts on someone forking to make a Fabric port?

### ISSUE THREAD

**Issue by sableseyler** [Serilum/.issue-tracker#558]
Having read the FAQ, I think you have an excellent argument about a great deal of confusion being introduced from having Fabric ports on the same page. It really can be a bit tedious to sort that out in Curseforge's interface. (I do have plans to make a different interface that automates this somewhat to support packmakers, but that's a separate story.) And yes, it makes a great deal of sense that maintaining an additional hundred-some project pages would be substantially tedious.

Nonetheless, I still want there to be Fabric support (and think they'll perform even better there, due to Fabric's architecture handling large numbers of small mods better). However, given that you've shared the source code but have "All Rights Reserved" licenses in the mods, I can't just "fork and hope for the best" once I have the time, as I might with other projects. Don't want to step on any toes, infringe any copyrights, etc. 

So, what are your thoughts on the subject of a fork to port my favorites to Fabric? You make an enormous pile of very impressive mods, some of which I consider essential additions to an immersive pack. I'd love to get some friends together, make them available to a wider audience, and spread the love of awesome micro-mods.

**Comment by James103** [comment]
If you want to do it yourself, you will need to use [Patreon](https://www.patreon.com/ricksouth) and pay @ricksouth $5.00 to gain access to the source code for the mods for one month, which should be enough time for you to clone the private repository  and make a local copy, which you can then use to port the mods over to Fabric. Alternatively, if and when the feature described in #586 is implemented, you may be able to get the Fabric versions of the mods from [Modrinth](https://modrinth.com/).

**Comment by ricksouth** [comment]
Most mods have had a Fabric port, and for those that haven't I'll be doing another attempt in the near future. I appreciate the interest!
