### ISSUE TITLE
Compatibility with terraforged?

### ISSUE THREAD

**Issue by G-Stav** [Serilum/.issue-tracker#559]
## **Information**
Mod name: 
villagespawnpoint__1.16.5-1.5.jar
TerraForged-1.16.5-0.2.10.jar

## **Feature description**
When using both TerraForged and Village Spawn Point you don't spawn in a village anymore. Not sure if it's on their side or yours but it would be cool to be able to use both mods together.

**Comment by James103** [comment]
Try the following steps:
1. Install both Terraforged and Village Spawn Point and no other mods.
2. Create a new world with cheats enabled, "Generate Structures" enabled, and TerraForged's world type.
3. Run command `/locate village`.

What output do you get from running the command?

**Comment by G-Stav** [comment]
"The nearest village is at [7360, ~, -6048] (505 blocks away)" Is what returns in the chat, or do you mean the log?

**Comment by Rx2TF** [comment]
I have the same issue. `/locate village` can find a village but the spawn is not set there.
https://github.com/TerraForged/tracker/issues/11

**Comment by shadowbolt79** [comment]
I know you're not going to work on the 1.12.2 version, but same thing happens with OpenTerrainGenerator worlds in 1.12.2. Not sure if that would help you narrow down the cause or not.

**Comment by ZAKsPop** [comment]
Any progress on this issue?

**Comment by twothe** [comment]
Having the same issue in 1.16 with Terraforge.

**Comment by ricksouth** [comment]
The compatibility has been added in version 2.6 of Village Spawn Point. Thanks for the request and giving the mod a try!

https://www.curseforge.com/minecraft/mc-mods/village-spawn-point/files
