### ISSUE TITLE
Issue with bed respawn

### ISSUE THREAD

**Issue by Greatone123** [Serilum/.issue-tracker#56]
## **Information**
Minecraft version: 1.15.2
Forge version: 31.1.25
Environment: Multiplayer

Mod name: Set World Spawn
Mod version: 1.0

## **Description**
I have the mod installed on the server. I set my respawn at my bed. (multiple locations tested, not obstructed) I respawn at my bed, and then almost immediately after, I get sent to world spawn. Remove the mod, it doesn't happen.

This is in the log when I die, so it might not be 100% the mod, but it's the event that happens and the mod is reacting to it.

Netty Epoll Server IO #2/ERROR
 
15:10:54

Could not serialize net.minecraftforge.server.command.ModIdArgument@92fe747 (class net.minecraftforge.server.command.ModIdArgument) - will not be sent to client!
Could not serialize net.minecraftforge.server.command.EnumArgument@137c8599 (class net.minecraftforge.server.command.EnumArgument) - will not be sent to client!

**Comment by ricksouth** [comment]
Thanks for letting me know! I've fixed this in version 1.1 of the mod.

[https://www.curseforge.com/minecraft/mc-mods/set-world-spawn-point](https://www.curseforge.com/minecraft/mc-mods/set-world-spawn-point)
