### ISSUE TITLE
Fixed Anvil Repair Cost - doesn't work as intended

### ISSUE THREAD

**Issue by Zothen1973** [Serilum/.issue-tracker#565]
## **Information**
Minecraft version: 1.16.5
Forge version: 36.1.9
Environment: Singleplayer / Multiplayer -> BOTH

Mod name: fixedanvilrepaircost_1.16.5-1.4.jar

## **Description**
No matter how many diamonds I put into the anvil, the diamond tools/armor only gets repaired by 33.33%.

![grafik](https://user-images.githubusercontent.com/77007295/117113788-4420ed00-ad8b-11eb-9e46-9818f4196682.png)

`
[General]
	#The amount of level it costs to repair an item on an anvil. A value of 0 keeps vanilla behaviour.
	#Range: 0 ~ 100
	repairCostLevelAmount = 3
	#The amount of material it costs to repair an item on an anvil. A value of 0 keeps vanilla behaviour.
	#Range: 0 ~ 64
	repairCostMaterialAmount = 1
	#How much the item is repaired per action. By default 33.33%, so 3 of 'repairCostMaterialAmount' fully repairs any item.
	#Range: 0.0 ~ 1.0
	percentRepairedPerAction = 0.3333
`

**Comment by Zothen1973** [comment]
Anyone there?

**Comment by ricksouth** [comment]
Thanks for opening the bug report! I've tested it locally just to be sure. If you want to repair an item, you'll have to use the anvil multiple times. So it uses 1 diamond when grabbing the output stack, and you put it back on the left. The mod does not change vanilla behaviour. It works as intended I believe.
