### ISSUE TITLE
Make the Enchanting Table waterloggable

### ISSUE THREAD

**Issue by Insane96** [Serilum/.issue-tracker#57]
## **Information**
Mod name: Underwater Enchanting

## **Feature description**
That's a pretty simple idea. Since the point of the mod is enchanting underwater a small enhancement would be make the Enchanting Table waterloggable.

**Comment by ricksouth** [comment]
I did try this when I initially created the mod, I didn't manage to get it to work however. I'll keep it in mind and will give it another go in the future. Thanks for using the mod and the idea!

**Comment by ricksouth** [comment]
It seems like Forge currently does not allow overwriting vanilla blocks with different blockstates (in this case waterlogging) than the normal block. There might be a workaround for it, but I can't seem to find it right now. The lack of waterlogging mods on Forge (there's one for fabric) doesn't give much hope either.

It's still in the back of my mind but for now I'm closing the issue. Thanks for the suggestion though!
