### ISSUE TITLE
1.12.2 Nether Portal Spread Crash (Just Enough Resources)

### ISSUE THREAD

**Issue by Krutoy242** [Serilum/.issue-tracker#570]
## **Information**
Minecraft version: 1.12.2
Forge version: 14.23.5.2855
Environment: Singleplayer

Mod name: Nether Portal Spread
Mod version: 5.1

## **Description**
Executing `/jer_profile` command from mod [Just Enough Resources](https://www.curseforge.com/minecraft/mc-mods/just-enough-resources-jer) freeze game with crash log:

## **Crash report**
[crash-2021-05-12_15.30.09-server.txt](https://github.com/ricksouth/serilum-mc-mods/files/6466159/crash-2021-05-12_15.30.09-server.txt)

**Comment by ricksouth** [comment]
It seems like they simulate the world in a certain way where WorldEvent.Load is not called correctly. I can add checks for this but it would cost more processing resources for such a rare case. Unless others experience the issue more often I won't fix it. Thanks for submitting the bug report and the interest though!
