### ISSUE TITLE
incompatibility with Repurposed Structures Mod

### ISSUE THREAD

**Issue by m3dus444** [Serilum/.issue-tracker#574]
version mc 1.16.5, forge 36.1.0, random village name 1.1

Hey, i found out that the mod isn't working with repurposed structures villages (https://www.curseforge.com/minecraft/mc-mods/repurposed-structures ) 
This mod only adds variants with wood type, stone type etc, nothing more than a vanilla village. Maybe you should add all repurposed_structures : id_village getting the area panel. That could be a nice compatibility. More, i think all mods that add modded villages should be incompatible as well.
Anyway, very good mod for rpg modpacks, thanks for the code man !

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! Version 2.0 of Random Village Names, together with the latest Collective update, adds compatibility with modded villages.

https://www.curseforge.com/minecraft/mc-mods/random-village-names/files
https://www.curseforge.com/minecraft/mc-mods/collective/files
