### ISSUE TITLE
Villager Names for Plague Doctors and Hero Villagers

### ISSUE THREAD

**Issue by ScoutTheSaneless** [Serilum/.issue-tracker#575]
## **Information**
Mod name: Villager Names

## **Feature description**
On my 1.16.5 server we have installed the Rats mod, which adds a wandering trader type NPC known as the Plague Doctor. Unfortunately, Villager Names does not register it as a viable villager to rename, regardless of the fact that they can spawn in naturally within the world. Furthermore, when using the Lucky Block mod, there is a chance a Hero Villager with a custom colored and bolded name can come from one upon opening it, however, Villager Names tends to say "nope, no longer will your name have special formatting" and will convert the name to the regular non-colored/bolded text upon interacting with the poor soul. I was hoping that these issues would at least be noted for future updates to the mod!

**Comment by ricksouth** [comment]
Thanks for the suggestions! Collective v2.53 makes the Plague Doctor be named by Villager Names. I'll leave the issue open for the Hero Villager losing its name style.

https://www.curseforge.com/minecraft/mc-mods/collective/files/all

**Comment by ricksouth** [comment]
The Hero Villager losing the style of its name has been fixed in version 3.2 of Villager Names.

https://www.curseforge.com/minecraft/mc-mods/villager-names/files/all
