### ISSUE TITLE
[world border] Question about server-side vs. client-side

### ISSUE THREAD

**Issue by MitztheKat** [Serilum/.issue-tracker#576]
## **Information**
(you can remove whatever is not applicable)
Minecraft version: 1.16.5
Environment: Multiplayer

Mod name: World Border
Mod version: newest, whichever it is

## **Question**
Hello,
I am hoping to use this mod on my server's modpack - I could not find an answer to my question whether I can have the config (or even the entire mod) server-side.
I want singleplayer worlds in my modpack to be infinite but on the server I want there to be limits, and the limits to be safe to ram into with elytras :P
Just curious.
Thanks,
Mitz

**Comment by MitztheKat** [comment]
If you can get back to me soon, that'd be great; otherwise I'll be testing this myself.

**Comment by 1point7point4** [comment]
I have this same question (will test it out myself if nobody responds, though i hate retesting the wheel :').

**Comment by ricksouth** [comment]
The mod is server-side only. Thanks for the interest!
