### ISSUE TITLE
Villager Death Message CTD with Atum 2 villager death.

### ISSUE THREAD

**Issue by judicius** [Serilum/.issue-tracker#577]
## **Information**
Minecraft version: 1.16.5
Forge version: 36.1.23
Environment: Singleplayer & Multiplayer

Mod name: Villager Death Messages
Mod version: 1.8

## **Description**
Crash to desktop on Atum Villager Death

## **Crash report**
https://gist.github.com/judicius/05a370445ca80245b786e5a83bf70e65

**Comment by ricksouth** [comment]
Thanks for submitting the bug report and giving the mod a try! I've fixed it in version 2.1 of Villager Death Messages. Please let me know if you've got any other issues.

https://www.curseforge.com/minecraft/mc-mods/villager-death-messages/files/all
