### ISSUE TITLE
speed of spreading 

### ISSUE THREAD

**Issue by idos500** [Serilum/.issue-tracker#581]
Minecraft version: 1.16.5
Forge version: 1.16
Environment: Singleplayer

Mod name: nether portal spread
Mod version: x.x

how do I change the speed of nether spreading?

**Comment by James103** [comment]
From the FAQ:
> All my mods use the Forge Configuration Manager. The config files are located in your root minecraft folder in ./config/. You can edit the .toml files with any text editor, like notepad. The name of the config file starts with the mod id.

Inside the .toml file, there should be a config option `spreadDelayTicks` which you can change. From the mod's description:
> spreadDelayTicks (default = 40, min 1, max 72000): The delay in ticks in between the spread around the nether portal. 20 ticks = 1 second.

**Comment by idos500** [comment]
> From the FAQ:
> 
> > All my mods use the Forge Configuration Manager. The config files are located in your root minecraft folder in ./config/. You can edit the .toml files with any text editor, like notepad. The name of the config file starts with the mod id.
> 
> Inside the .toml file, there should be a config option `spreadDelayTicks` which you can change. From the mod's description:
> 
> > spreadDelayTicks (default = 40, min 1, max 72000): The delay in ticks in between the spread around the nether portal. 20 ticks = 1 second.

I found the config files but I dont see the mod in there.. what to do?

**Comment by ricksouth** [comment]
Check out https://github.com/ricksouth/serilum-mc-mods/wiki/How-To-Configure-mods for more detailed steps. Thanks for giving the mod a try!
