### ISSUE TITLE
Consider releasing Fabric versions of Ricksouth's mods exclusively on Modrinth

### ISSUE THREAD

**Issue by James103** [Serilum/.issue-tracker#586]
## **Information**
Mod name: (Any and all of Ricksouth's mods)

## **Feature description**
There are now two main websites that host Minecraft mods, that being Curseforge and [Modrinth](https://modrinth.com/). There are also two major mod loaders: Forge and Fabric. Curseforge mainly hosted mods for Forge for a long time, while Modrinth currently hosts mainly Fabric mods.

Would it be possible to have the Fabric versions of Ricksouth's mods be available on Modrinth (instead of Curseforge)? For example, take the mod "Realistic Bees".
1. You port the mod to Fabric.
2. You release the mod exclusively on Modrinth.
3. You create a link on the Curseforge page suggesting to visit the Modrinth page to get the Fabric version for that mod.
4. You create the reverse link to step 3 (i.e. if you're on Modrinth and want the Forge version, visit the Curseforge page).
5. Repeat steps 3-4, but linking between https://minecraft.natamus.com (Forge version) and Modrinth (Fabric version).
6. You would then repeat steps 1-5 for every mod that you want a Fabric version of.

By doing this, you would effectively have two seperate profile pages for your mods, one for Forge and one for Fabric:
* The Forge version for the mods would be collected together and listed at https://www.curseforge.com/members/serilum/projects.
* The Fabric version for the mods would be collected together and listed at `https://modrinth.com/user/serilum` (or similar).

If implemented, this would likely resolve (most if not all of) the following: #585, #582, #558, #381, #380, #346, #316, #274, #272, #271, #265, #250, #219, and #183 (i.e. most of the issues returned in search results for term `fabric`, list may be incomplete)

**Comment by ricksouth** [comment]
As most of the mods now have Fabric ports on CurseForge this isn't an issue anymore. I have however created a Modrinth account and am looking into releasing the mods on there, if there's demand for it. I appreciate the request!
