### ISSUE TITLE
Repurposed Structures compat (Random Village Names)

### ISSUE THREAD

**Issue by PlayMCwithMe** [Serilum/.issue-tracker#588]
A feature/suggestion I have is compatibility for the Repurposed Structures mod, specifically the Villages it adds (excluding the Nether ones, those are Piglins and not Villagers).
These include: Badlands Village, Birch Village, Dark Oak Village, Giant Taiga Village, Jungle Village, Mountains Village, Oak Village, and Swamp Village.

Thank you for reading, and have a nice day.

**Comment by ricksouth** [comment]
The latest Collective version adds support for modded villages. Thanks for giving the mod a try and the patience! :)

https://www.curseforge.com/minecraft/mc-mods/collective/files
