### ISSUE TITLE
Configuration Issues

### ISSUE THREAD

**Issue by mswanson23** [Serilum/.issue-tracker#59]
## **Information**
Minecraft version: 1.15.2
Forge version: 1.15.2
Environment: Singleplayer

Mod name: Just More Heads
Mod version: 1.15.2

## **Description**
Hey! So I've been playing around with the mod and discovered that the Forge config does not work. I was wondering if this was intended or if this was a bug/error on my side. Thanks!

**Comment by ricksouth** [comment]
I've tested it, and the config seems to work fine. Let me know if you need help by sending your current config file. You might've done something wrong with the format. Thanks for using the mod!
