### ISSUE TITLE
Double doors config file

### ISSUE THREAD

**Issue by El-Banqui** [Serilum/.issue-tracker#591]
## **Information**
Minecraft version: 1.16.4
Forge version: 35.1.37
Environment: Singleplayer / Multiplayer

Mod name: Doubledoors
Mod version: 2.1

## **Description**
Hello, this mod is very cool, except when you decorate with trapdoors, I tried to disable trapdoors in the config file, but I can't find it, can you send me at least the script to disable trapdoos? And i'm sorry for my english, its kinda basic
Thanks in advance

## **Crash report**
If available.

**Comment by ricksouth** [comment]
Thanks for using the mod! The config file is located in your minecraft folder in ./config called double-doors-common.
