### ISSUE TITLE
End Portal Spread

### ISSUE THREAD

**Issue by Jollyolsport** [Serilum/.issue-tracker#598]
Minecraft version: 1.16.5
Forge version: 36.1.24
Environment: Singleplayer 

Mod name: Better End Forge
Mod version: 1.16.4-1.6.0
Mod name: Nether Portal Spread
Mod version: 1.16.5-5.1

## **Description**
The Better End's end portal is treated as a nether portal in regards to spread.

**Comment by ricksouth** [comment]
Thank you for opening the issue and giving the mod a try! This has been fixed in version 8.0 of Nether Portal Spread. Apologies it took so long for me to get to.

https://curseforge.com/minecraft/mc-mods/nether-portal-spread/files
