### ISSUE TITLE
Compatibility with Biomes O' Plenty

### ISSUE THREAD

**Issue by MrTuna13** [Serilum/.issue-tracker#599]
## **Information**
Mod name: Random Village Names

## **Feature description**
Please add village names to the villages from BoP.

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! Version 2.0 of Random Village Names, together with the latest Collective update, adds compatibility with modded villages.

https://www.curseforge.com/minecraft/mc-mods/random-village-names/files
https://www.curseforge.com/minecraft/mc-mods/collective/files
