### ISSUE TITLE
Flowers spawning 

### ISSUE THREAD

**Issue by Pscx1** [Serilum/.issue-tracker#6]
## **Information**
Minecraft version: 1.12.2
Forge version: 1.12.2-forge1.12.2-14.23.5.2846
Environment: Singleplayer

Mod name: Random Bone Meal Flower
Mod version: 1.0

## **Description**
Hi,
Flowers spawning not working correctly as mod desc says.
Im using FutureMC mod for flowers from future version (lol)
and it spawns only 10 types of flowers

**Comment by ricksouth** [comment]
Hi! Thanks for letting me know. The 1.1 version of the mod Random Bone Meal Flowers now also spawns any modded flowers, starting from version Minecraft 1.14+.
