### ISSUE TITLE
[1.14.4] Zombie horse spawn crashes server

### ISSUE THREAD

**Issue by sekelsta** [Serilum/.issue-tracker#60]
## **Information**
Minecraft version:1.14.4
Forge version: 28.2.0
Environment: Singleplayer / Multiplayer - Both

Mod name: Zombie Horse Spawn
Mod version: 2.1.2

## **Description**
Occasional server crash.
Create a world with seed 2158136203916531227, might as well be creative mode
Teleport to 450 70 550, then head in the general direction of 606 70 407
At some point chunks stop being loaded, items don't let you pick them up, and trying to throw an item will decrease the stack count but not make the item appear in the world

(Trying to spawn an entity in an unloaded chunk in 1.14 can cause this sort of behavior.)

## **Crash report**
No crash report.

**Comment by clarence112** [comment]
Also happens on 1.15

**Comment by ricksouth** [comment]
This has been fixed in the latest release. Thanks for submitting the issue and using the mod!

[https://www.curseforge.com/minecraft/mc-mods/zombie-horse-spawn](https://www.curseforge.com/minecraft/mc-mods/zombie-horse-spawn)
