### ISSUE TITLE
Teleportation 

### ISSUE THREAD

**Issue by gavel-2** [Serilum/.issue-tracker#600]
Is this mod meant to let you teleport with the compass? Because I don't see anything in the description that says that, and that doesn't seem too vanilla either, but I don't have any mods that change the compass other than this.

**Comment by James103** [comment]
Which mod are you referring to?

**Comment by gavel-2** [comment]
> Which mod are you referring to?

GUI Compass

**Comment by gaforb** [comment]
Nothing to do with GUI Compass - WorldEdit adds this feature to the compass for operators
