### ISSUE TITLE
Stack Refill - Right clicking planks puts an axe into the shield hand

### ISSUE THREAD

**Issue by TheIrishStud** [Serilum/.issue-tracker#605]
Does exactly as it says it does. Been trying to find that special world spawn with the same 100 mods for a while now and I didn't notice until this past week though but if you right click a plank with an axe in your hand, along with a 2nd axe in your inventory, the 2nd axe in your inventory gets put into your shield hand. I haven't crashed or anything while using Stack Refill and haven't noticed anything off besides this minor bug that's mildly inconvenient to experience at the start of every new world. Removing Stack Refill fixes the issue but I'm continuing to use Stack Refill anyway because it's extremely useful. - Version 1.16.5 - Forge 36.1.0 - I hope this helps! ^_^

**Comment by TheIrishStud** [comment]
Addition bug update. right clicking planks also causes a 2nd shovel to be added to the shield hand. Haven't tried or yet to have notice the same bug with the other tools.

**Comment by ricksouth** [comment]
Thanks for submitting the bug report and the description on how to duplicate it! I've fixed it in version 2.0 of Stack Refill. :)

https://www.curseforge.com/minecraft/mc-mods/stack-refill/files/all
