### ISSUE TITLE
Healing Campfire suggestions..

### ISSUE THREAD

**Issue by Milliath** [Serilum/.issue-tracker#61]
## **Information**
Mod name: Healing Campfire

## **Feature description**
1) Make the regeneration level configurable;
2) Add other effects with config for on/off and level?

**Comment by ricksouth** [comment]
I'd like to keep the mod regeneration only, as the name suggests. But I've added a config option to set the level of regeneration applied, just released version 2.3. Thanks for the idea!

[https://www.curseforge.com/minecraft/mc-mods/healing-campfire](https://www.curseforge.com/minecraft/mc-mods/healing-campfire)
