### ISSUE TITLE
Incompatibility with quark

### ISSUE THREAD

**Issue by xelotex** [Serilum/.issue-tracker#611]
## **Information**
Minecraft version: 1.16.5
Forge version: 36.1.0.
Environment: Single player 

Mod name: fixed anvil repair Mod
Mod version: 1.4.

## **Description**
Hey! Combining Quark with your mod, will make a crash on startup.

## **Crash report**
If available.

**Comment by James103** [comment]
Do you have the crash report and/or logs? If so, can you please post them here?

**Comment by xelotex** [comment]
> Do you have the crash report and/or logs? If so, can you please post them here?

damn, sorry bro i figure it out that this is my fault not yours, i'm having a weird error with the game, if i try to load 98 mods my game crashes, doesn't matter what mod is the game will crash anyway, and it won't leave any crash logs or something, i try to add more ram but that didn't work, so that confused me and make me thought your mod was incompatible with quark.
