### ISSUE TITLE
Configurable Extra Mob Drops issue with named item

### ISSUE THREAD

**Issue by Xiaolin2-g** [Serilum/.issue-tracker#614]
## **Information**
Minecraft version: 1.16.5
Forge version: 36.1.32
Environment: Singleplayer

Mod name: Configurable Extra Mob Drops
Mod version: 1.6

## **Description**
I'm making a modpack, and using Thermal's Coins as currency for my shop.
So for encouraging combat, I used this mod to make mobs drop coins at different chances, but after reloading the world, the new dropped coins change name. (Before reloading it has the right name).

Intended name:
![image](https://user-images.githubusercontent.com/79189625/124899413-7aaafc00-dfb6-11eb-839e-994fc67c2d19.png)

Name the newly dropped coins after reloading have:
![image](https://user-images.githubusercontent.com/79189625/124899476-8b5b7200-dfb6-11eb-8066-c218e4e468d1.png)

In the config file, it is the correct name:
![image](https://user-images.githubusercontent.com/79189625/124899976-0755ba00-dfb7-11eb-8c44-c89fe0699010.png)

It has to be a special problem with the symbol "¢", I hope there is a solution. It is not much of a difference of a name, but the problem is they don't stack with coins obtained by quests or the shop.

**Comment by ricksouth** [comment]
Apologies for the late fix, but version 1.7 should solve the issues you were having. Thanks for giving the mod a try and submitting the bug report!

https://www.curseforge.com/minecraft/mc-mods/configurable-extra-mob-drops/files
