### ISSUE TITLE
Crash during world gen

### ISSUE THREAD

**Issue by InteJason** [Serilum/.issue-tracker#615]
Mod: Collective
Version: collective-1.16.5-2.26.jar
Crash report: https://paste.ee/p/hA5Ar

To be specific, the crash happens when running around and loading new chunks.

**Comment by James103** [comment]
Copied paste to crash log file as the paste has an expiration date.
[Server crash log](https://github.com/ricksouth/serilum-mc-mods/files/6797639/Server.crash.log.txt)

**Comment by ricksouth** [comment]
This has been fixed in version 2.46 of Collective. Thanks for submitting the bug report!

https://www.curseforge.com/minecraft/mc-mods/collective/files
