### ISSUE TITLE
The Signs I Create don't Work

### ISSUE THREAD

**Issue by Balephor** [Serilum/.issue-tracker#617]
Minecraft version: 1.16.5
Forge version: Mohist-1.16.5-677
Environment: Multiplayer Server

Mod name: Areas
Mod version: 2.3

I installed both the mod and collective. They seem to work fine, /areas worked, but any area-sign i create cannot be detected by the mod.
The sign was a oak vanilla sign, i tried reinstalling both mods but nothing worked.

No crashes

**Comment by ricksouth** [comment]
Thanks for submitting the issue! I've fixed it in version 2.4, please let me know if you're still experiencing problems after updating.

https://www.curseforge.com/minecraft/mc-mods/areas
