### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ABlackPikatchu** [Serilum/.issue-tracker#618]
Minecraft version: 1.16.5
Forge version: 36.1.30
Environment: Singleplayer / Multiplayer

mod: Configurable Extra Mob Drops

Will this work to make a loot table for an item you right click? like say a lootbag?

**Comment by ricksouth** [comment]
You can add another mod with lootbags and have Configurable Extra Mob Drops drop them on an entities death. Let me know if it doesn't work so I can check the functionality. Thanks for opening the issue!
