### ISSUE TITLE
[Suggestion]Add a config option to restrict mobs head to player kills only

### ISSUE THREAD

**Issue by jinkhya** [Serilum/.issue-tracker#619]
## **Information**
Mod name: Just Mob Heads

## **Feature description**
Hello,
Could it be possible to add a config to only get the heads when the mobs are killed by a player?
Thanks in advance,
Jin

**Comment by ricksouth** [comment]
Apologies for the late response. I've added the config option **onlyDropHeadsByPlayerKill** in version 5.0 of Just Mob Heads, which should work how you want it. Thanks for giving the mod a try and submitting the idea!

https://www.curseforge.com/minecraft/mc-mods/just-mob-heads/files/all

**Comment by jinkhya** [comment]
Awesome ty !! 👍
