### ISSUE TITLE
Portals don't check for all obsidian

### ISSUE THREAD

**Issue by KingDnds** [Serilum/.issue-tracker#62]
## **Information**
Minecraft version: 1.15.2
Forge version: 31.1.25
Environment: Singleplayer

Mod name: Smaller Nether Portals
Mod version: smallernp_1.15.2-1.1

## **Description**
Portals can be created even if there isn't obsidian all the way around.
![Capture2](https://user-images.githubusercontent.com/58410172/78405275-03b5d500-75b5-11ea-8191-b735b2da675c.PNG)
![Capture](https://user-images.githubusercontent.com/58410172/78405276-044e6b80-75b5-11ea-8333-21d294d02c11.PNG)

**Comment by ricksouth** [comment]
Well found! I've fixed it in version 1.2 of the mod alongside with some other minor improvements. Thanks for letting me know and using the mod!

[https://www.curseforge.com/minecraft/mc-mods/smaller-nether-portals](https://www.curseforge.com/minecraft/mc-mods/smaller-nether-portals)
