### ISSUE TITLE
Villager Names For Evil Wandering Trader

### ISSUE THREAD

**Issue by huyhhuy1410** [Serilum/.issue-tracker#620]
## **Information**
Mod name: Village Names

## **Feature description**
Could you add custom names for the Traders of "Evil Wandering Trader" mod.
Thank you !

**Comment by ricksouth** [comment]
Collective v2.53 makes the Plague Doctor be named by Villager Names. Thanks for the suggestion!

https://www.curseforge.com/minecraft/mc-mods/collective/files/all
https://www.curseforge.com/minecraft/mc-mods/villager-names

**Comment by ricksouth** [comment]
Collective v2.53 makes the Evil Wanderer Trader be named by Villager Names. Thanks for the suggestion!

https://www.curseforge.com/minecraft/mc-mods/collective/files/all
https://www.curseforge.com/minecraft/mc-mods/villager-names

**Comment by huyhhuy1410** [comment]
Thank you so much

**Comment by huyhhuy1410** [comment]
I still see the their default names when i spawn them from eggs. Do i need to meet them when they naturally spawn for a custom names ?
