### ISSUE TITLE
Area signs not making areas, neither being registered by /areas

### ISSUE THREAD

**Issue by Catomax262** [Serilum/.issue-tracker#621]
## **Information**
Minecraft version: 1.16.5
Forge version: 36.1.32
Environment: Singleplayer

Mod name: Areas
Mod version: 2.3

## **Description**
I have made a sign, and i entered the correct text for it to be an area. But it somehow isn't registering. Might be Quark.

**Comment by James103** [comment]
Can you please try again with a vanilla sign crafted with e.g. oak, spruce, birch, acacia, or jungle planks?

**Comment by Catomax262** [comment]
Either way it doesn't work.

**Comment by Catomax262** [comment]
I specifically tried with an oak sign.

**Comment by ricksouth** [comment]
Thanks for submitting the issue! I've fixed it in version 2.4, please let me know if you're still experiencing problems after updating.

https://www.curseforge.com/minecraft/mc-mods/areas
