### ISSUE TITLE
Wither Skeleton Skulls Not Dropping

### ISSUE THREAD

**Issue by felicitywolf** [Serilum/.issue-tracker#622]
## **Information**
Minecraft version: 1.16.5
Forge version: 36.1.24
Environment: Multiplayer

Mod name: Just Mob Heads
Mod version: 4.0

## **Description**
So I have tried everything to fix it and can't find what is causing it. I have mobSpecificDropChances and enableStandardHeads set to true, but I get no wither skeleton skulls even with a looting III sword. I would also like to note the server provider I am using is called Aternos.

**Comment by James103** [comment]
1. Can you please try again on a seperate test world hosted by your client's integrated server?
2. Run the command `/give @p netherite_sword{Enchantments: [{id: "minecraft:looting", lvl: 255}]}`, then use the sword obtained to kill a vanilla wither skeleton. Do you get any wither skeleton skulls?
3. Add a `wither_skeleton` line with a value of `1` to your Minecraft instance's `./config/justmobheads/headchances.txt` file, run `/jmh reload`, then repeat step 2 a few more times. Do you get any wither skeleton skills?

Note that it could be just bad luck you're having with this, hence the above steps.

**Comment by ricksouth** [comment]
Just Mob Heads does not change the Wither Skeleton's head, because it already has a separate drop function. Though Always a Wither Skull might do what you want: https://www.curseforge.com/minecraft/mc-mods/always-a-wither-skull

Thanks for giving the mod a try!
