### ISSUE TITLE
Drowned Spawning

### ISSUE THREAD

**Issue by RandomUser73** [Serilum/.issue-tracker#623]
## **Information**
Minecraft version: 1.16.5
Forge version: 36.1.0
Environment: Singleplayer / Multiplayer

Mod name: Conduits Prevent Drowned
Mod version: 1.3

## **Description**
Is not working.

![2021-07-19_21 55 48](https://user-images.githubusercontent.com/87681741/126251436-b78b34c3-4b4a-4cae-bc05-d2309e984ad0.png)
In the image you can see two drowned that spawned several blocks away from a conduit. The conduit is active, as can be seen by the effect on me.
I've replicated the effect by flying in creative mode up to height 176 to despawn all mobs below ground, increasing chances of mobs spawning in the water. When I come back down there are typically two or more drowned under the boat or in the river behind me. Drowned do not spawn in the larger ocean body of water because it's a warm ocean which already deactivates their spawns.

Configuration range is set to 200

**Comment by ricksouth** [comment]
I couldn't replicate your issue locally, but I think it might have been spawned just outside of the maximum config range. I've set the max possible value to 400, which should hopefully fix the issue you were having. But please let me know if the issue persists.

Config value changed in version 1.4 of Conduits Prevent Drowned.

https://www.curseforge.com/minecraft/mc-mods/conduits-prevent-drowned/files
