### ISSUE TITLE
Mod bug

### ISSUE THREAD

**Issue by Gamersofty** [Serilum/.issue-tracker#624]
![Screenshot_2](https://user-images.githubusercontent.com/87708300/126334071-99c6cb21-ed17-4eba-8e44-4636232dd8f2.png)
Minecraft version: 1.16.5
Forge version: 36.1.65
Environment: Singleplayer

Mod name: Infinite Trading
Mod version: 1.5

## **Description**
when I try to use the mod, it doesn't work, it's still locking the trade

**Comment by James103** [comment]
Can you try enabling cheats ("Open to LAN" -> "Enable Cheats: On") and running the command `/data get entity @e[type=villager, limit=1, sort=nearest]`? Post the resulting output here.

**Comment by ricksouth** [comment]
This has been fixed in version 1.9 of Infinite Trading. Thanks for submitting the bug report!

https://www.curseforge.com/minecraft/mc-mods/infinite-trading/files/all
