### ISSUE TITLE
Consumes 3 block when placing

### ISSUE THREAD

**Issue by LoudShriek** [Serilum/.issue-tracker#627]
## **Information**
Minecraft version: 1.16.5
Forge version: 36.1.18
Environment: Singleplayer and Multiplayer

Mod name: Better Beacon Placement
Mod version: 1.4

## **Description**
Hey! It consumes 3 blocks when placing. When u have 3 more it still not placing it the correct way. There is no difference between shift right and only right click, either way u lose 3 blocks.

**Comment by ricksouth** [comment]
I can't replicate this issue locally. Could you tell me the steps to  or do you have screenshots/GIFs?
