### ISSUE TITLE
Areas 2.3 doesn't work

### ISSUE THREAD

**Issue by SunnyMenkov** [Serilum/.issue-tracker#628]
## **Information**
Minecraft version: 1.16.5
Forge version: 36.1.32
Environment: Singleplayer and Multiplayer

Mod name: Areas
Mod version: 2.3

## **Description**
Areas mod does not work on version 2.3 in singleplayer or multiplayer.
Command /areas can't detect any areas and i don't get the join/leave message.
Works perfectly on 2.2 version of the mod.

**Comment by ricksouth** [comment]
Thanks for submitting the issue! I've fixed it in version 2.4, please let me know if you're still experiencing problems after updating.

https://www.curseforge.com/minecraft/mc-mods/areas
