### ISSUE TITLE
How come you got rid of the 1.12.2 version of Giant Spawn?

### ISSUE THREAD

**Issue by SpencerMeow** [Serilum/.issue-tracker#629]
I was looking forward to using Giant Spawn in my modpack but you removed the version from Curseforge, is there a reason it can't stay there?

**Comment by James103** [comment]
See: #458

**Comment by ricksouth** [comment]
The 1.12.2 Giants were unable to receive the zombie AI via the way i did it in 1.14+. For now I won't be releasing a 1.12 version. Thanks for the interest though!
