### ISSUE TITLE
Change nether portal spread into mod blocks

### ISSUE THREAD

**Issue by seanimusprime** [Serilum/.issue-tracker#63]
## **Information**
Minecraft version: 1.15.2
Environment: Singleplayer / Multiplayer

Mod name: Nether Portal Spread

## **Question**
Can we change the spread to change blocks into blocks from mods (ie stone into Soulstone from Mystical Agriculture)?

**Comment by ricksouth** [comment]
Sorry for the late reaction, but yes you can! The format works like modid:blockid. Example with Soulstone from Mystical Agriculture:

<img width="366" alt="notepad_file" src="https://user-images.githubusercontent.com/38502394/82143073-7b785000-9841-11ea-851e-cebf9f196e95.png">

![2020-05-17_13 21 02](https://user-images.githubusercontent.com/38502394/82143074-7d421380-9841-11ea-88e2-76af2d43c391.png)

**Comment by ricksouth** [comment]
I've also added it to the description of the mod:
[https://www.curseforge.com/minecraft/mc-mods/nether-portal-spread](https://www.curseforge.com/minecraft/mc-mods/nether-portal-spread)
