### ISSUE TITLE
Mods not work

### ISSUE THREAD

**Issue by huyhhuy1410** [Serilum/.issue-tracker#632]
## **Information**
Minecraft version: 1.16.5
Forge version:  1.16.5-36.2.0
Environment: Singleplayer and Multiplayer

Mod name: Areas, Random Village Names
Mod version: 
areas_1.16.5-2.3
randomvillagenames_1.16.5-1.2

## **Description**
I don't know why mods not work anymore,there is no area in my single player or multiplayer, when i come to many villages, there no area apears, and when i use sign to make area, it not worked, type /areas and nothing happens. Please help !
![image](https://user-images.githubusercontent.com/86774570/127136552-3a113ae7-1b9f-4d63-be16-0d0131284ec0.png)

**Comment by ricksouth** [comment]
For now please downgrade to areas_1.16.5-2.2.jar, version 2.2. Something went wrong when updating to the new mojang mappings. Thanks for submitting the bug report!

**Comment by ricksouth** [comment]
I've fixed it in version 2.4, please let me know if you're still experiencing problems after updating.

https://www.curseforge.com/minecraft/mc-mods/areas

**Comment by huyhhuy1410** [comment]
It works fine. Thank so much. But i have small thing wanna ask you. When i created a sign and check it by command, it works, but when i enter and leave the area i created, it's not show up the HUD. it only show up when i enter/leave the villages.

**Comment by ricksouth** [comment]
Can you show me a screenshot of your sign?

**Comment by huyhhuy1410** [comment]
![image](https://user-images.githubusercontent.com/86774570/127767104-80351f57-e7e5-4aa2-ba54-0846e9675df6.png)
Here

**Comment by James103** [comment]
Can you try re-uploading the screenshot? The original upload didn't complete successfully.

**Comment by huyhhuy1410** [comment]
I re-uploaded the screenshot

**Comment by ricksouth** [comment]
Do you have the mod installed on your client? Can you send another screenshot of the village sign?

**Comment by huyhhuy1410** [comment]
Yes, i have on both client and server.
Here is the village:
![image](https://user-images.githubusercontent.com/86774570/127769350-fed15057-e73f-4abd-8583-89c6e5589d57.png)
![image](https://user-images.githubusercontent.com/86774570/127769358-58ba9cd9-99d7-4c3c-b7dc-d8c4c6b7d081.png)
![image](https://user-images.githubusercontent.com/86774570/127769365-ea690fa2-13ac-4461-ad19-71b2036f9afe.png)

**Comment by ricksouth** [comment]
I can't replicate your issue. It's also strange that /areas does pick up the sign, and it not showing in the GUI.

If you create a new world, place an areas sign there. Does it work?
Does it matter if you use any of the other prefixes? "[na]", "[area]", "[region]", "[zone]"

**Comment by ricksouth** [comment]
I've just released version 2.7 of Areas. Hopefully that fixes the issue you were having!

https://www.curseforge.com/minecraft/mc-mods/areas/files/all

**Comment by huyhhuy1410** [comment]
Ok, so i tested with forge server and it works perfectly, maybe it's the issue mohist-side. I will try to ask them for help. 
Thanks a lot !
