### ISSUE TITLE
Outdated Data Pack (just a Comment, not a Bug Report/Error Report)

### ISSUE THREAD

**Issue by Coraline77447** [Serilum/.issue-tracker#634]
Minecraft version: 1.17.1
Forge version: 37.0.10*
Environment: Singleplayer

Mod name: Collective
Mod version: from 1.17.1-2.29 to latest

I just want to inform you that your mods data packs are outdated, so could you please update your mods pack.mcmeta file? 
They're out of date as of their pack formatting number since minecraft's vanilla data pack for 1.17 requires pack format of 7 not 6.
I had to manually change your mods pack formatting number from a 6 to a 7 and I'll have to do so again with the latest version for Collective 1.17, which isn't my responsibility to make that change in your mods using 7Zip file manager.
Don't worry, the only changes I've made to them was their pack.mcmeta file as of the pack formatting number, nothing else in your mods was toughed, ok?
Again that change is NOT my responsibility to make and I don't like to manually changing a mod's pack formatting number from an outdated number to the latest number myself just for me to continue to play with your mods or any mods in general.
If you've already changed your mods pack formatting numbers to 7 already then you can simply ignore this comment entirely.

As what the title says that this really isn't a bug report or a error report either since the game hasn't crashed on me when I was in my first modded 1.17.1 world.
When that modded world was created I was able to load in apoun creation and everything was fine, but when I tried to load back into it for a second play session basically the next day I couldn't load into it anymore cause most of the mods that I play with (including your mods) and forge itself had or has outdated data packs.

How I've managed to figure out about this is when you create a new world and select the data packs menu, in there you can see all of your mods resource packs aka their data packs but they're all red which means they're outdated and needs to be updated....

(*The devs of forge may have released new version(s) of forge for 1.17.1 already, so 37.0.10 maybe an older version of forge 1.17.1 now.)

**Comment by ricksouth** [comment]
Thanks for letting me know! Saves me some time. I'll release updated versions for the mods.

I did check when the MDK was first released, but I suppose that was a bug on Forge's part.

**Comment by ricksouth** [comment]
I've uploaded a new version for all 1.17.1 mods, and other uploads will have it correct too. Thanks for letting me know!

**Comment by Coraline77447** [comment]
Your welcome, liking Villager Death Messages and your other mods btw! :)

Love the fact that Villager Death Messages letting me know where the guard villagers (from Guard Villagers mod) have died at to get their stuff.
Even tho most of the time when they do die and the death messages pop up I would be busy with something else.
I would have a hard time figuring out the coordinates of their death locations by the time I do go look for their "bodies". 
That's my own problem on my end as of myself (poor memory).
