### ISSUE TITLE
Grass Seeds dependency issue with Collective

### ISSUE THREAD

**Issue by chimericdream** [Serilum/.issue-tracker#635]
## **Information**
Minecraft version: 1.16.5

Mod name: Grass Seeds
Mod version: 1.6

## **Description**
The 1.16.5-1.6 version of the mod says that it depends on 2.36 of Collective. However, Collective 2.36 is 1.17 only.

**Comment by ricksouth** [comment]
Thanks for letting me know! I've released 2.38 of Collective which will work with the new Grass Seeds update.

https://www.curseforge.com/minecraft/mc-mods/collective
