### ISSUE TITLE
Nearby flowers break after harvesting tree

### ISSUE THREAD

**Issue by jengendler** [Serilum/.issue-tracker#639]
## **Information**
Minecraft version: 1.16.5
Forge version: 36.1.0
Environment: Singleplayer

Mod name: Tree Harvester
Mod version: 2.5

## **Description**
After chopping the bottom block of a tree with Tree Harvester, any flowers and grass within close proximity break when the tree leaves break. Doesn't seem to be intended behavior, as it should just instant break the leaves. Being in a flower forest, this issue is fairly annoying in terms of inventory management / flower re-planting.

Hopefully this is something that can be addressed. My current workaround is to use FTB Ultimine to chop trees when flowers and grass are nearby.

## **Crash report**
None.

**Comment by ricksouth** [comment]
Thanks for submitting the bug report! This has been fixed in Tree Harvester version 2.8.

https://www.curseforge.com/minecraft/mc-mods/tree-harvester/files
