### ISSUE TITLE
Great mod! Why update to 1.17?

### ISSUE THREAD

**Issue by Kasprenius** [Serilum/.issue-tracker#641]
I really want to use basically AAAALLLLLLL of your mods and was excited to see you update them to 1.17! But they aren't using the new mod format :/ I don't know how to make mods, but is that something you could do? For at least the Elytra take off one its so cool ;-; (Reason is that I use them on the 1.18 snapshot XD )

**Comment by ricksouth** [comment]
Thanks for the interest! My mods use the Forge framework to build mods upon. Forge has just been released for 1.17.1 which is why I've updated the mods to that version. If you want to use them in 1.18 you'll have to wait for the full release unfortunately.

-Rick
