### ISSUE TITLE
Crash at startup

### ISSUE THREAD

**Issue by agentwolf88** [Serilum/.issue-tracker#642]
## **Information**
Minecraft version: 1.16.5
Forge version: 36.2.2 / 36.2.0

Mod name: Areas
Mod version: 2.5

## **Description**
Crash at startup

## **Crash report**
[crash-2021-07-31_20.02.56-fml.txt](https://github.com/ricksouth/serilum-mc-mods/files/6911773/crash-2021-07-31_20.02.56-fml.txt)

**Comment by ricksouth** [comment]
Thanks for submitting the bug report, I appreciate it! I've fixed it in version 2.6 of Areas.

https://www.curseforge.com/minecraft/mc-mods/areas/files
