### ISSUE TITLE
Not compatibility with The Abyss 2

### ISSUE THREAD

**Issue by huyhhuy1410** [Serilum/.issue-tracker#643]
## **Information**
Minecraft version: 1.16.5
Forge version: 1.16.5-36.2.0
Environment: Multiplayer

Mod name: Villager Names
Mod version: villagernames_1.16.5-3.0
## **Description**
This mod is not compatibility with The Abyss 2 mod. When i enter the abyss portal, the server crash. I have searched and found many people with similar problems. Someone said to remove Villager Names mod, so i followed and it worked. The abyss mod have many NPC and entities with custom names. So i think Your mod and it have some issue that i don't know. Could you confirm and fix this ? Both mods are awesome. And i don't want to remove one of them. :(
I know i'm using mohist. But i found out many people have same issue. So i don't think it's mohist.
Thank you ! 

Here is the link of the mod:
https://www.curseforge.com/minecraft/mc-mods/the-abyss-chapter-ii

## **Crash report**
https://haste.mohistmc.com/bixevutihi.rb

**Comment by ricksouth** [comment]
Thanks for submitting the bug report! I've made some changes to the function that determines an entity's string, and this issue should be resolved in Collective version 2.49. I've tested it myself in 1.16.5 with the new version and Abyss 2, but please let me know if you still have any issues.

https://www.curseforge.com/minecraft/mc-mods/collective/files

**Comment by huyhhuy1410** [comment]
I think it is working perfectly. I downloaded the lastest collective and i added the villager names mod again and it's not crash anymore. 
Thank you so much !

**Comment by ricksouth** [comment]
Great! :)
