### ISSUE TITLE
I cant seem to get the mods to work as advertised ._.

### ISSUE THREAD

**Issue by WillouwCode** [Serilum/.issue-tracker#645]
## **Information**
(you can remove whatever is not applicable)
Minecraft version: 1.17.1
Forge version: 1.17.1-37.0.19
Environment: Multiplayer

Mod name: Areas 
Mod version: areas_1.17.1-2.6

## **Question**
Is there any special character that should be added to the [Area] 80 to have it work? its not actually naming nor does it pick up with /areas. I am using randomvillagenames_1.17.1-1.3 as well.

Mod name: villagernames
Mod version: villagernames_1.17.1-3.1

## **Question**
Does this only work on newly spawned villagers ? Ive seen it work on newly spawned ones but not on existing employed ones.

**Comment by ricksouth** [comment]
Can you give version 2.7 of Areas I've just released a try? If the problem remains please open another issue, and I'll have to do some more investigation. It works on my tests.

https://www.curseforge.com/minecraft/mc-mods/areas/files/all
