### ISSUE TITLE
Not Stopping Spawns

### ISSUE THREAD

**Issue by jpallen126** [Serilum/.issue-tracker#647]
## **Information**
Minecraft version: 1.17.1
Forge version: 37.0.22
Environment: Singleplayer 

Mod name: Better Spawner Control
Mod version: 1.4

## **Description**
Hey, I was testing some mods for my multiplayer world in single player and I couldn't get Better Spawner Control to work. You can see the blaze on the left had just spawned even though all five torches were placed. Was also tested with skeletons. Thanks for any help!

![2021-08-05_02 18 42](https://user-images.githubusercontent.com/77466083/128300992-a0f78ed5-c68b-4490-85a4-359cec9ad8f3.png)
![2021-08-05_02 26 17](https://user-images.githubusercontent.com/77466083/128301884-410777f0-d7ec-487f-9302-bb2131eea170.png)

**Comment by jpallen126** [comment]
Also Tested with Forge 37.0.25

**Comment by ricksouth** [comment]
Thanks for opening the bug report and giving the mod a try! I've fixed it in version 1.5 of Better Spawner Control.

https://www.curseforge.com/minecraft/mc-mods/better-spawner-control/files/all

**Comment by jpallen126** [comment]
Awesome! Appreciate it. Hoping to see a 1.17.1 build soon as well!

**Comment by ricksouth** [comment]
The future is now! ;)

https://www.curseforge.com/minecraft/mc-mods/better-spawner-control/files/3417019
