### ISSUE TITLE
enhancement

### ISSUE THREAD

**Issue by closeshot** [Serilum/.issue-tracker#65]
## **Information**
Mod name: double doors

## **Feature description**
Was wondering would you be able to make this compatible with double doors so both doors open and close would be amazing, for version 1.15.2

**Comment by ricksouth** [comment]
Check out version 2.0, I've added many features. Is that what you meant?

[https://www.curseforge.com/minecraft/mc-mods/double-doors](https://www.curseforge.com/minecraft/mc-mods/double-doors)
