### ISSUE TITLE
Thank you for bundling most of your mods together.

### ISSUE THREAD

**Issue by AbsorbingSafe11** [Serilum/.issue-tracker#651]
## **Information**
I always like using your mods but trying to find them all in the CurseForge app is always lesson in patience, this will save me actually hours when I am making modpacks for my own personal use. (Just for me to play in Survival Single Player)

Mod name: The Vanilla Experience (mod)
Mod version: All

## **Comment**
If possible a list of not included mods, of yours, not included in the mod would be helpful.

**Comment by ricksouth** [comment]
Glad you like it! And thanks for using some of the mods :)

The mods not included are:

Altered Damage
Configurable Extra Mob Drops
Configurable Mob Potion Effects
Difficulty Lock
Entity Information
Full Brightness Toggle
Healing Soup
Hidden Recipe Book
Humbling Bundle
Placeable Blaze Rods
Player Death Kick
Player Tracking Compass
Player Tracking
Random Mob Effects
Respawn Delay
Save and Load Inventories
Set World Spawn Point
Silence Mobs
Trample Everything
Vote Command
World Border
