### ISSUE TITLE
[Bug] Multiple bees spawn when using bottle of bees

### ISSUE THREAD

**Issue by GeorgeOrwell1** [Serilum/.issue-tracker#657]
## **Information**
Minecraft version: 1.16.5
Forge version: 36.2.2
Environment: _Singleplayer_ and _Multiplayer_

Mod name: The Vanilla Experience / Realistic Bees
Mod version: 1.3

## **Description**
When emptying/using a bottle of bees from the Buzzier Bees mod, instead of just spawning one bee, if I have Realistic Bees (via TVE) installed it spawns about five of them. This happens in both creative mode and survival mode. See video for visualization:

https://user-images.githubusercontent.com/72312697/128629336-09a2b334-13d3-4869-8d69-77d1b47decbc.mp4

_Edit: This also happens when summoning bees either by a command or via a spawn egg._

**Comment by James103** [comment]
Does the same occur if using a spawn egg to spawn bees? In other words, does using a bee spawn egg spawn 5 bees instead of the expected 1?

**Comment by GeorgeOrwell1** [comment]
> 
> 
> Does the same occur if using a spawn egg to spawn bees? In other words, does using a bee spawn egg spawn 5 bees instead of the expected 1?

Yes; if I use a spawn egg, I also spawn five bees instead of one.

**Comment by James103** [comment]
Can you please try running the following command? `/summon bee`
How many bees do you get (1 as expected, or 5)?

**Comment by GeorgeOrwell1** [comment]
I currently don't have access to my computer, will test when I come home.

**Comment by GeorgeOrwell1** [comment]
Yes, this also happens when using the `/summon` command.

**Comment by James103** [comment]
Can you please try running this command instead?
`/summon minecraft:bee ~ ~ ~ {Tags:["realisticbees.ignorebee"]}`
Do you still get 5 bees, or is it 1 bee this time?

**Comment by GeorgeOrwell1** [comment]
When using that command I only summon one bee.

**Comment by James103** [comment]
Response from linked issue from @bageldotjpg:
> This seems like something that should be fixed on Realistic Bees' end, because it could cause issues for just about any mod that spawns bees for something. Realistic Bees should instead check the SpawnReason when a bee is spawned to make sure it is natural rather than duplicating all bee spawns.

In other words, only if the bee was spawned because of `SpawnReason.CHUNK_GENERATION` or `SpawnReason.NATURAL` should Realistic Bees duplicate the spawned bee.

**Comment by ricksouth** [comment]
Thanks for submitting the bug report and using the mod! This has been fixed in version 2.0 of Realistic Bees. It now prevents multiple mob spawns when a player is within a 5 block radius of the spawn. This will fix breeding and the bottle of bees.

I couldn't use SpawnReason because it's not fired for bee spawns. But this should fix the problem you were having!

Oh and also-- tiny bees have been added.

https://www.curseforge.com/minecraft/mc-mods/realistic-bees
