### ISSUE TITLE
Tree Harvester Crashing Server

### ISSUE THREAD

**Issue by uwuscutely** [Serilum/.issue-tracker#658]
## **Information**
Minecraft version: 1.12.2
Forge version: 1.12.2 - 14.23.5.2855
Environment: Multiplayer

Mod name: Tree Harvester 
Mod version: 1.12.2-2.8

## **Description**
My server crashed with this crash report, not sure why

## **Crash report**
https://bin.bloom.host/ipipolomec

**Comment by James103** [comment]
Are you able to reproduce this crash?

**Comment by uwuscutely** [comment]
> Are you able to reproduce this crash?

Yes, the server has not successfully started once. It just keeps repeatedly crashing

**Comment by ricksouth** [comment]
Thanks for submitting the bug report! Version 2.9 should solve the issue you were having.

https://www.curseforge.com/minecraft/mc-mods/tree-harvester/files/all
