### ISSUE TITLE
Typo in README.md ("an 1.12.2" instead of "a 1.12.2")

### ISSUE THREAD

**Issue by James103** [Serilum/.issue-tracker#659]
## **Information**
In README.md as of f2b0d16668a156a23f4e7c11ec27b98fdfc3fde5

## **Description**
There is a typo in the following sentence:
> Some mods might not have an 1.12.2 version if the code is too different.

Here, "an" should be just "a", which results in the following:
> Some mods might not have a 1.12.2 version if the code is too different.

**Comment by ricksouth** [comment]
Thanks @James103! :) I've fixed it.
