### ISSUE TITLE
More Zombie Villagers - Unable to load worlds made prior to mod installation

### ISSUE THREAD

**Issue by demonJ5** [Serilum/.issue-tracker#66]
## **Information**
Minecraft version: 1.15.2
Forge version: 31.1.27
Environment: Singleplayer

Mod name: More Zombie Villagers
Mod version: mzombv_1.15.2-1.0.jar

## **Description**
Loading worlds made before installing the mod creates gamebreaking behavior. Upon loading the world, the player may spawn into an empty void that never populates chunks. 

Alternatively, few chunks within a small radius of the player may load. No further chunks will load and a void will appear at the edge of the loaded chunks. During this time, the player may move and destroy blocks, but these blocks will not drop as items. Additionally, all mobs will be frozen. Walking into the void makes the player fall for an eternity.

In either case, trying to save and quit will hang the game.

## **Crash report**
N/A

**Comment by ricksouth** [comment]
I wasn't able to replicate the issue, but I've released a new version which has been completely rewritten. I'm confident this will solve your issues, but if they persists please let me know! Thanks for submitting the issue and using the mod.

[https://www.curseforge.com/minecraft/mc-mods/more-zombie-villagers](https://www.curseforge.com/minecraft/mc-mods/more-zombie-villagers)
