### ISSUE TITLE
[Bug] Lycanites Mobs Not Burning Around Campfire 

### ISSUE THREAD

**Issue by Punkin-GH** [Serilum/.issue-tracker#660]
### Information
Minecraft version: 1.16.5
Forge version: 36.2.2
Environment: Singleplayer (Multiplayer not tested)
Mod 1: nohostilesaroundcampfire_1.16.5-3.3.jar
Mod 2: lycanitesmobs-1.16.5-2.3.2.2.jar
### Description
When using the mod "No Hostiles Around Campfire", none of the hostile mobs from Lycanites Mobs are affected.

**Comment by ricksouth** [comment]
Do you have a list of hostile mobs for me in the mod? I'm not familiar with Lycanites Mobs

**Comment by Punkin-GH** [comment]
It's safe to assume pretty much all of them. To my knowledge, there wouldn't be a way of differentiating between hostile creatures, and creatures you summoned of the same type. There are so few passive creatures, it wouldn't be a bad call to just add all of the Lycanites Mobs to the "burn list".

**Comment by ricksouth** [comment]
Took me a little while but I've added support for all the Lycanites Mobs in version 3.8 of the mod. Thanks for giving it a try and the suggestion!

https://www.curseforge.com/minecraft/mc-mods/no-hostiles-around-campfire/files/all
