### ISSUE TITLE
Areas not showing message on server

### ISSUE THREAD

**Issue by lucymosshollow** [Serilum/.issue-tracker#661]
I got this mod to work in my singleplayer world but when i try to use it on my server the entering or leaving message will not show up.   I made sure to have both this mod and the collective mod installed on both my client and on the server. 
when i use the command /areas it will detect that there's a sign nearby.
Playing on 1.16.5

**Comment by ricksouth** [comment]
What version is Areas and Collective?

**Comment by WillouwCode** [comment]
I have the same issue following my last question, I did update and on a server still doesn't work. On single player worlds it works perfectly :)

Minecraft 1.17.1
Forge + server 1.17.1-37.0.29
collective-1.17.1-2.54
areas_1.17.1-2.7

**Comment by lucymosshollow** [comment]
Sorry, i completely forgot to add the version numbers!

Forge-1.16.5-36.2.2
collective-1.16.5-2.54
areas_1.16.5-2.7

**Comment by bindingflare** [comment]
Forge-1.16.5-36.2.2
collective-1.16.5-2.54
areas_1.16.5-2.7

Also, it seems setting only the first line does not generate a random name in the sign. Same symptoms with the /areas command as above.
Automatic random sign generation for Villages works fine.

**Comment by Dennery123** [comment]
i have the same problem. runs fine in singleplayer but not on my server
Minecraft 1.17.1
Forge and server 1.17.1-37.0.27
collective-1.17.1-2.55
areas_1.17.1-2.7

**Comment by ricksouth** [comment]
Thanks everyone! Really appreciate it.

Can you give version 2.8 of Areas a try? It works in my development environment but just want to make sure it's fixed before closing the issue.

https://www.curseforge.com/minecraft/mc-mods/areas/files/all

**Comment by Dennery123** [comment]
Yup works for me!
great job and thanks man

**Comment by lucymosshollow** [comment]
The mod now works perfectly, Thank you!

**Comment by ricksouth** [comment]
Thanks for confirming!
