### ISSUE TITLE
[1.12.2] 'clockPositionIsCenter' isn't actually centered.

### ISSUE THREAD

**Issue by SonicX8000** [Serilum/.issue-tracker#664]
Minecraft: 1.12.2
Forge: 14.23.5.2854

Mods: 3
collective-1.12.2-2.55
guiclock_1.12.2-2.5
jei_1.12.2-4.16.1.302

=====

Testing out the bugfix with the GUI Clock and finding a perfect spot to put it... and apparently the GUI Clock isn't really centered. Here's an image of what I see.

![](https://cdn.discordapp.com/attachments/377171551155650560/875134079522177044/guiclocknotinmiddle.PNG)

Top: The GUI Clock is 'centered' but it's off by a few pixels to the right.

Bottom: A mock-up of where the GUI Clock should be. At least... what I was expecting it to be at.

-----

Unsure if the Position config options are still being used only because I recall seeing an suggestion to allow the GUI Clock to be moved via X Coordinates, as currently you can only change it via the Y Coordinates.

This is where the suggestion was mentioned for allowing X Coordinates.
https://github.com/ricksouth/serilum-mc-mods/issues/410

**Comment by ricksouth** [comment]
Thanks for submitting the bug report! I've fixed the clock icon not being centered and added the clockWidthOffset config option in version 2.6 of GUI Clock. So you shouldn't need the config option anymore but it's there if others have a use for it.

https://www.curseforge.com/minecraft/mc-mods/gui-clock/files

**Comment by SonicX8000** [comment]
guiclock_1.12.2-2.6

![](https://cdn.discordapp.com/attachments/377171551155650560/875144523276255272/guiclockcentered.PNG)
It's now centered correctly, thank you for this as well as adding the X Coordinate option.
