### ISSUE TITLE
Creepers create AreaEffectClouds with infinite duration upon exploding

### ISSUE THREAD

**Issue by floral-qua-floral** [Serilum/.issue-tracker#668]
## **Information**
Minecraft version: 1.16.5
Forge version: 36.2.2
Environment: Singleplayer & Multiplayer

Mod name: Random Mob Effects
Mod version: 1.5

## **Description**
Upon exploding, Creepers which have potion effects will create an AreaEffectCloud with their current effects, similar to if a Lingering Potion was thrown. Because the duration is inherited from the Creeper, this poses some rather significant balance concerns - players can be given an infinitely long Strength, Absorption, Speed, Night Vision, etc buff, or on the other hand, they may receive an infinitely long Mining Fatigue, Hunger, Poison, or heaven forbid Blindness debuff.

## **Crash report**
N/A

**Comment by James103** [comment]
What do you get if you run `/data get entity @s ActiveEffects`? Make sure to turn cheats on or reproduce in a separate creative test world to run the command.

**Comment by ricksouth** [comment]
Thanks for giving the mod a try and opening the bug report! I've added a config option, enabled by default, to version 1.6 which prevents creepers from getting an effect.

https://www.curseforge.com/minecraft/mc-mods/random-mob-effects
