### ISSUE TITLE
pressure plates?

### ISSUE THREAD

**Issue by CharleeToombs** [Serilum/.issue-tracker#67]
## **Information**
Minecraft version: 1.15.2
Forge version: 31.1.0
Environment: **Multiplayer**

Mod name: Double Doors
Mod version: doubledoors_1.15.2-1.2

Hey! it seem that integration with pressure-plates has not be included? i was hoping both doors would close behind me when walking over a pressure plate in front of either door.

In case it matters i believe it was jungle wood.

**Comment by ricksouth** [comment]
Thanks for the idea! Check out version 2.0, it adds this and other features :)

[https://www.curseforge.com/minecraft/mc-mods/double-doors](https://www.curseforge.com/minecraft/mc-mods/double-doors)
