### ISSUE TITLE
bro i got a crash...

### ISSUE THREAD

**Issue by xelotex** [Serilum/.issue-tracker#670]
## **Information**
Minecraft version: 1.16.5
Forge version: 36.1.32
Environment: Singleplayer / 

Mod name: transcending trident
Mod version: 1.6

## **Description**
i just try to use the mod in my modpack and it crashed :D.

## **Crash report**
[crash-2021-08-14_09.05.09-server.txt](https://github.com/ricksouth/serilum-mc-mods/files/6986680/crash-2021-08-14_09.05.09-server.txt)

available.

**Comment by TheNickm2** [comment]
Had the same or similar crash occur today

## **Information**
Minecraft version: 1.16.5
Modloader: Forge
Modpack Name: Better Minecraft
Modpack Version: 37
Forge version: 36.2.2
Environment: Multiplayer

Mod name: Transcending Trident
Mod version: 1.6


## **Steps to reproduce**
1) enchant a trident with Riptide 4 via Serilum Enchanting Commands 1.7 mod
2) attempt to throw the trident with a bucket in your inventory (tested with a bucket in off hand and just in inventory, crashed both times)
3) expected: flight! actual: crash & burn :(


## **Crash report**
[crash-2021-09-15_20.00.24-server.txt](https://github.com/ricksouth/serilum-mc-mods/files/7172956/crash-2021-09-15_20.00.24-server.txt)

**Comment by ricksouth** [comment]
Version 2.0 fixes the issues you were having. Thanks for opening the report and giving the mod a try! It's been completely rewritten to add the compatibility.

https://www.curseforge.com/minecraft/mc-mods/transcending-trident/files/all
