### ISSUE TITLE
Goblin Traders would be a great addition

### ISSUE THREAD

**Issue by BigMartin58** [Serilum/.issue-tracker#672]
Mod name: Villager Names

The mod Goblin Traders offers tiny wandering villager-like goblins who show up randomly with rare items.

**Comment by ricksouth** [comment]
Thanks for giving the mod a try and submitting the request! I've added support for the goblin traders in Collective version 2.65.

https://www.curseforge.com/minecraft/mc-mods/villager-names
https://www.curseforge.com/minecraft/mc-mods/collective
