### ISSUE TITLE
Tree harvester exit code 1

### ISSUE THREAD

**Issue by Eccomi21** [Serilum/.issue-tracker#674]
## **Information**
Minecraft version: 1.17.1
Forge version: 37.0.42
Environment: Singleplayer

Mod name: Tree harvester
Mod version: 2.9

## **Description**
Loading the Mod into the Mods folder and then starting the game results in a crash and Exit code 1 in console plus exit code 0 in the crash reporter

## **Crash report**
23:05:24.416
monitor
Process Monitor
Process crashed with exit code 1

**Comment by ricksouth** [comment]
Can you supply the crash log? Located in the "crash-reports" folder in your root server folder.

**Comment by Eccomi21** [comment]
> Can you supply the crash log? Located in the "crash-reports" folder in your root server folder.

Unfortunately just before i checked github i deleted my old .minecraft folder and installed a newer forge version plus your collective and the tree harvester mod. works now. also i dont believe i have/had a root server folder as i am playing on singleplayer as stated above.
I'm closing the issue as it no longer arises after a fresh install of everything. Thank you.
