### ISSUE TITLE
TreeHarvester Crashing Server

### ISSUE THREAD

**Issue by uwuscutely** [Serilum/.issue-tracker#676]
## **Information**
Minecraft version: 1.12.2
Forge version: 1.12.2 - 14.23.5.2855
Environment: Multiplayer

Mod name: TreeHarvester
Mod version: 2.9

## **Description**
Server spam crashes every time a single person tries to chop down a tree

## **Crash report**
https://bin.bloom.host/kekodovapu.sql

**Comment by James103** [comment]
Are you able to reproduce the ~~crash~~ tick lag/freeze in single player?

**Comment by uwuscutely** [comment]
Not sure haven't tried it

**Comment by ricksouth** [comment]
Seems like the crash report isn't available anymore. Do you still have it in your server root folder?
