### ISSUE TITLE
Crash on 1.16.5 forge  36.2.0

### ISSUE THREAD

**Issue by Mr-Syntax** [Serilum/.issue-tracker#677]
[crash-2021-08-26_04.06.11-server.txt](https://github.com/ricksouth/serilum-mc-mods/files/7051077/crash-2021-08-26_04.06.11-server.txt)

my pack is pretty extensive and something in collective is messing with it, sometimes it will completely disable all structure gen, but when i change versions and get it working again it will suddenly die while loading chunks

**Comment by ricksouth** [comment]
This has been fixed in Collective version 2.62. If not, please let me know. Thanks for trying out my mods!

https://www.curseforge.com/minecraft/mc-mods/collective/files
