### ISSUE TITLE
Some trees not working with Tree Harvester?

### ISSUE THREAD

**Issue by ChielTheOread** [Serilum/.issue-tracker#680]
Minecraft version: 1.16.5
Forge version: 36.2.2
Environment: Singleplayer 
Mod: Tree harvester
Mod version: 1.16.5-2.9

So I'm playing on the Better Minecraft modpack, and it seems some of the modded trees don't work with tree harvester _(mods involve Biomes You'll Go, Terra Incognita, and Upgrade Aquatic)_, it works on all vanilla trees though.

Is there a way to fix this? If not, is it possible in the future we could have a block whitelist and blacklist in config so we can manually add IDs of logs not working to fix it? 

Sorry if this is the wrong place for this.

**Comment by ricksouth** [comment]
Which trees are not working? I've tested a dozen of them and it all seems to work

**Comment by ricksouth** [comment]
The goal is to have them all work out of the box, without a config necessary. Otherwise I can update the mod to include those which are not working. So it's the right place. Appreciate the issue!

**Comment by ChielTheOread** [comment]
> Which trees are not working? I've tested a dozen of them and it all seems to work

To clarify, i haven't tested all trees yet as this is in a survival playthrough, but one of the trees not working with the mod, is River wood trees from Upgrade Aquatic

I'll try and check more that don't work

**Comment by ricksouth** [comment]
I've just released version 4.0 of Tree Harvester which should fix the issues you were having. I lowered the requirement of how many leaves a tree should have before it's considered a tree. Tested it with the River wood trees but others should work better now too. Thanks for giving the mod a try and submitting the bug report!

https://www.curseforge.com/minecraft/mc-mods/tree-harvester/files
