### ISSUE TITLE
Villager Names are not working in Villages but they work on Wandering Traders?

### ISSUE THREAD

**Issue by jigglebi** [Serilum/.issue-tracker#682]
## **Information**
Minecraft version: 1.17.1
Forge version: 37.0.51
Environment: Singleplayer

Mod name: Villager Names
Mod version: 3.3

## **Description**
I have both the Collective and Villager Names in my mod folder and I don't crash on start up but when I am in a Village no names are popping up above the villager heads or in their trading hud. The wandering traders have names though so I know the mod works I just don't have any idea why it's not working completely. Any suggestions?

## **Crash report**
N/A

**Comment by ricksouth** [comment]
This unfortunately is something in Forge itself that's not working correctly. We're waiting on https://github.com/MinecraftForge/MinecraftForge/pull/8033 to be merged. The mod uses this event which is not firing correctly for all mods currently.

I'll let you know when it's fixed on their end. Thanks for using the mod!

**Comment by jigglebi** [comment]
Thank you. :) I thought I was doing something wrong. Well, I hope they do it soon.

**Comment by ricksouth** [comment]
This has been fixed in Forge version 37.0.65! :)

https://files.minecraftforge.net/net/minecraftforge/forge/

**Comment by jigglebi** [comment]
Thank you so much for letting me know. :) They work! I'm so excited. I also
have some of your other mods and they are awesome. Thank you for the great
mods.
