### ISSUE TITLE
Bee sting will remain after respawn

### ISSUE THREAD

**Issue by Exokyhh** [Serilum/.issue-tracker#685]
## **Information**
Minecraft version: 1.16.5
Forge version: 36.2.0
Environment: Singleplayer

Mod name: Mod
Mod version: 1.5

## **Question**
Hi, i'm not sure if this a feature or not, but when you die after one or multiple bees left their sting inside your skin, if you respawn the sting will keep pumping poison.

**Comment by ricksouth** [comment]
Thanks for submitting the bug report! This was not intentional. Version 2.1 of Realistic Bees makes sure to remove the stinger from a player when they die.

https://www.curseforge.com/minecraft/mc-mods/realistic-bees/files/all
