### ISSUE TITLE
is this for forge or fabric?

### ISSUE THREAD

**Issue by zxcdevlop** [Serilum/.issue-tracker#686]
i use optifabric a lot for minecraft, so i want to know if this is for forge or fabric. thanks!

**Comment by James103** [comment]
All of Ricksouth's mods are Forge only unless otherwise stated. See [the FAQ](https://github.com/ricksouth/serilum-mc-mods/wiki/FAQ) for more info.

**Comment by ricksouth** [comment]
Yep, all for Forge. Thanks for the interest though!
