### ISSUE TITLE
Mod does not work at all

### ISSUE THREAD

**Issue by ksk-waqs** [Serilum/.issue-tracker#689]
## **Information**
Minecraft version: 1.16.5
Forge version: 36.2.2
Environment: Singleplayer

Mod name: Tree Harvester
Mod version: 3.2

## **Description**
Hello, for some reason the mod does not work at all. I tried to install the previous version, but it doesn't work either. I put in a clean build with no other mods but it still doesn't work

P.S. I installed the library collective of course

**Comment by ricksouth** [comment]
Are you holding an axe and crouching while chopping down a log block? What tree are you testing it on?

**Comment by ksk-waqs** [comment]
I'm sorry, the problem was that I didn’t press the shift key 😅
