### ISSUE TITLE
Doesn't work in deserts

### ISSUE THREAD

**Issue by BriceFable** [Serilum/.issue-tracker#691]
Title! I've been bonemealing in the desert and all it spawns is grass, no flowers. I do not have anything blacklisted.

**Comment by JaxckLl** [comment]
I've noticed this too when working in Badlands. I assumed it's because deserts & badlands don't naturally spawn flowers.

**Comment by ricksouth** [comment]
The mod only changes existing flower spawns, indeed because deserts and badlands don't spawn flowers it can't randomize them. As this is Minecraft's intended behaviour it's not a bug. Thanks for giving the mod a try though!
