### ISSUE TITLE
[Tree Harvester] Adding to the config the ability to specify the exhaustion level coefficient

### ISSUE THREAD

**Issue by ksk-waqs** [Serilum/.issue-tracker#692]
## **Information**
Mod name: Tree Harvester

## **Feature description**
Hello, how about adding to the config the ability to specify the exhaustion level coefficient

**Comment by ricksouth** [comment]
I've just released version 4.0 of Tree Harvester which adds the config option 'increaseExhaustionModifier'. This should add the functionality you've requested. Thanks for giving the mod a try and submitting the sugestion!

https://www.curseforge.com/minecraft/mc-mods/tree-harvester/files
