### ISSUE TITLE
The config file reloads itself 

### ISSUE THREAD

**Issue by Blugori** [Serilum/.issue-tracker#696]
## **Information**
Minecraft version: 1.16.5
Forge version: 36.2.0
Environment: Singleplayer

Mod name: Configurable extra mob drop
Mod version: 1.6

## **Description**
Hi !
I wanted to configure the iron golem drops, and edited the config file to be able to use commands in game (I saw that the minecraft:iron_golem was missing in the file).
So I first edited the file and added the iron golem entity to the list, then launched the game, and edited the drops in a world, I killed some iron golems and drops were working.
But each time I launch the game again the config file reloads, I don't know if that is linked to the iron golem thing, maybe its an incompatibility with an other mod.

## **Crash report**
I have no crash report to provide, I noticed that the config file reloads when I launch the game, but if I edited it before launching I could still use commands to configure the iron golem drops, even if it was no more written on the config list

Thanks for reading :) (and for the mod !)

**Comment by ricksouth** [comment]
Apologies for the late fix. I've fixed it in version 1.8 of the mod. Iron golems are categorized in the game as "Misc", which is why the mod didnt list them. Thanks for giving the mod a try and submitting the bug report!

https://www.curseforge.com/minecraft/mc-mods/configurable-extra-mob-drops/files/all

**Comment by jojofenin-jpg** [comment]
I have the same issue but instead for the male and female villagers from the Minecraft comes alive reborn mod
