### ISSUE TITLE
Supplementaries compatible problem

### ISSUE THREAD

**Issue by GauntAndreX8** [Serilum/.issue-tracker#697]
## **Information**
Minecraft version: 1.16.5
Forge version: 36.3.0
Environment: Singleplayer / Multiplayer

Mod name: supplementaries
Mod version: 0.16.0

## **Description**
Do you think you can make a more compatible for the supplementaries mod cause it added the red wandering trader but did not have a name from the this mod can you fix this plz

## **Crash report**
If available.

**Comment by ricksouth** [comment]
Thanks for giving the mod a try and submitting the request! I've added support for the red merchant from Supplementaries in Collective version 2.65.

https://www.curseforge.com/minecraft/mc-mods/villager-names
https://www.curseforge.com/minecraft/mc-mods/collective
