### ISSUE TITLE
[Villager Names] No Cyrillic support

### ISSUE THREAD

**Issue by ksk-waqs** [Serilum/.issue-tracker#699]
## **Information**
Minecraft version: 1.16.5
Forge version: 36.2.2
Environment: Multiplayer

Mod name: Villager Names
Mod version: 3.3

## **Description**
The mod does not support the Cyrillic alphabet. Names in Russian are not displayed correctly

## **Example**
The Russian name "Иван" (Ivan) in the game appears as ���� or Р?РІР°РЅ

**Comment by Nicknaem** [comment]
yup I wanted to use Georgian names with no success ჯიგარო

**Comment by James103** [comment]
Can you please try with each of the following strings for villager names:
```
鲍勃
アレックス
एरिक
مرحبا!
Ήθος
Złoty
Thụy Sĩ
```

The first five strings are likely to fail outright. Of the last 2 strings, the ASCII characters should display correctly, but the non-ASCII characters such as `ł`, `ụ`, and `ĩ` may not display correctly.

**Comment by ricksouth** [comment]
Thanks for submitting the bug report and giving the mod a try! Version 3.4 adds support for non-Latin alphabets, such as Cyrillic and Georgian.

https://www.curseforge.com/minecraft/mc-mods/villager-names
