### ISSUE TITLE
Conduit?

### ISSUE THREAD

**Issue by pomarf** [Serilum/.issue-tracker#7]
Better Beacon Placement

So, would it be possible to make it possible to take the functionality of Better Beacon Placement and apply that idea to Conduits as well? They are a lot more annoying to build with them having to be constructed under water and all. :D

**Comment by ricksouth** [comment]
It'll take a few hours for it to be approved, but I think this is what you've been looking for: [https://www.curseforge.com/minecraft/mc-mods/better-conduit-placement](https://www.curseforge.com/minecraft/mc-mods/better-conduit-placement), thanks for the idea!
