### ISSUE TITLE
Tree Harvester doesn't work with Biomes o' Plenty mod

### ISSUE THREAD

**Issue by Gantros** [Serilum/.issue-tracker#71]
This mod doesn't break non-vanilla trees, in this case BoP.

**Comment by ricksouth** [comment]
Thanks for letting me know! I've added support for all modded trees in version 1.1.

[https://www.curseforge.com/minecraft/mc-mods/tree-harvester](https://www.curseforge.com/minecraft/mc-mods/tree-harvester)
