### ISSUE TITLE
Question about double doors and villagers

### ISSUE THREAD

**Issue by vico93** [Serilum/.issue-tracker#72]
I'm in process of disabling Quark's double doors system and adding your mod in place.

But i have a question about: Does your mod allows Villagers to enter/use double doors? In quark there's a option to allow it happen but i dont know about your mod.

Thanks in advance!

**Comment by ricksouth** [comment]
They should be able to enter if there's a pressure plate in front of the door. I'm not sure about manually. I think they'll only open 1 door and leave the other one closed.

I'd appreciate it if you could test it for me! :)

**Comment by vico93** [comment]
Will do. Thanks!

**Comment by vico93** [comment]
I didnt test yet because i just realized this mod is only for 1.15 and i still playing on 1.12.2 :P sorry to misinform you
