### ISSUE TITLE
12 hour clock still shows 24 hour time

### ISSUE THREAD

**Issue by rckymtnrfc** [Serilum/.issue-tracker#73]
## **Information**
Minecraft version: 1.15.2
Forge version: 31.1.41
Environment: Multiplayer

Mod name: GUI Clock
Mod version: 1.4

## **Description**
I've got the config set to "24hourformat = false" and I do see the AM/PM displayed but the clock still displays time in the 24 hour format.

**Comment by ricksouth** [comment]
Thank for letting me know! I've fixed it in version 1.5 of the mod.

[https://www.curseforge.com/minecraft/mc-mods/gui-clock](https://www.curseforge.com/minecraft/mc-mods/gui-clock)

**Comment by rckymtnrfc** [comment]
Still a small issue.  When the time goes to 12:00 PM it actually displays as 0:00 PM.  Once it gets to 1:00 PM it looks correct.

**Comment by ricksouth** [comment]
That's my fault for not actually using the 12-hour format myself. I've checked [wikipedia](https://en.wikipedia.org/wiki/12-hour_clock) and cycled through all the times. Everything should work as intended in version 1.6.

Thanks for letting me know!
