### ISSUE TITLE
Planting sapling when the base block is chopped.

### ISSUE THREAD

**Issue by kevgogo** [Serilum/.issue-tracker#74]
## **Information**
Mod name: Tree Harvester

## **Feature description**
I've had this amazing idea, a new config that makes possible the plant of a sapling replacing the base block if this is chopped.

**Comment by ricksouth** [comment]
Thanks for using the mod! You mean this one:

replaceSaplingIfBottomLogIsBroken (default = true): If enabled, automatically replaces the sapling from the drops when the bottom log is broken.

that already exists right now? O:)
