### ISSUE TITLE
Change custom name location to config folder

### ISSUE THREAD

**Issue by ricksouth** [Serilum/.issue-tracker#76]
It is currently in /mods, change that to /config.
https://www.curseforge.com/minecraft/mc-mods/villager-names

**Comment by tobi-polar** [comment]
I literally came here to post the same thing

**Comment by ricksouth** [comment]
Great minds think alike ;)

I've updated it in version 2.1! The folder is located in ./config/villagernames/customnames.txt.

[https://www.curseforge.com/minecraft/mc-mods/villager-names](https://www.curseforge.com/minecraft/mc-mods/villager-names)
