### ISSUE TITLE
Button Combo For XP Bottling

### ISSUE THREAD

**Issue by UnseenAcademical** [Serilum/.issue-tracker#77]
## **Information**
Minecraft version: 14.4
Forge version: 28.2.3
Environment: Multiplayer

Mod name: Bottle Your XP
Mod version: 14.4-1.0

## **Description**
I'm unable to shift right click a bottle and get it to fill with XP. Are there alternate buttons to try?

## **Crash report**
If available.

**Comment by ricksouth** [comment]
It currently only works while holding the crouch button. Did you remap that key?

**Comment by UnseenAcademical** [comment]
No, button has not been remapped.

**Comment by ricksouth** [comment]
Do you have other mods installed?

**Comment by UnseenAcademical** [comment]
Yes. I have checked the keybindings in the options menu, and didn't see any other Left Shift usages.

**Comment by UnseenAcademical** [comment]
Suddenly working again for no reason I can see.

**Comment by UnseenAcademical** [comment]
And now not working again for no discernable reason

**Comment by ricksouth** [comment]
I was wondering, are you sure you have enough xp to bottle at the times it does not work?
