### ISSUE TITLE
Bottling xp can kill you in creative mode

### ISSUE THREAD

**Issue by jsdomine** [Serilum/.issue-tracker#78]
## **Information**
Minecraft version: 1.14.4
Forge version: 28.2.0
Environment: Singleplayer / Multiplayer

Mod name: Bottle Your Xp
Mod version: 1.14-1.0

## **Description**
[As above]

## **Crash report**
[None]

**Comment by ricksouth** [comment]
Thanks for letting me know! I've fixed it in version 1.1 of the mod.

[https://www.curseforge.com/minecraft/mc-mods/bottle-your-xp](https://www.curseforge.com/minecraft/mc-mods/bottle-your-xp)
