### ISSUE TITLE
Named Villager Properties?

### ISSUE THREAD

**Issue by Yourname942** [Serilum/.issue-tracker#8]
## **Information**
Minecraft version: 12.2.2
Forge version: 14.23.5.2847
Environment: Multiplayer

Mod name: Villager Names
Mod version: vilnames_1.12-1.4.jar
--

## **Question**
1) Do named villagers keep chunks loaded? 
2) Do named villagers have the same properties as when you giving a nametag to an entity?
3) Do named villagers despawn?

**Comment by ricksouth** [comment]
Hi, little late but here it goes!

1. No, they act as normal named mobs.
2. Yes
3. No

Thanks for using the mod.
