### ISSUE TITLE
Lower Minecraft Version Support

### ISSUE THREAD

**Issue by HAJDog247** [Serilum/.issue-tracker#80]
## **Information**
Mod name: _Named Areas_

## **Feature description**
You see, I'm a (local) multiplayer server owner, and, I'm looking forward to adding this mod in. But, the problem is, I'm using `1.7.10` version of the game -- in which your mod doesn't support. So, I hope you **could** support it.

Please, this will be a big help for all my friends and me. Thank you! 👍

**Comment by ricksouth** [comment]
I won't be updating the mod for minecraft 1.7, the code structure has changed a lot. Thanks for the interest though!
