### ISSUE TITLE
Crash when getting near a Rough Mobs Revamped Boss

### ISSUE THREAD

**Issue by TheVisionaryOne** [Serilum/.issue-tracker#81]
## **Information**
Minecraft version: 1.12.2
Forge version: 14.23.5.2847
Environment: Multiplayer (LAN)

Mod name: Just Player Heads
Mod version: 1.0

## **Description**
I was testing my pack on an LAN world, and one of the players got near a Rough Mobs Revamped boss (just a regular zombie in full diamond armor), and the game crashed. We reloaded the world, and eventually I ran into the same zombie, and the game crashed again. Both instances cite Just Player Heads as the first offender. The second crash oddly named Primitive Mobs as one of the offenders, which doesn't make sense, since I was right next to a Rough Mobs mob, not a Primitive Mobs mob.

The strange thing is I've fought a couple of Rough Mobs bosses on the same world before, with no problem. Both of them were skeletons though, so maybe it's a really weird niche incompatibility when players get too close to a RMR zombie boss specifically?

## **Crash report**
Here are both crash reports:
[https://paste.dimdev.org/ucohoyezug.mccrash](https://paste.dimdev.org/ucohoyezug.mccrash)
[https://paste.dimdev.org/ezaseyebic.mccrash](https://paste.dimdev.org/ezaseyebic.mccrash)

**Comment by ricksouth** [comment]
I've released a new version of Just Player Heads with a complete code rewrite. This should resolve the issues you were having. Thanks for letting me know and using the mod!

[https://www.curseforge.com/minecraft/mc-mods/just-player-heads](https://www.curseforge.com/minecraft/mc-mods/just-player-heads)
