### ISSUE TITLE
No regeneration effect with newly placed campfires

### ISSUE THREAD

**Issue by anupu** [Serilum/.issue-tracker#82]
## **Information**
Minecraft version: 1.15.2
Forge version: 31.1.0
Environment: Singleplayer / Multiplayer

Mod name: Healing campfire
Mod version: 1.15.2-2.0

## **Description**
Are there any special things I need to do before the campfire can heal? I placed a new campfire, but it didn't give the regeneration effect, while campfires placed before I added this mod gave the effect (I can't find anything different, and destroying/replacing the old campfires with new ones resulted again in no effect.

**Comment by anupu** [comment]
Starting the world new resulted in the effect beeing applied, but new campfires still don't apply the effect

**Comment by ricksouth** [comment]
I believe this has to do with the efficiency. The mod doesn't check for campfires all the time, in order to use less resources. I'll add a manual force check when placing a new campfire though, thanks for letting me know. I'll keep you updated!

**Comment by ricksouth** [comment]
I've fixed it in version 2.1! Let me know if anything else doesn't work as intended. Thanks for using the mod.

[https://www.curseforge.com/minecraft/mc-mods/healing-campfire](https://www.curseforge.com/minecraft/mc-mods/healing-campfire)
