### ISSUE TITLE
It's Opposite Day!

### ISSUE THREAD

**Issue by Tyrius1** [Serilum/.issue-tracker#83]
## **Information**
Mod name: No Hostiles Around Campfire

## **Feature description**
Campfires that attract zombies! I was asking a friend how far they thought the range should be and they were like "wouldn't in the zombie world it attract them?" So here I am.
As a config, it doesn't make sense considering the name
But perhaps a new mod? Where mobs are drawn to campfires?

**Comment by ricksouth** [comment]
I do like the idea! Do you think only zombies should be attracted by fire? What about torches? What about a burning furnace?
