### ISSUE TITLE
Red mushroom suspicious stew

### ISSUE THREAD

**Issue by EternalOne11** [Serilum/.issue-tracker#84]
## **Information**
Mooshroom tweaks

## **Feature description**
Perhaps you could make red mooshrooms able to be used to get suspicious stew.  There is no reason not to since by default both moohroom types have the same spawn rate. (you should also make it configurable.

**Comment by ricksouth** [comment]
You can already get a mushroom stew by right clicking a cow with a bowl. I think that's the correct functionality. But thanks for the idea and using the mod!
