### ISSUE TITLE
No Hostiles Around Campfire no longer works after updating to 1.15-2.1.jar in Multiplayer

### ISSUE THREAD

**Issue by JMZED** [Serilum/.issue-tracker#86]
## **Information**
Minecraft version: 1.15.2
Forge version: 31.1.0
Environment: Multiplayer

Mod name: No Hostiles Around Campfire
Mod version: 1.15-2.1.jar

## **Description**
Mobs seem to be able to spawn within a campfire's radius after switching to version 1.15-2.1.jar.

**Comment by ricksouth** [comment]
The mod currently works by preventing a mob spawn when it's natural in the world. Spawn eggs for example still work inside the campfire's radius. Is that what you've tried or are there actual natural spawns within the radius?
