### ISSUE TITLE
Automatic Doors: LAN Muitplayer open/close bug

### ISSUE THREAD

**Issue by akharding91** [Serilum/.issue-tracker#87]
## **Information**
Minecraft version: 1.15.2
Forge version: 31.1.37
Environment: LAN Multiplayer with another play connected 

Mod name: Automatic Doors
Mod version: 1.3

## **Description**
When in a LAN Multiplayer world with another person playing, the doors rapidly open/close when you enter the range for the mod to work on the doors.

## **Crash report**
N/A

**Comment by ricksouth** [comment]
Thanks for letting me know and using the mod! Version 1.4 should fix the problems you were having.

[https://www.curseforge.com/minecraft/mc-mods/automatic-doors](https://www.curseforge.com/minecraft/mc-mods/automatic-doors)
