### ISSUE TITLE
Support Milk Buckets of other mods

### ISSUE THREAD

**Issue by cech12** [Serilum/.issue-tracker#88]
## **Information**
Mod name: Nutritious Milk

## **Feature description**
I am the developer of the Ceramic Bucket mod and I am already supporting your Milk All The Mobs mod https://github.com/cech12/CeramicBucket/issues/10. Now I wanted to support your Nutritious Milk mod https://github.com/cech12/CeramicBucket/issues/9. One problem is, that I cannot look into your code, so it is difficult to support it. ;) 
But maybe there is a possibility that you can support all bucket mods if you add a forge tag where all mods can add their milk buckets and instead of checking for the vanilla bucket you check for this tag. Example "forge:buckets/milk" like in my mod: https://github.com/cech12/CeramicBucket/tree/master/src/main/resources/data/forge/tags/items/buckets
But if you want another tag, I can use it. :D

**Comment by ricksouth** [comment]
I've put it on the todo list and will add the tag functionality in the near future. Thanks for making them compatible!

**Comment by ricksouth** [comment]
I've added support for modded milk buckets in version 1.2! Thanks for the suggestion.

Also-- I saw you called it Milk Ceramic Bucket. I think it might be a little easier on the eyes if it's called Ceramic Milk Bucket. But that's up to you of course :)

**Comment by cech12** [comment]
Very nice! I will test it. :D 
Thanks for your hint. That would be a better name of course.^^
