### ISSUE TITLE
Milking incompatibility (Industrial Foregoing)

### ISSUE THREAD

**Issue by cech12** [Serilum/.issue-tracker#89]
## **Information**
Minecraft version: 1.15.2
Forge version: 31.1.27
Environment: Singleplayer

Mod name:  Milk All The Mobs
Mod version: 1.0

Other Mod: industrial-foregoing-1.15.2-2.2.2-28d4a81

## **Description**
I have installed Industrial Foregoing and your mod Milk All The Mobs. When I right click on a sheep with a single bucket in the hand and the ground behind is in range, the bucket is not filled and a milk fluid source (from industrial foregoing) is placed on the ground. When I right click on a sheep with a stack of more than one bucket, all works fine. With cows all works fine, too.

**Comment by ricksouth** [comment]
Took me a little bit but I've fixed the problem in version 1.2 of the mod. Thanks for letting me know and using the mod!

[https://www.curseforge.com/minecraft/mc-mods/milk-all-the-mobs](https://www.curseforge.com/minecraft/mc-mods/milk-all-the-mobs)
