### ISSUE TITLE
The player doesn't spawn in a Village in 1.15.1

### ISSUE THREAD

**Issue by BetaCarotina** [Serilum/.issue-tracker#90]
Minecraft version: 1.15.1
Environment: Singleplayer
The new world spawn point isn't centered in a Village, even though it should be according to modpack page

**Comment by ricksouth** [comment]
Currently the Village Spawn Point mod hasn't been updated to 1.15 due to the /locate command functionality missing in the Forge MDK. I'll try to get it sorted out so I can update the mod and the modpack after. Thanks for the interest!
