### ISSUE TITLE
Death blocks gravestones

### ISSUE THREAD

**Issue by Pengu-Hunter** [Serilum/.issue-tracker#92]
## **Information**
Minecraft version: 1.12.2
Forge version: 14.23.5.2547
Environment: Singleplayer 

Mod name: bottle your xp
Mod version: 1.0

## **Description**
If you die by this mod the graves from other mods don't work, I already took this to the issue section of the grave mod I use and they confirmed that it wasn't on their end, but suggested it had to do with how this mod kills the player.

**Comment by ricksouth** [comment]
I believe how it currently works is the health of the players is set to 0. This should in theory run the deathEvent which the other mod probably uses. But I'll test it out and if needed add a check when the players' health is 0 or below, it'll run the death event.

Thanks for letting me know and using the mod!

**Comment by Pengu-Hunter** [comment]
Thank you for the reply, in the mean time I've used the config to disable damage on use of the mod.

**Comment by ricksouth** [comment]
I've fixed it in version 1.2 of the mod, tested it with the gravestones mod you've mentioned. Before it just set the player's health to below 0, now it checks whether the new health is less than 0 and instead runs the death event.

Thanks for letting me know!
[https://www.curseforge.com/minecraft/mc-mods/bottle-your-xp](https://www.curseforge.com/minecraft/mc-mods/bottle-your-xp)
