### ISSUE TITLE
Healing not working with firstAid mod

### ISSUE THREAD

**Issue by NicolaSpadari** [Serilum/.issue-tracker#93]
## **Information**
Minecraft version: 1.15,2
Forge version: 31.1.46
Environment: Singleplayer and Multiplayer

Mod name: Healing Campfire
Mod version: 2.1

## **Description**
I'm using this mod with first aid. The first aid's config has an option to disable vanilla regen, which I set to true. Another option is to allow external healing items, which I set to true.
When I'm around a campfire it gives me regeneration and the heart containers start to wobble, as expected. However, health doesn't increase.
When I try with a simple healing potion, it works with no problem.
I think this mod should apply regeneration in the same way the potion does, to avoid conflicts.

## **Crash report**
No crash. Just not working as espected.

**Comment by ricksouth** [comment]
Thanks for using the mod!

Currently in the code it does exactly what the regeneration potion does. I think this is something you'll have to mention in the other mod's issue page.
