### ISSUE TITLE
Optional support for CuriosElytra 

### ISSUE THREAD

**Issue by phlane** [Serilum/.issue-tracker#95]
## **Information**
Mod name: Mod
Easy Elytra Takeoff

## **Feature description**
I've had this amazing idea..
Optional support for CuriosElytra for ease of convenience

**Comment by ricksouth** [comment]
Thanks for using the mod! Adding the compatibility without depending on the mod isn't possible. I've added the Colytra because that actually added a statistic to the player.

I believe the CuriousElytra does have its own Simple Takeoff system which was recently added though.

**Comment by ricksouth** [comment]
Version 1.5 of Easy Elytra Takeoff adds support for Curious Elytra.

https://www.curseforge.com/minecraft/mc-mods/easy-elytra-takeoff
