### ISSUE TITLE
Add a 1.7.10 version to the mod.

### ISSUE THREAD

**Issue by mahdialhassani** [Serilum/.issue-tracker#98]
## **Information**
Minecraft version: 1.7.10
Forge version: 1.7.10
Environment: Singleplayer / Multiplayer

Mod name: World Border
Mod version: 1.7.10

## **Question**
I'd really hope to see this in 1.7.10. Is it possible that you can remake this in 1.7.10? Really REALLY would appreciate it.

**Comment by ricksouth** [comment]
I've currently got no plans to make a 1.7 version, sorry. If you want I can create it for a small fee, but doing it free doesn't make sense at the moment for the amount of people using that version of Minecraft.
